### DISCUSSION TITLE
how to use mailu with nginx-proxy

### DISCUSSION THREAD

**Discussion by toshirov** [Mailu/Mailu#3037] [User support]
Hi,

Is there any documentation that shows how to run mailu using nginx-proxy (https://github.com/nginx-proxy/nginx-proxy)  as a reverse proxy? I've been struggling with this for several days but couldn't make this work.

Any hints would be appreciated, thank you!

**Comment by pini-gh** [comment]
Do you use acme-companion along with nginx-proxy? I do, and here are the relevant bits of configuration:

* In the Mailu docker-compose file I comment out the lines related to ports 80 and 443:
```
    ports:
      #- "80:80"
      #- "443:443"
      - "25:25"
      - ...
```
* In `mailu.env`:
```
TLS_FLAVOR=mail
TLS_CERT_FILENAME=fullchain.pem
```
* The `mailu_certs` volume is defined in my nginx-proxy + acme-companion docker-compose file:
```
version: "3.5"
services:
  reverse-proxy:
    image: nginxproxy/nginx-proxy
    ...
    volumes:
      ...
      - mailu_certs:/etc/nginx/certs/mail.example.com
    ...
  letsencrypt:
    image; nginxproxy/acme-companion
    ...
    volumes:
      ...
      - mailu_certs:/etc/nginx/certs/mail.example.com
    ...
...
volumes:
  ...
  mailu_certs:
    name: mailu_certs
```
* The same volume is declared as external into the Mailu docker-compose file:
```
version: '2.2'
services:
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    ...
    volumes:
      - "certs:/certs"
...
volumes:
  certs:
    external: true
    name: mailu_certs
...
```
* Finally I declare these environment variables for the `front` service:
```
      VIRTUAL_HOST: "mail.example.com"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "mail.example.com"
      # Hook acme.sh to reload the nginx configuration after a certificate update
      ACME_POST_HOOK: "bash -c '. /app/functions.sh && docker_exec mailu_front_1 '\\''[\\\"nginx\\\", \\\"-s\\\", \\\"reload\\\"]'\\'"
```
