### DISCUSSION TITLE
Missing cert or key file, disabling TLS

### DISCUSSION THREAD

**Discussion by liuhr-ncu** [Mailu/Mailu#3202] [User support] [answered]
The cert.pem file does not appear to be read, Here is part of my configuration:
**docker-compose.yml**
```
 # Core services
services:
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "192.168.1.101:80:80"
      - "192.168.1.101:443:443"
      - "192.168.1.101:25:25"
      - "192.168.1.101:465:465"
      - "192.168.1.101:587:587"
      - "192.168.1.101:110:110"
      - "192.168.1.101:995:995"
      - "192.168.1.101:143:143"
      - "192.168.1.101:993:993"
    networks:
      - default
      - webmail
      - radicale
    volumes:
      - "/software/mailu/certs:/certs"
      - "/software/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
```
**mailu.env**
```
# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=cert

# Override certificate and key file names
TLS_CERT_FILENAME=cert.pem
TLS_KEYPAIR_FILENAME=key.pem
```
and here is my folder directory:
![image](https://github.com/Mailu/Mailu/assets/29883424/08a0c6f4-736e-4cbd-8419-917cb891123e)

here is my debug log :
![bug1](https://github.com/Mailu/Mailu/assets/29883424/765118c9-53bf-4227-a4e6-af31e7960093)

I don't know why can't find this file
