### DISCUSSION TITLE
IMAP and POP3 not accessible

### DISCUSSION THREAD

**Discussion by sepa-sancheze** [Mailu/Mailu#3211] [User support]
Hello, support.

I hope you are doing okay.

I'm deploying MailU on a kubernetes cluster using Helm.

Here is the configuration file that I'm using:

```
# Domain configuration
domain: example.com
hostnames:
  - email.dev.example.com
  - mailu.dev.example.com

# Server and network configuration
timezone: Etc/PST
subnet: 10.43.0.0/16
logLevel: INFO

# Initial account
initialAccount:
  enabled: true
  username: admin
  domain: email.dev.example.com
  password: password

# Limits
limits:
  authRatelimit:
    ip: 100/minute;3600/hour
    user: 100/day

  messageRatelimit:
    value: 200/day

  messageSizeLimitInMegabytes: 200

# Storage
persistence:
  size: 20Gi
  storageClass: nfs-client

# Customization
customization:
  siteName: Dev example.com
  website: https://example.com

welcomeMessage:
  enabled: true
  subject: Welcome to example.com Mailserver (Dev)
  body: Welcome to example.com MailServer (Dev). Please change your password and update your profile.

# Services
ingress:
  enabled: true
  ingressClassName: traefik-external
  pathType: ImplementationSpecific
  path: /
  selfSigned: true
  tlsFlavorOverride: letsencrypt

front:
  externalService:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: 10.30.60.48
    externalTrafficPolicy: Local
    ports:
      pop3: true
      pop3s: true
      imap: true
      imaps: true
      smtp: true
      smtps: true
      submission: true

postfix:
  hostname: email.dev.example.com
```

However, when I execute a nmap for the IP or domain it will only show me SMTP as open:

```
$ nmap -Pn 10.30.60.48
Starting Nmap 7.80 ( https://nmap.org ) at 2024-03-27 20:20 PDT
Nmap scan report for 10.30.60.48
Host is up (0.00088s latency).
Not shown: 993 filtered ports
PORT    STATE  SERVICE
25/tcp  open   smtp
110/tcp closed pop3
143/tcp closed imap
465/tcp closed smtps
587/tcp closed submission
993/tcp closed imaps
995/tcp closed pop3s
```

For now, the service that has that IP is the "front" service. I know that dovecot is the one that opens those ports (IMAP and POP3), however I need both IMAP and SMTP open over the same IP.

When using webmail I can send and receive messages without any issues.

Do you have any idea why this may be failing?

Regard and thanks in advance =D
