### DISCUSSION TITLE
why my domain not open return This page isn’t working , my.domainb.com refused to connect.

### DISCUSSION THREAD

**Discussion by vahidalvandi** [Mailu/Mailu#3248] [User support]
i use default setting in docker-compose.yml and last version of docker 26 It seems that the web server is not active 

```
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
      - "127.0.0.1:25:25"
      - "127.0.0.1:465:465"
      - "127.0.0.1:587:587"
      - "127.0.0.1:110:110"
      - "127.0.0.1:995:995"
      - "127.0.0.1:143:143"
      - "127.0.0.1:993:993"
    networks:
      - default
      - webmail
      - radicale
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
```
also mailu.env
```
SECRET_KEY=3Mss4DI0U3CZY7Y7

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (>
SUBNET=192.168.203.0/24

# Main mail domain
DOMAIN=my.domainb.com

# Hostnames for this server, separated with comas
HOSTNAMES=mail.domainb.com

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=cert

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

......
```

so DNS have a record for my.domainb.com and mail.domainb.com . 

return docker log  front

```
root@ccxc:/mailu# docker compose logs -f front

WARN[0000] /mailu/docker-compose.yml: `version` is obsolete 
front-1  | 2024/05/06 11:01:09 [notice] 1#1: using the "epoll" event method
front-1  | 2024/05/06 11:01:09 [notice] 1#1: nginx/1.24.0
front-1  | 2024/05/06 11:01:09 [notice] 1#1: OS: Linux 5.15.0-105-generic
front-1  | 2024/05/06 11:01:09 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
front-1  | 2024/05/06 11:01:09 [notice] 1#1: start worker processes
front-1  | 2024/05/06 11:01:09 [notice] 1#1: start worker process 14
front-1  | 2024/05/06 11:01:09 [notice] 1#1: start worker process 15
front-1  | 2024/05/06 12:26:40 [notice] 1#1: signal 15 (SIGTERM) received, exiting
front-1  | 2024/05/06 12:26:40 [notice] 14#14: exiting
front-1  | 2024/05/06 12:26:40 [notice] 15#15: exiting
front-1  | 2024/05/06 12:26:40 [notice] 1#1: signal 14 (SIGALRM) received
front-1  | 2024/05/06 12:26:40 [notice] 15#15: exit
front-1  | 2024/05/06 12:26:40 [notice] 14#14: exit
front-1  | 2024/05/06 12:26:40 [notice] 1#1: signal 17 (SIGCHLD) received from 15
front-1  | 2024/05/06 12:26:40 [notice] 1#1: worker process 15 exited with code 0
front-1  | 2024/05/06 12:26:40 [notice] 1#1: signal 29 (SIGIO) received
front-1  | 2024/05/06 12:26:40 [notice] 1#1: signal 17 (SIGCHLD) received from 14
front-1  | 2024/05/06 12:26:40 [notice] 1#1: worker process 14 exited with code 0
front-1  | 2024/05/06 12:26:40 [notice] 1#1: exit
front-1  | 2024/05/06 12:27:05 [notice] 1#1: using the "epoll" event method
front-1  | 2024/05/06 12:27:05 [notice] 1#1: nginx/1.24.0
front-1  | 2024/05/06 12:27:05 [notice] 1#1: OS: Linux 5.15.0-105-generic
front-1  | 2024/05/06 12:27:05 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
front-1  | 2024/05/06 12:27:05 [notice] 1#1: start worker processes
front-1  | 2024/05/06 12:27:05 [notice] 1#1: start worker process 14
front-1  | 2024/05/06 12:27:05 [notice] 1#1: start worker process 15
```
