### DISCUSSION TITLE
please add auto update with watchtower

### DISCUSSION THREAD

**Discussion by vahidalvandi** [Mailu/Mailu#3266] [Feature requests / Ideas]
It is very important that new updates are received daily and automatically

```
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
```
