### DISCUSSION TITLE
What is certdumper doing?

### DISCUSSION THREAD

**Discussion by seisdr** [Mailu/Mailu#3278] [User support]
I'm desperately trying to get traefik certs to work with mailu
I noticed ins the master branch docker-compose.yml in fronter service a line `/opt/mailu/certs` but no certdumper to provide these certs so i added certdump as follow 
```
certdumper:
    restart: always
    image: ghcr.io/mailu/traefik-certdumper:master
    environment:
      - DOMAIN=example.com
      - TRAEFIK_VERSION=v2
    volumes:
      - "/opt/Traefik/letsencrypt/:/traefik"
      - "/opt/mailu/certs:/output"
```

Running the compose file ,this is what i get 
```
root@localhost:/opt/mailu# docker logs -f mailu-certdumper-1
Sun May 26 16:59:04 UTC 2024 Dumping certificates
Sun May 26 16:59:04 UTC 2024 Certificate or key differ, updating
mv: can't rename '/tmp/work/example.com/*.pem': No such file or directory                     
```
