### DISCUSSION TITLE
letsencrypt.py script crash on startup

### DISCUSSION THREAD

**Discussion by abaurens** [Mailu/Mailu#3402] [User support]
## Environment & Version

- Docker Compose version: `v2.29.1`
- Version: `pr-3353`

## Description
I have installed mailu behind an nginx reverse proxy (swag).
The overall server works great, but the `front` app crashes at startup when setting `TLS_FLAVOR` to either `letsencrypt` or `mail-letsencrypt`.
I managed to dodge the issue by using `TLS_FLAVOR=mail` and providing the cert files manually. But since mailu is suppose to be able to handle these by itself, I'd rather have that sorted out.

## Replication Steps
I simply installed mailu by following the steps on [mailu.io](https://mailu.io/2024.06/compose/setup.html), tweaked what I could from the setup utility tool and then modified both the `compose` and in the `.env` file ended up with this configuration:

<details><summary>compose.yml</summary>

> NOTE: I think the only manual editing I did here was the addition of the `portainer` network
> which is required for the reverse proxy.

```yaml
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: "2"
services:
  # External dependencies
  redis:
    image: redis:alpine
    container_name: mailu_redis
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-uuid-fb70dc4d-b310-4343-883b-17fe83085c7e/containers/mailu/redis:/data
    depends_on:
      - resolver
    dns:
      - 172.26.255.254

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    container_name: mailu_front
    restart: unless-stopped
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - 0.0.0.0:25:25
      - 0.0.0.0:465:465
      - 0.0.0.0:587:587
      - 0.0.0.0:110:110
      - 0.0.0.0:995:995
      - 0.0.0.0:143:143
      - 0.0.0.0:993:993
      - 0.0.0.0:4190:4190
    networks:
      - default
      - portainer
    volumes:
      - /srv/dev-disk-by-uuid-fb70dc4d-b310-4343-883b-17fe83085c7e/containers/mailu/overrides/nginx:/overrides:ro
    depends_on:
      - resolver
    dns:
      - 172.26.255.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2024.06}
    container_name: mailu_resolver
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-resolver
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.26.255.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    container_name: mailu_admin
    restart: unless-stopped
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - /srv/dev-disk-by-uuid-fb70dc4d-b310-4343-883b-17fe83085c7e/containers/mailu/data:/data
      - /srv/dev-disk-by-uuid-fb70dc4d-b310-4343-883b-17fe83085c7e/containers/mailu/dkim:/dkim
    depends_on:
      - redis
      - resolver
    dns:
      - 172.26.255.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    container_name: mailu_imap
    restart: unless-stopped
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - /srv/dev-disk-by-uuid-fb70dc4d-b310-4343-883b-17fe83085c7e/containers/mailu/mail:/mail
      - /srv/dev-disk-by-uuid-fb70dc4d-b310-4343-883b-17fe83085c7e/containers/mailu/overrides/dovecot:/overrides:ro
    networks:
      - default
      - fts_attachments
    depends_on:
      - front
      - fts_attachments
      - resolver
    dns:
      - 172.26.255.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    container_name: mailu_smtp
    restart: unless-stopped
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - /srv/dev-disk-by-uuid-fb70dc4d-b310-4343-883b-17fe83085c7e/containers/mailu/mailqueue:/queue
      - /srv/dev-disk-by-uuid-fb70dc4d-b310-4343-883b-17fe83085c7e/containers/mailu/overrides/postfix:/overrides:ro
    depends_on:
      - front
      - resolver
    dns:
      - 172.26.255.254

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2024.06}
    container_name: mailu_oletools
    hostname: oletools
    logging:
      driver: journald
      options:
        tag: mailu-oletools
    restart: unless-stopped
    networks:
      - oletools
    depends_on:
      - resolver
    dns:
      - 172.26.255.254

  fts_attachments:
    image: apache/tika:2.9.2.1-full
    container_name: mailu_fts_attachments
    hostname: tika
    logging:
      driver: journald
      options:
        tag: mailu-tika
    restart: unless-stopped
    networks:
      - fts_attachments
    depends_on:
      - resolver
    dns:
      - 172.26.255.254
    healthcheck:
      test: ["CMD-SHELL", "wget -nv -t1 -O /dev/null http://127.0.0.1:9998/tika || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}
    container_name: mailu_antispam
    hostname: antispam
    restart: unless-stopped
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - oletools
      - clamav
    volumes:
      - /srv/dev-disk-by-uuid-fb70dc4d-b310-4343-883b-17fe83085c7e/containers/mailu/filter:/var/lib/rspamd
      - /srv/dev-disk-by-uuid-fb70dc4d-b310-4343-883b-17fe83085c7e/containers/mailu/overrides/rspamd:/overrides:ro
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 172.26.255.254

  # Optional services
  antivirus:
    image: clamav/clamav-debian:1.2.0-6
    container_name: mailu_antivirus
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: mailu-antivirus
    networks:
      - clamav
    volumes:
      - /srv/dev-disk-by-uuid-fb70dc4d-b310-4343-883b-17fe83085c7e/containers/mailu/filter/clamav:/var/lib/clamav
    healthcheck:
      test: ["CMD-SHELL", "kill -0 `cat /tmp/clamd.pid` && kill -0 `cat /tmp/freshclam.pid`"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s


  fetchmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-2024.06}
    container_name: mailu_fetchmail
    restart: unless-stopped
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-fetchmail
    volumes:
      - /srv/dev-disk-by-uuid-fb70dc4d-b310-4343-883b-17fe83085c7e/containers/mailu/data/fetchmail:/data
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - 172.26.255.254

  # Webmail

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
  clamav:
    driver: bridge
  oletools:
    driver: bridge
    internal: true
  fts_attachments:
    driver: bridge
    internal: true
  portainer:
    name: portainer
    external: true
```

</details>
<details><summary>.env</summary>

```env
MAILU_VERSION=pr-3353
LD_PRELOAD=/usr/lib/libhardened_malloc.so
SECRET_KEY=REDACTED
SUBNET=172.26.0.0/16
DOMAIN=example.com
HOSTNAMES=mail.example.com, autoconfig.example.com
POSTMASTER=admin
TLS_FLAVOR=mail-letsencrypt
AUTH_RATELIMIT_IP=5/hour
AUTH_RATELIMIT_USER=50/day
DISABLE_STATISTICS=True
ADMIN=true
WEBMAIL=none
API=false
WEBDAV=none
ANTIVIRUS=clamav
SCAN_MACROS=true
MESSAGE_SIZE_LIMIT=50000000
MESSAGE_RATELIMIT=200/day
RELAYNETS=
RELAYHOST=
FETCHMAIL_ENABLED=true
FETCHMAIL_DELAY=600
RECIPIENT_DELIMITER=+
DMARC_RUA=admin
DMARC_RUF=admin
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!
COMPRESSION=
COMPRESSION_LEVEL=
FULL_TEXT_SEARCH=en
WEBROOT_REDIRECT=/admin
WEB_ADMIN=/admin
WEB_WEBMAIL=/webmail
WEB_API=/api
SITENAME=Mailu
WEBSITE=https://mail.example.com
COMPOSE_PROJECT_NAME=mailu
CREDENTIAL_ROUNDS=12
REAL_IP_HEADER=X-Real-IP
REAL_IP_FROM=172.19.0.0/24
REJECT_UNLISTED_RECIPIENT=
LOG_LEVEL=INFO
TZ=Europe/Paris
DEFAULT_SPAM_THRESHOLD=80
API_TOKEN=
FULL_TEXT_SEARCH_ATTACHMENTS=true
INITIAL_ADMIN_ACCOUNT=admin
INITIAL_ADMIN_DOMAIN=example.com
INITIAL_ADMIN_PW=REDACTED
INITIAL_ADMIN_MODE=ifmissing
PORTS=80,443,25,465,587,110,995,143,993,4190
```

</details>

I also added all the required DNS entries from the `domain` page of the admin panel, as well as an `A` entry for both `example.com` and `mail.example.com`, both pointing to the server ip.
And finallyu a `CNAME` entry for `autoconfig.example.com` pointing back to `mail.example.com`

## Observed behaviour
Starting the `front` container or manually running the `letsencrypt.py` script with the above configuration gives me the following python stack trace:
<details>
<summary>Stack trace</summary>

```
Exception in thread Thread-1 (serve_one_request):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "//./letsencrypt.py", line 58, in serve_one_request
    with HTTPServer(("127.0.0.1", 8008), MyRequestHandler) as server:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/lib/python3.12/http/server.py", line 136, in server_bind
Traceback (most recent call last):
    socketserver.TCPServer.server_bind(self)
  File "/app/venv/lib/python3.12/site-packages/urllib3/connection.py", line 198, in _new_conn
  File "/usr/lib/python3.12/socketserver.py", line 473, in server_bind
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address in use
    raise err
  File "/app/venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/app/venv/lib/python3.12/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/app/venv/lib/python3.12/site-packages/urllib3/connection.py", line 238, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x733edfc5a480>: Failed to establish a new connection: [Errno 101] Network unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='mail.example.com', port=80): Max retries exceeded with url: /.well-known/acme-challenge/testing (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x733edfc5a480>: Failed to establish a new connection: [Errno 101] Network unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//./letsencrypt.py", line 68, in <module>
    r = requests.get(target)
        ^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='mail.example.com', port=80): Max retries exceeded with url: /.well-known/acme-challenge/testing (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x733edfc5a480>: Failed to establish a new connection: [Errno 101] Network unreachable'))
```

</details>

I _think_ the `OSError: [Errno 98] Address in use` error suggests that the `8008` port is already in use somewhere. But I can't find where. I didn't check my other containers and services as I think this connection is supposed to stay within the `front` container and it shouldn't collide with other containerized applications.

## Expected behaviour
The `letsencrypt.py` script should generate the certificates (or at least output some understandable letsencrypt error).

**Comment by nextgens** [comment]
Unless you are certain that this is something wrong with Mailu that only a code-change can fix, you should create support requests and not issues.

Do you have a working loopback interface in that container? Does ``ping 127.0.0.1`` in that container work?

**Reply by abaurens** [reply]
Hi, Sorry for the inconvenience. I indeed wasn't sure if this was more suited as an issue or a discussion. The fact that i'm getting an unhandled python exception stacktrace is what oriented my choice toward an issue.

> Do you have a working loopback interface in that container?

Seems like it:
```
#> docker exec mailu_front ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
...
```
> Does ping 127.0.0.1 in that container work?

Also yes:
```
#> docker exec mailu_front ping 127.0.0.1 -c 10
PING 127.0.0.1 (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.028 ms
64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.040 ms
64 bytes from 127.0.0.1: seq=2 ttl=64 time=0.116 ms
64 bytes from 127.0.0.1: seq=3 ttl=64 time=0.107 ms
64 bytes from 127.0.0.1: seq=4 ttl=64 time=0.104 ms
64 bytes from 127.0.0.1: seq=5 ttl=64 time=0.110 ms
64 bytes from 127.0.0.1: seq=6 ttl=64 time=0.115 ms
64 bytes from 127.0.0.1: seq=7 ttl=64 time=0.113 ms
64 bytes from 127.0.0.1: seq=8 ttl=64 time=0.114 ms
64 bytes from 127.0.0.1: seq=9 ttl=64 time=0.110 ms

--- 127.0.0.1 ping statistics ---
10 packets transmitted, 10 packets received, 0% packet loss
round-trip min/avg/max = 0.028/0.095/0.116 ms
```

**Reply by nextgens** [reply]
The stack trace is fairly clear: the exception is "Max retries exceeded with url: /.well-known/acme-challenge/testing".

Does ``http://mail.example.com/.well-known/acme-challenge/testing`` point to the right place? this is HTTP and not HTTPS.

**Reply by abaurens** [reply]
> Does `http://mail.example.com/.well-known/acme-challenge/testing` point to the right place? this is HTTP and not HTTPS.

It redirects me to the admin pannel:
```
$> curl https://mail.example.com/.well-known/acme-challenge/testing
<!doctype html>
<html lang=en>
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to the target URL: <a href="https://mail.example.com/admin/?homepage">https://mail.example.com/admin/?homepage</a>. If not, click the link.
```

But i'm not sure if this is revelant as the python errors are listed in the order they appeared, which means the last 2 exceptions got triggered because of the exceptions above them.

So the root cause of all the exceptions seems to be this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "//./letsencrypt.py", line 58, in serve_one_request
    with HTTPServer(("127.0.0.1", 8008), MyRequestHandler) as server:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/lib/python3.12/http/server.py", line 136, in server_bind
Traceback (most recent call last):
    socketserver.TCPServer.server_bind(self)
  File "/app/venv/lib/python3.12/site-packages/urllib3/connection.py", line 198, in _new_conn
  File "/usr/lib/python3.12/socketserver.py", line 473, in server_bind
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address in use
    raise err
  File "/app/venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network unreachable
```
Which looks like a port conflict issue

**Reply by nextgens** [reply]
> It redirects me to the admin pannel:

well here is the problem: `it` should not; Odds are this is not Mailu doing it.

**Reply by abaurens** [reply]
Hey. Sorry for late answer.

I actually tried the same test but with direct ip address access (after forwarding port 80 from `front`) to avoid any possibly bad redirection from the reverse proxy and still got redirected to the admin page.
```
$> curl http://192.168.1.85/.well-known/acme-challenge/testing
<!doctype html>
<html lang=en>
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to the target URL: <a href="http://192.168.1.85/admin/?homepage">http://192.168.1.85/admin/?homepage</a>. If not, click the link.
```

Also, whenever I try to hit that endpoint, I can see a verry clear redirection log inside of the `front` container:
```
192.168.1.61 - - [20/Sep/2024:12:57:24 +0200] "GET /.well-known/acme-challenge/testing HTTP/1.1" 308 257 "-" "curl/8.8.0"
```

It seems like it in fact is Mailu doing it..

**Reply by abaurens** [reply]
I may have found what's wrong with my config thanks to [this answer](https://github.com/Mailu/Mailu/discussions/3402#discussioncomment-10600146) and once I saw it finally working [here](https://github.com/Mailu/Mailu/discussions/3402#discussioncomment-10704034).

My reverse proxy is setup to proxy both `http` and `https`, but it's container does not forward port 80 as I never really wanted to allow `http` access trough it.

The referenced answers finally made me understand that `http` is in fact required in order for letsencrypt to work.
Now that I think of it, it make sense since it needs to be able to generates certificates without any certificate already present.

Forwarding port 80 in the reverse proxy container should be enough to solve the issue for me, but I can't test that for now as I am on cooldown from letsencrypt's servers.

I'll test this again tomorrow.

**Comment by marfis89** [comment]
Hi, I have the same setup and the same problem. 

letsencrypt.py crash on startup
ping to 127.0.0.1 works

**Comment by franzil** [comment]
@nextgens  Hi, I have the same setup and the same problem.

The Mailu installation has been working fine for 7 months.
Automatic certificate renewal has worked until June 2024.
This is a dedicated server for this installation, with no other containers or services running.
I don't know if this issue is due to the Mailu 2024.06 update or the latest Docker releases (now 27.2.1).
Pinging 127.0.0.1 works, but nginx no longer resolves the connection to `http://127.0.0.1:8008/.well-known/acme-challenge/`
`curl: (7) Failed to connect to 127.0.0.1 port 8008 after 0 ms: Couldn't connect to server`
Launching certbot to renew from inside the container, using the letsencrypt.py command, returns this error:
`Could not bind TCP port 8008 because it is already in use by another process on this system (such as a web server). Please stop the program in question and then try again.`
Trying to reach `http://mail.mydomain.tld/.well-known/acme-challenge/testing` from the internet results in a "502 Bad Gateway" error.

**Reply by nextgens** [reply]
The reporter's problem is that he is not exposing port 80 on front.

I am unclear what the problem is with your setup without more logs and config files. We need your docker-compose.yml and the corresponding logs from front at the very least.

**Reply by franzil** [reply]
MAILU 2024.06.15
DOCKER ENGINE 27.2.1
Docker Compose version v2.29.2
TLS_FLAVOR=letsencrypt

`front-1  | requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='mail.redacted.tld', port=80): Max retries exceeded with url: /.well-known/acme-challenge/testing (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7326b1026600>, 'Connection to mail.redacted.tld timed out. (connect timeout=None)'))`
or
`front-1  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='mail.redacted.tld', port=80): Max retries exceeded with url: /.well-known/acme-challenge/testing (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x73801ebef2f0>, 'Connection to mail.redacted.tld timed out. (connect timeout=None)'))`

docker-compose.yml
```
services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "redacted:80:80"
      - "redacted:443:443"
      - "redacted:25:25"
      - "redacted:465:465"
      - "redacted:587:587"
      - "redacted:110:110"
      - "redacted:995:995"
      - "redacted:143:143"
      - "redacted:993:993"
      - "redacted:4190:4190"
    networks:
      - default
      - radicale
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2024.06}
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-resolver
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "/mailu/mail:/mail"
      - "/mailu/overrides/dovecot:/overrides:ro"
    networks:
      - default
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "/mailu/mailqueue:/queue"
      - "/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2024.06}
    hostname: oletools
    logging:
      driver: journald
      options:
        tag: mailu-oletools
    restart: always
    networks:
      - oletools
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - oletools
      - clamav
    volumes:
      - "/mailu/filter:/var/lib/rspamd"
      - "/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: clamav/clamav-debian:1.2.3-45
    restart: always
    logging:
      driver: journald
      options:
        tag: mailu-antivirus
    networks:
      - clamav
    volumes:
      - "/mailu/filter/clamav:/var/lib/clamav"
    healthcheck:
      test: ["CMD-SHELL", "kill -0 `cat /tmp/clamd.pid` && kill -0 `cat /tmp/freshclam.pid`"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  webdav:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-2024.06}
    restart: always
    logging:
      driver: journald
      options:
        tag: mailu-webdav
    volumes:
      - "/mailu/dav:/data"
    networks:
      - radicale


  # Webmail

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  radicale:
    driver: bridge
  clamav:
    driver: bridge
  oletools:
    driver: bridge
    internal: true
```
