### DISCUSSION TITLE
DNS MX entry

### DISCUSSION THREAD

**Discussion by DieterSmeulders** [Mailu/Mailu#3624] [User support] [answered]
I am running mailu behind nginx proxy manager reverse proxy. I am hosting my main website at exampledomain.com, and exposing the mailu admin panel on port 89 and 444 (since port 80 and 443 are used by another service). mail.exampledomain.com points to 89 and exposes the admin panel. Nginx proxy manager generates certificates (for exampledomain.com, problem persists if I use mail.exampledomain.com certs) which are loaded into mailu using a bind mount. Front container gives the warning "nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/certs/cert.pem"". The docker compose looks like this.

 ```
 front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "127.0.0.1:89:80"
      - "127.0.0.1:444:443"
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
      - "4190:4190"
    networks:
      - default
    volumes:
      - "/home/dockeruser/dockerconfig/mailu/overrides/nginx:/overrides:ro"
      - type: bind
        source: /etc/letsencrypt/archive/npm-18/privkey1.pem
        target: /certs/key.pem
        read_only: true
      - type: bind
        source: /etc/letsencrypt/archive/npm-18/cert1.pem
        target: /certs/cert.pem
        read_only: true
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
```

```
environmental variables:
DOMAIN = exampledomain.com
HOSTNAMES = exampledomain.com
TLS_FLAVOR = mail
```

Mostly everything is working, I can access the admin panel and send and receive emails. However the "DNS MX entry" is not working (red exclamation). I cannot send emails to Gmail (550-5.7.26 Your email has been blocked because the sender is unauthenticated). If I change TLS_FLAVOR to mail-letsencrypt, front container returns "CRITICAL:root:Can't reach http://exampledomain.dev/.well-known/acme-challenge/testing!, please ensure it's fixed or change the TLS_FLAVOR." Could someone point me in the right direction?
