### DISCUSSION TITLE
Hosting a Static Website with Mailu's Integrated Nginx

### DISCUSSION THREAD

**Discussion by metabsd** [Mailu/Mailu#3711] [User support]
Hi Mailu Community,

I am currently hosting my email services using Mailu, which utilizes Nginx for web interfaces. I would like to host a simple static webpage alongside my email services. Given that Mailu's Nginx is already occupying ports 80 and 443, I am seeking guidance on the best approach to achieve this without disrupting my existing email setup.

Specific Questions:

Is it advisable to modify Mailu's Nginx configuration to serve additional static content? If so, what steps should I follow to implement this safely?

Are there potential risks or conflicts associated with altering the default Nginx configuration provided by Mailu?

Would it be more appropriate to set up an external reverse proxy to handle both Mailu's services and the static website? If yes, could you provide recommendations or best practices for configuring such a setup?

I appreciate any insights or experiences you can share regarding hosting additional web content alongside Mailu's email services.

Thank you for your assistance.

Best regards,

**Comment by ErwanMAS** [comment]
I have the same need , i want to give ability admin users to host a small web service . 

My concept :
   Create a new feature web services ( like mail domain )  , 2 main attributes DNS name  & admin users
   for each web service  , you must use WebDav to push files 
   web service will be serve by a shared dedicated container .
   front ngnix will serve has a reverse proxy  for http/https .
   TLS/SSL certificates will be renew by the current system 
   
  Feel free to contact me , to discuss more or start to work together on this concept

**Comment by JensUweB** [comment]
### TL;DR
Instead of modifying mailu's nginx, you could put a traefik proxy in front of mailu's admin container. I personally think that allowing (admin) users to upload websites themself is too insecure, so I would always recommend using a custom reverse proxy like traefik & handling the website setup yourself.

### Setup summary:
For this you need to remove the ports 80 & 443 from the container & set TLS_FLAVOR to "mail" in your .env file. You need to add a certdumper to your stack to grab the tls certs from traefik & put them in a mounted folder so that mailu can use them to encrypt email traefik. Then traefik handles all the http routing and you can put as many websites as you wish besides your mailu server on whatever paths or domains you wish. For your static sites, you could add another nginx container where you mount some folder into www folder where you put all your static sites. But for a production environment I would recommend to run one container per website - static or not.

### Modified docker-compose.yml excerpt:
The following file is just how it roughly looks on my deployment except the traefik command section - I use a traefik.yml file instead for config with all sorts of stuff there. Please look into the traefik docs for details. Technically you could route all the traffic including emails through traefik thus eliminating the need for a certdumper & having more control over traffic flow, but that is more complicated so I didn't put that here.

```yml
  traefik:
    container_name: traefik
    image: traefik:v2.8
    restart: always
    env_file: ./.env
      # Inline traefik config. I would recommend to use a traefik.yml for production.
    command:
      - "--providers.docker"
      - "--providers.docker.endpoint=tcp://socket-proxy:2375"
      - "--providers.docker.exposedbydefault=false"
      # Http to Https
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      # Let's Encrypt Certificates
      - "--certificatesresolvers.lets-encrypt.acme.email=$WEBMASTER_EMAIL"
      - "--certificatesresolvers.lets-encrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.lets-encrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.lets-encrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.lets-encrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      # Enable traefik monitor
      - "--api"
      - "--api.dashboard=true"
      - "--log.level=INFO"
    labels:
      # Set rate limits to mitigate brute force attacks
      - "traefik.http.middlewares.test-ratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.burst=50"
      - "traefik.http.routers.api.rule=Host(`monitor.domain.cloud`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:some-hashed-pw"
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    networks:
      - traefik_proxy
    volumes:
       # This is not safe. Use a socket proxy for production!
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - /var/log/traefik:/var/log/traefik
      - /data/traefik/acme.json:/acme.json
   
# Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "0.0.0.0:25:25"
      - "0.0.0.0:465:465"
      - "0.0.0.0:587:587"
      - "0.0.0.0:110:110"
      - "0.0.0.0:995:995"
      - "0.0.0.0:143:143"
      - "0.0.0.0:993:993"
      - "0.0.0.0:4190:4190"
    networks:
      - default
      - webmail
      - radicale
      # My traefik container runs in a separate stack, so I add the admin container to this external network
      - traefik_proxy 
    volumes:
      - "/data/mailu/certs:/certs"
      - "/data/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      #HTTPs and TLS
      - "traefik.http.routers.mailu_front.rule=Host(`mail.domain.cloud`,`mail.domain2.cloud`)"
      - "traefik.http.services.mailu_front.loadbalancer.server.port=80"
      - "traefik.http.routers.mailu_front.entrypoints=web,websecure"
      - "traefik.http.routers.mailu_front.tls=true"
      - "traefik.http.routers.mailu_front.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.mailu_front.middlewares=mailu-redirect-dev"

      # Redirect main page to personal homepage
      # In my case I'm doing this for legal reasons. So other mailserver admins know who is responsible for my server
      - "traefik.http.middlewares.mailu-redirect-dev.redirectregex.regex=^https?://mail.domain\\.cloud/$"
      - "traefik.http.middlewares.mailu-redirect-dev.redirectregex.replacement=https://example.com/"
      - "traefik.http.middlewares.mailu-redirect-dev.redirectregex.permanent=false"

      # other FQDNS can be added here:
      - "traefik.tcp.routers.mailu_front_secure.rule=HostSNI(`mail.domain.cloud`) || HostSNI(`mail.domain2.cloud`) || HostSNI(`autoconfig.domain.cloud`) || HostSNI(`mta-sts.domain.cloud`)"
      - "traefik.tcp.routers.mailu_front_secure.entrypoints=websecure"
      - "traefik.tcp.routers.mailu_front_secure.tls.passthrough=true"
      - "traefik.tcp.routers.mailu_front_secure.service=mailu_front_secure"
      - "traefik.tcp.services.mailu_front_secure.loadbalancer.server.port=443"
      - "traefik.tcp.services.mailu_front_secure.loadbalancer.proxyProtocol.version=2"

  certdumper:
    restart: always
    env_file: stack.env
    image: humenius/traefik-certs-dumper:1.3.2
    environment:
      - DOMAIN=mail.domain.cloud
      # Set TRAEFIK_VERSION to v2 in your env if you're using Traefik v2
      - TRAEFIK_VERSION=v2
    volumes:
      # Path to traefik data
      - "/data/traefik/acme.json:/traefik/acme.json"
      - "/data/traefik/letsencrypt/certs:/tmp/work"
      - "/data/mailu/certs:/output"
```
