### DISCUSSION TITLE
Port 587 only on 127.0.0.1 not external IP

### DISCUSSION THREAD

**Discussion by Eloque** [Mailu/Mailu#3736] [User support]
I've upgraded my Mailu to 2024.06 and all seems to work fine. But, my 587 port is only available on the local machine, not external.

```
root@alpha-d725a3fcba:/opt/mailu# nc -vz 127.0.0.1 587
Connection to 127.0.0.1 587 port [tcp/submission] succeeded!

root@alpha-d725a3fcba:/opt/mailu# nc -vz 0.0.0.0 587
Connection to 0.0.0.0 587 port [tcp/submission] succeeded!

root@alpha-d725a3fcba:/opt/mailu# nc -vz 78.xx.xx.184 587
nc: connect to 78.xx.xx.184 port 587 (tcp) failed: Connection refused
```

And I can't figure out why. Ports in docker compose yml is setup correctly. There is no iptables issue or firewall rule that I am aware off. And it works locally and via 0.0.0.0. Just not via the external IP either from the local box or from outside.

I am running out of places to look. Anyone have an idea?

Update: 
If I bring down mail and then run 

`nc -l 78.xx.xx.184 587`

The connection works fine, so I am thinking something with the config is not in order. I am including the config here:

```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/opt/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
      - "78.xx.xx.184:25:25"
      - "78.xx.xx.184:465:465"
      - "78.xx.xx.184:587:587"
      - "78.xx.xx.184:110:110"
      - "78.xx.xx.184:995:995"
      - "78.xx.xx.184:143:143"
      - "78.xx.xx.184:993:993"
    networks:
      - default
      - webmail
    volumes:
      - "/opt/mailu/certs:/certs"
      - "/opt/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2024.06}
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-resolver
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "/opt/mailu/data:/data"
      - "/opt/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "/opt/mailu/mail:/mail"
      - "/opt/mailu/overrides/dovecot:/overrides:ro"
    networks:
      - default
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "/opt/mailu/mailqueue:/queue"
      - "/opt/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2024.06}
    hostname: oletools
    logging:
      driver: journald
      options:
        tag: mailu-oletools
    restart: always
    networks:
      - oletools
    depends_on:
      - resolver
    dns:
      - 192.168.203.254


  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - oletools
    volumes:
      - "/opt/mailu/filter:/var/lib/rspamd"
      - "/opt/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - resolver
    dns:
      - 192.168.203.254
    ports:
      - "11333:11333"

  # Optional services



  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-webmail
    volumes:
      - "/opt/mailu/webmail:/data"
      - "/opt/mailu/overrides/roundcube:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  webmail:
    driver: bridge
  oletools:
    driver: bridge
    internal: true

```
