### DISCUSSION TITLE
The page isn’t redirecting properly

### DISCUSSION THREAD

**Discussion by CompileNix** [Mailu/Mailu#3746] [User support]
## Environment & Version

- `Docker Compose version v2.32.1`
- Version: `2024.06.31`
- Firefox 133.0
- Ubuntu 24.04.1 LTS
- No reverse proxy software, like nginx or traffic is being used
- No overrides are configured via `/mailu/overrides`

<details>
<summary>/proc/cpuinfo</summary>

```txt
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz
stepping        : 0
microcode       : 0x2007006
cpu MHz         : 2992.968
cache size      : 25344 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid xsaveopt arat md_clear flush_l1d arch_capabilities
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_stale_data retbleed bhi
bogomips        : 5985.93
clflush size    : 64
cache_alignment : 64
address sizes   : 45 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) Gold 6136 CPU @ 3.00GHz
stepping        : 0
microcode       : 0x2007006
cpu MHz         : 2992.968
cache size      : 25344 KB
physical id     : 2
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid xsaveopt arat md_clear flush_l1d arch_capabilities
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_stale_data retbleed bhi
bogomips        : 5985.93
clflush size    : 64
cache_alignment : 64
address sizes   : 45 bits physical, 48 bits virtual
power management:
```

</details>

## Description

After visiting the main page https://mail-intern-1.plan.de/ (has no public internet access), entering the username and password, I expect to be redirected to the webmail. Instead It end's in a redirect loop.

Note: The admin ui on `/admin` works as expected.

## Replication Steps

- Follow the [setup guide](https://mailu.io/2024.06/setup.html) to deploy the service
- We kept the old docker networks (`front` and `back`) setup from older `docker-compose.yml` versions of this project. Our setup got upgraded from 2.x versions several months ago, after which the webmail still worked.
- Make sure to do a `docker compose down && docker compose up -d` to recreate all networks and containers

## Observed behaviour

- Login on https://mail-intern-1.plan.de/
- Receive redirect (301) to `/webmail`
- Receive redirect (302) to `/webmail/`
- Receive redirect (302) to `/webmail/sso.php`
- Receive redirect (302) to `/webmail/index.php?sso&hash=12297f6d55034e1d9a0f1b1ea22eaa63ffe3423a`
- Receive redirect (302) to `/webmail/`
- Receive redirect (302) to `/webmail/sso.php`
- Receive redirect (302) to `/webmail/index.php?sso&hash=2d25d6178dcf62548c0d375a3a0271e58675b34d`
- Receive redirect (302) to `/webmail/`
- Receive redirect (302) to `/webmail/sso.php`
- Receive redirect (302) to `/webmail/index.php?sso&hash=c580b70bab710311d5187ed671822f08b5871937`
- Receive redirect (302) to `/webmail/`
- Receive redirect (302) to `/webmail/sso.php`
- Receive redirect (302) to `/webmail/index.php?sso&hash=47f839ae4aa56e861e82091191713f712fc4e050`
- Receive redirect (302) to `/webmail/`
- Receive redirect (302) to `/webmail/sso.php`
- Receive redirect (302) to `/webmail/index.php?sso&hash=5d3ef7510dcced24feac8efde568069f265875fe`
- Receive redirect (302) to `/webmail/`
- Receive redirect (302) to `/webmail/sso.php`
- Receive redirect (302) to `/webmail/index.php?sso&hash=955e064254e12feb97d12deab41d3fb944bf5a22`
- Receive redirect (302) to `/webmail/`
- Firefox aborts requests with the error message: The page isn’t redirecting properly

## Expected behaviour

I expected to get redirected to the webmail (snappymail).

### Web Server Logs (docker compose "front" service)

Logs obtained via: `docker compose logs -f front`

<details>
<summary>Logs</summary>

```txt
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:28 +0100] "GET / HTTP/2.0" 301 162 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:28 +0100] "GET /webmail/?homepage HTTP/2.0" 302 138 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:28 +0100] "GET /sso/login?url=/webmail/?homepage HTTP/2.0" 200 2187 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:28 +0100] "GET /static/app.css HTTP/2.0" 200 441 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:28 +0100] "GET /static/vendor.css HTTP/2.0" 200 170516 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:28 +0100] "GET /static/mailu.png HTTP/2.0" 200 4935 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:28 +0100] "GET /static/app.js HTTP/2.0" 200 11511 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 2025/01/15 12:37:28 [warn] 33#33: *112 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/proxy/2/00/0000000002 while reading upstream, client: 172.24.1.1, server: , request: "GET /static/vendor.js HTTP/2.0", upstream: "http://172.24.1.4:8080/static/vendor.js", host: "mail-intern-1.plan.de", referrer: "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:28 +0100] "GET /static/vendor.js HTTP/2.0" 200 586908 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:28 +0100] "GET /static/fa-solid-900.woff2 HTTP/2.0" 200 78268 "https://mail-intern-1.plan.de/static/vendor.css" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:28 +0100] "GET /favicon.ico HTTP/2.0" 200 2487 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "POST /sso/login?url=/webmail/?homepage HTTP/2.0" 302 203 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail HTTP/2.0" 301 162 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/ HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/sso.php HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/index.php?sso&hash=12297f6d55034e1d9a0f1b1ea22eaa63ffe3423a HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/ HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/sso.php HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/index.php?sso&hash=2d25d6178dcf62548c0d375a3a0271e58675b34d HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/ HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/sso.php HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/index.php?sso&hash=c580b70bab710311d5187ed671822f08b5871937 HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/ HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/sso.php HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/index.php?sso&hash=47f839ae4aa56e861e82091191713f712fc4e050 HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/ HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/sso.php HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/index.php?sso&hash=5d3ef7510dcced24feac8efde568069f265875fe HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/ HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/sso.php HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/index.php?sso&hash=955e064254e12feb97d12deab41d3fb944bf5a22 HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
front-1  | 172.24.1.1 - - [15/Jan/2025:12:37:33 +0100] "GET /webmail/ HTTP/2.0" 302 0 "https://mail-intern-1.plan.de/sso/login?url=/webmail/?homepage" "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
```

</details>

### Web Browser HAR

The HAR contains the following redacted content:
- `user_name`: local part of the e-mail address of the user used for authentication
- `email_domain.tld`: the domain part of the e-mail address of the user used for authentication
- `user_password`: the password of the user used for authentication

[mail-intern-1.plan.de_Archive [25-01-15 12-09-02].json](https://github.com/user-attachments/files/18424192/mail-intern-1.plan.de_Archive.25-01-15.12-09-02.json)

### `docker-compose.yml`

<details>
<summary>docker-compose.yml</summary>

```yml
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - front
      - back
    logging:
      options:
        tag: mailu-redis
    volumes:
      - "/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 172.24.159.254

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    restart: unless-stopped
    env_file: mailu.env
    logging:
      options:
        tag: mailu-front
    ports:
      - "10.232.69.6:80:80"
      - "10.232.69.6:443:443"
      - "10.232.69.6:25:25"
      - "10.232.69.6:465:465"
      - "10.232.69.6:587:587"
      - "10.232.69.6:110:110"
      - "10.232.69.6:995:995"
      - "10.232.69.6:143:143"
      - "10.232.69.6:993:993"
      - "10.232.69.6:4190:4190"
    networks:
      - front
      - back
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 172.24.159.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2024.06}
    restart: unless-stopped
    env_file: mailu.env
    logging:
      options:
        tag: mailu-resolver
    networks:
      front:
        ipv4_address: 172.24.159.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    restart: unless-stopped
    env_file: mailu.env
    logging:
      options:
        tag: mailu-admin
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    networks:
      - front
      - back
    depends_on:
      - redis
      - resolver
    dns:
      - 172.24.159.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    restart: unless-stopped
    env_file: mailu.env
    logging:
      options:
        tag: mailu-imap
    volumes:
      - "/mailu/mail:/mail"
      - "/mailu/overrides/dovecot:/overrides:ro"
    networks:
      - front
    depends_on:
      - front
      - resolver
    dns:
      - 172.24.159.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    restart: unless-stopped
    env_file: mailu.env
    networks:
      - front
    logging:
      options:
        tag: mailu-smtp
    volumes:
      - "/mailu/mailqueue:/queue"
      - "/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 172.24.159.254

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}
    hostname: antispam
    restart: unless-stopped
    env_file: mailu.env
    logging:
      options:
        tag: mailu-antispam
    networks:
      - front
      - noinet
    volumes:
      - "/mailu/filter:/var/lib/rspamd"
      - "/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - resolver
    dns:
      - 172.24.159.254

  # Optional services



  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2024.06}
    restart: unless-stopped
    hostname: webmail
    env_file: mailu.env
    logging:
      options:
        tag: mailu-webmail
    volumes:
      - "/mailu/webmail:/data"
      - "/mailu/overrides/snappymail:/overrides:ro"
    networks:
      - front
      - back
    depends_on:
      - front
      - resolver
    dns:
      - 172.24.159.254

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.159.0/24
  back:
    driver: bridge
  noinet:
    driver: bridge
    internal: true

```

</details>

### `mailu.env`

Note: Antivirus, Macro-Scanning and fulltext search is intentionally disabled.

The `mailu.env` contains the following redacted content:
- `SECRET_KEY`
- `DOMAIN`
- `API_TOKEN`

<details>
<summary>mailu.env</summary>

```sh
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=AAAAAAAAAAAAAAAA

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=172.24.0.0/16

# Main mail domain
DOMAIN=email-domain.tld

# Hostnames for this server, separated with commas
HOSTNAMES=email-domain.tld,second-email-domain.tld

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=cert

# Authentication rate limit per IP (per /24 on ipv4 and /48 on ipv6)
AUTH_RATELIMIT_IP=100/minute

# Authentication rate limit per user (regardless of the source-IP)
AUTH_RATELIMIT_USER=50/day

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=True

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, snappymail, none). To enable this feature, recreate the docker-compose.yml file via setup.
WEBMAIL=snappymail

# Expose the API interface (value: true, false)
API=true

# Dav server implementation (value: radicale, none). To enable this feature, recreate the docker-compose.yml file via setup.
WEBDAV=none

# Antivirus solution (value: clamav, none). To enable this feature, recreate the docker-compose.yml file via setup.
ANTIVIRUS=none

# Scan Macros solution (value: true, false). To enable this feature, recreate the docker-compose.yml file via setup.
SCAN_MACROS=false

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Message rate limit (per user)
MESSAGE_RATELIMIT=200/day

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Enable fetchmail
FETCHMAIL_ENABLED=False

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: gz, bz2, zstd)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

# IMAP full-text search is enabled by default.
# Set the following variable to off in order to disable the feature
# or a comma separated list of language codes to support
FULL_TEXT_SEARCH=off

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/webmail

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/webmail

# Path to the API interface if enabled
WEB_API=/api

# Website name
SITENAME=Mailu

# Linked Website URL
WEBSITE=https://mail-intern-1.plan.de



###################################
# Advanced settings
###################################

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Number of rounds used by the password hashing scheme
CREDENTIAL_ROUNDS=12

# Header to take the real ip from
REAL_IP_HEADER=X-Real-IP

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=0.0.0.0/0, ::0

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=INFO

# Timezone for the Mailu containers. See this link for all possible values https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TZ=Europe/Berlin

# Default spam threshold used for new users
DEFAULT_SPAM_THRESHOLD=99

# API token required for authenticating to the RESTful API.
# This is a mandatory setting for using the RESTful API.
API_TOKEN=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

# Whether tika should be enabled (scan/OCR email attachements). To enable this feature, recreate the docker-compose.yml file via setup.
FULL_TEXT_SEARCH_ATTACHMENTS=

LD_PRELOAD=/usr/lib/libhardened_malloc.so

```

</details>
