### DISCUSSION TITLE
cannot access webmail

### DISCUSSION THREAD

**Discussion by sishida-gsx** [Mailu/Mailu#3774] [User support]
accessing admin page has no problem
https://{IP_address}/sso/login?url=/webmail/?homepage
but accessing /webmail causes redirect loop. I am using roundcube for webmail.
<img width="500" alt="スクリーンショット 2025-02-20 11 25 29" src="https://github.com/user-attachments/assets/77510799-31df-4b54-804a-56a9722441ca" />

webmail container does seem to be working.  docker-compose logs do not seem to show any problem.  Can anyone help me figure way the problem?

```
    Name                     Command                  State                                                                                     Ports                                                                               
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
mailu_admin_1       /bin/sh -c /start.py             Up (healthy)                                                                                                                                                                     
mailu_antispam_1    /bin/sh -c /start.py             Up (healthy)                                                                                                                                                                     
mailu_fetchmail_1   /fetchmail.py                    Up (healthy)                                                                                                                                                                     
mailu_front_1       /bin/sh -c /start.py             Up (healthy)   ::1:110->110/tcp,172.16.1.20:110->110/tcp, 172.16.1.20:143->143/tcp,::1:143->143/tcp, 172.16.1.20:25->25/tcp,::1:25->25/tcp, 4190/tcp,                            
                                                                    172.16.1.20:443->443/tcp,::1:443->443/tcp,172.16.1.20:8443->443/tcp, ::1:465->465/tcp,172.16.1.20:465->465/tcp, ::1:587->587/tcp,172.16.1.20:587->587/tcp,        
                                                                    172.16.1.20:80->80/tcp,172.16.1.20:8080->80/tcp,::1:80->80/tcp, ::1:993->993/tcp,172.16.1.20:993->993/tcp, ::1:995->995/tcp,172.16.1.20:995->995/tcp              
mailu_imap_1        /bin/sh -c /start.py             Up (healthy)                                                                                                                                                                     
mailu_redis_1       docker-entrypoint.sh redis ...   Up             6379/tcp                                                                                                                                                          
mailu_resolver_1    /bin/sh -c /start.py             Up (healthy)                                                                                                                                                                     
mailu_smtp_1        /bin/sh -c /start.py             Up (healthy)                                                                                                                                                                     
mailu_webmail_1     /bin/sh -c /start.py             Up (healthy)   80/tcp   
```

my docker-compose.yml is 

```
version: '2'

services:

  front:
    image: ghcr.io/mailu/nginx:$VERSION
    restart: always
    env_file: .env
    logging:
      driver: $LOG_DRIVER
    ports:
    - "$BIND_ADDRESS4:8080:80"
    - "$BIND_ADDRESS4:8443:443"
    - "$BIND_ADDRESS4:80:80"
    - "$BIND_ADDRESS4:443:443"
    - "$BIND_ADDRESS4:110:110"
    - "$BIND_ADDRESS4:143:143"
    - "$BIND_ADDRESS4:993:993"
    - "$BIND_ADDRESS4:995:995"
    - "$BIND_ADDRESS4:25:25"
    - "$BIND_ADDRESS4:465:465"
    - "$BIND_ADDRESS4:587:587"
    - "$BIND_ADDRESS6:80:80"
    - "$BIND_ADDRESS6:443:443"
    - "$BIND_ADDRESS6:110:110"
    - "$BIND_ADDRESS6:143:143"
    - "$BIND_ADDRESS6:993:993"
    - "$BIND_ADDRESS6:995:995"
    - "$BIND_ADDRESS6:25:25"
    - "$BIND_ADDRESS6:465:465"
    - "$BIND_ADDRESS6:587:587"
    volumes:
      - "$ROOT/certs:/certs"
      - "$ROOT/overrides/nginx:/overrides"
    depends_on:
      - resolver
    networks:
      - default
    dns:
      - 192.168.203.254

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "$ROOT/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ghcr.io/mailu/dovecot:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/mail:/mail"
      - "$ROOT/overrides:/overrides"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ghcr.io/mailu/postfix:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/overrides:/overrides"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ghcr.io/mailu/rspamd:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/filter:/var/lib/rspamd"
      - "$ROOT/dkim:/dkim"
      - "$ROOT/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  admin:
    image: ghcr.io/mailu/admin:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ghcr.io/mailu/unbound:$VERSION
    env_file: .env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  webmail:
    image: "ghcr.io/mailu/$WEBMAIL:$VERSION"
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/webmail:/data"
      - "$ROOT/overrides/$WEBMAIL:/overrides:ro"
    depends_on:
      - imap
      - resolver
    dns:
      - 192.168.203.254

  fetchmail:
    image: ghcr.io/mailu/fetchmail:$VERSION
    restart: always
    env_file: .env
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - 192.168.203.254
    
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: $SUBNET
  noinet:
    driver: bridge
    internal: true
```
