### DISCUSSION TITLE
Why am I slow to send emails

### DISCUSSION THREAD

**Discussion by liuhr-ncu** [Mailu/Mailu#3802] [User support]
I deployed the mail server using mailu2.0 in a LAN environment, but after the deployment was complete, I found that sending emails was very slow (note that the smtp log display delay=5.3). The following are log files:
```yml
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "./redis:/data"
    depends_on:
      - bind
    dns:
      - 192.168.203.254
      
  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
    networks:
      - default
      - webmail
    volumes:
      - "./certs:/certs"
      - "./overrides/nginx:/overrides:ro"
    depends_on:
      - bind
    dns:
      - 192.168.203.254
      
  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "./data:/data"
      - "./dkim:/dkim"
      - "./start.py:/start.py"
    depends_on:
      - redis
      - bind
    dns:
      - 192.168.203.254
      
  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "./mail:/mail"
      - "./overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - bind
    dns:
      - 192.168.203.254
      
  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "./mailqueue:/queue"
      - "./overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - bind
    dns:
      - 192.168.203.254

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2.0}
    hostname: oletools
    restart: always
    networks:
      - noinet
    depends_on:
      - bind
    dns:
      - 192.168.203.254
            
  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - noinet
    volumes:
      - "./filter:/var/lib/rspamd"
      - "./overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - bind
    dns:
      - 192.168.203.254
  # Optional services


  fetchmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "./data/fetchmail:/data"
    depends_on:
      - admin
      - smtp
      - imap
      - bind
    dns:
      - 192.168.203.254
      
  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "./webmail:/data"
      - "./overrides/roundcube:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front
  
  #dns bind
  bind:
    image: sameersbn/bind:9.16.1-20200524
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254
    ports:
      - "53:53"
      - "53:53/udp"
      - "10000:10000"
    volumes:
      - './bind:/data'
    environment:
      ROOT_PASSWORD: 123456
      
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  webmail:
    driver: bridge
  noinet:
    driver: bridge
    internal: true
```

```log
smtp-1  | Mar 21 16:19:38 mail postfix/smtpd[418]: connect from mailu-front-1.mailu_default[192.168.203.3]
smtp-1  | Mar 21 16:19:38 mail postfix/smtpd[418]: discarding EHLO keywords: PIPELINING
smtp-1  | Mar 21 16:19:38 mail postfix/smtpd[418]: discarding EHLO keywords: PIPELINING
smtp-1  | Mar 21 16:19:38 mail postfix/smtpd[418]: DF92F480AC97: client=mailu-webmail-1.mailu_webmail[172.25.0.3], sasl_method=XCLIENT, sasl_username=admin@xc.ht
smtp-1  | Mar 21 16:19:38 mail postfix/cleanup[422]: DF92F480AC97: message-id=<ea9080e76c2312200870406476d237ee@xc.ht>
smtp-1  | Mar 21 16:19:44 mail postfix/qmgr[349]: DF92F480AC97: from=<admin@xc.ht>, size=334, nrcpt=1 (queue active)
smtp-1  | Mar 21 16:19:44 mail postfix/smtpd[418]: disconnect from mailu-webmail-1.mailu_webmail[172.25.0.3] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=1 quit=1 commands=6/7
smtp-1  | Mar 21 16:19:44 mail postfix/lmtp[429]: DF92F480AC97: to=<admin@xc.ht>, relay=imap[192.168.203.7]:2525, delay=5.3, delays=5.1/0.06/0/0.14, dsn=2.0.0, status=sent (250 2.0.0 <admin@xc.ht> qIT3AyAh3WeLAAAAOT3Amg Saved)
```
