### DISCUSSION TITLE
failed to create network mailu_default: Error response from daemon: Pool overlaps with other one on this address space

### DISCUSSION THREAD

**Discussion by tusooa** [Mailu/Mailu#3813] [User support]
mailu 2.0

Very infrequently, when running `docker compose up -d`, it will give the error:

```
 Network mailu_noinet  Creating
 Network mailu_noinet  Created
 Network mailu_webmail  Creating
 Network mailu_webmail  Created
 Network mailu_default  Creating
 Network mailu_default  Error
failed to create network mailu_default: Error response from daemon: Pool overlaps with other one on this address space
```

Usually, `docker compose down` and then `docker compose up -d` will make it start normally again. 

Observing the logs, it is because that in the network configuration:

```
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  webmail:
    driver: bridge
  noinet:
    driver: bridge
    internal: true
```

"default" is created after "webmail" and "noinet", and the subnet can be already taken by either of the two.
