### DISCUSSION TITLE
Trouble Reaching Admin Container with Antispam

### DISCUSSION THREAD

**Discussion by okdlukas** [Mailu/Mailu#3848] [User support]
Hi there. I have a mailu setup with portainer and got it all running. The only container unhealthy is the Antispam which logs say that it is contantly trying to reach the admin container but is not able to. 

If i login manually into the antispam container i can reach the admin container without trouble. Only the automatic process does not work and is not able to get through. 

My Setup uses an upstream resolver so i deactivated the unbound resolver that comes with mailu. Is there any dependence that could interfere with the antispam if the resolver is not set via container? 

The Setup looks like this: 

```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

services:

  # External dependencies
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - "/mailu/redis:/data"

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    container_name: front
    restart: always
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "x.x.x.x:80:80"
      - "x.x.x.x:443:443"
      - "x.x.x.x:25:25"
      - "x.x.x.x:465:465"
      - "x.x.x.x:587:587"
      #- "x.x.x.x:110:110"
      - "x.x.x.x:995:995"
      #- "x.x.x.x:143:143"
      - "x.x.x.x:993:993"
      - "x.x.x.x:4190:4190"``
    networks:
      - default
      - webmail
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides:ro"

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    container_name: admin
    restart: always
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    depends_on:
      - redis

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    container_name: imap
    restart: always
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "/mailu/mail:/mail"
      - "/mailu/overrides/dovecot:/overrides:ro"
    networks:
      - default
    depends_on:
      - front

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    container_name: smtp
    restart: always
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "/mailu/mailqueue:/queue"
      - "/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2024.06}
    container_name: oletools
    hostname: oletools
    logging:
      driver: journald
      options:
        tag: mailu-oletools
    restart: always
    networks:
      - oletools


  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}
    container_name: antispam
    hostname: antispam
    restart: always
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - oletools
    volumes:
      - "/mailu/filter:/var/lib/rspamd"
      - "/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools

  # Optional services



  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2024.06}
    restart: always
    container_name: webmail
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-webmail
    volumes:
      - "/mailu/webmail:/data"
      - "/mailu/overrides/roundcube:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

volumes:
  mailu:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.48.9.0/24
  webmail:
    driver: bridge
  oletools:
    driver: bridge
    internal: true`

ENV:
`SECRET_KEY=xxxxxx
SUBNET=10.48.9.0/24
DOMAIN=mailu-test.abc.de
HOSTNAMES=mailu-test.abc.de
POSTMASTER=admin
TLS_FLAVOR=letsencrypt
AUTH_RATELIMIT_IP=5/hour
AUTH_RATELIMIT_USER=50/day
DISABLE_STATISTICS=True
ADMIN=true
WEBMAIL=roundcube
API=false
WEBDAV=none
ANTIVIRUS=clamav
SCAN_MACROS=true
MESSAGE_SIZE_LIMIT=50000000
MESSAGE_RATELIMIT=200/day
RELAYNETS=
RELAYHOST=
FETCHMAIL_ENABLED=False
FETCHMAIL_DELAY=600
RECIPIENT_DELIMITER=+
DMARC_RUA=admin
DMARC_RUF=admin
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!
COMPRESSION=
COMPRESSION_LEVEL=
FULL_TEXT_SEARCH=en
WEBROOT_REDIRECT=/admin
WEB_ADMIN=/admin
WEB_WEBMAIL=/webmail
WEB_API=/api
SITENAME=Mailu
WEBSITE=https://mailu-test.abc.de
COMPOSE_PROJECT_NAME=mailu
CREDENTIAL_ROUNDS=12
REAL_IP_HEADER=
REAL_IP_FROM=
REJECT_UNLISTED_RECIPIENT=
LOG_LEVEL=INFO
TZ=Etc/UTC
DEFAULT_SPAM_THRESHOLD=80
API_TOKEN=
FULL_TEXT_SEARCH_ATTACHMENTS=
INITIAL_ADMIN_ACCOUNT=admin
INITIAL_ADMIN_DOMAIN=mailu-test.abc.de
INITIAL_ADMIN_PW=xxx
INITIAL_ADMIN_MODE=ifmissing
HTTP_PROXY=xxx
HTTPS_PROXY=xxx


```
