### ISSUE TITLE
Mailu Stack wont start

### ISSUE THREAD

**Issue by bilyboy785** [Mailu/Mailu#1080]
Hello, I'm running Mailu on 1.5, and stack wont start, i've got many errors like : 

```imap         | Traceback (most recent call last):
imap         |   File "/start.py", line 11, in <module>
imap         |     os.environ["FRONT_ADDRESS"] = socket.gethostbyname("front")
imap         | socket.gaierror: [Errno -2] Name does not resolve
imap         | Traceback (most recent call last):
imap         |   File "/start.py", line 11, in <module>
imap         |     os.environ["FRONT_ADDRESS"] = socket.gethostbyname("front")
imap         | socket.gaierror: [Errno -2] Name does not resolve
imap         | Traceback (most recent call last):
imap         |   File "/start.py", line 11, in <module>
imap         |     os.environ["FRONT_ADDRESS"] = socket.gethostbyname("front")
imap         | socket.gaierror: [Errno -2] Name does not resolve
imap         | Traceback (most recent call last):
imap         |   File "/start.py", line 11, in <module>```

Somebody can help me ?

**Comment by kaiyou** [comment]
Sorry about the delay. This looks either like something is wrong with your Docker internal DNS or your front container has issues starting up. Could you provide more logs from that container?

**Comment by unixfox** [comment]
I fixed the issue by inserting `hostname: front` in the service `front` like this:
````
front:
        image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.6}
        env_file: mailu.env
        hostname: front
        logging:
            driver: json-file
        ports:
            - target: 25
              published: 25
              mode: host
            - target: 465
              published: 465
              mode: host
            - target: 587
              published: 587
              mode: host
            - target: 110
              published: 110
              mode: host
            - target: 995
              published: 995
              mode: host
            - target: 143
              published: 143
              mode: host
            - target: 993
              published: 993
              mode: host
        volumes:
            - "/data/mailu/certs:/certs"
            - "/data/mailu/overrides/nginx:/overrides"
        networks:
            - default
            - global
        deploy:
            replicas: 1
````
