### ISSUE TITLE
Issues with HOST env vars

### ISSUE THREAD

**Issue by boldt** [Mailu/Mailu#1101]
I want to prefix all containers with `mailu-`, but it does not work. To do so, I configured my docker-compose as follows:

```yaml
mailu-redis:
    container_name: mailu-redis
...
mailu-front:
    container_name: mailu-front
...
mailu-admin:
    container_name: mailu-admin
    ...
    depends_on:
      - mailu-redis
...
```

Based on the [infrastructure settings](https://mailu.io/master/configuration.html#infrastructure-settings), I added the following to my `mailu.env`:

```
HOST_REDIS=mailu-redis
HOST_IMAP=mailu-imap
HOST_POP3=mailu-imap
HOST_SMTP=mailu-smtp
HOST_ADMIN=mailu-admin
HOST_ANTISPAM=mailu-antispam
HOST_WEBMAIL=mailu-webmail

FRONT_ADDRESS=mailu-front
WEBMAIL_ADDRESS=mailu-webmail
IMAP_ADDRESS=mailu-imap
```

# Issue 1

It's unclear from the [infrastructure settings](https://mailu.io/master/configuration.html#infrastructure-settings), what's the diffrence between:

* `HOST_WEBMAIL` and `WEBMAIL_ADDRESS`
* `HOST_IMAP` and `IMAP_ADDRESS`

# Issue 2

What means `HOST_HOSTIMAP`?

# Issue 3

I don't have an env var to configure the database and fetchmail, e.g., for my container `mailu-database` and `mailu-fetchmail`

# Related issue

- #884 #940 - Seems to fix issue 1 and 2
