### ISSUE TITLE
Authentication fails SMTP, IMAP & WebMail

### ISSUE THREAD

**Issue by ItsEcholot** [Mailu/Mailu#1156]
Webmail (Rainloop), smtp & imap authentication fails even though admin login works perfectly.

`2019/09/02 15:43:25 [info] 12#12: *2856 upstream sent invalid response: "NO [AUTHENTICATIONFAILED] Authentication failed." while reading response from upstream, client: 131.255.7.26, server: 0.0.0.0:993, login: "froster2406@frostbolt.ch", upstream: 192.168.0.5:143`

docker-compose:
```
version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/home/mailu/redis:/data"
    labels:
      - traefik.enable=false    

  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      #- "116.203.223.222:80:80"
      #- "::1:80:80"
      #- "116.203.223.222:443:443"
      #- "::1:443:443"
      - "116.203.223.222:25:25"
      - "::1:25:25"
      - "116.203.223.222:465:465"
      - "::1:465:465"
      - "116.203.223.222:587:587"
      - "::1:587:587"
      - "116.203.223.222:110:110"
      - "::1:110:110"
      - "116.203.223.222:995:995"
      - "::1:995:995"
      - "116.203.223.222:143:143"
      - "::1:143:143"
      - "116.203.223.222:993:993"
      - "::1:993:993"
    networks:
      - default
      - traefik_default
    volumes:
      - "/home/traefik/ssl/mail-new.frostbolt.ch.crt:/certs/cert.pem"
      - "/home/traefik/ssl/mail-new.frostbolt.ch.key:/certs/key.pem"
      - "/home/mailu/overrides/nginx:/overrides"
    labels:
      - traefik.backend=mailu-front
      - traefik.frontend.rule=Host:mail-new.domain.com
      - traefik.port=80

#  resolver:
#    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.7}
#    env_file: mailu.env
#    restart: always
#    networks:
#      default:
#        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/data:/data"
      - "/home/mailu/dkim:/dkim"
    depends_on:
      - redis
    labels:
      - traefik.enable=false

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/mail:/mail"
      - "/home/mailu/overrides:/overrides"
    depends_on:
      - front
    labels:
      - traefik.enable=false

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/overrides:/overrides"
    depends_on:
      - front
    #  - resolver
    #dns:
    #  - 192.168.203.254
    labels:
      - traefik.enable=false

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/filter:/var/lib/rspamd"
      - "/home/mailu/dkim:/dkim"
      - "/home/mailu/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
    #  - resolver
    #dns:
    #  - 192.168.203.254
    labels:
      - traefik.enable=false

  # Optional services

  webdav:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/dav:/data"
    labels:
      - traefik.enable=false

  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    #depends_on:
    #  - resolver
    #dns:
    #  - 192.168.203.254
    labels:
      - traefik.enable=false

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rainloop:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/webmail:/data"
    depends_on:
      - imap
    labels:
      - traefik.enable=false

networks:
  traefik_default:
    external:
      name: traefik_default
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```

mailu.env
```
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

#TLS_CERT_FILENAME=
#TLS_KEYPAIR_FILENAME=

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=xxx

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.168.203.0/24

# Main mail domain
DOMAIN=domain.com

# Hostnames for this server, separated with comas
HOSTNAMES=mail-new.domain.com

# Postmaster local part (will append the main mail domain)
POSTMASTER=postmaster

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=mail

# Authentication rate limit (per source IP address)
AUTH_RATELIMIT=10/minute;1000/hour 

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=True

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=rainloop

# Dav server implementation (value: radicale, none)
WEBDAV=radicale

# Antivirus solution (value: clamav, none)
#ANTIVIRUS=none

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=75000000

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: bz2, gz)
COMPRESSION=gz
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=6

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/

# Website name
SITENAME=Mail

# Linked Website URL
WEBSITE=https://mail-new.domain.com



###################################
# Advanced settings
###################################

# Log driver for front service. Possible values:
# json-file (default)
# journald (On systemd platforms, useful for Fail2Ban integration)
# syslog (Non systemd platforms, Fail2Ban integration. Disables `docker-compose log` for front!)
# LOG_DRIVER=json-file

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Default password scheme used for newly created accounts and changed passwords
# (value: BLF-CRYPT, SHA512-CRYPT, SHA256-CRYPT, MD5-CRYPT, CRYPT)
PASSWORD_SCHEME=BLF-CRYPT

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=no

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

###################################
# Database settings
###################################
DB_FLAVOR=sqlite
```

Any help is greatly appreciated

**Comment by kaiyou** [comment]
Could you provide a bit more logs, from front, imap and admin containers?

**Comment by ItsEcholot** [comment]
For sure here's some more logs:

front:
```
2019/09/02 16:47:16 [info] 12#12: *3132 client 40.85.91.8:12296 connected to 0.0.0.0:993

2019/09/02 16:47:16 [info] 12#12: *3132 peer closed connection in SSL handshake while SSL handshaking, client: 40.85.91.8, server: 0.0.0.0:993

2019/09/02 16:47:16 [info] 12#12: *3133 client 40.85.91.8:12297 connected to 0.0.0.0:993

2019/09/02 16:47:16 [info] 12#12: *3134 client 40.85.91.8:12298 connected to 0.0.0.0:993

127.0.0.1 - - [02/Sep/2019:16:47:16 +0000] "GET /auth/email HTTP/1.0" 200 0 "-" "-"

2019/09/02 16:47:18 [info] 12#12: *3134 upstream sent invalid response: "NO [AUTHENTICATIONFAILED] Authentication failed." while reading response from upstream, client: 40.85.91.8, server: 0.0.0.0:993, login: "mail@domain.com", upstream: 192.168.0.5:143
```

admin:
```
127.0.0.1 - - [02/Sep/2019:16:47:15 +0000] "GET /ui/login?next=ui.index HTTP/1.1" 200 4039 "-" "curl/7.65.1"

192.168.0.4 - - [02/Sep/2019:16:47:16 +0000] "GET /internal/auth/email HTTP/1.0" 200 0 "-" "-"

192.168.0.5 - - [02/Sep/2019:16:47:16 +0000] "GET /internal/dovecot/passdb/mail@domain.com HTTP/1.1" 200 67 "-" "Python/3.7 aiohttp/3.5.4"

127.0.0.1 - - [02/Sep/2019:16:47:45 +0000] "GET /ui/login?next=ui.index HTTP/1.1" 200 4039 "-" "curl/7.65.1"
```

imap:
```
Sep 02 16:46:57 pop3-login: Info: Aborted login (no auth attempts in 0 secs): user=<>, rip=127.0.0.1, lip=127.0.0.1, secured, session=<uz9UuJSRZLV/AAAB>

Sep 02 16:47:18 imap-login: Info: Disconnected (auth failed, 1 attempts in 2 secs): user=<mail@domain.com>, method=PLAIN, rip=192.168.0.4, lip=192.168.0.5, session=<4HSAuZSRtoLAqAAE>

Sep 02 16:47:27 pop3-login: Info: Aborted login (no auth attempts in 0 secs): user=<>, rip=127.0.0.1, lip=127.0.0.1, secured, session=<sW8iupSR95p/AAAB>

Sep 02 16:47:57 pop3-login: Info: Aborted login (no auth attempts in 0 secs): user=<>, rip=127.0.0.1, lip=127.0.0.1, secured, session=<Qszwu5SRG7B/AAAB>
```

**Comment by kaiyou** [comment]
Okay. It looks like authentication against the nginx front is fine but dovecot then fails to authenticate. Dovecot authenticates the nginx container using its IP.

Could you check that your `SUBNET` setting is properly set?

**Comment by ItsEcholot** [comment]
My current setting is:

`# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)`
`SUBNET=192.168.203.0/24`

I currently have this set to the default as it said to only change it if it conflicts which it shouldn't. Could you guide me through the process of checking if the `SUBNET` is properly set?

These are the ips of the running containers after launching the docker-compose file (1. post in this issue):
![image](https://user-images.githubusercontent.com/2771251/64194949-9dcb6880-ce80-11e9-9098-17ea0a58294b.png)

**Comment by kaiyou** [comment]
But you did remove the network ipam settings from the compose file, didn't you? That would explain why your machines so not have addresses in your declared subnet.

**Comment by ItsEcholot** [comment]
I think you mean this part:

```
networks:
  traefik_default:
    external:
      name: traefik_default
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```

It is present in the compose. But I agree it is weird that my containers have a different subnet
