### ISSUE TITLE
Update of letsencrypt certificates not possible

### ISSUE THREAD

**Issue by oli-ver** [Mailu/Mailu#1164]
I cannot update the mailserver's letsencrypt certificates. The following error message is shown in the logs:
```
front_1      | Failed authorization procedure. webmail.myhost.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching https://127.0.0.1/.well-known/acme-challenge/<the-challenge>: Invalid host in redirect target "127.0.0.1". Only domain names are supported, not IP addresses
```

I don't know where this comes from as in the .env file host names and urls seem to be set correctly. 127.0.0.1 is not part of any configuration parameter.

Mailu-Version: 1.7 (actually the docker image is still listed as 1.6 when executing `docker container ls`, so I am not 100% sure. I did a `docker-compose pull` and `docker-compose up -d` after the 1.7 release.

**Comment by oli-ver** [comment]
Actually the docker-compose.yml has entries for 127.0.0.1 (mailu is executed behind a nginx proxy, but the certificates for letsencrypt are configured to be managed by mailu).
```
...
 # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.6}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "127.0.0.1:83:80"
      - "127.0.0.1:444:443"
...
```
