### ISSUE TITLE
Mailu Setup with traefik v2

### ISSUE THREAD

**Issue by Zelle97** [Mailu/Mailu#1300]
Hello, 
I was trying to setup Mailu as my new mail server. I already use traefik v2 and ran into some Issues with the setup. I already updated the certdumper ( as mentioned in this https://github.com/Mailu/Mailu/pull/1215 ) And the certificates seem fine. All the containers startup fine thats why im kind of lost atm.

I cant access the ui in any way.  Also some containers write out logs i dont quite get. 
All helps and tipps are appreciated :)

mailu_imap logs:
```
Dec 29 11:26:37 master: Info: Dovecot v2.3.7.2 (3c910f64b) starting up for imap, pop3, lmtp, sieve
Dec 29 11:27:06 pop3-login: Info: Aborted login (no auth attempts in 0 secs): user=<>, rip=127.0.0.1, lip=127.0.0.1, secured, session=<J/rAAdaah7J/AAAB>
Dec 29 11:27:36 pop3-login: Info: Aborted login (no auth attempts in 0 secs): user=<>, rip=127.0.0.1, lip=127.0.0.1, secured, session=<Z3KNA9aaeZF/AAAB>
```
mailu_smtp logs:
```
Dec 29 11:29:38 mail postfix/smtpd[128]: connect from localhost[127.0.0.1]
Dec 29 11:29:38 mail postfix/smtpd[128]: disconnect from localhost[127.0.0.1] quit=1 commands=1
Dec 29 11:30:08 mail postfix/smtpd[128]: connect from localhost[127.0.0.1]
Dec 29 11:30:08 mail postfix/smtpd[128]: disconnect from localhost[127.0.0.1] quit=1 commands=1
Dec 29 11:30:38 mail postfix/smtpd[128]: connect from localhost[127.0.0.1]
Dec 29 11:30:38 mail postfix/smtpd[128]: disconnect from localhost[127.0.0.1] quit=1 commands=1
````
My docker-compose:

```
version: '3'

services:
  certdumper:
    restart: always
    image: mailu/traefik-certdumper:master
    environment:
      - DOMAIN=mail.XXXXXX.xx
      - TRAEFIK_VERSION=v2
    volumes:
      - "/home/docker/traefik/letsencrypt:/traefik"
      - "/mnt/mail/certs:/output"
    userns_mode: "host"

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/mnt/mail/redis:/data"

  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "xx.xx.xx.xx:25:25"
      - "xx.xx.xx.xx:465:465"
      - "xx.xx.xx.xx:587:587"
      - "xx.xx.xx.xx:110:110"
      - "xx.xx.xx.xx:995:995"
      - "xx.xx.xx.xx:143:143"
      - "xx.xx.xx.xx:993:993"
    volumes:
      - "/mnt/mail/certs:/certs"
      - "/mnt/mail/overrides/nginx:/overrides"
    userns_mode: "host"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=web"
      - "traefik.http.routers.mail.rule=Host(`mail.XXXX.XXX`)"
      - "traefik.http.routers.mail.entrypoints=websecure"
      - "traefik.http.routers.mail.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.mail.tls.domains[0].main=XXXXXX.XX"
      - "traefik.http.routers.mail.tls.domains[0].sans=mail.XXXXXX.XX"

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-master}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mnt/mail/data:/data"
      - "/mnt/mail/dkim:/dkim"
    depends_on:
      - redis

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mnt/mail/mail:/mail"
      - "/mnt/mail/overrides:/overrides"
    depends_on:
      - front

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mnt/mail/mailqueue:/queue"
      - "/mnt/mail/overrides:/overrides"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mnt/mail/filter:/var/lib/rspamd"
      - "/mnt/mail/dkim:/dkim"
      - "/mnt/mail/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mnt/mail/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  webdav:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mnt/mail/dav:/data"

  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Webmail


networks:
  web:
    external: true
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24

```

**Comment by khannurien** [comment]
I think when you explicitly set `networks` for a service, you need to explicitly connect it to its default network too (usually `mailu_default`).

Either that, or just connect your Traefik container to Mailu's network -- that's what I did, and just added these labels to the `front` container:

```
    labels:
      - "traefik.http.services.mailu.loadbalancer.server.port=443"
      - "traefik.http.services.mailu.loadbalancer.server.scheme=https"
      - "traefik.http.routers.mailu.rule=Host(`mail.example.org`)"
      - "traefik.http.routers.mailu.tls.certresolver=le"
      - "traefik.http.routers.mailu.entrypoints=websecure"
```

**Comment by sholl** [comment]
It would be nice having such a great example for the docs in the traefik-section though.

**Comment by tomwiggers** [comment]
Why are you using the certdumper and NGINX when you have Traefik 2.0? Traefik 2.0 can proxy TCP too, not only HTTP(S). I am currently struggling with something similar, might open a seperate issue tho as I am not even getting this far. I am trying it without NGINX and certdumper.

**Comment by khannurien** [comment]
> 
> 
> It would be nice having such a great example for the docs in the traefik-section though.

Please point me to the correct file and I will gladly update the doc :-)

**Comment by Zelle97** [comment]
@khannurien Thank you for your tips :)

I tried to connect all containers to the default network (I renamed the mailu_default in the bottom). Only the front container is connected to both default and web but im still having the same problem.

Connecting the traefik container to the mailu network sounds way simpler, but im having a different problem there. I want my traefik and mailu to be in seperate files. How did you make the default network external so i can use it in a different file?

**Comment by sholl** [comment]
> > It would be nice having such a great example for the docs in the traefik-section though.
> 
> Please point me to the correct file and I will gladly update the doc :-)

the relevant file is 

   https://github.com/Mailu/Mailu/blob/master/docs/reverse.rst

Feel free to create a PR.

**Comment by khannurien** [comment]
> Connecting the traefik container to the mailu network sounds way simpler, but im having a different problem there. I want my traefik and mailu to be in seperate files. How did you make the default network external so i can use it in a different file?

I am not sure if I understood your question correctly. In your traefik docker-compose.yml file, declare mailu_default as external:

```
networks:
  example_default:
    external: true
  mailu_default:
    external: true
```

Connect traefik to mailu_default:

```
services:
  traefik:
    networks:
      - example_default
      - mailu_default
    image: traefik:latest
```

> Feel free to create a PR.

What should I do with the current Traefik v1 chapter? I feel most of it is outdated, but surely some people use Traefik v1. Should we make a Traefik section and subdivide it so I can add instructions regarding Traefik v2?

**Comment by Zelle97** [comment]
Thanks again @khannurien I got mailu and traefik to communicate :)
But know it seems like the mailu front doesent like my certificate:

```
2020/01/16 22:28:09 [info] 79#79: *29 SSL_do_handshake() failed (SSL: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:SSL alert number 42) while SSL handshaking, client: 172.24.0.3, server: 0.0.0.0:443
```

I checked and traefik is providing the right certificate so im a little lost why mailu doesn't like it.

**Comment by kaiyou** [comment]
@tomwiggers unfortunately traefik does not support SMTP or IMAP with starttls. And it will probably never do, so it is no valid option for replacing nginx in that role.

**Comment by alexanderadam** [comment]
Shouldn't it be possible since Træfik 2 allows Pass-Through?

@Zelle97 did you try `traefik.tcp.routers.your-smtp-or-imap-container.tls.passthrough=true`?
And do you have your configuration on GitHub or GitLab?

**Comment by Zelle97** [comment]
@alexanderadam I tried with passthrough but getting the same results.

I dont have my configuration on github but ill upload my compose and env file here.

@khannurien do you have a working traefikv2 docker-compose setup with mailu? If yes could i have a look at it?

**Comment by Zelle97** [comment]
I used the Mailu configuration setup utility to generate those files :)

docker-compose.yml:

```
version: '3'

services:
  certdumper:
    restart: always
    image: mailu/traefik-certdumper:master
    environment:
      - DOMAIN=mail.mydomain.example
      - TRAEFIK_VERSION=v2
    volumes:
      - "/home/docker/traefik/letsencrypt:/traefik"
      - "/mnt/mail/certs:/output"
    userns_mode: "host"

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/mnt/mail/redis:/data"

       # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
    volumes:
      - "/mnt/mail/certs:/certs"
      - "/mnt/mail/overrides/nginx:/overrides"
    userns_mode: "host"
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=default"
      - "traefik.tcp.routers.mail.tls.passthrough=true"
      - "traefik.http.services.mailu.loadbalancer.server.port=443"
      - "traefik.http.services.mailu.loadbalancer.server.scheme=https"
      - "traefik.http.routers.mail.rule=Host(`mail.mydomain.example`)"
      - "traefik.http.routers.mail.entrypoints=websecure"
      - "traefik.http.routers.mail.tls.certresolver=le"
      - "traefik.http.routers.mail.tls.domains[0].main=mail.mydomain.example"
      - "traefik.http.routers.mail.tls.domains[0].sans=mydomain.example"

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-master}
    env_file: mailu.env
    restart: always
    userns_mode: "host"
    networks:
     default:
        ipv4_address: 192.168.203.254

   admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mnt/mail/data:/data"
      - "/mnt/mail/dkim:/dkim"
    depends_on:
      - redis

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mnt/mail/mail:/mail"
      - "/mnt/mail/overrides:/overrides"
    depends_on:
      - front

  smtp:
      image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-master}
      restart: always
      env_file: mailu.env
      volumes:
        - "/mnt/mail/mailqueue:/queue"
        - "/mnt/mail/overrides:/overrides"
      depends_on:
        - front
        - resolver
      dns:
        - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mnt/mail/filter:/var/lib/rspamd"
      - "/mnt/mail/dkim:/dkim"
      - "/mnt/mail/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

 # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mnt/mail/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254


  webdav:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mnt/mail/dav:/data"

  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
  # Webmail

networks:
  web:
    external: true
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24


```

mailu.env:

```
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=XXXXXXXX

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!
)
SUBNET=192.168.203.0/24

# Main mail domain
DOMAIN=mydomain.example

# Hostnames for this server, separated with comas
HOSTNAMES=mail.mydomain.example,mydomain.example

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=mail

# Authentication rate limit (per source IP address)
AUTH_RATELIMIT=10/minute;1000/hour

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=False

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=none

# Dav server implementation (value: radicale, none)
WEBDAV=radicale

# Antivirus solution (value: clamav, none)
#ANTIVIRUS=clamav

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: bz2, gz)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=

# Website name
SITENAME=Zelles Mail

# Linked Website URL
WEBSITE=https://mail.mydomain.example

###################################
# Advanced settings
###################################

# Log driver for front service. Possible values:
# json-file (default)
# journald (On systemd platforms, useful for Fail2Ban integration)
# syslog (Non systemd platforms, Fail2Ban integration. Disables `docker-compose log` for front!)
# LOG_DRIVER=json-file

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Default password scheme used for newly created accounts and changed passwords
# (value: PBKDF2, BLF-CRYPT, SHA512-CRYPT, SHA256-CRYPT)
PASSWORD_SCHEME=PBKDF2

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

###################################
# Database settings
###################################
DB_FLAVOR=sqlite
```
