### ISSUE TITLE
Admin, apache proxy in 1.7

### ISSUE THREAD

**Issue by blogwebpl** [Mailu/Mailu#1309]
Hi,
After upgrade from 1.6 to 1.7 admin panel redirect to bad address.

When I write 
`https://domain.pl/poczta/ `
every thing is ok in 1.6 and 1.7 (poczta mean webmail)

When I write 
`https://domain.pl/admin/`
in 1.6 is ok, in 1.7 redirect to `http://127.0.0.1:8443/admin/ui/`

docker-compose.yml:

```
  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "127.0.0.1:8080:80"
      - "::1:80:80"
      - "127.0.0.1:8443:443"
      - "::1:443:443"
      - "10.10.2.245:25:25"
      - "::1:25:25"
      - "10.10.2.245:465:465"
      - "::1:465:465"
      - "10.10.2.245:587:587"
      - "::1:587:587"
      - "10.10.2.245:110:110"
      - "::1:110:110"
      - "10.10.2.245:995:995"
      - "::1:995:995"
      - "10.10.2.245:143:143"
      - "::1:143:143"
      - "10.10.2.245:993:993"
      - "::1:993:993"
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides"
```

Apache conf:
  ```
  ServerName domain.pl:443
    SSLEngine on
    SSLCertificateFile "/mailu/certs/cert.pem"
    SSLCertificateKeyFile "/mailu/certs/key.pem"
    SSLCertificateChainFile "/mailu/certs/vmail.ca"

    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off

    RewriteEngine on
    RewriteRule ^/admin$ /admin/ [R]
    RewriteRule ^/poczta$ /poczta/ [R]

    ProxyPass /poczta https://127.0.0.1:8443/poczta/
    ProxyPassReverse /poczta https://127.0.0.1:8443/poczta/

    ProxyPass /admin https://127.0.0.1:8443/admin/
    ProxyPassReverse /admin https://127.0.0.1:8443/admin/
```

**Comment by kaiyou** [comment]
That would be related to your proxy headers, as passed by your Apache reverse proxy. Make sure you have all the `X-Forwarded-` set.

**Comment by kaiyou** [comment]
Any news here?

**Comment by blogwebpl** [comment]
No news. I don't know how to set X-Forwarded. I don't understand why version 1.6 works and 1.7 don't.

**Comment by M1Sports20** [comment]
I am actually seeing the same thing here.  It works with v1.6 and not with v1.7.  The only difference is I am using traefik v2 as my frontend.

**Comment by kaiyou** [comment]
It is possible that some redirects used to be relative and are now absolute.

See the Apache mod_proxy doc about the forward headers : https://httpd.apache.org/docs/2.4/mod/mod_proxy.html

**Comment by M1Sports20** [comment]
@kaiyou I can take a look at it, I am using traefik and not apache so I am a little confused why this applies.  Maybe traefik has a equivalent setting.  As far as I can tell I did follow the 1.7 docs.

**Comment by M1Sports20** [comment]
@blogwebpl 
If it helps my problem was I was listening on https only.  The admin page gave me a url back in http.  If I forwarded all http to https traffic everything worked.  Again I am using traefik v2, so I don't know how you do that on apache.

**Comment by matzrm** [comment]
Same here. Fresh installation with apache as reverse proxy. Webmail works while my admin  is redirect to internal url (localhost:8443). Any helps? Which X-Forwarded I have to set?

**Comment by matzrm** [comment]
Finally I get it works. Add this to your configuration:

```
ProxyPreserveHost  On
RequestHeader set X-Forwarded-Host mail.domain.pl:443
RequestHeader set X-Forwarded-Proto https   
```

Remember that to use RequestHeader you have to enable apache2 module headers:
`a2enmod headers`

**Comment by numericalatina** [comment]
I can confirm that behind an **Nginx** reverse proxy, this issue is solved setting the following headers
```
        proxy_set_header Host      $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```
(of which the *Host* header is the real solution, the other is just to keep the originating IP address)

**Comment by brian-maloney** [comment]
I am seeing this regression as well, I've traced it to the admin container's handling of the `X-Forwarded-Proto` request header.

In 1.6:
```
# curl -H "Host: my.mail.server" -H "X-Forwarded-Host: my.mail.server" -H "X-Forwarded-Proto: https" -v 192.168.203.11/ui/ 2>&1 | grep Location
< Location: https://my.mail.server/ui/login?next=ui.index
```
In 1.7:
```
# curl -H "Host: my.mail.server" -H "X-Forwarded-Host: my.mail.server" -H "X-Forwarded-Proto: https" -v 192.168.203.8/ui/ 2>&1 | grep Location
< Location: http://my.mail.server/ui/login?next=ui.index
```

**Comment by Nebukadneza** [comment]
#1557 is merged, and the likely solution for this issue. Thus, closing …

**Comment by lucki1000** [comment]
Hi,

I also have a Problem with mailu, I tried it today to setup but my apache gives me only 502 Proxy error and I really don't know how to solve this.
Also I tried the apache conf from the op but the result doesnt changed, here's my docker-compose.yml generated from Mailu Configurator.

```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 172.15.255.254

  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "127.0.0.1:8880:80"
      - "127.0.0.1:4440:443"
      - "127.0.0.1:25:25"
      - "127.0.0.1:465:465"
      - "127.0.0.1:587:587"
      - "127.0.0.1:110:110"
      - "127.0.0.1:995:995"
      - "127.0.0.1:143:143"
      - "127.0.0.1:993:993"
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 172.15.255.254

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 172.15.255.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 172.15.255.254

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mail:/mail"
      - "/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 172.15.255.254

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mailqueue:/queue"
      - "/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 172.15.255.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.9}
    hostname: antispam
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/var/lib/rspamd"
      - "/mailu/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 172.15.255.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 172.15.255.254


  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/data/fetchmail:/data"
    depends_on:
      - resolver
    dns:
      - 172.15.255.254

  # Webmail

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/12
```

My env file:
```
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=172.0.0.0/12

# Main mail domain
DOMAIN=example.de

# Hostnames for this server, separated with comas
HOSTNAMES=mail.example.de

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=letsencrypt

# Authentication rate limit per IP (per /24 on ipv4 and /56 on ipv6)
AUTH_RATELIMIT_IP=60/hour

# Authentication rate limit per user (regardless of the source-IP)
AUTH_RATELIMIT_USER=100/day

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=False

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=none

# Dav server implementation (value: radicale, none)
WEBDAV=none

# Antivirus solution (value: clamav, none)
ANTIVIRUS=clamav

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Message rate limit (per user)
MESSAGE_RATELIMIT=200/day

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: gz, bz2, lz4, zstd)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

# IMAP full-text search is enabled by default. Set the following variable to off in order to disable the feature.
# FULL_TEXT_SEARCH=off

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=

# Path to the admin interface if enabled
WEB_ADMIN=/mail-admin

# Path to the webmail if enabled
WEB_WEBMAIL=

# Website name
SITENAME=My Mail Server

# Linked Website URL
WEBSITE=



###################################
# Advanced settings
###################################

# Log driver for front service. Possible values:
# json-file (default)
# journald (On systemd platforms, useful for Fail2Ban integration)
# syslog (Non systemd platforms, Fail2Ban integration. Disables `docker-compose log` for front!)
# LOG_DRIVER=json-file

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Number of rounds used by the password hashing scheme
CREDENTIAL_ROUNDS=12

# Header to take the real ip from
REAL_IP_HEADER=MY_PUBLIC_IP

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

# Timezone for the Mailu containers. See this link for all possible values https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TZ=Etc/UTC

###################################
# Database settings
###################################
DB_FLAVOR=sqlite

```
And the last file my apache config:
```
<IfModule mod_ssl.c>
<VirtualHost *:443> 
    ServerName mail.example.de
    ProxyPass / http://0.0.0.0:4440/
    ProxyPassReverse / http://0.0.0.0:4440/
        RewriteEngine on
        SSLEngine on
        SSLProxyEngine on
        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        RewriteEngine on
        RewriteRule ^/admin$ /admin/ [R]
        ProxyPass / https://127.0.0.1:4440/
        ProxyPassReverse / https://127.0.0.1:4440/
        ProxyPass /admin https://127.0.0.1:4440/admin/
        ProxyPassReverse /admin https://127.0.0.1:4440/admin/

# Some rewrite rules in this file were disabled on your HTTPS site,
# because they have the potential to create redirection loops.

# RewriteCond %{SERVER_NAME} =mail.example.de
# RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]

SSLCertificateFile /etc/letsencrypt/live/mail.example.de/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/mail.example.de/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

Hopefully anyone can help me :)
