### ISSUE TITLE
Fetchmail: wrong SSL_Version 

### ISSUE THREAD

**Issue by sholl** [Mailu/Mailu#1348]
mailu/fetchmail:v1.7
Is there an option to set the SSL-Version used by fetchmail?

The error in the logs of the fetchmail-container:
```
[...]
fetchmail_1   | fetchmail: socket error while fetching from user@pop3.web.de
fetchmail_1   | fetchmail: OpenSSL reported: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
fetchmail_1   | fetchmail: SSL connection failed.
[...]
```
Perhaps it is my very own configuration of the container?
```
 fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

```
