### ISSUE TITLE
traefik certdumper not working on v2

### ISSUE THREAD

**Issue by bd8392** [Mailu/Mailu#1413]
Something is wrong with the command I think...mv can't find the dumped certs, because they get not dumped...thats may config:
```
  certdumper:
    image: 
    environment:
      DOMAIN: test.something.com
      TRAEFIK_VERSION: v2
    volumes:
     - traefik_reverseproxy_letsencrypt:/traefik
     - mailu_certs:/output
    networks:
     - net
    logging:
      driver: json-file
```
logs show:
```
bw8069i Fri Mar 20 18:56:39 UTC 2020 Dumping certificates
bw8069i Fri Mar 20 18:56:39 UTC 2020 Certificate or key differ, updating
bw8069i mv: can't rename '/tmp/work/test.something.com/*.pem': No such file or directory
```
when I ls into the container, I see that nothing gets dumped to tmp/work. When I take the commands from idez/traefik-certs-dumper directly, it seems to work...the workaround is to use the container from idez with the --watch option, and mount the output from command for now...I just wnated to let you know =)

**Comment by tinonaumann** [comment]
For me

```
  certdumper:
    restart: always
    image: mailu/traefik-certdumper:${MAILU_VERSION:-master}
    environment:
      - DOMAIN=domain.de
      - TRAEFIK_VERSION=v2
    volumes:
      - traefik_certificates:/traefik
      - mailu_certificates:/output

```

works as expected and generate the certs properly
