### ISSUE TITLE
How to replace rainloop with roundcube?

### ISSUE THREAD

**Issue by dennorske** [Mailu/Mailu#1439]
Hi readers,

I am currently running Mailu 1.7 and I am wondering how to correctly run roundcube webmail, instead of what I am currently running (Rainloop). 

I tried editing the .env file without any luck - rainloop is still there. Yes, I restarted and tried rebuilding the containers.

Can someone explain me if i need to remove the web directory files manually or something? I would also be very happy to keep my existing mails intact.

Thank you!

**Comment by ofthesun9** [comment]
Hello,
May be your docker-compose.yml is still referring to the roundcube image ? (I don't remember if the webmail service is hard-coded in the yml or if it is referring to $WEBMAIL)

**Comment by mboogert** [comment]
Change it in you docker-compose file. Replace rainloop with roundcube.

```
  # Webmail
  webmail:
    #image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rainloop:${MAILU_VERSION:-1.7}
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/webmail:/data"
    depends_on:
      - imap
```

Also check your ./webmail/ directory. I think this directory needs to be removed as well. So do a mv webmail webmail.rainloop.

Restart your docker-compose project afterwards.

Regards,
Marcel.
