### ISSUE TITLE
how to prevent open relay 

### ISSUE THREAD

**Issue by fritzlab** [Mailu/Mailu#1468]
I see a lot of comments on here regarding mailu being an open relay by default.  however, It's not clear to me how to actually fix the problem.  I'm starting to think I'm using Mailu in a way it was not intended to be used. 

Part of my docker-compose:
```
version: '2.2'
services:
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "A.B.C.10:80:80"
      - "A.B.C.20:80:80"
      - "2001:db8::10:80:80"
      - "2001:db8::20:80:80"
      - "A.B.C.10:443:443"
      - "A.B.C.20:443:443"
      - "2001:db8::10:443:443"
      - "2001:db8::20:443:443"
      - "A.B.C.10:25:25"
      - "A.B.C.20:25:25"
      - "2001:db8::10:25:25"
      - "2001:db8::20:25:25"
      - "A.B.C.10:465:465"
      - "A.B.C.20:465:465"
      - "2001:db8::10:465:465"
      - "2001:db8::20:465:465"
      - "A.B.C.10:587:587"
      - "A.B.C.20:587:587"
      - "2001:db8::10:587:587"
      - "2001:db8::20:587:587"
      - "A.B.C.10:110:110"
      - "A.B.C.20:110:110"
      - "2001:db8::10:110:110"
      - "2001:db8::20:110:110"
      - "A.B.C.10:995:995"
      - "A.B.C.20:995:995"
      - "2001:db8::10:995:995"
      - "2001:db8::20:995:995"
      - "A.B.C.10:143:143"
      - "A.B.C.20:143:143"
      - "2001:db8::10:143:143"
      - "2001:db8::20:143:143"
      - "A.B.C.10:993:993"
      - "A.B.C.20:993:993"
      - "2001:db8::10:993:993"
      - "2001:db8::20:993:993"
```

My docker host has publicly routable IPv4 and IPv6 addresses on it.  There is no NAT'ing in the network. 

The docs mention to expose specific ports with their addresses vs a `-"25:25"`, but it's effectively the same result. Either way mxtoolbox reports this mail server as an open SMTP relay (and it is, based on my testing). 

Is there any way to fix this, or is the expectation that Mailu should not be directly on the internet like this?

**Comment by ofthesun9** [comment]
Hello,
I see in your other PR #1467  that you created an IPv6 network for your internal docker network. INMHO it's unusual, I would start digging around this.

More generally, Open Relay can be due to the an improper RELAYNETS settings.
Could you check the logs from the "front" container when checking with mxtoolbox ? My guess is that the front container is seeing an ip address that is included in either your SUBNET or RELAYNETS definition, hence allowing the relay feature

**Comment by muhlemmer** [comment]
@fritzlab as you mentioned in issue #1467 you have a globally routed IPv6 network. This is causing the open relay. Anything on the subnet of Mailu is considered trusted. So you have now trusted the global internet.

Have you read our FAQ?: https://mailu.io/1.7/faq.html#how-to-make-ipv6-work
It explains the risks of IPv6 and how to solve them.

In short:

1. Use setup to generate a safe IPv6 ULA
2. [`docker run -d --restart=always -v /var/run/docker.sock:/var/run/docker.sock:ro --privileged --net=host robbertkl/ipv6nat`](https://github.com/robbertkl/docker-ipv6nat)

I'm running this setup since the release of `1.7` without issues.

**Comment by fritzlab** [comment]
Thanks @muhlemmer and @ofthesun9 for the information.  I think I understand what's happening now. 

@muhlemmer, I want to chat about this a bit more:

> you have a globally routed IPv6 network. This is causing the open relay. Anything on the subnet of Mailu is considered trusted. So you have now trusted the global internet.

The SMTP open relay test of mxtoolbox does not appear to support IPv6 today, so the requests from mxtoolbox come in over IPv4.  It looks like the front container is a reverse proxy for everything.  Requests from the front to the smtp container also appear to be over IPv4 based on my packet tracing.  So IPv6 is not in the mix here at all. I _think_ what you're referring to is that since the smtp container has a global IPv6 address, requests could go directly to it, bypassing the front.  I do agree, however, in my setup there's a state-full firewall in the network that would disallow that from happening (but there's no way you would have known that) (it has exceptions for the port/IPs of the front/docker-host only).  It appears to me that since the front proxies everything to the smtp container, the entire internet will always be trusted since the smtp container will only ever see mail coming from the proxy on it's local network segment. 

The `RELAYNETS` option looks like this is exactly the toggle I'm looking for, however, it didn't work for me.  Here's what I set:
```
RELAYNETS=192.168.203.0/24 203.0.113.0/24 2001:db8::/48
```
Where `203.0.113.0/24` and `2001:db8::/48` are public IPv4 and IPv6 CIDRs.  

The network settings in docker-compose are:
```
networks:
  default:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
        - subnet: 2001:db8:d30a::/64
```

So `RELAYNETS` seems to be IP based restrictions based on the observed IPs by the containers themselves. Since the front proxies everything, the IP based restrictions basically useless then since the IP will always be on the local network segment on the docker host. 

Let me know if I'm not grasping this correctly.  My background heavier on networking than systems/email.  But I think I understand the problem. 

What is the recommendation here?
How do people generally solve this problem when trying to run Mailu as a personal mail server on the internet?
