### ISSUE TITLE
Reverse proxy documentation does not support Traefik v2.x

### ISSUE THREAD

**Issue by patryk-tech** [Mailu/Mailu#1503]
Hey! Thanks for this project, I am currently trying to deploy it on a server. While doing so, I have noticed that the [configuration instructions for Traefik](https://github.com/Mailu/Mailu/blob/master/docs/reverse.rst#traefik-as-reverse-proxy) only provide the configuration for Traefik <= v1.7, as they use `[[acme.domains]]`.

In Traefik v2+, SANs should be defined under routers, in the dynamic configuration, or under entrypoints, in the static config.

Examples from the traefik docs below...

****

# Dynamic configuration examples using routers

## TOML

```toml
## Dynamic configuration
[http.routers]
  [http.routers.routerbar]
    rule = "Host(`snitest.com`) && Path(`/bar`)"
    [http.routers.routerbar.tls]
      certResolver = "bar"
      [[http.routers.routerbar.tls.domains]]
        main = "snitest.com"
        sans = ["*.snitest.com"]
```

## YAML

```yaml
## Dynamic configuration
http:
  routers:
    routerbar:
      rule: "Host(`snitest.com`) && Path(`/bar`)"
      tls:
        certResolver: "bar"
        domains:
          - main: "snitest.com"
            sans:
              - "*.snitest.com"
```

## Docker Labels

```yaml
  - "traefik.http.routers.router1.tls.domains[0].main=foobar"
  - "traefik.http.routers.router1.tls.domains[0].sans=foobar, foobar"
  - "traefik.http.routers.router1.tls.domains[1].main=foobar"
  - "traefik.http.routers.router1.tls.domains[1].sans=foobar, foobar"
```

- https://docs.traefik.io/routing/routers/#domains
- https://docs.traefik.io/reference/dynamic-configuration/docker/

****

# Static configuration using entrypoints

## TOML file

```toml
[entryPoints]
  [entryPoints.EntryPoint0]
    address = "foobar"
    [entryPoints.EntryPoint0.http]
      [entryPoints.EntryPoint0.http.tls]
        [[entryPoints.EntryPoint0.http.tls.domains]]
          main = "foobar"
          sans = ["foobar", "foobar"]

```

## YAML file

```yaml
entryPoints:
  EntryPoint0:
    address: foobar
    http:
      tls:
        domains:
        - main: foobar
          sans:
          - foobar
          - foobar
```

- https://docs.traefik.io/reference/static-configuration/file/
