### ISSUE TITLE
No database tables created: "database is locked" when using CIFS mounts

### ISSUE THREAD

**Issue by unikitty37** [Mailu/Mailu#1546]
I have just tried to create a new Mailu instance using docker-compose, but the admin container fails to create any tables, giving a "database is locked" error and leaving `data/main.db` at size 0. I'm running this on a debian/buster VM with nothing else installed apart from the prerequisites for docker and docker-compose.

The `/mailu` directory is mounted over CIFS:

```
//nas.example.net/mail on /mailu type cifs (rw,nosuid,relatime,vers=default,cache=strict,username=email,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.1.100,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
```

I've tried with `lock` and `nolock` mount options. Removing the database file and running `docker-compose up -d` produces the same error. Copying the `docker-compose.yml` and `mailu.env` to a local directory solves the problem, but it would make life *much* easier to have the filesystem mounted from the NAS as then it has the protection of RAID (and is backed up by existing solutions).

Is there a way to get mailu to work when it's in a remotely-mounted directory?

(Incidentally, why is `ANTIVIRUS=clamav` commented out by default in the generated .env file? Does this not work at the moment?)

## docker-compose.yml

```yaml
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/mailu/redis:/data"
    
  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "192.168.1.99:80:80"
      - "::1:80:80"
      - "192.168.1.99:443:443"
      - "::1:443:443"
      - "192.168.1.99:25:25"
      - "::1:25:25"
      - "192.168.1.99:465:465"
      - "::1:465:465"
      - "192.168.1.99:587:587"
      - "::1:587:587"
      - "192.168.1.99:110:110"
      - "::1:110:110"
      - "192.168.1.99:995:995"
      - "::1:995:995"
      - "192.168.1.99:143:143"
      - "::1:143:143"
      - "192.168.1.99:993:993"
      - "::1:993:993"
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides"

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.7}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    depends_on:
      - redis

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mail:/mail"
      - "/mailu/overrides:/overrides"
    depends_on:
      - front

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/overrides:/overrides"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/var/lib/rspamd"
      - "/mailu/dkim:/dkim"
      - "/mailu/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254


  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/webmail:/data"
    depends_on:
      - imap


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```

## mailu.env

```
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY={{ mailu_secret_key }}

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.168.203.0/24

# Main mail domain
DOMAIN=example.net

# Hostnames for this server, separated with comas
HOSTNAMES=mail.example.net

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=mail

# Authentication rate limit (per source IP address)
AUTH_RATELIMIT=10/minute;100/hour

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=True

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=roundcube

# Dav server implementation (value: radicale, none)
WEBDAV=none

# Antivirus solution (value: clamav, none)
#ANTIVIRUS=clamav

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=120

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: bz2, gz)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/

# Website name
SITENAME=Mailu

# Linked Website URL
WEBSITE=https://mail.example.net



###################################
# Advanced settings
###################################

# Log driver for front service. Possible values:
# json-file (default)
# journald (On systemd platforms, useful for Fail2Ban integration)
# syslog (Non systemd platforms, Fail2Ban integration. Disables `docker-compose log` for front!)
# LOG_DRIVER=json-file

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Default password scheme used for newly created accounts and changed passwords
# (value: BLF-CRYPT, SHA512-CRYPT, SHA256-CRYPT, MD5-CRYPT, CRYPT)
PASSWORD_SCHEME=BLF-CRYPT

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

###################################
# Database settings
###################################
DB_FLAVOR=sqlite
```

## Admin container log

```
Attaching to mailu_admin_1
admin_1      | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
admin_1      | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
admin_1      | Traceback (most recent call last):
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
admin_1      |     cursor, statement, parameters, context
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
admin_1      |     cursor.execute(statement, parameters)
admin_1      | sqlite3.OperationalError: database is locked
admin_1      | 
admin_1      | The above exception was the direct cause of the following exception:
admin_1      | 
admin_1      | Traceback (most recent call last):
admin_1      |   File "/usr/bin/flask", line 8, in <module>
admin_1      |     sys.exit(main())
admin_1      |   File "/usr/lib/python3.7/site-packages/flask/cli.py", line 894, in main
admin_1      |     cli.main(args=args, prog_name=name)
admin_1      |   File "/usr/lib/python3.7/site-packages/flask/cli.py", line 557, in main
admin_1      |     return super(FlaskGroup, self).main(*args, **kwargs)
admin_1      |   File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
admin_1      |     rv = self.invoke(ctx)
admin_1      |   File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
admin_1      |     return _process_result(sub_ctx.command.invoke(sub_ctx))
admin_1      |   File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
admin_1      |     return _process_result(sub_ctx.command.invoke(sub_ctx))
admin_1      |   File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
admin_1      |     return ctx.invoke(self.callback, **ctx.params)
admin_1      |   File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
admin_1      |     return callback(*args, **kwargs)
admin_1      |   File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
admin_1      |     return f(get_current_context(), *args, **kwargs)
admin_1      |   File "/usr/lib/python3.7/site-packages/flask/cli.py", line 412, in decorator
admin_1      |     return __ctx.invoke(f, *args, **kwargs)
admin_1      |   File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
admin_1      |     return callback(*args, **kwargs)
admin_1      |   File "/usr/lib/python3.7/site-packages/flask_migrate/cli.py", line 134, in upgrade
admin_1      |     _upgrade(directory, revision, sql, tag, x_arg)
admin_1      |   File "/usr/lib/python3.7/site-packages/flask_migrate/__init__.py", line 95, in wrapped
admin_1      |     f(*args, **kwargs)
admin_1      |   File "/usr/lib/python3.7/site-packages/flask_migrate/__init__.py", line 280, in upgrade
admin_1      |     command.upgrade(config, revision, sql=sql, tag=tag)
admin_1      |   File "/usr/lib/python3.7/site-packages/alembic/command.py", line 276, in upgrade
admin_1      |     script.run_env()
admin_1      |   File "/usr/lib/python3.7/site-packages/alembic/script/base.py", line 475, in run_env
admin_1      |     util.load_python_file(self.dir, "env.py")
admin_1      |   File "/usr/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
admin_1      |     module = load_module_py(module_id, path)
admin_1      |   File "/usr/lib/python3.7/site-packages/alembic/util/compat.py", line 156, in load_module_py
admin_1      |     spec.loader.exec_module(module)
admin_1      |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
admin_1      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
admin_1      |   File "migrations/env.py", line 98, in <module>
admin_1      |     run_migrations_online()
admin_1      |   File "migrations/env.py", line 91, in run_migrations_online
admin_1      |     context.run_migrations()
admin_1      |   File "<string>", line 8, in run_migrations
admin_1      |   File "/usr/lib/python3.7/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
admin_1      |     self.get_context().run_migrations(**kw)
admin_1      |   File "/usr/lib/python3.7/site-packages/alembic/runtime/migration.py", line 342, in run_migrations
admin_1      |     self._ensure_version_table()
admin_1      |   File "/usr/lib/python3.7/site-packages/alembic/runtime/migration.py", line 292, in _ensure_version_table
admin_1      |     self._version.create(self.connection, checkfirst=True)
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 860, in create
admin_1      |     bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1607, in _run_visitor
admin_1      |     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
admin_1      |     return meth(obj, **kw)
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 826, in visit_table
admin_1      |     include_foreign_key_constraints,
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
admin_1      |     return meth(self, multiparams, params)
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
admin_1      |     return connection._execute_ddl(self, multiparams, params)
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
admin_1      |     compiled,
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
admin_1      |     e, statement, parameters, cursor, context
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
admin_1      |     util.raise_from_cause(sqlalchemy_exception, exc_info)
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
admin_1      |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
admin_1      |     raise value.with_traceback(tb)
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
admin_1      |     cursor, statement, parameters, context
admin_1      |   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
admin_1      |     cursor.execute(statement, parameters)
admin_1      | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
admin_1      | [SQL: 
admin_1      | CREATE TABLE alembic_version (
admin_1      | 	version_num VARCHAR(32) NOT NULL, 
admin_1      | 	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
admin_1      | )
admin_1      | 
admin_1      | ]
admin_1      | (Background on this error at: http://sqlalche.me/e/e3q8)
admin_1      | [2020-06-22 12:30:52 +0000] [10] [INFO] Starting gunicorn 19.9.0
admin_1      | [2020-06-22 12:30:52 +0000] [10] [INFO] Listening at: http://0.0.0.0:80 (10)
admin_1      | [2020-06-22 12:30:52 +0000] [10] [INFO] Using worker: sync
admin_1      | [2020-06-22 12:30:52 +0000] [12] [INFO] Booting worker with pid: 12
admin_1      | [2020-06-22 12:30:53 +0000] [13] [INFO] Booting worker with pid: 13
admin_1      | [2020-06-22 12:30:53 +0000] [14] [INFO] Booting worker with pid: 14
admin_1      | [2020-06-22 12:30:53 +0000] [15] [INFO] Booting worker with pid: 15
```
