### ISSUE TITLE
I am getting 502: Bad Gateway when I try to access the mail url with nginx reverse proxy

### ISSUE THREAD

**Issue by keystroke3** [Mailu/Mailu#1576]
I am a beginner with docker, and need some help with my configs. I set up nginx as a reverse proxy outside of docker. It manages other services on the vps and wanted to add mail services to the list. I followed the procedure on the Mailu manual and generated a yaml file.  I start docker with the command `docker-compose -p mailu up -d `. 
When ever I go to `mail.siliconraven.co` or `admin.siliconraven.co`, I get the Bad Gateway error. Other services on `siliconraven.co` work fine.

I would like to know what I am doing wrong and if there is anything I can change.
 

```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/mailu/redis:/data"

  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "<myserver_ip>:19080:80"
      - "::1:9080:80"
      - "<myserver_ip>:19443:443"
      - "::1:9443:443"
      - "<myserver_ip>:25:25"
      - "::1:25:25"
      - "<myserver_ip>:465:465"
      - "::1:465:465"
      - "<myserver_ip>:587:587"
      - "::1:587:587"
      - "<myserver_ip>:110:110"
      - "::1:110:110"
      - "<myserver_ip>:995:995"
      - "::1:995:995"
      - "<myserver_ip>:143:143"
      - "::1:143:143"
      - "<myserver_ip>:993:993"
      - "::1:993:993"
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides"

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.7}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    depends_on:
      - redis

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mail:/mail"
      - "/mailu/overrides:/overrides"
    depends_on:
      - front

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/overrides:/overrides"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/var/lib/rspamd"
      - "/mailu/dkim:/dkim"
      - "/mailu/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  webdav:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/dav:/data"

  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rainloop:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/webmail:/data"
    depends_on:
      - imap


networks:
  default:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
        - subnet: fd9e:5055:c8f6:beef::/64

server { 
         listen 80; 
         listen 443;
         root /var/www/; 
         index index.php index.html index.htm;
 
         server_name mail.siliconraven.co admin.siliconraven.co;  
 
          location / { 
          proxy_pass http://0.0.0.0:19443/;
          }    
  
          location /admin/ {
          proxy_pass https://0.0.0.0:19443/admin;
          }   
        
          location ~ /\.ht {
                 deny all;
         }   
 }

 ```

For `proxy_pass` in place of `0.0.0.0` I tried my server ip and localhost, but none of them had any difference.

If I have left out information please ask me to include it. Thanks.
