### ISSUE TITLE
Deploying issue with SSL_ERROR_SYSCAL, peer closed connection in SSL handshake while SSL handshaking to upstream

### ISSUE THREAD

**Issue by gbalcewicz** [Mailu/Mailu#1634]
**Environment:** docker-compose
**Version:** 1.7
**Steps I've made:**
1. mkdir mailu
2. generated and downloaded docker-compose.yml and mailu.env
3. docker-compose up -d
4. created admin user

**Issue description:**
I'm trying to deploy mailu behind reverse proxy (nginx). I have generated docker-compose.yml with https://setup.mailu.io/. 
```
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "127.0.0.1:8080:80"
      - "::1:8080:80"
      - "127.0.0.1:8443:443"
      - "::1:8443:443"
      - "127.0.0.1:25:25"
      - "::1:25:25"
      - "127.0.0.1:465:465"
      - "::1:465:465"
      - "127.0.0.1:587:587"
      - "::1:587:587"
      - "127.0.0.1:110:110"
      - "::1:110:110"
      - "127.0.0.1:995:995"
      - "::1:995:995"
      - "127.0.0.1:143:143"
      - "::1:143:143"
      - "127.0.0.1:993:993"
      - "::1:993:993"
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides"
```

I have tried to set my nginx to proxy like in the documentation, my virtual host:
```
upstream mail_server {
    server 127.0.0.1:8443;
}

server {
    listen 443 ssl;
    server_name ****;

    location / {
        proxy_pass https://mail_server;
    }

    location /admin {
        proxy_pass https://mail_server/admin;
    }

    location /webmail {
        proxy_pass https://mail_server/webmail;
    }

    ssl_certificate /etc/letsencrypt/live/*****/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/*****/privkey.pem; # managed by Certbot
}
```
I have also tried without the upstream and used
```
proxy_pass https://127.0.0.1:8443;
```
Also I have tried `proxy_ssl_session_reuse off;` and `proxy_ssl_server_name on;` without luck. The logs are telling me:
```
*57 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: ****, server: *****, request: "GET /admin HTTP/1.1", upstream: "https://127.0.0.1:8443/admin", host: "*****", referrer: "https://*****/admin"
```

So after that I tried to curl the 127.0.0.1 I get error SSL_ERROR_SYSCALL

```
curl -v -H -GET https://127.0.0.1:8443
*   Trying 127.0.0.1:8443...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:8443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:8443 
```

I'm lost after googling half day to make it work. Any hints what direction I should go, or what I can also check?
