### ISSUE TITLE
Server's public IP address changed - nginx (mailu_front_1) container fails to start.

### ISSUE THREAD

**Issue by David00** [Mailu/Mailu#1659]
My hosting provider ran into some issues on a machine that was running my Mailu setup. We agreed that migrating my VM to a new machine was the best course of action to resolve the issues, but this migration provided me with a new IP address.

I am running Mailu version 1.7 with roughly a 6-month old docker-compose deployment on Ubuntu 18.04 server.

When I start docker-compose, I get the following error:
>ERROR: for mailu_front_1  Cannot restart container d0e8eacdf612b443dbc5f1e5c5fd795b27f39ac0ccde727c38fc08bdb166039b: driver failed programming external connectivity on endpoint mailu_front_1 (f37be441992e3899b0e18c1a591a13e1fb97c7dc5c9c1a52b2e5af1ee0cae0d1): Error starting userland proxy: listen tcp REDACTED:995: bind: cannot assign requested address

... where the REDACTED text is my previous public IP address. 

I've removed all mention of the old address in my docker-compose.yml file. I've tried replacing the old IP address with the new IP address in the docker-compose.yml file, and also completely removing the IP address, like this:

```
version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/mailu/redis:/data"
    
  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "80:80"             
      - "::1:80:80"
      - "443:443"             
      - "::1:443:443"
      - "25:25"             
      - "::1:25:25"
      - "465:465"             
      - "::1:465:465"
      - "587:587"             
      - "::1:587:587"
      - "110:110"             
      - "::1:110:110"
      - "995:995"             
      - "::1:995:995"
      - "143:143"             
      - "::1:143:143"
      - "993:993"             
      - "::1:993:993"
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides"
```

There are no overrides in /mailu/overrides/nginx:
```
$ ls /mailu/overrides/nginx/
$ 
```

I have not regenerated certificates with the new IP address yet - I wanted to make sure everything was up and running first. Even though the cert is still for the old IP, that's an issue that should only be between the client and the webserver.

Any ideas about why Nginx is trying to bind to the old IP address?
