### ISSUE TITLE
Impossible to send a mail, http error occurred: HTTP parser error: invalid HTTP method

### ISSUE THREAD

**Issue by xoxopeter** [Mailu/Mailu#1668]
Hello guys,

Since three weeks i tried to install mailu 1.7 without using the stack or the docker compose (manually installation)

I've checked on official documentation and on issues pages but seem alone to do that.

### Environment 
Using mailu 1.7
Using the setup.mailu.io to get all env variable and use https://mailu.io/1.7/configuration.html too to get all necessary variable.
I'm behind a traefik reverse proxy and he have his network name "traefik".
I'm using a new network named "mailu" for all mailu containers.
Services opened on docker host firewall: imap imaps pop3 pop3s smtp smtps.
Ports opened on docker host firewall: 465/tcp 587/tcp 143/tcp.
"A" record configured for the hostname "mail.domain.net".
The mx domain.net.  IN  MX  10 mail.domain.net is configured too.

Here you can see my containers configuration:
```
# External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/docker_path/mailu/redis:/data"
    networks:
      - mailu:


# Core services
  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.7}
    env_file: mailu.env
    restart: always
    networks:
      mailu:
        ipv4_address: xxx.xxx.255.254


  certdumper:
    restart: always
    image: mailu/traefik-certdumper:${MAILU_VERSION:-1.7}
    environment:
      - DOMAIN=domain.net
      - TRAEFIK_DOMAIN=mail.domain.net
    volumes:
      # Folder, which contains the acme.json
      - "/docker_path/traefik:/traefik"
      # Folder, where cert.pem and key.pem will be written
      - "/docker_path/mailu/certs:/output"
    networks:
      mailu:

    

  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "127.0.0.1:25:25"
      - "::1:25:25"
      - "127.0.0.1:465:465"
      - "::1:465:465"
      - "127.0.0.1:587:587"
      - "::1:587:587"
      - "127.0.0.1:110:110"
      - "::1:110:110"
      - "127.0.0.1:995:995"
      - "::1:995:995"
      - "127.0.0.1:143:143"
      - "::1:143:143"
      - "127.0.0.1:993:993"
      - "::1:993:993"
    volumes:
      - "/docker_path/mailu/certs:/certs"
      - "/docker_path/mailu/overrides/nginx:/overrides"
    networks:
      - mailu:
      - traefik:
    labels:
        traefik.docker.network: traefik
        traefik.enable: true
        traefik.frontend.headers.browserXSSFilter: true
        traefik.frontend.rule:	Host:mail.domain.net
        traefik.port: 80


  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/docker_path/mailu/data:/data"
      - "/docker_path/mailu/dkim:/dkim"
    depends_on:
      - redis
    networks:
      - mailu:


  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/docker_path/mailu/mail:/mail"
      - "/docker_path/mailu/overrides:/overrides"
    depends_on:
      - front
    networks:
      - mailu:


  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/docker_path/mailu/overrides:/overrides"
    depends_on:
      - front
      - resolver
    dns:
      - xxx.xxx.255.254
    networks:
      - mailu:


  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/docker_path/mailu/filter:/var/lib/rspamd"
      - "/docker_path/mailu/dkim:/dkim"
      - "/docker_path/mailu/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
      - resolver
    dns:
      - xxx.xxx.255.254
    networks:
      - mailu:


  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/docker_path/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - xxx.xxx.255.254
    networks:
      - mailu:


  webdav:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/docker_path/mailu/dav:/data"
    networks:
      - mailu:


  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    depends_on:
      - resolver
    dns:
      - xxx.xxx.255.254
    networks:
      - mailu:


  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rainloop:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/docker_path/mailu/webmail:/data"
    depends_on:
      - imap
    networks:
      - mailu:


networks:
  mailu:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: xxx.xxx.0.0/16

  traefik:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
      # subnet different from mailu network
        - subnet: xxx.xx.0.0/16

```

Example of env:
```
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=XXXXXXXXXXXXXXXX

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=xxx.xxx.0.0/16

# Main mail domain
DOMAIN=domain.net

# Hostnames for this server, separated with comas
HOSTNAMES=mail.domain.net

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=mail

# Authentication rate limit (per source IP address)
AUTH_RATELIMIT=10/minute;1000/hour 

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=False


###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=rainloop

# Dav server implementation (value: radicale, none)
WEBDAV=radicale

# Antivirus solution (value: clamav, none)
ANTIVIRUS=clamav


###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: bz2, gz)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=


###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/webmail

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/webmail

# Website name
SITENAME=Mailu

# Linked Website URL
WEBSITE=https://mail.domain.net


###################################
# Advanced settings
###################################

# Log driver for front service. Possible values:
# json-file (default)
# journald (On systemd platforms, useful for Fail2Ban integration)
# syslog (Non systemd platforms, Fail2Ban integration. Disables `docker-compose log` for front!)
# LOG_DRIVER=json-file

# Default password scheme used for newly created accounts and changed passwords
# (value: BLF-CRYPT, SHA512-CRYPT, SHA256-CRYPT, MD5-CRYPT, CRYPT)
PASSWORD_SCHEME=BLF-CRYPT

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING


###################################
# Database settings
###################################
DB_FLAVOR=mysql
DB_USER=db
DB_PW=db
DB_HOST=db
DB_NAME=db


###################################
# INFRA SETTINGS if you don’t use docker-compose
###################################
HOST_IMAP=imap
HOST_LMTP=imap:2525
HOST_HOSTIMAP=imap
HOST_POP3=imap
HOST_SMTP=smtp
HOST_AUTHSMTP=smtp
HOST_ADMIN=admin
HOST_ANTISPAM=antispam:11334
HOST_ANTIVIRUS=antivirus:3310
HOST_WEBMAIL=webmail
HOST_WEBDAV=webdav:5232
HOST_REDIS=redis

FRONT_ADDRESS=front
WEBMAIL_ADDRESS=webmail
IMAP_ADDRESS=webmail


###################################
# reverse proxy settings
###################################
TRAEFIK_DOMAIN=mail.domain.net
```

## Description
The installation seems good but when i want send a mail from my webmail, i have a red message "Can't send message" or "Authentication failed". 
I don't know why i have this issue. If someone have an idea or already get this message ?

 ## Replication Steps
Firstly, I connect to the webmail, then i create new message and send it (or try to send it in my case)

## Expected behaviour
I would like to be able to send an email to external addresses but the sending doesn't work

## Logs
antispam log:
````markdown
```
2020-10-23T15:55:01.303731424Z 2020-10-23 15:55:01 #8(controller) <5dfdca>; csession; rspamd_controller_error_handler: http error occurred: HTTP parser error: invalid HTTP method
```
````

smtp log:
````markdown
```
Oct 23 15:58:07 mail postfix/smtpd[43944]: connect from localhost[127.0.0.1]

Oct 23 15:58:07 mail postfix/smtpd[43944]: warning: milter inet:xxx.xxx.0.9:11334: unreasonable packet length: 1213486160 > 1073741823

Oct 23 15:58:07 mail postfix/smtpd[43944]: warning: milter inet:xxx.xxx.0.9:11334: read error in initial handshake

Oct 23 15:58:07 mail postfix/smtpd[43944]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP

Oct 23 15:58:07 mail postfix/smtpd[43944]: disconnect from localhost[127.0.0.1] quit=1 commands=1
```
````

**Comment by xoxopeter** [comment]
Hi,

It possible to close this issue,

The problem was on postfix container (smtp container). We need to use the environment variable HOST_ANTISPAM=antispam:11332 and on the all other container we need to use HOST_ANTISPAM=antispam:11334,

Thanks bivolf for the solution,

Workaround:

1. Remove HOST_ANTISPAM from mailu.env

2. Create following files:
```
cat mailu-admin.env
HOST_ANTISPAM=antispam:11334

cat mailu-postfix.env
HOST_ANTISPAM=antispam:11332

cat mailu-dovecot.env
HOST_ANTISPAM=antispam:11334

cat mailu-nginx.env
HOST_ANTISPAM=antispam:11334
```

3. Change your docker-compose to:
```
  admin:
    env_file:
      - mailu.env
      - mailu-admin.env
 
  smtp:
    env_file:
      - mailu.env
      - mailu-postfix.env

  imap:
    env_file:
      - mailu.env
      - mailu-dovecot.env

  front:
    env_file:
      - mailu.env
      - mailu-nginx.env
```
