### ISSUE TITLE
letsencrypt fails to check the challenge (403)

### ISSUE THREAD

**Issue by leolivier** [Mailu/Mailu#1686]
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
My own image built on Raspbian Buster based on the master branch (1.8+)

## Description
Running with TLS_FLAVOR=mail-letsencrypt since >1years
Moved to 1.8 "testing" branch
When renewing my certificates, letsencrypt complains on the challenge verification with a 403 code.

## Replication Steps
You need a certificate to be renewed.
Start the docker compose file 

```
version: '2.2'
services:
  redis:
    container_name: mailu.redis
    image: redis:alpine
    restart: always
    volumes:
      - "$ROOT/redis:/data"

  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    container_name: mailu.front
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "$BIND_ADDRESS4:8080:80"
      - "$BIND_ADDRESS4:8443:443"
      - "$BIND_ADDRESS4:110:110"
      - "$BIND_ADDRESS4:143:143"
      - "$BIND_ADDRESS4:993:993"
      - "$BIND_ADDRESS4:995:995"
      - "$BIND_ADDRESS4:25:25"
      - "$BIND_ADDRESS4:465:465"
      - "$BIND_ADDRESS4:587:587"
    volumes:
      - "$ROOT/certs:/certs"
      - "$ROOT/overrides/nginx:/overrides"

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.7}
    container_name: mailu.resolver
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: $DNS

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.7}
    container_name: mailu.admin
    restart: always
    env_file: mailu.env
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/dkim:/dkim"
    depends_on:
      - redis

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.7}
    container_name: mailu.imap
    restart: always
    env_file: mailu.env
    volumes:
      - "$ROOT/mail:/mail"
      - "$ROOT/overrides:/overrides"
    depends_on:
      - front

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.7}
    container_name: mailu.smtp
    restart: always
    env_file: mailu.env
    volumes:
      - "$ROOT/overrides:/overrides"
    depends_on:
      - front
      - resolver
    dns:
      - $DNS

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.7}
    container_name: mailu.antispam
    restart: always
    env_file: mailu.env
    volumes:
      - "$ROOT/filter:/var/lib/rspamd"
      - "$ROOT/dkim:/dkim"
      - "$ROOT/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
      - resolver
    dns:
      - $DNS

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: $SUBNET
```
with the following mailu.env:

```
SECRET_KEY=***
SUBNET=192.168.203.0/24
DOMAIN=***
HOSTNAMES=mail.***
POSTMASTER=admin
TLS_FLAVOR=mail-letsencrypt
AUTH_RATELIMIT=10/minute;100/hour
DISABLE_STATISTICS=False
ADMIN=true
WEBMAIL=none
WEBDAV=none
ANTIVIRUS=none
MESSAGE_SIZE_LIMIT=12000000
RELAYNETS=192.168.0.0/24 localhost.localdomain
RELAYHOST=
FETCHMAIL_DELAY=600
RECIPIENT_DELIMITER=+
DMARC_RUA=admin
DMARC_RUF=admin
WELCOME=true
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!
COMPRESSION=bz2
COMPRESSION_LEVEL=
WEBROOT_REDIRECT=
WEB_ADMIN=/admin
WEB_WEBMAIL=
SITENAME=Mailu 
WEBSITE=https://mail.***
COMPOSE_PROJECT_NAME=mailu
PASSWORD_SCHEME=BLF-CRYPT
REAL_IP_HEADER=
REAL_IP_FROM=
REJECT_UNLISTED_RECIPIENT=
LOG_LEVEL=WARNING
DB_FLAVOR=sqlite
INITIAL_ADMIN_ACCOUNT=admin
INITIAL_ADMIN_DOMAIN=*
INITIAL_ADMIN_PW=***
INITIAL_ADMIN_MODE=ifmissing
```
I noticed that the nginx config is proxyfying .well-knwon/acme-challenge to http://127.0.0.1:8008 but I can't find any process listening on the 8008 port, so maybe I don't get it but wouldn't it be the issue?

/cong/nginx.conf contains (didn't change anything):
```                                                                                                    
      {% if TLS_FLAVOR == 'mail-letsencrypt' %}                                                      
      location ^~ /.well-known/acme-challenge/ {                                                     
          proxy_pass http://127.0.0.1:8008;                                                          
      }                                                                                              
      {% endif %}         
```
/etc/nginx/nginx.conf contains:
```
      location ^~ /.well-known/acme-challenge/ {
          proxy_pass http://127.0.0.1:8008;
      }

      # If TLS is failing, prevent access to anything except certbot
      location / {
        return 403;
      }

```

## Expected behaviour
Should renew the certificate as it did before

## Logs
```
Challenge failed for domain mail.levillain.ml
http-01 challenge for mail.levillain.ml
Cleaning up challenges
Running post-hook command: /config.py
2020/11/15 17:36:39 [notice] 1#1: signal 1 (SIGHUP) received from 16, reconfiguring
2020/11/15 17:36:39 [notice] 1#1: reconfiguring
2020/11/15 17:36:39 [notice] 1#1: using the "epoll" event method
2020/11/15 17:36:39 [notice] 1#1: start worker processes
2020/11/15 17:36:39 [notice] 1#1: start worker process 17
2020/11/15 17:36:39 [notice] 1#1: start worker process 18
2020/11/15 17:36:39 [notice] 1#1: start worker process 19
2020/11/15 17:36:39 [notice] 1#1: start worker process 20
Output from post-hook command config.py:
Missing cert or key file, disabling TLS   <================ because I removed the files
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:
   Domain: mail.levillain.ml
   Type:   unauthorized
   Detail: Invalid response from
   https://mail.levillain.ml/.well-known/acme-challenge/eNrH9BMxcsA5fCj0I9raHsnYCGQD0o4QwaWx-9Npr7w
   [78.203.12.245]: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML
   2.0//EN\">\n<html><head>\n<title>403
   Forbidden</title>\n</head><body>\n<h1>Forbidden</h1>\n<p"

   To fix these errors, please make sure that your domain name was  entered correctly and the DNS A/AAAA record(s)
   for that domain contain(s) the right IP address.
```
