### ISSUE TITLE
kubernetes yaml files not compatible with recent kubernetes releases 1.20+

### ISSUE THREAD

**Issue by HaleyACS** [Mailu/Mailu#1722]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [ X] Check if no issue or pull-request for this already exists.
- [ X] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [ X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [ ] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [ ] kubernetes - Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+k3s2", GitCommit:"2ea6b16315c093d739c370f8f035ad3fa5eb5d11", GitTreeState:"clean", BuildDate:"2020-12-22T02:10:12Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).   

Not possible, as the pods cannot be deployed yet.   
Currently using latest github.

## Description
Further explain the bug in a few words. It should be clear what the unexpected behaviour is.  Share it in an easy-to-understand language.

Deploying the mailu kubernetes environment fails.
```
smurphy@stargate:/home/prodadm/k3s/mailu$ kubectl apply -f rbac.yaml
namespace/mailu-mailserver unchanged
smurphy@stargate:/home/prodadm/k3s/mailu$ kubectl apply -f configmap.yaml 
configmap/mailu-config unchanged
smurphy@stargate:/home/prodadm/k3s/mailu$ kubectl apply -f pvc-redis.yaml -f pvc-mailu.yaml -f pv-mailu.yaml 
persistentvolumeclaim/redis-hdd unchanged
persistentvolumeclaim/pvc-mailu unchanged
persistentvolume/pv-mailu unchanged
smurphy@stargate:/home/prodadm/k3s/mailu$ kubectl apply -f redis.yaml 
deployment.apps/mailu-redis unchanged
service/redis unchanged
smurphy@stargate:/home/prodadm/k3s/mailu$ kubectl apply -f front.yaml 
service/front unchanged
error: unable to recognize "front.yaml": no matches for kind "DaemonSet" in version "apps/v1beta2"
smurphy@stargate:/home/prodadm/k3s/mailu$ kubectl apply -f webmail.yaml 
error: error validating "webmail.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
smurphy@stargate:/home/prodadm/k3s/mailu$ kubectl apply -f imap.yaml 
error: error validating "imap.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
smurphy@stargate:/home/prodadm/k3s/mailu$ kubectl apply -f security.yaml 
error: error validating "security.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

## Replication Steps
Steps for replicating your issue

Just try to install mailu yaml files on a current kubernetes cluster.

## Expected behaviour
Explain what results you expected - be as specific as possible. Just saying "it doesn’t work as expected" is not useful. It's also helpful to describe what you actually experienced.

Should not bail out with an error.

## Logs
Often it is very useful to include log fragments of the involved component. You can get the logs via `docker logs <container name> --tail 1000`. For example for the admin container:
`docker logs mailu_admin_1 --tail 1000`
or using docker-compose `docker-compose -f /mailu/docker-compose.yml logs --tail 1000 admin`
If you can find the relevant section, please share only the parts that seem relevant. If you have any logs, please enclose them in code tags, like so:
````markdown
```
Your logs here!
```
````

**Comment by dominick-han** [comment]
@HaleyACS You can try 1.8 (soft release?) or master, the YAMLs worked like a charm after minor modifications
Maybe I should make a PR and merge in some small fixes to master/1.8? Things like API version (v1beta2 things)

**Comment by HaleyACS** [comment]
Just tried master branch. Still at the:
```
$ kubectl apply -f front.yaml 
service/front unchanged
error: unable to recognize "front.yaml": no matches for kind "DaemonSet" in version "apps/v1beta2"
```
Don't know what that means actually.

**Comment by dominick-han** [comment]
Yeah, you need to add "selector" under "spec"
Sample (my namespace is just "mailu")
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailu-roundcube
  namespace: mailu
spec:
  selector:
    matchLabels:
      app: mailu-roundcube
      role: mail
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: mailu-roundcube
        role: mail
        tier: frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: macmini
      containers:
      - name: roundcube
        image: mailu/roundcube:1.8
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: mailu-config
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 1000m
        volumeMounts:
          - mountPath: /data
            name: maildata
            subPath: webmail
        ports:
          - containerPort: 80
      volumes:
        - name: maildata
          hostPath:
            path: /mailu
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: webmail
  namespace: mailu
  labels:
    app: mailu-roundcube
    role: mail
    tier: frontend
spec:
  selector:
    app: mailu-roundcube
    role: mail
    tier: frontend
  ports:
  - name: http
    port: 80
    protocol: TCP

```
