### ISSUE TITLE
502 Bad Gateway when using Nginx Proxy Manager and Mailu

### ISSUE THREAD

**Issue by apainter2** [Mailu/Mailu#1807]
I have mailu setup and working, but I would prefer to run it behind a Nginx Reverse Proxy, which I use Nginx Proxy Manager (https://nginxproxymanager.com/).

I am getting '502 Bad Gateway' for the root address, as well as /webmail, /admin and /admin/ui

Running mailui 1.7

I am running under docker containerd, and my docker-compose file for 'front' looks like this:

```
 # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
    env_file: /home/user/docker_files/mailu/mailu.env
    logging:
      driver: json-file
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
      - "xxx.xxx.xxx.xxx:25:25"
      - "xxx.xxx.xxx.xxx:465:465"
      - "xxx.xxx.xxx.xxx:587:587"
      - "xxx.xxx.xxx.xxx:110:110"
      - "xxx.xxx.xxx.xxx:995:995"
      - "xxx.xxx.xxx.xxx:143:143"
      - "xxx.xxx.xxx.xxx:993:993"
```

doing a 'ss -ltup' on the console to verify that the mailu webserver for ports 8080 and 8443 are listening show:
```
sudo ss -ltupn
Netid                       State                        Recv-Q                        Send-Q                                                     Local Address:Port                                                Peer Address:Port                       Process
udp                         UNCONN                       0                             0                                                          127.0.0.53%lo:53                                                       0.0.0.0:*                           users:(("systemd-resolve",pid=537,fd=12))
udp                         UNCONN                       0                             0                                                    xxx.xxx.xxx.xxx%ens3:68                                                       0.0.0.0:*                           users:(("systemd-network",pid=407,fd=19))
tcp                         LISTEN                       0                             4096                                                      aaa.bbb.ccc.ddd:110                                                      0.0.0.0:*                           users:(("docker-proxy",pid=122038,fd=4))
tcp                         LISTEN                       0                             4096                                                      aaa.bbb.ccc.ddd:143                                                      0.0.0.0:*                           users:(("docker-proxy",pid=121994,fd=4))
tcp                         LISTEN                       0                             4096                                                           127.0.0.1:8080                                                     0.0.0.0:*                           users:(("docker-proxy",pid=121934,fd=4))
tcp                         LISTEN                       0                             4096                                                             0.0.0.0:80                                                       0.0.0.0:*                           users:(("docker-proxy",pid=120878,fd=4))
tcp                         LISTEN                       0                             4096                                                      aaa.bbb.ccc.ddd:465                                                      0.0.0.0:*                           users:(("docker-proxy",pid=121982,fd=4))
tcp                         LISTEN                       0                             4096                                                             0.0.0.0:81                                                       0.0.0.0:*                           users:(("docker-proxy",pid=120860,fd=4))
tcp                         LISTEN                       0                             4096                                                             0.0.0.0:30033                                                    0.0.0.0:*                           users:(("docker-proxy",pid=21874,fd=4))
tcp                         LISTEN                       0                             4096                                                       127.0.0.53%lo:53                                                       0.0.0.0:*                           users:(("systemd-resolve",pid=537,fd=13))
tcp                         LISTEN                       0                             128                                                              0.0.0.0:22                                                       0.0.0.0:*                           users:(("sshd",pid=626,fd=3))
tcp                         LISTEN                       0                             4096                                                      aaa.bbb.ccc.ddd:25                                                       0.0.0.0:*                           users:(("docker-proxy",pid=122062,fd=4))
tcp                         LISTEN                       0                             4096                                                           127.0.0.1:8443                                                     0.0.0.0:*                           users:(("docker-proxy",pid=121922,fd=4))
tcp                         LISTEN                       0                             4096                                                             0.0.0.0:443                                                      0.0.0.0:*                           users:(("docker-proxy",pid=120842,fd=4))
tcp                         LISTEN                       0                             4096                                                             0.0.0.0:10011                                                    0.0.0.0:*                           users:(("docker-proxy",pid=21892,fd=4))
tcp                         LISTEN                       0                             4096                                                      aaa.bbb.ccc.ddd:993                                                      0.0.0.0:*                           users:(("docker-proxy",pid=121958,fd=4))
tcp                         LISTEN                       0                             4096                                                      aaa.bbb.ccc.ddd:995                                                      0.0.0.0:*                           users:(("docker-proxy",pid=121946,fd=4))
tcp                         LISTEN                       0                             4096                                                      aaa.bbb.ccc.ddd:2376                                                     0.0.0.0:*                           users:(("dockerd",pid=6445,fd=8))
tcp                         LISTEN                       0                             4096                                                      aaa.bbb.ccc.ddd:587                                                      0.0.0.0:*                           users:(("docker-proxy",pid=121970,fd=4))
```

The custom ngnix configuration for the proxy host was taken from the mailu documentation, and reads:
```
location / {
  proxy_pass http://127.0.0.1:8080;
  proxy_redirect https://127.0.0.1 https://mail.mydomain.tld;
}
location /webmail {
  proxy_pass http://127.0.0.1:8080/webmail;
  proxy_redirect https://127.0.0.1 https://mail.mydomain.tld;
}
location /admin {
  proxy_pass http://127.0.0.1:8080/admin;
  proxy_redirect https://127.0.0.1 https://mail.mydomain.tld;
  proxy_set_header Host $http_host;
}
```

Below are some screen grabs of the Nginx Proxy Manager configuration for the proxy settings:
![1](https://user-images.githubusercontent.com/66255771/118189114-46ddab00-b439-11eb-925d-0ff69cf891e0.PNG)

and

![2](https://user-images.githubusercontent.com/66255771/118189132-4c3af580-b439-11eb-851f-75aee231ef86.PNG)

There are no mailu error logs, as the web browser is not hitting the mailu_front_1 instance.

Does anyone have any advise on how to go about configuring nginx proxy manager and mailu to play nice with each other?

**Comment by dgalli1** [comment]
You shouldn't have to do anything besides pointing. NPM at localhost:8080
The location stuff is only necessary if you have something else running on this domain. But it doesn't look like it because you also proxy it to 8080
This is all i had to do to proxy mailu to mail.domain.tld I proxied the https port but i don't think that's the issue in your case

![grafik](https://user-images.githubusercontent.com/6371945/118332237-0ef26880-b50a-11eb-80bd-1b2e57b32fa2.png)

**Comment by apainter2** [comment]
Thanks, I tried it again, but used the https port and I still get 602 gateway error. 

Would you be willing to share your ports section of the front container mailu configuration/docker-compose, so I can see how you setup the IP:PORT allocations?

Also, did you place the NPM container on its own network, the bridge network or on the mailu network?

**Comment by dgalli1** [comment]
Alright this is gonne be a long one. First of Mailu Docker-Compose Port config:
```yaml
  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "2080:80"
      - "2443:443"
      - "2025:25"
      - "2465:465"
      - "2587:587"
      - "2110:110"
      - "2995:995"
      - "2143:143"
      - "2993:993"
    volumes:
      - "/ssl/cert/wildcard.galli.li:/certs"
```

I'm on two different machines that are connected via a Wireguard connection.
So I'm getting the cert by syncing them via rsync. This is my script for ref: https://github.com/dgalli1/sync-npm-change
Also I'm connecting to mailu via the host for the same reason.

Mailu SSL is configured like this:
```yaml
# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=cert
##Custome cert filenames
TLS_KEYPAIR_FILENAME=privkey.pem
```

**Comment by apainter2** [comment]
@dgalli1 THank you! Your suggestions really helped!

As I run mailu and npm on the same docker host, there were a few things I had to do to get this to work, I had to migrate the mailu network from its default 192.168.x.x network that the setup script had me using, to a 172.x.0.0/24 network.

I also had to adjust my docker-compose.yml file for the front network ports to the following:

```
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "0.0.0.0:9080:80"
      - "0.0.0.0:9443:443"
      - "xxx.xxx.xxx.xxx:25:25"
      - "xxx.xxx.xxx.xxx:465:465"
      - "xxx.xxx.xxx.xxx:587:587"
      - "xxx.xxx.xxx.xxx:110:110"
      - "xxx.xxx.xxx.xxx:995:995"
      - "xxx.xxx.xxx.xxx:143:143"
      - "xxx.xxx.xxx.xxx:993:993"
    volumes:
      - "/home/user/docker_files/mailu/certs:/certs"
      - "/home/userdocker_files/mailu/overrides/nginx:/overrides"
```

For Nginx Proxy Manager, I set the proxy host address IP to the IP address of the server, it would not work with localhost/127.0.0.1, as I kept getting 502 Bad Gateway,
