### ISSUE TITLE
How to prevent external access to web mail?

### ISSUE THREAD

**Issue by MohseniBigBoy** [Mailu/Mailu#1808]
After installing Mailu, I run my mail server successfully. Everything is OK. Now I want to prevent external access to webmail (Roundcube). I want to access webmail and web admin from localhost, not other systems. How to do this?

**Comment by bdelwood** [comment]
[You can have Mailu listen only locally](https://mailu.io/master/reverse.html) by editing the service in docker-compose.

For example, only exposing mailu-front on localhost on port 8080 and 8443 of the host:
```yaml
front:
  # build: nginx
  image: mailu/nginx:$VERSION
  restart: always
  env_file: .env
  ports:
    - "127.0.0.1:8080:80"
    - "127.0.0.1:8443:443"
    ...
  volumes:
    - "$ROOT/certs:/certs"
```
