### ISSUE TITLE
Reverse DNS does not match SMTP Banner

### ISSUE THREAD

**Issue by parisni** [Mailu/Mailu#1821]
### Versions
mailu 1.8.0 begind a nginx reverse proxy
Here is the front configuration (i made several attempts and I removed the template provided `IPv4 listen address` to make things almost work):

```
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.8}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "8077:80"
      - "4477:443"
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides:ro"

```

My reverse proxy looks like this:

```
    server {
        server_name  mail.domain.com;


        location /webmail {
                      proxy_pass https://127.0.0.1:4477/webmail;
                      proxy_redirect https://localhost https://mail.domain.com; # makes accessible the webmail
                      proxy_set_header   Host $host;
                        }

        location /admin {
                      proxy_pass https://127.0.0.1:4477/admin;
                      proxy_set_header Host $http_host;
                        }
}
```

## Description
gmail and other provider works get my emails however hotmail and gmx do not. Then I checked on mxtoolbox and I have **only** this warning:

```
Reverse DNS does not match SMTP Banner
```

I tested this:
```
echo QUIT|nc mail.domain.com 25
220 mail.domain.com ESMTP ready
221 2.0.0 Bye
```
And also:

```
echo QUIT|nc domain.com 25
220 mail.domain.com ESMTP ready
221 2.0.0 Bye
```

I suspect the above trouble with mail delivery is related to the SMTP Banner problem. How to improve this ? 

Thanks 

## Logs

```
smtp_1      | May 30 14:48:52 mail postfix/smtp[18620]: B6A5E31000E9: to=<yyyy@xxx.zz>, relay=mx00.gmx.net[212.227.zz.zz]:25, delay=0.29, delays=0.17/0/0.13/0, dsn=4.0.0, status=deferred (host mx00.gmx.net[212.227.zz.zz] refused to talk to me: 554-gmx.net (mxgmx001) Nemesis ESMTP Service not available 554-No SMTP service 554-Bad DNS PTR resource record. 554 For explanation visit https://www.gmx.net/mail/senderguidelines?ip=109.26.xx.xx&c=rdns)
```
