### ISSUE TITLE
mailu with nginx proxy not working

### ISSUE THREAD

**Issue by Robin-Sch** [Mailu/Mailu#1954]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

## Description
https://mailu.io/master/reverse.html, this doesn't work, when trying to go to https://mail.mydomain.com it (= the browser) gives an error of `ERR_ADDRESS_UNREACHABLE`. 

If I change the compose ports to 80/443, I can connect (https://mail.mydomain.com/, http://mail.mydomain.com/ (redirects to https), https://serverIP/ (invalid cert), http://serverIP/ (redirects to https) all work).

But when setting nginx to proxy_pass to the compose port (like 8000) it doesn't and the browser gets that error. (https://mail.mydomain.com/, http://mail.mydomain.com/, https://serverIP/, http://serverIP/ all give that error).

## Replication Steps
Edit a nginx config to
```
server {
        server_name mail.mydomain.com;
        listen 443;

        location / {
                proxy_pass https://localhost:8001/;
        }
}
server {
        server_name mail.mydomain.com;
        listen 80;

        location / {
                proxy_pass http://localhost:8000/;
        }
}
```
And docker compose
```
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-local}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
#      - "0.0.0.0:80:80"
#      - "::1:80:80"
#      - "0.0.0.0:443:443"
#      - "::1:443:443"
      - "0.0.0.0:8000:80"
      - "0.0.0.0:8001:443"
      - "0.0.0.0:25:25"
      - "::1:25:25"
      - "0.0.0.0:465:465"
      - "::1:465:465"
      - "0.0.0.0:587:587"
      - "::1:587:587"
      - "0.0.0.0:110:110"
      - "::1:110:110"
      - "0.0.0.0:995:995"
      - "::1:995:995"
      - "0.0.0.0:143:143"
      - "::1:143:143"
      - "0.0.0.0:993:993"
      - "::1:993:993"
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides"
```

## Expected behaviour
Nginx should work the exact same as setting port 80/443 in the compose file.

## Logs
```
docker logs mailu_front_1
```
Doesn't change when visiting the webpage.

If I set `error_log` with nginx, nothing gets logged either.
