### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ulm0** [Mailu/Mailu#1963]
### Environment
 - [ ] docker-compose
 - [x] kubernetes
 - [ ] docker swarm

### Versions
`v1.8` via helm-chart (https://github.com/Mailu/helm-charts)

## Description

I've recently deploy a fresh installation of mailu in kubernetes using the helm chart, everything seems to work perfectly. But when attempting to login to roundcube it fails with error `Login Failed`.

**Note**: I can login succesfully to the admin panel, though.

## Replication Steps
- Deploy helm chart (0.1.2)

## Expected behaviour
Be able to login to mail client

## Values file for helm

```yml
mailuVersion: "1.8"
hostnames:
  - mail.domain.com
domain: domain.com
initialAccount:
  domain: domain.com
  username: me
  password: ch4ng3m3!
logLevel: INFO
secretKey: ch4ng3m3!
mail:
  authRatelimit: 100/minute;3600/hour
  messageSizeLimitInMegabytes: 200
certmanager:
  issuerName: le-clusterissuer
persistence:
  size: 200Gi
  storageClass: local-path
webdav:
  enabled: true
ingress:
  tlsFlavor: cert
  externalIngress: true
  annotations:
    kubernetes.io/ingress.class: kong
    ingress.kubernetes.io/force-ssl-redirect: "true"
```

## Logs

logs collected using stern, so it contains logs from different services. Some values have been edited for obvious reasons.

```
mailu-dovecot-ff788d5fd-9dc9k admin Aug 30 23:31:19 imap-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 2 secs): user=<me@domain.com>, method=PLAIN, rip=10.0.0.155, lip=10.0.0.223, session=<whvROs/KuoYKAACb>
mailu-front-6db6894c96-wjwwr front 2021/08/30 23:31:19 [info] 11#11: *226 upstream sent invalid response: "NO [AUTHENTICATIONFAILED] Authentication failed." while reading response from upstream, client: 10.0.0.32, server: 0.0.0.0:10143, login: "me@domain.com", upstream: 10.43.168.56:143
mailu-roundcube-9dcc564d7-9txxn roundcube [30-Aug-2021 23:31:19 +0000]: <c1ebe1a1> IMAP Error: Login failed for me@domain.com against mailu-front from 10.0.0.155(X-Real-IP: 10.0.0.132,X-Forwarded-For: 192.168.1.124, 10.0.0.132). AUTHENTICATE PLAIN: Authentication failed. in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
mailu-front-6db6894c96-wjwwr front 10.0.0.132 - - [30/Aug/2021:23:31:20 +0000] "POST /?_task=login HTTP/1.1" 401 2145 "https://mail.domain.com/?_task=login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
mailu-roundcube-9dcc564d7-9txxn roundcube 10.0.0.155 - - [30/Aug/2021:23:31:17 +0000] "POST /?_task=login HTTP/1.1" 401 2818 "https://mail.domain.com/?_task=login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
```
