### ISSUE TITLE
Replying to message causes error: "can't read SMFIC_BODYEOB reply packet header: Application error"

### ISSUE THREAD

**Issue by technodrome** [Mailu/Mailu#2021]
## Before you open your issue
- [X] Check if no issue or pull-request for this already exists.
- [Y] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [ ] docker-compose
 - [X] kubernetes
 - [ ] docker swarm

### Versions
1.8 (Helm), using images from `leolivier/mailu_*`, running on RPi cluster, three nodes (4 GB memory each), NFS share as shared data storage, OS Raspbian GNU/Linux 10 (buster), kernel 5.10.63-v8+, K3s version: v1.21.0+k3s1, containerd://1.4.4-k3s1

`my-values-file.yaml`
```yaml
# A list of mail hostnames is required. The first will be used as primary mail hostname
hostnames:
 - mail.macgyver.com # fake hostname

# The mail domain is required. See https://github.com/leolivier/mailu_leolivier/mailu_blob/master/docs/faq.rst#what-is-the-difference-between-domain-and-hostnames
domain: macgyver.com

# The secret key is required for protecting authentication cookies and must be set individually for each deployment
secretKey: XXXXXXXX

# An initial account can automatically be created:
initialAccount:
 username: mailadmin
 domain: macgyver.com
 password: xxxxxxx

nameOverride: ""
fullnameOverride: ""
clusterDomain: cluster.local

nodeSelector: {}

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: {}

# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

database:
  # type of the database for mailu (sqlite or mysql)
  # default database is an embedded sqlite
  # for mysql, see settings below
  type: sqlite

  # type of the database for roundcube (sqlite or mysql)
  # default database is an embedded sqlite
  # for mysql, see settings below
  roundcubeType: sqlite

# For mysql/mariadb use the following config:
# Set the host to use an external database.
# If not host is set, a database instance is created by this chart.
#   type: mysql
  mysql: {}
    # host: external-db-hostname
    # root password for mysql database
    # rootPassword: chang3m3! # can only be set for embedded mysql

    # settings for mailu (required if mailu database type is "mysql")
    # database: mailu
    # user: mailu
    # password: chang3m3!

  # For an external PostgreSQL database, use the following config:
  postgresql: {}
    # host: external-db-hostname
    # database: mailu
    # user: mailu
    # password: chang3m3!

    # settings for roundcube (required if roundcube database type is "mysql" or "postgresql")
    # roundcubeDatabase: roundcube
    # roundcubeUser: roundcube
    # roundcubePassword: chang3m3!

external_relay: {}
#    host: "[domain.tld]:port"
#    username: username
#    password: SECRET

persistence:
  size: 100Gi
  accessMode: ReadWriteOnce
  #annotations:
  #  "helm.sh/resource-policy": keep
  #hostPath: /path/on/the/host
  #existingClaim: name-of-existing.claim
  storageClass: nfs-client
  #claimNameOverride: my-claim-name

# Change this if you're using different address ranges for pods
subnet: 10.42.0.0/16

# Version of mailu docker images to use when not specified otherwise
mailuVersion: 1.8

# default log level. can be overridden globally or per service
logLevel: WARNING

mail:
  messageSizeLimitInMegabytes: 50
  authRatelimit: 10/minute;1000/hour

# certmanager settings
certmanager:
  enabled: true
  issuerType: ClusterIssuer
  issuerName: letsencrypt-production
  apiVersion: cert-manager.io/v1

# Set ingress and loadbalancer config
ingress:
  externalIngress: true
  tlsFlavor: cert
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"

# Frontend load balancer for non-HTTP(s) services
front:
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_nginx
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  # Deployment or DaemonSet
  controller:
    kind: Deployment

admin:
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_admin
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 500m
  podAnnotations: {}

redis:
  image:
    repository: redis
    tag: 5-alpine
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 300Mi
      cpu: 200m

postfix:
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_postfix
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 500m

dovecot:
  enabled: true
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_dovecot
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 500m
  # enable dovecot overrides
  # overrides:
  #   dovecot.conf: |
  #     # More info here: https://mailu.io/1.8/kubernetes/leolivier/mailu_index.html#dovecot
  #     mail_nfs_index = yes
  #     mail_nfs_storage = yes
  #     mail_fsync = always
  #     mmap_disable = yes
  #     mail_max_userip_connections=100

rspamd:
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_rspamd
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m

clamav:
  enabled: false
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_clamav
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 1Gi
      cpu: 1000m
    limits:
      memory: 2Gi
      cpu: 1000m

roundcube:
  enabled: true
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_roundcube
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m


webdav:
  enabled: true
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_radicale
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release

mysql:
  image:
    repository: library/mariadb
    tag: 10.4.10
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

fetchmail:
  enabled: true
  # logLevel: WARNING
  image:
    repository: leolivier/mailu_fetchmail
    # tag defaults to mailuVersion
    tag: rpi-armv7-1.8-release
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  delay: 600
```

## Description
With the abovementioned .yaml values file and clamav disabled and "enable spam filter" disabled for the current user, **replying** to a message fails with the following error (user names, domains and IP addresses redacted):

```
Oct 21 13:15:22 mail postfix/smtpd[12073]: connect from 10-42-0-58.mailu-front.mailu-mailserver.svc.cluster.local[10.42.0.58]
Oct 21 13:15:23 mail postfix/smtpd[12073]: 181C8A00079: client=unknown[000.000.000.000], sasl_method=XCLIENT, sasl_username=mac@macgyver.com
Oct 21 13:15:23 mail postfix/cleanup[12076]: 181C8A00079: replace: header Received: from [127.0.0.1] (unknown [000.000.000.000])??by mail.macgyver.com (Postfix) with ESMTPA id 181C8A00079??for <XXX@gmail.com>; Thu, 21 Oct 2021 13:15:22 +0000 (UTC) from unknown[000.000.000.000]; from=<mac@macgyver.com> to=<XXX@gmail.com> proto=ESMTP helo=<[127.0.0.1]>: Received: from authenticated-user (mail.macgyver.com [111.111.111.111])??by mail.macgyver.com (Postfix) with ESMTPA id 181C8A00079??for <XXX@gmail.com>; Thu, 21 Oct 2021 13:15:22 +0000 (UTC)
Oct 21 13:15:23 mail postfix/cleanup[12076]: 181C8A00079: message-id=<EDD14E18-2B9C-4AC3-9D71-C771ADA2FF35@macgyver.com>
Oct 21 13:15:24 mail postfix/cleanup[12076]: warning: milter inet:mailu-rspamd:11332: can't read SMFIC_BODYEOB reply packet header: Application error
Oct 21 13:15:24 mail postfix/cleanup[12076]: 181C8A00079: milter-reject: END-OF-MESSAGE from unknown[000.000.000.000]: 4.7.1 Service unavailable - try again later; from=<mac@macgyver.com> to=<XXX@gmail.com> proto=ESMTP helo=<[127.0.0.1]>
Oct 21 13:15:24 mail postfix/smtpd[12073]: disconnect from unknown[000.000.000.000] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=0/1 quit=1 commands=5/7
```

This `warning: milter inet:mailu-rspamd:11332: can't read SMFIC_BODYEOB reply packet header: Application error` is caused only when replying to a delivered email. Let's say I sent email from `macgyver.com` to `gmail.com` - that works. But when I try to reply from `gmail.com` to the delivered email, receiving `mail.macgyver.com` returns that error.

Things to note:
- domains uses DNSSEC by Cloudflare, traffic to mail.macgyver.com is not proxified by Cloudflare
- all relevant ports on the router's firewall are routed to the K3s master node, mail delivery works only with postfix's `nodeSelector` set to master, but I will open a separate ticket for that
- mxtoolbox.com does not report any errors
- reverse PTR is set for the mail domain

I do not understand this mail filter error when spam checks for that email address are turned off. Any assistance with this error is appreciated. Thank you.
