### ISSUE TITLE
mailu postfix not starting on k8s

### ISSUE THREAD

**Issue by radoslav-stefanov** [Mailu/Mailu#2022]
Hi guys,

Trying to start Mailu on Kubernetes environment. Attaching my helm values file bellow.

For some reason the postfix pod stays in unhealthy status. Checking pod status says Readiness and Liveness probes have failed.

Not sure how to debug further as there are no logs.

Mailu version is ```1.8``` and postfix image appears to be ```mailu/postfix:1.8```.

Pods status
```
kubectl get pods -n mailu
NAME                               READY   STATUS    RESTARTS   AGE
mailu-admin-685997bc95-smr72       1/1     Running   0          17m
mailu-clamav-ff6778464-csbr8       1/1     Running   0          17m
mailu-dovecot-5749f7cdb9-2fn8s     1/1     Running   0          17m
mailu-front-786974864f-btb66       1/1     Running   0          17m
mailu-postfix-9597d9c46-xdx84      0/1     Running   3          17m
mailu-redis-58666b6b4d-7zvg9       1/1     Running   0          17m
mailu-roundcube-7f69cfb9c9-j8gg5   1/1     Running   0          17m
mailu-rspamd-79bf487b59-45r99      1/1     Running   0          17m
```

Docker container logs (its empty)
```
docker logs k8s_postfix_mailu-postfix-9597d9c46-xdx84_mailu_57db1866-fd4f-4f53-81af-bf900df55f5a_2
```

kubectl describe pod
```
kubectl describe pod -n mailu mailu-postfix-9597d9c46-xdx84
Name:         mailu-postfix-9597d9c46-xdx84
Namespace:    mailu
Priority:     0
Node:         k8s-n1/162.55.243.36
Start Time:   Sat, 23 Oct 2021 15:17:38 +0300
Labels:       app=mailu
              component=postfix
              pod-template-hash=9597d9c46
Annotations:  cni.projectcalico.org/containerID: 7bcf3f9205a8496f97eb49bd18b1a6066abdc38518315a6937eb8b5ebccf0017
              cni.projectcalico.org/podIP: 10.42.215.94/32
              cni.projectcalico.org/podIPs: 10.42.215.94/32
Status:       Running
IP:           10.42.215.94
IPs:
  IP:           10.42.215.94
Controlled By:  ReplicaSet/mailu-postfix-9597d9c46
Containers:
  postfix:
    Container ID:   docker://9c0b371659fbd929427b491ea1f0d70291cb26fa13a65cda57e6402804b21288
    Image:          mailu/postfix:1.8
    Image ID:       docker-pullable://mailu/postfix@sha256:dc7793c6887a2d7558358800ff06d130638125bac7c7f65af163942f4ace6a56
    Ports:          25/TCP, 465/TCP, 587/TCP, 10025/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Sat, 23 Oct 2021 15:39:59 +0300
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Sat, 23 Oct 2021 15:34:29 +0300
      Finished:     Sat, 23 Oct 2021 15:39:58 +0300
    Ready:          False
    Restart Count:  4
    Limits:
      cpu:     500m
      memory:  2Gi
    Requests:
      cpu:      500m
      memory:   2Gi
    Liveness:   exec [sh -c echo QUIT|nc localhost 25|grep "220 .* ESMTP Postfix"] delay=0s timeout=5s period=10s #success=1 #failure=30
    Readiness:  exec [sh -c echo QUIT|nc localhost 25|grep "220 .* ESMTP Postfix"] delay=0s timeout=5s period=10s #success=1 #failure=3
    Environment:
      LOG_LEVEL:                  WARNING
      REJECT_UNLISTED_RECIPIENT:  yes
      DOMAIN:                     domain.com
      HOSTNAMES:              domain.com
      MESSAGE_SIZE_LIMIT:         52428800
      SUBNET:                     10.42.0.0/16
      RECIPIENT_DELIMITER:        +
      LMTP_ADDRESS:               mailu-dovecot:2525
      ANTISPAM_MILTER_ADDRESS:    mailu-rspamd:11332
      ADMIN_ADDRESS:              mailu-admin
      FRONT_ADDRESS:              mailu-front
    Mounts:
      /queue from data (rw,path="mailqueue")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-6467c (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mailu
    ReadOnly:   false
  kube-api-access-6467c:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute for 300s
                             node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  25m                    default-scheduler  Successfully assigned mailu/mailu-postfix-9597d9c46-xdx84 to k8s-n1
  Normal   Pulling    24m                    kubelet, k8s-n1    Pulling image "mailu/postfix:1.8"
  Normal   Pulled     24m                    kubelet, k8s-n1    Successfully pulled image "mailu/postfix:1.8" in 5.928828227s
  Normal   Created    24m                    kubelet, k8s-n1    Created container postfix
  Normal   Started    24m                    kubelet, k8s-n1    Started container postfix
  Warning  Unhealthy  9m44s (x84 over 24m)   kubelet, k8s-n1    Liveness probe failed:
  Warning  Unhealthy  4m44s (x124 over 24m)  kubelet, k8s-n1    Readiness probe failed:
```

Here is my values.yaml file.

values.yaml
```
# Default values for mailu.

# A list of mail hostnames is required. The first will be used as primary mail hostname
hostnames:
  - mail.domain.com

# The mail domain is required. See https://github.com/Mailu/Mailu/blob/master/docs/faq.rst#what-is-the-difference-between-domain-and-hostnames
domain: domain.com

# The secret key is required for protecting authentication cookies and must be set individually for each deployment
secretKey: secret_key

# An initial account can automatically be created:
initialAccount:
  username: admin
  domain: domain.com
  password: pwd


nameOverride: ""
fullnameOverride: ""
clusterDomain: cluster.local

nodeSelector: {}

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: {}

# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

database:
  # type of the database for mailu (sqlite or mysql)
  # default database is an embedded sqlite
  # for mysql, see settings below
  type: sqlite

  # type of the database for roundcube (sqlite or mysql)
  # default database is an embedded sqlite
  # for mysql, see settings below
  roundcubeType: sqlite

# For mysql/mariadb use the following config:
# Set the host to use an external database.
# If not host is set, a database instance is created by this chart.
#   type: mysql
  mysql: {}
    # host: external-db-hostname
    # root password for mysql database
    # rootPassword: chang3m3! # can only be set for embedded mysql

    # settings for mailu (required if mailu database type is "mysql")
    # database: mailu
    # user: mailu
    # password: chang3m3!

  # For an external PostgreSQL database, use the following config:
  postgresql: {}
    # host: external-db-hostname
    # database: mailu
    # user: mailu
    # password: chang3m3!

    # settings for roundcube (required if roundcube database type is "mysql" or "postgresql")
    # roundcubeDatabase: roundcube
    # roundcubeUser: roundcube
    # roundcubePassword: chang3m3!

external_relay: {}
#    host: "[domain.tld]:port"
#    username: username
#    password: SECRET

persistence:
  size: 10Gi
  accessMode: ReadWriteOnce
  annotations:
    "helm.sh/resource-policy": keep
  #hostPath: /path/on/the/host
  #existingClaim: name-of-existing.claim
  storageClass: "longhorn"
  claimNameOverride: mailu

# Change this if you're using different address ranges for pods
subnet: 10.42.0.0/16

# Version of mailu docker images to use when not specified otherwise
mailuVersion: 1.8

# default log level. can be overridden globally or per service
logLevel: WARNING

mail:
  messageSizeLimitInMegabytes: 50
  authRatelimit: 10/minute;1000/hour

# certmanager settings
certmanager:
  enabled: true
  issuerType: ClusterIssuer
  issuerName: letsencrypt-dns01
  apiVersion: cert-manager.io/v1

# Set ingress and loadbalancer config
ingress:
  externalIngress: true
  tlsFlavor: cert
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"

# Frontend load balancer for non-HTTP(s) services
front:
  # logLevel: WARNING
  image:
    repository: mailu/nginx
    # tag defaults to mailuVersion
    # tag: master
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  # Deployment or DaemonSet
  controller:
    kind: Deployment

admin:
  # logLevel: WARNING
  image:
    repository: mailu/admin
    # tag defaults to mailuVersion
    # tag: master
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 500m
  podAnnotations: {}

redis:
  image:
    repository: redis
    tag: 5-alpine
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 300Mi
      cpu: 200m

postfix:
  # logLevel: WARNING
  image:
    repository: mailu/postfix
    # tag defaults to mailuVersion
    # tag: master
  resources:
    requests:
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 500m

dovecot:
  enabled: true
  # logLevel: WARNING
  image:
    repository: mailu/dovecot
    # tag defaults to mailuVersion
    # tag: master
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 500m
  # enable dovecot overrides
  # overrides:
  #   dovecot.conf: |
  #     # More info here: https://mailu.io/1.8/kubernetes/mailu/index.html#dovecot
  #     mail_nfs_index = yes
  #     mail_nfs_storage = yes
  #     mail_fsync = always
  #     mmap_disable = yes
  #     mail_max_userip_connections=100

rspamd:
  # logLevel: WARNING
  image:
    repository: mailu/rspamd
    # tag defaults to mailuVersion
    # tag: master
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m

clamav:
  enabled: true
  # logLevel: WARNING
  image:
    repository: mailu/clamav
    # tag defaults to mailuVersion
    # tag: master
  resources:
    requests:
      memory: 1Gi
      cpu: 1000m
    limits:
      memory: 2Gi
      cpu: 1000m

roundcube:
  enabled: true
  # logLevel: WARNING
  image:
    repository: mailu/roundcube
    # tag defaults to mailuVersion
    # tag: master
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m


webdav:
  enabled: false
  # logLevel: WARNING
  image:
    repository: mailu/radicale
    # tag defaults to mailuVersion
    # tag: master

mysql:
  image:
    repository: library/mariadb
    tag: 10.4.10
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

fetchmail:
  enabled: false
  # logLevel: WARNING
  image:
    repository: mailu/fetchmail
    # tag defaults to mailuVersion
    # tag: master
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  delay: 600
```
