### ISSUE TITLE
Disable/Enable domain for migration purpose

### ISSUE THREAD

**Issue by bascouba** [Mailu/Mailu#2026]
Hi,

I would like to migrate my mail server domain per domain but the already migrated domains will start to send mails to the "on-migration" domains that are being created in the mailu server. Thus the old server will never receive any of that.
I have an efa system right behind the MX that can redirect domains to the old/new server but the mails won't go to them since the domain is already listed on the server

Is there a way to achieve what I want that I haven't seen yet ?

My old server is an ISP where I can disable/enable domains and then receive my mails on the new server from it without deleting old domains

**Comment by ghostwheel42** [comment]
Hi @bascouba 
Sorry, I didn't see your question. Did you try listing the domain under "Relay-Domains"?
You could try to list the domain under Relayed domain name "not-migrated-yet.tld" and point via Remote host to your efa systems IP address.
I didn't test if this works, but its worth a try.

**Comment by bascouba** [comment]
Hi @ghostwheel42 , thank you for your answer. 
The problem is that once I created a relayed domain I can't create the same one in my domains to work on it. And I can't create a tmp domain name since it is locked after creation (or I would have to interact with database directly but I don't want to do that)

**Comment by ghostwheel42** [comment]
Hi. Okay, I see. With 1.9 you'll be able to export / import / update the configuration on the commandline.

With this you can create all "relays" and migrate each domain by updating your configuration step by step like this:
```
docker exec -i <mailu_admin_1> flask mailu config-import -vu <<EOF
relay:
  - -name: migrate.foo.bar
domain:
  - name: migrate.foo.bar
user:
  - email: user@migrate.foo.bar
    password: ...
EOF
```

This will update the configuration in one step.
