### ISSUE TITLE
No `database` container in `docker-compose.yml`, `admin` container has a dependency.

### ISSUE THREAD

**Issue by c4lliope** [Mailu/Mailu#2041]
Hello all,
I used https://setup.mailu.io/1.8 and generated a `docker-compose.yml` and `mailu.env`.

I had to change the `front` service `ports` so that they reference my machine's IP address. That way, I can see the webmail interface when I go to my domain in a browser.

Besides the `front - ports` mappings, I haven't changed anything in my `docker-compose.yml` file.
The services listed inside are:
```
redis:
front:
admin:
imap:
antispam:
antivirus:
webdav:
fetchmail:
webmail:
```

There is no `database` service - expected to be running postgresql based on my setup configuration, which causes an error when I run the documentation's command:

```
docker-compose exec admin flask mailu admin me example.net 'password'
```

The error is:
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "database" to address: Name does not resolve
```

I am looking for a postgres service I can drop into my `docker-compose.yml` file to add a postgres database in a manner which can serve the `admin` container's needs. Any drop-in code block available?

**Comment by c4lliope** [comment]
Similar to #1670 , except not platform-specific.

**Comment by c4lliope** [comment]
The final configuration in my `mailu.env` file is:
```.env
###################################
# Database settings
###################################
DB_FLAVOR=postgresql
```

although that variable does not appear any place in my `docker-compose.yml`.

**Comment by c4lliope** [comment]
I succeeded by using this in my `docker-compose.yml`:

```
services:

  database:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=mailu
      - POSTGRES_USER=mailu
      - POSTGRES_PASSWORD=mailu
    expose:
      - 5432
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg: {}
```
