### ISSUE TITLE
Kustomize setup

### ISSUE THREAD

**Issue by pgmillon** [Mailu/Mailu#2089]
### Environment
 kubernetes

### Versions
Mailu 1.8

## Description
First, thank you guys for the amazing work you're doing to provide a fully operational postfix/dovecot/db mail server on containers.

I just wanted to share that it's very easy to also deploy with Kustomize since it supports helm charts (given that helm is installed).
With such combo you can extend mailu official helm charts with components (like mailman):

kustomization.yml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mail_namespace

helmCharts:
  - name: mailu
    includeCRDs: false
    valuesInline:
      domain: example.com
      hostnames:
        - mail.example.com
      initialAccount:
        domain: example.com
        password: ...
        username: admin
      logLevel: INFO
      mail:
        authRatelimit: 100/minute;3600/hour
        messageSizeLimitInMegabytes: 200
      persistence:
        size: 20Gi
        storageClass: standard
      secretKey: s3cr3t
      database:
        type: mysql
        roundcubeType: mysql
        mysql:
          database: mail_db
          user: mail_admin
          password: s3cr3t
          host: mysql
          roundcubeDatabase: roundcube_db
          roundcubeUser: roundcube_user
          roundcubePassword: s3cr3t
      subnet: 172.17.0.0/16
      certmanager:
        enabled: true
        issuerType: Issuer
        issuerName: letsencrypt-prod
        apiVersion: cert-manager.io/v1
      rspamd:
        resources:
          limits:
            memory: 500Mi
    releaseName: main
    namespace: mail_namespace
    version: 0.1.6
    repo: https://mailu.github.io/helm-charts/

resources:
  - certificate.yml # certbot issuers
  
# created from https://github.com/maxking/docker-mailman/blob/main/docker-compose-mysql.yaml
  - mailman-core/pvc.yml
  - mailman-core/deployment.yml
  - mailman-core/service.yml
  - mailman-core/config-map.yml
  
  - mailman-web/deployment.yml
  - mailman-web/service.yml
  - mailman-web/ingress.yml

# override main.cf with a transport map for mailman (source: https://github.com/maxking/docker-mailman/blob/9beb9a1517fe3cc4e7054c4f9e7600f243888bd9/README.md?plain=1#L379-L380)
configMapGenerator:
  - name: postfix-config
    files:
      - postfix/main.cf
      
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: main-mailu-postfix
    spec:
      template:
        spec:
          containers:
            - name: postfix
              volumeMounts:
              - name: mailman
                mountPath: /opt/mailman
                subPath: mailman/var/data
              - name: config
                mountPath: /conf/main.cf
                subPath: main.cf
          volumes:
            - name: mailman
              persistentVolumeClaim:
                claimName: mailman
            - name: config
              configMap:
                name: postfix-config
```
This is still a work in progress but I hope that can help some folks.
