### ISSUE TITLE
mail-letsencrypt -> imap: Can't load SSL certificate (ssl_cert setting): The certificate is empty

### ISSUE THREAD

**Issue by mdartmann** [Mailu/Mailu#2110]
### Environment
docker-compose

### Versions
1.8

## Description
After setting up Mailu behind a reverse proxy with the mail-letsencrypt TLS setting, I cannot connect to my server via IMAP using TLS or STARTTLS; after checking the logs for the imap container, I get `Error: Failed to initialize SSL server context: Can't load SSL certificate (ssl_cert setting): The certificate is empty` as an error message.

## Replication Steps
1. Set up Mailu using the docker-compose settings below
2. Try to connect to IMAP using implicit TLS => Server closes connection and error message appears in logs
3. Try to connect to IMAP using STARTTLS => Server sends invalid TLS header

## Expected behaviour
When using the mail-letsencrypt setting, I expect to have a properly generated certificate in place.

## Logs
```log
❯ telnet -4 maedartmann.name 993
Trying 83.138.55.44...
Connected to maedartmann.name.
Escape character is '^]'.
Connection closed by foreign host.
```
```log
Attaching to mailu_imap_1
imap_1      | Dec 25 19:54:19 master: Info: Dovecot v2.3.15 (0503334ab1) starting up for imap, po
p3, lmtp, sieve
imap_1      | Dec 25 19:54:25 imap-login: Error: Failed to initialize SSL server context: Can't l
oad SSL certificate (ssl_cert setting): The certificate is empty: user=<>, rip=172.19.0.1, lip=17
2.19.0.6, session=<UoGr1v3TDpKsEwAB>
```

#### `mailu.env`:
```sh
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=REDACTED4PRIVACY

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.168.0.0/16

# Main mail domain
DOMAIN=maedartmann.name

# Hostnames for this server, separated with comas
HOSTNAMES=mail.maedartmann.name,maedartmann.name

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=mail-letsencrypt

# Authentication rate limit (per source IP address)
AUTH_RATELIMIT=30/minute

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=True

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=roundcube

# Dav server implementation (value: radicale, none)
WEBDAV=none

# Antivirus solution (value: clamav, none)
ANTIVIRUS=none

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: bz2, gz)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

# IMAP full-text search is enabled by default. Set the following variable to off in order to disable the feature.
# FULL_TEXT_SEARCH=off

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/webmail

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/webmail

# Website name
SITENAME=Mae Dartmann

# Linked Website URL
WEBSITE=https://maedartmann.name



###################################
# Advanced settings
###################################

# Log driver for front service. Possible values:
# json-file (default)
# journald (On systemd platforms, useful for Fail2Ban integration)
# syslog (Non systemd platforms, Fail2Ban integration. Disables `docker-compose log` for front!)
# LOG_DRIVER=json-file

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Default password scheme used for newly created accounts and changed passwords
# (value: PBKDF2, BLF-CRYPT, SHA512-CRYPT, SHA256-CRYPT)
PASSWORD_SCHEME=PBKDF2

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

###################################
# Database settings
###################################
DB_FLAVOR=sqlite
```
#### docker-compose.yml:
```yml
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/srv/mailu/redis:/data"
    
  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.8}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "465:465"
      - "25:25"
      - "587:587"
    volumes:
      - "/srv/mailu/certs:/certs"
      - "/srv/mailu/overrides/nginx:/overrides:ro"
    environment:
      VIRTUAL_HOST: mail.maedartmann.name
      LETSENCRYPT_HOST: mail.maedartmann.name
    expose:
      - "80"
    networks:
      - default
      - frontproxy_default

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.8}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.255.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.8}
    restart: always
    env_file: mailu.env
    volumes:
      - "/srv/mailu/data:/data"
      - "/srv/mailu/dkim:/dkim"
    depends_on:
      - redis

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.8}
    restart: always
    env_file: mailu.env
    volumes:
      - "/srv/mailu/mail:/mail"
      - "/srv/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
    ports:
      - "143:143"
      - "993:993"
      - "110:110"
      - "995:995"
    networks:
      - default
      - frontproxy_default

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.8}
    restart: always
    env_file: mailu.env
    volumes:
      - "/srv/mailu/mailqueue:/queue"
      - "/srv/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.255.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.8}
    hostname: antispam
    restart: always
    env_file: mailu.env
    volumes:
      - "/srv/mailu/filter:/var/lib/rspamd"
      - "/srv/mailu/dkim:/dkim:ro"
      - "/srv/mailu/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.255.254

  # Optional services
  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.8}
    restart: always
    env_file: mailu.env
    volumes:
      - "/srv/mailu/webmail:/data"
    depends_on:
      - imap


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
  frontproxy_default: 
    external: true
```

**Comment by Diman0** [comment]
Why did you change the docker-compose.yml file?
All communication goes through front. This part from the imap service must be moved back to the front service. 
```
  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.8}
    restart: always
    env_file: mailu.env
    volumes:
      - "/srv/mailu/mail:/mail"
      - "/srv/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
    ports:
      - "143:143"
      - "993:993"
      - "110:110"
      - "995:995"
 ```

I recommend to recreate the docker-compose.yml file via setup.mailu.io to make sure any incorrect changes are undone.
