### ISSUE TITLE
Access denied for user 'roundcube'

### ISSUE THREAD

**Issue by romannik007** [Mailu/Mailu#2112]
### Environment
 - [ ] docker-compose
 

```
...
webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.8}
    restart: always
    env_file: mailu.env
    volumes:
      - "./mailu/webmail:/data"
    depends_on:
      - imap
      - mysql

mysql:
    build:
      context: ./mysql
      dockerfile: dockerfile.mysql
    hostname: mysql
    restart: always
    env_file: mailu.env
    volumes:
      - "./mysql/mysql_entrypoint.sh:/mysql_entrypoint.sh"
      - "./mailu/mysql:/var/lib/mysql"
    command: "/mysql_entrypoint.sh
```
```
docker-compose up -d --build
docker-compose logs webmail
```

## Logs

webmail_1    | Initializing database
webmail_1    | ERROR: SQLSTATE[HY000] [1045] Access denied for user 'roundcube'@'192.168.203.11' (using password: YES)
webmail_1    | ERROR: Failed to connect to database

i fixed setup.py in webmail service to
```
...
if db_flavor=="sqlite":
    os.environ["DB_DSNW"]="sqlite:////data/roundcube.db"
elif db_flavor=="mysql":
    os.environ["DB_DSNW"]="mysql://%s:%s@%s/%s" % (
        os.environ.get("ROUNDCUBE_DB_USER","roundcube"),
        os.environ.get("ROUNDCUBE_DB_PW",os.environ.get("DB_PW","password")),
        os.environ.get("ROUNDCUBE_DB_HOST",os.environ.get("DB_HOST","database")),
        os.environ.get("ROUNDCUBE_DB_NAME","roundcube")
...
```
it's work
