### ISSUE TITLE
releases are created with tag on latest commit on master instead of the passed commit hash

### ISSUE THREAD

**Issue by Diman0** [Mailu/Mailu#2124]
https://github.com/Mailu/Mailu/blob/3453d12ccbc2624b45178ddc1332c4e650b2c9ce/.github/workflows/CI.yml#L658
```
      - name: Tag and create release
        if: ${{ env.BRANCH != 'testing' && env.BRANCH != 'staging' && env.BRANCH != 'master' && env.PINNED_MAILU_VERSION != '' }}
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "RELEASE_TEMPLATE.md"
          commit: ${{ env.GITHUB_SHA }}
          tag: ${{ env.PINNED_MAILU_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
```

Even though the action for creating the release receives the correct commit hash ( see env.GITHUB_SHA ), it tags the release/tag to the latest commit on the master branch. The tags should have been set to the following commits:
1.9.1: https://github.com/Mailu/Mailu/commit/89227e566524f24d0214ee0ff1a93f860b86d432
1.9.2: https://github.com/Mailu/Mailu/commit/bbca4f876ae4b97e7fdd918214f01b03ff2f4b32

The action documentation shows that we could also use a branch name instead of the commit hash. See https://github.com/ncipollo/release-action#notes

`
If the tag of the release you are creating does not yet exist, you should set both the tag and commit action inputs. commit can point to a commit hash or a branch name (ex - main).
`

We could try changing `commit: ${{ env.GITHUB_SHA }}` to `commit: ${{ env.BRANCH }}`. I hope the action "ncipollo/release-action@v1" works properly if we pass the branch (1.9) instead of the commit hash.

```
      - name: Tag and create release
        if: ${{ env.BRANCH != 'testing' && env.BRANCH != 'staging' && env.BRANCH != 'master' && env.PINNED_MAILU_VERSION != '' }}
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "RELEASE_TEMPLATE.md"
          commit: ${{ env.BRANCH  }}
          tag: ${{ env.PINNED_MAILU_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
```
