### ISSUE TITLE
recurring error in admin limiter: KeyError: 'WEBMAIL_ADDRESS'

### ISSUE THREAD

**Issue by leolivier** [Mailu/Mailu#2125]
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9.0 (erriez multiarch version)

## Description
A **lot** of the same error in the admin logs:
```
mailu.admin  | [2022-01-01 18:18:26,695] ERROR in app: Exception on /internal/auth/email [GET]
mailu.admin  | Traceback (most recent call last):
mailu.admin  |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
mailu.admin  |     response = self.full_dispatch_request()
mailu.admin  |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
mailu.admin  |     rv = self.handle_user_exception(e)
mailu.admin  |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
mailu.admin  |     rv = self.dispatch_request()
mailu.admin  |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
mailu.admin  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
mailu.admin  |   File "/app/mailu/internal/views/auth.py", line 19, in nginx_authentication
mailu.admin  |     utils.limiter.rate_limit_ip(client_ip)
mailu.admin  |   File "/app/mailu/limiter.py", line 56, in rate_limit_ip
mailu.admin  |     if ip != app.config['WEBMAIL_ADDRESS']:
mailu.admin  | KeyError: 'WEBMAIL_ADDRESS'
```

So the error seems to be that WEBMAIL_ADDRESS is not defined but I'm not using any webmail (neither roundcube nor rainloop)

## Replication Steps
Nothing special

## Expected behaviour
Shouldn't have this error in the logs

## Logs
see above. Always the same lines, only the time changes.
It's overwhelming the logs...

**Comment by Erriez** [comment]
Are you using `webmail:` in `docker-compose.yml`? For example:

```
services:
  ...
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-master}
    container_name: mailu_webmail
    restart: always
    env_file: mailu.env
    volumes:
      - "${VOLUME_DIR}/mailu/webmail:/data"
      - "${VOLUME_DIR}/mailu/overrides/roundcube:/overrides:ro"
    depends_on:
      - imap
```
