### ISSUE TITLE
Error 500 Internal Server Error after webdav (radicale) login version 1.9.0

### ISSUE THREAD

**Issue by Erriez** [Mailu/Mailu#2126]
## Before you open your issue
- [X] Check if no issue or pull-request for this already exists.
- [X] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [X] docker-compose

### Versions
Mailu Docker images with tag 1.9.0.

## Replication Steps
1. Follow [Webdav (radicale) FAQ](https://mailu.io/1.9/faq.html?highlight=webdav%20radicale#how-do-i-use-webdav-radicale)
2. `For first time set up, the user must access radicale via the url https://mail.example.com/webdav/.web and then log in using the user’s full email address and password.`
3. After the login, the webbrowser shows `Error 500 Internal Server Error` by `nginx`. No debug information or error messages from docker-compose (without `-d` deamon option).

## Configuration

Relevant parts `docker-compose.yml`:
```yaml
version: '3'

services:
# External dependencies
  redis:
    image: redis:alpine
    container_name: mailu_redis
    restart: always
    volumes:
      - "${VOLUME_DIR}/mailu/redis:/data"
    
  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master}
    container_name: mailu_nginx
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      #- "0.0.0.0:80:80"
      #- "0.0.0.0:443:443"
      - "0.0.0.0:25:25"   # Required SMTP port

      - "0.0.0.0:465:465" # SMTP TLS or 578 STARTTLS
      - "0.0.0.0:587:587" # SMTP STARTTLS
      
      #- "0.0.0.0:110:110" # POP3
      #- "0.0.0.0:995:995" # POP3 SSL
      
      - "0.0.0.0:143:143" # IMAP STARTTLS, or 993
      - "0.0.0.0:993:993" # IMAP TLS
    volumes:
      #- "${VOLUME_DIR}/mailu/certs:/certs"
      - "${VOLUME_DIR}/swag/config/etc/letsencrypt:/certs:ro"
      - "${VOLUME_DIR}/mailu/overrides/nginx:/overrides:ro"

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-master}
    container_name: mailu_resolver
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-master}
    container_name: mailu_admin
    restart: always
    env_file: mailu.env
    volumes:
      - "${VOLUME_DIR}/mailu/data:/data"
      - "${VOLUME_DIR}/mailu/dkim:/dkim"
    depends_on:
      - redis

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-master}
    container_name: mailu_imap
    restart: always
    env_file: mailu.env
    volumes:
      - "${VOLUME_DIR}/mailu/mail:/mail"
      - "${VOLUME_DIR}/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-master}
    container_name: mailu_smtp
    restart: always
    env_file: mailu.env
    volumes:
      - "${VOLUME_DIR}/mailu/mailqueue:/queue"
      - "${VOLUME_DIR}/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-master}
    container_name: mailu_antispam
    hostname: antispam
    restart: always
    env_file: mailu.env
    volumes:
      - "${VOLUME_DIR}/mailu/filter:/var/lib/rspamd"
      - "${VOLUME_DIR}/mailu/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - resolver

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-master}
    container_name: mailu_antivirus
    restart: always
    env_file: mailu.env
    volumes:
      - "${VOLUME_DIR}/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
  
  webdav:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-master}
    container_name: mailu_webdav
    restart: always
    env_file: mailu.env
    volumes:
      - "${VOLUME_DIR}/mailu/dav:/data"

  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-master}
    container_name: mailu_fetchmail
    restart: always
    env_file: mailu.env
    volumes:
      - "${VOLUME_DIR}/mailu/data/fetchmail:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-master}
    container_name: mailu_webmail
    restart: always
    env_file: mailu.env
    volumes:
      - "${VOLUME_DIR}/mailu/webmail:/data"
      - "${VOLUME_DIR}/mailu/overrides/roundcube:/overrides:ro"
    depends_on:
      - imap
```

Relevant parts `mailu.env` (using Swag reverse proxy):
```bash
# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.168.203.0/24

# Main mail domain
DOMAIN=mail.mydomain.nl

# Hostnames for this server, separated with comas
HOSTNAMES=mail.mydomain.nl

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=mail
TLS_CERT_FILENAME=live/mydomain.nl/fullchain.pem
TLS_KEYPAIR_FILENAME=live/mydomain.nl/privkey.pem

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=roundcube

# Dav server implementation (value: radicale, none)
WEBDAV=radicale

# Header to take the real ip from
REAL_IP_HEADER=X-Real-IP

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=192.168.203.200
```

Any hint or suggestion?
