### ISSUE TITLE
mailu_admin_1 is unhealthy (please see the logs).

### ISSUE THREAD

**Issue by medram** [Mailu/Mailu#2163]
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
Every container is healthy except for mailu_admin_1, which is unhealthy I don't know why.
Please help :D

## Expected behaviour
mailu_admin_1 should be healthy.

## Logs
````markdown
```
CRITICAL:root:Your DNS resolver at 127.0.0.11 isn't doing DNSSEC validation; Please use another resolver or enable unbound via https://setup.mailu.io.
CRITICAL:root:Your DNS resolver at 127.0.0.11 isn't doing DNSSEC validation; Please use another resolver or enable unbound via https://setup.mailu.io.
CRITICAL:root:Your DNS resolver at 127.0.0.11 isn't doing DNSSEC validation; Please use another resolver or enable unbound via https://setup.mailu.io.
CRITICAL:root:Your DNS resolver at 127.0.0.11 isn't doing DNSSEC validation; Please use another resolver or enable unbound via https://setup.mailu.io.
CRITICAL:root:Your DNS resolver at 127.0.0.11 isn't doing DNSSEC validation; Please use another resolver or enable unbound via https://setup.mailu.io.
CRITICAL:root:Your DNS resolver at 127.0.0.11 isn't doing DNSSEC validation; Please use another resolver or enable unbound via https://setup.mailu.io.
CRITICAL:root:Your DNS resolver at 127.0.0.11 isn't doing DNSSEC validation; Please use another resolver or enable unbound via https://setup.mailu.io.
```
````

**Comment by archerne** [comment]
I had this yesterday. If you recreate the docker-compose (on setup.mailu.io) and compare to yours there is most likely some unbound configuration that you need to update on a couple of the containers. You probably updated to the latest version but didnt change all the settings.

**Comment by medram** [comment]
Thanks for your reply Archerne,
You're right, I did update to the latest version using 'docker-compose pull'.
can I use a new generated configs from setup.mailu.io and use it with my previous mailu data (that is located at '/mailu' folder), without clearing any cache or something like that?

**Comment by Diman0** [comment]
There was an error in the docker-compose.yml created by the setup site. Not all services were configured with the resolver (unbound). This has been resolved.

To resolver your issue you can either.

- Regenerate your docker-compose.yml file on setup.mailu.io
- Manually update the docker-compose.yml file
  - Open the docker-compos.yml file
  - Locate the resolver service and note down the IP address. 

 ```
 resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254
 ```
  - Make sure **all** service (but resolver) have the following config
```
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
```

**Comment by medram** [comment]
Thank you and I appreciate  your help 👍

**Comment by macdabby** [comment]
I just ran into this issue also, but I'm not using unbound. I have my own DNS server running in another container. Do I just need to tell it to use that DNS instead? And how?

**Comment by medram** [comment]
Since you have your DNS server, I guess just change the DNS IP for each docker service you have in docker-compose by your DNS IP, except for 'resolver' service.
Note: ensure your DNS server has a fixed IP.

**Comment by alex1528** [comment]
here still failed

```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:25:25"
      - "0.0.0.0:465:465"
      - "0.0.0.0:587:587"
      - "0.0.0.0:110:110"
      - "0.0.0.0:995:995"
      - "0.0.0.0:143:143"
      - "0.0.0.0:993:993"
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mail:/mail"
      - "/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mailqueue:/queue"
      - "/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.9}
    hostname: antispam
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/var/lib/rspamd"
      - "/mailu/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  webdav:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/dav:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/data/fetchmail:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/webmail:/data"
      - "/mailu/overrides/roundcube:/overrides:ro"
    depends_on:
      - imap
      - resolver
    dns:
      - 192.168.203.254

  # Database
  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=mailu
      - POSTGRES_PASSWORD=**********
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "/mailu/data/external_psql/pgdata:/var/lib/postgresql/data/pgdata"
      - "/mailu/data/psql_backup:/dump"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```
