### ISSUE TITLE
Mailu 1.9 update requires recreation of docker-compose.yml file

### ISSUE THREAD

**Issue by Diman0** [Mailu/Mailu#2164]
There was an error in the docker-compose.yml created by the setup site. Not all services were configured to use the resolver (unbound). This has been addressed, but requires the docker-compose.yml to be updated. An update was also pushed to ensure a proper resolver is used which supports DNSSEC. With the old docker-compose.yml file the admin service will not start with the error that the resolver does not support DNSSEC.

To resolve your issue you can either:
- Regenerate your docker-compose.yml file on setup.mailu.io
  - Stop Mailu: docker-compose down
  - Replace docker-compose.yml with the file downloaded from the website. If you used different values in setup, then you must update mailu.env as well.
  - docker-compose up -d
- Manually update the docker-compose.yml file
1. Stop all services: docker-compose down
2. Open the docker-compose.yml file
3. Locate the resolver service and note down the IP address. For a default setup it is 192.168.203.254.
```
resolver:
   image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
   env_file: mailu.env
   restart: always
   networks:
     default:
       ipv4_address: 192.168.203.254
```
  4.  Make sure all service (but resolver) have the following config
```
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
```
5. Start all services: docker-compose up -d
