### ISSUE TITLE
overrides for unbound to make a local-zone possible

### ISSUE THREAD

**Issue by weltmaister** [Mailu/Mailu#2227]
Hi is it possible to make an override for unbound too? That would help to use unbound for declaring a local-zone. Something like:

```
# /unbound.conf
include: "/etc/unbound/unbound.conf.d/*.con"
```

and

```
# /etc/unbound/unbound.conf.d/local_names.conf
private-address: 192.168.1.0/24
local-zone: "domain.example." transparent
        local-data: "mail.domain.example. IN A 192.168.1.11"
        local-data: "cloud.domain.example. IN A 192.168.1.11"
        local-data-ptr: "192.168.1.11 mail.domain.example"
        local-data-ptr: "192.168.1.11 cloud.domain.example"
```

and
```

# ~/docker-compose.yml
...
  resolver:
    image: mailu/unbound:1.8
    container_name: mailu_resolver
    volumes:
      - ${CONFIG}/mail/overrides/unbound/local_names.conf:/etc/unbound/unbound.conf.d/local_names.conf 
    restart: always
    ports:
      - "53:53"
 ...
```

and finally declare the docker-host as a lokal DNS in router?
