### ISSUE TITLE
nginx/front does not resolve IPv6 -> rspamd problems

### ISSUE THREAD

**Issue by Niduroki** [Mailu/Mailu#2260]
[Cause of problem found](https://github.com/Mailu/Mailu/issues/2260#issuecomment-1062846938)

## Before you open your issue
- [X] Check if no issue or pull-request for this already exists.
- [X] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [X] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
```
[root@server mailu]# docker exec -it mailu-antispam-1 cat /version
1.9.20
```

## Description
I recently enabled IPv6 on my server (following the FAQ steps of defining an IPv6 subnet, and enabling docker's ip6tables NATing).

`/etc/docker/daemon.json`
```
{
          "ipv6": true,
          "experimental": true,
          "fixed-cidr-v6": "fd00:dead:beef::/48",
          "ip6tables": true
}
```

It works, and IPv6 is used properly now. Instead of `192.168.190.1` in rspamd mails are received from - e.g. - `2607:f8b0:4864:20::746` (Google-Mail).

However in rspamd IPv6 PTR lookups seem to fail, meaning there's always going to be an added 2.5 spam points, via `HFILTER_HOSTNAME_UNKNOWN` to every mail that is delivered via IPv6.

```
HFILTER_HOSTNAME_UNKNOWN (2.5)
DMARC_POLICY_ALLOW (-0.5) [google.com,reject]
R_SPF_ALLOW (-0.2) [+ip6:2607:f8b0:4000::/36]
R_DKIM_ALLOW (-0.2) [google.com:s=20210112]
…
```

Curiosly, doing a `nslookup` in the rspamd container works, however:

```
[root@server mailu]# docker exec -it mailu-antispam-1 sh
/ # nslookup 2607:f8b0:4864:20::746 192.168.190.254
Server:         192.168.190.254
Address:        192.168.190.254:53

Non-authoritative answer:
6.4.7.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.0.0.4.6.8.4.0.b.8.f.7.0.6.2.ip6.arpa        name = mail-qk1-x746.google.com

/ # exit
```

## Replication Steps

Send mail to mailu server, from an ipv6 enabled server (e.g. gmail).

## Expected behaviour

PTR lookups work - no `HFILTER_HOSTNAME_UNKNOWN` for IPv6 addresses with a valid PTR entry.

## Logs

<details><summary>logs</summary>
<p>

```
mailu-front-1     | 2022/02/27 14:25:29 [info] 11#11: *2056 client [2a00:1450:4864:20::535]:33682 connected to [::]:25
mailu-front-1     | 2022/02/27 14:25:29 [error] 11#11: *2056 "mail-ed1-x535.google.com" could not be resolved (3: Host not found) while in resolving client hostname, client: 2a00:1450:4864:20::535, server: [::]:25
mailu-front-1     | 2022/02/27 14:25:29 [info] 11#11: *2056 client logged in, client: 2a00:1450:4864:20::535 using starttls, server: [::]:25
mailu-antispam-1  | 2022-02-27 14:25:29 #7(rspamd_proxy) <22435d>; proxy; proxy_accept_socket: accepted milter connection from 192.168.190.7 port 41688
mailu-antispam-1  | 2022-02-27 14:25:29 #7(rspamd_proxy) <c542b3>; proxy; proxy_accept_socket: accepted milter connection from 192.168.190.7 port 41690
mailu-antispam-1  | 2022-02-27 14:25:29 #7(rspamd_proxy) <22435d>; milter; rspamd_milter_process_command: got connection from 192.168.190.3:60470
mailu-antispam-1  | 2022-02-27 14:25:29 #7(rspamd_proxy) <22435d>; proxy; proxy_milter_finish_handler: finished milter connection
mailu-antispam-1  | 2022-02-27 14:25:29 #7(rspamd_proxy) <c542b3>; milter; rspamd_milter_process_command: got connection from [2a00:1450:4864:20::535]:60470
mailu-antispam-1  | 2022-02-27 14:25:29 #7(rspamd_proxy) <c542b3>; proxy; rspamd_message_parse: loaded message; id: <[removed]@googlemail.com>; queue-id: <DD59B11941A>; size: 2796; checksum: <bba5f808b8e6ff085c4f3feea47eede1>
mailu-antispam-1  | 2022-02-27 14:25:30 #7(rspamd_proxy) <c542b3>; lua; once_received.lua:69: source hostname has not been passed to Rspamd from MTA, but we could resolve source IP address PTR 5.3.5.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.0.0.4.6.8.4.0.5.4.1.0.0.a.2.ip6.arpa as "mail-ed1-x535.google.com"
mailu-antispam-1  | 2022-02-27 14:25:30 #7(rspamd_proxy) <c542b3>; proxy; dkim_module_key_handler: stored DKIM key for 20210112._domainkey.googlemail.com in LRU cache for 300 seconds, 1/2000 elements in the cache
mailu-antispam-1  | 2022-02-27 14:25:30 #7(rspamd_proxy) <c542b3>; proxy; rspamd_spf_maybe_return: stored record for googlemail.com (0xc6f0caade56f8346) in LRU cache for 300 seconds, 1/2000 elements in the cache
mailu-smtp-1      | 2022-02-27T14:25:29.850736+01:00 740b67e9fb8f postfix/smtpd[353]: connect from mailu-front-1.mailu_default[192.168.190.3]
mailu-smtp-1      | 2022-02-27T14:25:29.907025+01:00 740b67e9fb8f postfix/smtpd[353]: DD59B11941A: client=unknown[2a00:1450:4864:20::535]
mailu-smtp-1      | 2022-02-27T14:25:29.969103+01:00 740b67e9fb8f postfix/cleanup[763]: DD59B11941A: message-id=<[removed]@googlemail.com>
mailu-antispam-1  | 2022-02-27 14:25:30 #7(rspamd_proxy) <c542b3>; proxy; rspamd_symcache_finalize_item: slow rule: SEM_URIBL_FRESH15_UNKNOWN(261): 345.17 ms; enable slow timer delay
mailu-antispam-1  | 2022-02-27 14:25:30 #7(rspamd_proxy) <c542b3>; proxy; rspamd_symcache_finalize_item: slow rule: SEM_URIBL_UNKNOWN(273): 366.17 ms
mailu-antispam-1  | 2022-02-27 14:25:30 #7(rspamd_proxy) <c542b3>; proxy; rspamd_symcache_finalize_item: slow rule: URIBL_MULTI(257): 379.17 ms
mailu-front-1     | 2022/02/27 14:25:31 [info] 11#11: *2056 proxied session done, client: 2a00:1450:4864:20::535 using starttls, server: [::]:25
mailu-imap-1      | Feb 27 14:25:31 lmtp(489): Error: SSL context initialization failed, disabling SSL: Can't load SSL certificate (ssl_cert setting): The certificate is empty
mailu-imap-1      | Feb 27 14:25:31 lmtp(489): Info: Connect from 192.168.190.7
mailu-smtp-1      | 2022-02-27T14:25:31.250119+01:00 740b67e9fb8f postfix/qmgr[343]: DD59B11941A: from=<SRS0=yV4K=TK=googlemail.com=[removed]@[removed]>, size=3060, nrcpt=1 (queue active)
mailu-smtp-1      | 2022-02-27T14:25:31.322978+01:00 740b67e9fb8f postfix/smtpd[353]: disconnect from unknown[2a00:1450:4864:20::535] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=1 quit=1 commands=6/7
mailu-antispam-1  | 2022-02-27 14:25:31 #7(rspamd_proxy) <c542b3>; proxy; rspamd_symcache_finalize_item: slow rule: RBL_NIXSPAM(263): 908.73 ms; enable slow timer delay
mailu-antispam-1  | 2022-02-27 14:25:31 #7(rspamd_proxy) <c542b3>; proxy; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_HAM of classifier bayes: not enough learns 17; 200 required
mailu-antispam-1  | 2022-02-27 14:25:31 #7(rspamd_proxy) <c542b3>; proxy; rspamd_stat_classifiers_process: skip statistics as HAM class is missing
mailu-antispam-1  | 2022-02-27 14:25:31 #7(rspamd_proxy) <c542b3>; lua; greylist.lua:318: Score too low - skip greylisting
mailu-antispam-1  | 2022-02-27 14:25:31 #7(rspamd_proxy) <c542b3>; proxy; rspamd_task_write_log: id: <[removed]@googlemail.com>, qid: <DD59B11941A>, ip: 2a00:1450:4864:20::535, from: <[removed]@googlemail.com>, (default: F (no action): [1.91/20.00] [HFILTER_HOSTNAME_UNKNOWN(2.50){},DMARC_POLICY_ALLOW(-0.50){googlemail.com;quarantine;},R_MIXED_CHARSET(0.41){subject;},R_DKIM_ALLOW(-0.20){googlemail.com:s=20210112;},R_SPF_ALLOW(-0.20){+ip6:2a00:1450:4000::/36;},MIME_GOOD(-0.10){text/plain;},ARC_NA(0.00){},ARC_SIGNED(0.00){niduroki.net:s=dkim:i=1;},ASN(0.00){asn:15169, ipnet:2a00:1450::/32, country:US;},DKIM_TRACE(0.00){googlemail.com:+;},DWL_DNSWL_NONE(0.00){googlemail.com:dkim;},FREEMAIL_ENVFROM(0.00){googlemail.com;},FREEMAIL_FROM(0.00){googlemail.com;},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},MID_RHS_MATCH_FROM(0.00){},MIME_TRACE(0.00){0:+;},PREVIOUSLY_DELIVERED(0.00){[removed]@niduroki.net;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_THREE(0.00){3;},RCVD_IN_DNSWL_NONE(0.00){2a00:1450:4864:20::535:from;},RCVD_NO_TLS_LAST(0.00){},RCVD_VIA_SMTP_AUTH(0.00){},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 2796, time: 1237.310ms, dns req: 31, digest: <bba5f808b8e6ff085c4f3feea47eede1>, rcpts: <[removed]@niduroki.net>, mime_rcpts: <[removed]@niduroki.net>
mailu-antispam-1  | 2022-02-27 14:25:31 #7(rspamd_proxy) <c542b3>; proxy; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 6 regexps matched, 176 regexps total, 73 regexps cached, 0B scanned using pcre, 1.35KiB scanned total
mailu-antispam-1  | 2022-02-27 14:25:31 #7(rspamd_proxy) <983f04>; proxy; proxy_milter_finish_handler: finished milter connection
mailu-smtp-1      | 2022-02-27T14:25:31.459238+01:00 740b67e9fb8f postfix/lmtp[765]: DD59B11941A: to=<[removed]@[removed]>, orig_to=<[removed]@niduroki.net>, relay=192.168.190.9[192.168.190.9]:2525, delay=1.6, delays=1.4/0.05/0.02/0.14, dsn=2.0.0, status=sent (250 2.0.0 <[removed]@[removed]> tWfLEst7G2LpAQAAxvTh+g Saved)
mailu-smtp-1      | 2022-02-27T14:25:31.460352+01:00 740b67e9fb8f postfix/qmgr[343]: DD59B11941A: removed
mailu-imap-1      | Feb 27 14:25:31 lmtp([removed]@[removed])<489><tWfLEst7G2LpAQAAxvTh+g>: Info: sieve: msgid=<[removed]@googlemail.com>: stored mail into mailbox 'INBOX'
mailu-imap-1      | Feb 27 14:25:31 lmtp(489): Info: Disconnect from 192.168.190.7: Logged out (state=READY)
```

</p></details>

<s>Notable observation (regarding line 2 `mail-ed1-x535.google.com could not be resolved, host not found`):  
`mail-ed1-x535.google.com` has no `A` record, just an `AAAA` record. Is this maybe related?</s>  
**Edit**: Unrelated, I have found other IPv6 addresses also with an A record, where this problem occurs, too.

## Configuration

<details><summary>docker-compose.yml</summary>
<p>

```
version: '3.9'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/home/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.190.254

  database: …
    
  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
    volumes:
      - "/home/mailu/certs:/certs"
      - "/home/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.190.254
    networks:
      - default
      - nginx-proxy-net

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.190.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/data:/data"
      - "/home/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.190.254

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/mail:/mail"
      - "/home/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.190.254

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/mailqueue:/queue"
      - "/home/mailu/overrides:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.190.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.9}
    hostname: antispam
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/filter:/var/lib/rspamd"
      - "/home/mailu/dkim:/dkim:ro"
      - "/home/mailu/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.190.254

  # Optional services

  webdav: …

networks:
  default:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.190.0/24
        - subnet: fd9a:5a5b:35c1:beef::/64
  nginx-proxy-net:
    external: true
    name: nginx-proxy-net
```

</p></details>

<details><summary>mailu.env</summary>
<p>

```
###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=[removed]

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.168.190.0/24
SUBNET6=fd9a:5a5b:35c1:beef::/64

# Main mail domain
DOMAIN=[removed]

# Hostnames for this server, separated with comas
HOSTNAMES=[removed]

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=mail-letsencrypt

# Authentication rate limit (per source IP address)
AUTH_RATELIMIT_IP=60/hour 

# Authentication rate limit per user (regardless of the source-IP)
AUTH_RATELIMIT_USER=100/day

# Disable authentication ratelimit for this comma-separated network CIDRs (e.g. 0.0.0.0/0, ::/0 to disable it completely)
AUTH_RATELIIMIT_EXCEPTION=

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=False

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=none

# Dav server implementation (value: radicale, none)
WEBDAV=radicale

# Antivirus solution (value: clamav, none)
ANTIVIRUS=none

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Message rate limit (per user)
MESSAGE_RATELIMIT=200/day

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=dmarc-report
DMARC_RUF=dmarc-report

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=true
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: bz2, gz)
COMPRESSION=gz
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=1

# IMAP full-text search is enabled by default. Set the following variable to off in order to disable the feature.
FULL_TEXT_SEARCH=off

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/admin

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=

# Website name
SITENAME=[removed]

# Linked Website URL
WEBSITE=[removed]

###################################
# Advanced settings
###################################

# Log driver for front service. Possible values:
# json-file (default)
# journald (On systemd platforms, useful for Fail2Ban integration)
# syslog (Non systemd platforms, Fail2Ban integration. Disables `docker-compose log` for front!)
# LOG_DRIVER=json-file

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Number of rounds used by the password hashing scheme
CREDENTIAL_ROUNDS=12

# Header to take the real ip from
REAL_IP_HEADER=X-Real-IP

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=172.18.0.0/16

# Whether to not send ISG Root X1 in TLS handshakes. Incompatible with Android older than 7.1.1
LETSENCRYPT_SHORTCHAIN=True

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

# Timezone for the Mailu containers. See this link for all possible values https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TZ=Europe/Berlin

###################################
# Database settings
###################################
DB_FLAVOR=postgresql
DB_USER=[removed]
DB_PW=[removed]
DB_HOST=[removed]
DB_NAME=[removed]

POSTGRES_PASSWORD=[removed]
```

</p></details>

------

~~Can anybody even reproduce this, or is this some weird problem with my setup …~~ *Edit:* It is not, see comment.
I just can't figure out how to debug this, any pointers in the right direction, if no one can reproduce this, would be greatly appreciated.

Thanks for your time!

**Comment by Niduroki** [comment]
**Update:** This is definitely a bug in mailu (or some part of it), rather than a peculiarity with my setup. I have just setup a new, completely fresh mailu install on a completely fresh server (only configuration change being an update `/etc/docker/daemon.json` equal to the one from the first post) for testing, and the same bug occurs.

<details>
<summary>logs when receiving a mail from googlemail</summary>
```
front_1     | 2022/03/09 10:10:53 [info] 17#17: *454 client [2a00:1450:4864:20::632]:43829 connected to [::]:25
front_1     | 2022/03/09 10:10:53 [error] 17#17: *454 "mail-ej1-x632.google.com" could not be resolved (3: Host not found) while in resolving client hostname, client: 2a00:1450:4864:20::632, server: [::]:25
front_1     | 2022/03/09 10:10:54 [info] 17#17: *454 client logged in, client: 2a00:1450:4864:20::632 using starttls, server: [::]:25
smtp_1      | 2022-03-09T10:10:54.093861+00:00 99d2c7f90e76 postfix/smtpd[403]: connect from mailu_front_1.mailu_default[192.168.203.3]
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <0496cf>; proxy; proxy_accept_socket: accepted milter connection from 192.168.203.7 port 44438
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <0496cf>; milter; rspamd_milter_process_command: got connection from 192.168.203.3:57150
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <0496cf>; proxy; proxy_milter_finish_handler: finished milter connection
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <5e3a94>; proxy; proxy_accept_socket: accepted milter connection from 192.168.203.7 port 44440
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <5e3a94>; milter; rspamd_milter_process_command: got connection from [2a00:1450:4864:20::632]:57150
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <5e3a94>; proxy; rspamd_message_parse: loaded message; id: <[removed]@googlemail.com>; queue-id: <2262C41EE4>; size: 2823; checksum: <c737d5ba0f0d5e0c23ff442575d0243e>
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <5e3a94>; lua; spf.lua:160: use cached record for googlemail.com (0xc6f0caade56f8346) in LRU cache for 149 seconds
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <5e3a94>; lua; once_received.lua:69: source hostname has not been passed to Rspamd from MTA, but we could resolve source IP address PTR 2.3.6.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.0.0.4.6.8.4.0.5.4.1.0.0.a.2.ip6.arpa as "mail-ej1-x632.google.com"
smtp_1      | 2022-03-09T10:10:54.141228+00:00 99d2c7f90e76 postfix/smtpd[403]: 2262C41EE4: client=unknown[2a00:1450:4864:20::632]
smtp_1      | 2022-03-09T10:10:54.209392+00:00 99d2c7f90e76 postfix/cleanup[502]: 2262C41EE4: message-id=<[removed]@googlemail.com>
front_1     | 2022/03/09 10:10:54 [info] 17#17: *454 proxied session done, client: 2a00:1450:4864:20::632 using starttls, server: [::]:25
imap_1      | Mar 09 10:10:54 lmtp(137): Error: SSL context initialization failed, disabling SSL: Can't load SSL certificate (ssl_cert setting): The certificate is empty
smtp_1      | 2022-03-09T10:10:54.605222+00:00 99d2c7f90e76 postfix/qmgr[393]: 2262C41EE4: from=<SRS0=cemB=TU=googlemail.com=[removed]@mailtest.niduroki.net>, size=3104, nrcpt=1 (queue active)
smtp_1      | 2022-03-09T10:10:54.620834+00:00 99d2c7f90e76 postfix/smtpd[403]: disconnect from unknown[2a00:1450:4864:20::632] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=1 quit=1 commands=6/7
smtp_1      | 2022-03-09T10:10:54.792634+00:00 99d2c7f90e76 postfix/lmtp[504]: 2262C41EE4: to=<admin@mailtest.niduroki.net>, relay=192.168.203.6[192.168.203.6]:2525, delay=0.69, delays=0.51/0.04/0.02/0.13, dsn=2.0.0, status=sent (250 2.0.0 <admin@mailtest.niduroki.net> ZquaJy59KGKJAAAA3ikgBA Saved)
smtp_1      | 2022-03-09T10:10:54.794025+00:00 99d2c7f90e76 postfix/qmgr[393]: 2262C41EE4: removed
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <5e3a94>; proxy; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_SPAM of classifier bayes: not enough learns 0; 200 required
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <5e3a94>; proxy; rspamd_redis_connected: skip obtaining bayes tokens for BAYES_HAM of classifier bayes: not enough learns 0; 200 required
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <5e3a94>; proxy; rspamd_stat_classifiers_process: skip statistics as SPAM class is missing
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <5e3a94>; lua; greylist.lua:318: Score too low - skip greylisting
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <5e3a94>; lua; neural.lua:315: skip ham sample to keep spam/ham balance; probability 1; 0 spam and 1 ham vectors stored
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <5e3a94>; proxy; rspamd_task_write_log: id: <[removed]@googlemail.com>, qid: <2262C41EE4>, ip: 2a00:1450:4864:20::632, from: <[removed]@googlemail.com>, (default: F (no action): [2.50/15.00] [HFILTER_HOSTNAME_UNKNOWN(2.50){},R_MIXED_CHARSET(1.00){subject;},DMARC_POLICY_ALLOW(-0.50){googlemail.com;quarantine;},R_DKIM_ALLOW(-0.20){googlemail.com:s=20210112;},R_SPF_ALLOW(-0.20){+ip6:2a00:1450:4000::/36:c;},MIME_GOOD(-0.10){text/plain;},ARC_NA(0.00){},ASN(0.00){asn:15169, ipnet:2a00:1450::/32, country:US;},DKIM_TRACE(0.00){googlemail.com:+;},DWL_DNSWL_NONE(0.00){googlemail.com:dkim;},FREEMAIL_ENVFROM(0.00){googlemail.com;},FREEMAIL_FROM(0.00){googlemail.com;},FROM_EQ_ENVFROM(0.00){},FROM_HAS_DN(0.00){},MID_RHS_MATCH_FROM(0.00){},MIME_TRACE(0.00){0:+;},PREVIOUSLY_DELIVERED(0.00){admin@mailtest.niduroki.net;},RCPT_COUNT_ONE(0.00){1;},RCVD_COUNT_THREE(0.00){3;},RCVD_IN_DNSWL_NONE(0.00){2a00:1450:4864:20::632:from;},RCVD_NO_TLS_LAST(0.00){},RCVD_VIA_SMTP_AUTH(0.00){},TO_DN_NONE(0.00){},TO_MATCH_ENVRCPT_ALL(0.00){}]), len: 2823, time: 363.872ms, dns req: 25, digest: <c737d5ba0f0d5e0c23ff442575d0243e>, rcpts: <admin@mailtest.niduroki.net>, mime_rcpts: <admin@mailtest.niduroki.net>
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <5e3a94>; proxy; rspamd_protocol_http_reply: regexp statistics: 0 pcre regexps scanned, 6 regexps matched, 176 regexps total, 73 regexps cached, 0B scanned using pcre, 1.40KiB scanned total
antispam_1  | 2022-03-09 10:10:54 #15(rspamd_proxy) <f6d7c7>; proxy; proxy_milter_finish_handler: finished milter connection
imap_1      | Mar 09 10:10:54 lmtp(137): Info: Connect from 192.168.203.7
imap_1      | Mar 09 10:10:54 lmtp(admin@mailtest.niduroki.net)<137><ZquaJy59KGKJAAAA3ikgBA>: Info: sieve: msgid=<[removed]@googlemail.com>: stored mail into mailbox 'INBOX'
imap_1      | Mar 09 10:10:54 lmtp(137): Info: Disconnect from 192.168.203.7: Logged out (state=READY)
```
</details>

IPv4 works fine, and does not trigger HFILTER_HOSTNAME_UNKNOWN.

-----

docker-compose.yml and mailu.env were downloaded and used as is from [setup.mailu.io/1.9/setup/a9b60d8d-a4f4-43af-a3cc-3a359a1c46bf](https://setup.mailu.io/1.9/setup/a9b60d8d-a4f4-43af-a3cc-3a359a1c46bf) without any changes. (Server has been since deleted, no worries, about `secret_key`, e.g.)

I don't know how long these links last, so here's a copy, for longevity:

<details>
<summary>docker-compose.yml</summary>

```yml
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/home/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "159.69.214.172:80:80"
      - "2a01:4f8:1c1c:c13b::1:80:80"
      - "159.69.214.172:443:443"
      - "2a01:4f8:1c1c:c13b::1:443:443"
      - "159.69.214.172:25:25"
      - "2a01:4f8:1c1c:c13b::1:25:25"
      - "159.69.214.172:465:465"
      - "2a01:4f8:1c1c:c13b::1:465:465"
      - "159.69.214.172:587:587"
      - "2a01:4f8:1c1c:c13b::1:587:587"
      - "159.69.214.172:110:110"
      - "2a01:4f8:1c1c:c13b::1:110:110"
      - "159.69.214.172:995:995"
      - "2a01:4f8:1c1c:c13b::1:995:995"
      - "159.69.214.172:143:143"
      - "2a01:4f8:1c1c:c13b::1:143:143"
      - "159.69.214.172:993:993"
      - "2a01:4f8:1c1c:c13b::1:993:993"
    volumes:
      - "/home/mailu/certs:/certs"
      - "/home/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/data:/data"
      - "/home/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/mail:/mail"
      - "/home/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/mailqueue:/queue"
      - "/home/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.9}
    hostname: antispam
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/mailu/filter:/var/lib/rspamd"
      - "/home/mailu/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  # Optional services



  # Webmail

networks:
  default:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
        - subnet: fd5e:3ca5:1800:beef::/64
```
</details>

<details>
<summary>mailu.env</summary>

```bash
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=T1ZNKHZZMLPTFOW3

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.168.203.0/24
SUBNET6=fd5e:3ca5:1800:beef::/64

# Main mail domain
DOMAIN=mailtest.niduroki.net

# Hostnames for this server, separated with comas
HOSTNAMES=mailtest.niduroki.net

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=letsencrypt

# Authentication rate limit per IP (per /24 on ipv4 and /56 on ipv6)
AUTH_RATELIMIT_IP=60/hour

# Authentication rate limit per user (regardless of the source-IP)
AUTH_RATELIMIT_USER=100/day

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=False

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=none

# Dav server implementation (value: radicale, none)
WEBDAV=none

# Antivirus solution (value: clamav, none)
ANTIVIRUS=none

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Message rate limit (per user)
MESSAGE_RATELIMIT=200/day

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: gz, bz2, lz4, zstd)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

# IMAP full-text search is enabled by default. Set the following variable to off in order to disable the feature.
# FULL_TEXT_SEARCH=off

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=

# Website name
SITENAME=mailtest.niduroki.net

# Linked Website URL
WEBSITE=https://mailtest.niduroki.net



###################################
# Advanced settings
###################################

# Log driver for front service. Possible values:
# json-file (default)
# journald (On systemd platforms, useful for Fail2Ban integration)
# syslog (Non systemd platforms, Fail2Ban integration. Disables `docker-compose log` for front!)
# LOG_DRIVER=json-file

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Number of rounds used by the password hashing scheme
CREDENTIAL_ROUNDS=12

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

# Timezone for the Mailu containers. See this link for all possible values https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TZ=Etc/UTC

###################################
# Database settings
###################################
DB_FLAVOR=sqlite
```
</details>

-----

I will try to set up a rspamd instance, to see if this is a configuration issue, or an actual bug with rspamd, if I get around to it.
