### ISSUE TITLE
warning in domain details' DNS check

### ISSUE THREAD

**Issue by elandorr** [Mailu/Mailu#2267]
v1.9
It shows an exclamation mark for the MX record for some domains. They're all exactly identical, valid. The only difference there seems to be DNSSEC - the ones where it shows a warning have valid DNSSEC, the other ones that show up green do not.

Why is there only 1 checkmark anyway, and not for the rest of the records?

**Comment by Diman0** [comment]
The relevant code for the checkmark is
https://github.com/Mailu/Mailu/blob/fe7397bedf2dd3d611f9f2837a1253133aa0b4f2/core/admin/mailu/models.py#L321
```
    def check_mx(self):
        """ checks if MX record for domain points to mailu host """
        try:
            hostnames = set(app.config['HOSTNAMES'].split(','))
            return any(
                rset.exchange.to_text().rstrip('.') in hostnames
                for rset in dns.resolver.resolve(self.name, 'MX')
            )
        except dns.exception.DNSException:
            return False
```

It checks if the mx record point of the domain points to the mailu host. When this check fails you have no green check mark, but an exclamation mark.

**Comment by elandorr** [comment]
@Diman0 Thank you for pointing to the code. This is weird then, because the setup is exactly identical on all domains on that. I don't have time to debug right now, but if you have a specific log or idea I'd get it to you.

**Comment by ghostwheel42** [comment]
Would you share the content of your HOSTNAMES variable and one of the failing domains with us?

If not: do you have multiple hostnames in your HOSTNAMES variable? Are there spaces inside?

**Comment by elandorr** [comment]
@ghostwheel42 I've just replaced the names, but the syntax is identical:

`HOSTNAMES=mail.foobar.com` no spaces, single mail host
failing domain: `mail.foobar.com`, `foobar.com`, `unrelated-3rd-domain.com`
MX copied straight from mailu to all domains: `mail.foobar.com. 600 IN MX 10 mail.foobar.com.`

**Comment by ghostwheel42** [comment]
It's working fine in my tests. 
Probably it's a problem with the resolver. 
Could you try running this in a Python interpreter:

import dns.resolver
dns.resolver.resolve('example.com', 'MX')

With your domain names and post the exception and/or output?

You should do it inside the admin container using python3, but doing it outside is also an option.

**Comment by elandorr** [comment]
It times out. The DNS it uses is docker's internal. I tried using dig in other containers which also use docker's internal, and it works there. Why is mailu different?

**Comment by Diman0** [comment]
Are you using the unbound resolver that comes with Mailu?
The docker-compose.yml should show that almost all services use the resolver service for DNS resolving. e.g.
```
  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254
...
  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-master}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

```
