### ISSUE TITLE
[helm] SASL login name rejected: Server configuration error

### ISSUE THREAD

**Issue by krakazyabra** [Mailu/Mailu#2359]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] kubernetes

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).
```
1.9.10
```

## Description
Deployed mailu with helm

<details><summary>Values.yaml</summary>
<p>

```yaml
# Default values for mailu.

# A list of mail hostnames is required. The first will be used as primary mail hostname
hostnames:
 - mail.domain.io

# The mail domain is required. See https://github.com/Mailu/Mailu/blob/master/docs/faq.rst#what-is-the-difference-between-domain-and-hostnames
domain: mail.domain.io

# The secret key is required for protecting authentication cookies and must be set individually for each deployment
secretKey: <VerySecretKey>

# An initial account can automatically be created:
initialAccount:
 username: <adminUser>
 domain: domain.io
 password: <VeryStrongPassword>


nameOverride: ""
fullnameOverride: ""
clusterDomain: cluster.local

nodeSelector: {}

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: {}

# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

database:
  # type of the database for mailu (sqlite or mysql)
  # default database is an embedded sqlite
  # for mysql, see settings below
  type: postgresql

  # type of the database for roundcube (sqlite or mysql)
  # default database is an embedded sqlite
  # for mysql, see settings below
  roundcubeType: postgresql

# For mysql/mariadb use the following config:
# Set the host to use an external database.
# If not host is set, a database instance is created by this chart.
#   type: mysql
  mysql: {}
    # host: external-db-hostname
    # root password for mysql database
    # rootPassword: chang3m3! # can only be set for embedded mysql

    # settings for mailu (required if mailu database type is "mysql")
    # database: mailu
    # user: mailu
    # password: chang3m3!

  # For an external PostgreSQL database, use the following config:
  postgresql:
    host: stolon-proxy.postgresql.svc.cluster.local
    database: <DataBaseName>
    user: <DataBaseUser>
    password: <VeryStrongPassword>

    # settings for roundcube (required if roundcube database type is "mysql" or "postgresql")
    roundcubeDatabase: <DataBaseName>
    roundcubeUser: <DataBaseUser>
    roundcubePassword: <VeryStrongPassword>

external_relay: {}
#    host: "[domain.tld]:port"
#    username: username
#    password: SECRET
#    # username and password can also be stored as secret:
#    secretName: external-relay-secret
#    usernameKey: username
#    passwordKey: password

persistence:
  # Setings for a single volume for all apps
  # set single_pvc: false to use a per app volume and set the properties in <app>.persistence (ex. admin.persistence)
  single_pvc: false
  size: 12Gi
  accessMode: ReadWriteOnce
  #annotations:
  #  "helm.sh/resource-policy": keep
  #hostPath: /path/on/the/host
  #existingClaim: name-of-existing.claim
  storageClass: "linstor-thindata-r3"
  #claimNameOverride: my-claim-name

# Change this if you're using different address ranges for pods
subnet: 10.111.0.0/16

# Version of mailu docker images to use when not specified otherwise
mailuVersion: 1.9.10

# default log level. can be overridden globally or per service
logLevel: WARNING

# Sets the timezone Mailu will use.
# See TZ [database name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) for a list of valid timezones
# Defaults to Etc/UTC
timezone: CZ

# local part of the postmaster email address (Mailu will use @$DOMAIN as domain part)
postmaster: postmaster

mail:
  messageSizeLimitInMegabytes: 10
  authRatelimit: 10/minute;1000/hour

# certmanager settings
certmanager:
  enabled: true
  issuerType: ClusterIssuer
  issuerName: cloudflare
  apiVersion: cert-manager.io/v1

# Set ingress and loadbalancer config
ingress:
  externalIngress: true
  tlsFlavor: cert
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  realIpHeader: X-Forwarded-For
  realIpFrom: 0.0.0.0/0

# Frontend load balancer for non-HTTP(s) services
front:
  # logLevel: WARNING
  image:
    repository: mailu/nginx
    # tag defaults to mailuVersion
    # tag: master
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  startupProbe:
    periodSeconds: 10
    failureThreshold: 30
    timeoutSeconds: 5
  livenessProbe:
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 10
    failureThreshold: 1
    timeoutSeconds: 5
  # Deployment or DaemonSet
  controller:
    kind: Deployment
  nodeSelector: {}

  # Expose front mail ports via hostPort
  hostPort:
    enabled: true

  # Expose front mail ports via external service (ClusterIP or LoadBalancer)
  externalService:
    enabled: false
    type: ClusterIP
    # LoadBalancer
    # type: LoadBalancer
    # loadBalancerIP:
    externalTrafficPolicy: Local
    annotations: {}
    pop3:
      pop3: false
      pop3s: true
    imap:
      imap: false
      imaps: true
    smtp:
      smtp: true
      smtps: true
      submission: true

admin:
  # logLevel: WARNING
  image:
    repository: mailu/admin
    # tag defaults to mailuVersion
    # tag: master
  persistence:
    size: 4Gi
    storageClass: "linstor-thindata-r2"
    accessMode: ReadWriteOnce
    claimNameOverride: ""
    #annotations:
    #  "helm.sh/resource-policy": keep

  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 500m
  podAnnotations: {}
  startupProbe:
    periodSeconds: 10
    failureThreshold: 30
    timeoutSeconds: 5
  livenessProbe:
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 10
    failureThreshold: 1
    timeoutSeconds: 5


redis:
  image:
    repository: redis
    tag: 5-alpine
  persistence:
    size: 4Gi
    storageClass: "linstor-thindata-r2"
    accessMode: ReadWriteOnce
    claimNameOverride: ""
    #annotations:
    #  "helm.sh/resource-policy": keep
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 300Mi
      cpu: 200m
  startupProbe:
    periodSeconds: 10
    failureThreshold: 30
    timeoutSeconds: 5
  livenessProbe:
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 10
    failureThreshold: 1
    timeoutSeconds: 5

postfix:
  # logLevel: WARNING
  image:
    repository: mailu/postfix
    # tag defaults to mailuVersion
    # tag: master
  containerSecurityContext: {}
  #    CRI-O users will need to add the following:
  #    capabilities:
  #      add:
  #        - SYS_CHROOT
  persistence:
    size: 12Gi
    storageClass: "linstor-thindata-r3"
    accessMode: ReadWriteOnce
    claimNameOverride: ""
    #annotations:
    #  "helm.sh/resource-policy": keep
  resources:
    requests:
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 500m
  startupProbe:
    periodSeconds: 10
    failureThreshold: 30
    timeoutSeconds: 5
  livenessProbe:
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 10
    failureThreshold: 1
    timeoutSeconds: 5

dovecot:
  enabled: true
  # logLevel: WARNING
  image:
    repository: mailu/dovecot
    # tag defaults to mailuVersion
    # tag: master
  containerSecurityContext: {}
#    CRI-O users will need to add the following:
#    capabilities:
#      add:
#        - SYS_CHROOT
  persistence:
    size: 12Gi
    storageClass: "linstor-thindata-r3"
    accessMode: ReadWriteOnce
    claimNameOverride: ""
    #annotations:
    #  "helm.sh/resource-policy": keep
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 500m
  startupProbe:
    periodSeconds: 10
    failureThreshold: 30
    timeoutSeconds: 5
  livenessProbe:
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 10
    failureThreshold: 1
    timeoutSeconds: 5
  # enable dovecot overrides
  # overrides:
  #   dovecot.conf: |
  #     # More info here: https://mailu.io/1.8/kubernetes/mailu/index.html#dovecot
  #     mail_nfs_index = yes
  #     mail_nfs_storage = yes
  #     mail_fsync = always
  #     mmap_disable = yes
  #     mail_max_userip_connections=100

# historically rspamd and clamav shared their volumes in this chart
# this isn't needed anymore. to maintain backward compatibility and give users
# some time to migrate we keep this here.
#
# if you want a "shared" volume keep in mind you have to use affinity rules on
# rspamd and clamav pods so that both pods are scheduled on the same node
# to keep RWO volumes working
#
# otherwise set rspamd_clamav_persistence.single_pvc to true and review
# rspamd.persistence and clamav.persistence
rspamd_clamav_persistence:
  size: 4Gi
  storageClass: "linstor-thindata-r2"
  accessMode: ReadWriteOnce
  claimNameOverride: ""
  single_pvc: false
  #annotations:
  #  "helm.sh/resource-policy": keep

rspamd:
  # logLevel: WARNING
  image:
    repository: mailu/rspamd
    # tag defaults to mailuVersion
    # tag: master
  persistence:
    size: 1Gi
    storageClass: "linstor-thindata-r2"
    accessMode: ReadWriteOnce
    claimNameOverride: ""
    #annotations:
    #  "helm.sh/resource-policy": keep
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 600m
  startupProbe: # give it 15 minutes for initial rule compilation
    periodSeconds: 10
    failureThreshold: 90
    timeoutSeconds: 5
  livenessProbe:
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 10
    failureThreshold: 1
    timeoutSeconds: 5

clamav:
  enabled: true
  # logLevel: WARNING
  image:
    repository: mailu/clamav
    # tag defaults to mailuVersion
    # tag: master
  persistence:
    size: 2Gi
    storageClass: "linstor-thindata-r2"
    accessMode: ReadWriteOnce
    claimNameOverride: ""
    #annotations:
    #  "helm.sh/resource-policy": keep
  resources:
    requests:
      memory: 1Gi
      cpu: 1000m
    limits:
      memory: 2Gi
      cpu: 1000m
  startupProbe: # give it 10 minutes for initial freshclam update
    periodSeconds: 10
    failureThreshold: 60
    timeoutSeconds: 5
  livenessProbe:
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 10
    failureThreshold: 1
    timeoutSeconds: 5
  # clamav must share a volume with rspamd. This is usually enforced by the volume itself (RWO). If you use RWM volumes and want to
  # have clamav running on the same node, add the following affinity rule:
#  affinity:
#    podAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        - labelSelector:
#            matchExpressions:
#              - key: component
#                operator: In
#                values:
#                  - rspamd
#          topologyKey: kubernetes.io/hostname

roundcube:
  enabled: true
  # logLevel: WARNING
  image:
    repository: mailu/roundcube
    # tag defaults to mailuVersion
    # tag: master
  persistence:
    size: 12Gi
    storageClass: "linstor-thindata-r3"
    accessMode: ReadWriteOnce
    claimNameOverride: ""
    #annotations:
    #  "helm.sh/resource-policy": keep
  uri: /roundcube
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  startupProbe:
    periodSeconds: 10
    failureThreshold: 30
    timeoutSeconds: 5
  livenessProbe:
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 10
    failureThreshold: 1
    timeoutSeconds: 5


webdav:
  enabled: false
  # logLevel: WARNING
  image:
    repository: mailu/radicale
    # tag defaults to mailuVersion
    # tag: master
  persistence:
    size: 4Gi
    storageClass: "linstor-thindata-r2"
    accessMode: ReadWriteOnce
    claimNameOverride: ""
    #annotations:
    #  "helm.sh/resource-policy": keep
  startupProbe:
    periodSeconds: 10
    failureThreshold: 30
    timeoutSeconds: 5
  livenessProbe:
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 10
    failureThreshold: 1
    timeoutSeconds: 5

mysql:
  image:
    repository: library/mariadb
    tag: 10.4.10
  persistence:
    size: 12Gi
    storageClass: "linstor-thindata-r3"
    accessMode: ReadWriteOnce
    claimNameOverride: ""
    #annotations:
    #  "helm.sh/resource-policy": keep
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m
  startupProbe:
    periodSeconds: 10
    failureThreshold: 30
    timeoutSeconds: 5
  livenessProbe:
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 5
  readinessProbe:
    periodSeconds: 10
    failureThreshold: 1
    timeoutSeconds: 5

fetchmail:
  enabled: false
  # logLevel: WARNING
  image:
    repository: mailu/fetchmail
    # tag defaults to mailuVersion
    # tag: master
  persistence:
    size: 4Gi
    storageClass: "linstor-thindata-r2"
    accessMode: ReadWriteOnce
    claimNameOverride: ""
    #annotations:
    #  "helm.sh/resource-policy": keep
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  delay: 600


```

</p>
</details>

DNS were configured, keys were generated and set up. 
When try to send mail from adminUser@domain.io to anotheruser@gmail.com see error in Roundcube interface:

```
SASL login name rejected: Server configuration error
```

## Replication Steps
Deploy in helm using provided values

## Expected behaviour
Email goes from mailu to gmail

## Logs

Postfix
```
2022-05-26T08:30:58.444441+00:00 mailu-postfix-5cf9cc5977-w446k postfix/smtpd[234200]: connect from 10-111-2-156.mailu-front.mailu.svc.cluster.local[10.111.2.156]
2022-05-26T08:30:58.457381+00:00 mailu-postfix-5cf9cc5977-w446k postfix/smtpd[234200]: discarding EHLO keywords: PIPELINING
2022-05-26T08:30:58.465236+00:00 mailu-postfix-5cf9cc5977-w446k postfix/smtpd[234200]: discarding EHLO keywords: PIPELINING
2022-05-26T08:30:58.481948+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: connect to /tmp/podop.socket: No such file or directory
2022-05-26T08:30:58.482186+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: table socketmap:unix:/tmp/podop.socket:transport lookup error: No such file or directory
2022-05-26T08:30:58.482367+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: socketmap:unix:/tmp/podop.socket:transport lookup error for "*"
2022-05-26T08:30:58.482654+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: connect to /tmp/podop.socket: No such file or directory
2022-05-26T08:30:58.482825+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: table socketmap:unix:/tmp/podop.socket:transport lookup error: No such file or directory
2022-05-26T08:30:58.483065+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: socketmap:unix:/tmp/podop.socket:transport lookup error for "*"
2022-05-26T08:30:58.487871+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: connect to /tmp/podop.socket: No such file or directory
2022-05-26T08:30:58.488390+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: table socketmap:unix:/tmp/podop.socket:domain lookup error: No such file or directory
2022-05-26T08:30:58.488624+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: virtual_mailbox_domains: socketmap:unix:/tmp/podop.socket:domain: table lookup problem
2022-05-26T08:30:58.488790+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: virtual_mailbox_domains lookup failure
2022-05-26T08:30:58.497525+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: connect to /tmp/podop.socket: No such file or directory
2022-05-26T08:30:58.498959+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: table socketmap:unix:/tmp/podop.socket:domain lookup error: No such file or directory
2022-05-26T08:30:58.499185+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: virtual_mailbox_domains: socketmap:unix:/tmp/podop.socket:domain: table lookup problem
2022-05-26T08:30:58.499915+00:00 mailu-postfix-5cf9cc5977-w446k postfix/trivial-rewrite[234202]: warning: virtual_mailbox_domains lookup failure
2022-05-26T08:30:58.501637+00:00 mailu-postfix-5cf9cc5977-w446k postfix/smtpd[234200]: warning: connect to /tmp/podop.socket: No such file or directory
2022-05-26T08:30:58.501689+00:00 mailu-postfix-5cf9cc5977-w446k postfix/smtpd[234200]: warning: table socketmap:unix:/tmp/podop.socket:senderrate lookup error: No such file or directory
2022-05-26T08:30:58.501730+00:00 mailu-postfix-5cf9cc5977-w446k postfix/smtpd[234200]: warning: socketmap:unix:/tmp/podop.socket:senderrate lookup error for "adminUser@domain.io"
2022-05-26T08:30:58.501837+00:00 mailu-postfix-5cf9cc5977-w446k postfix/smtpd[234200]: NOQUEUE: reject: RCPT from 10-111-2-100.mailu-roundcube.mailu.svc.cluster.local[10.111.2.100]: 451 4.3.5 <adminUser@domain.io>: SASL login name rejected: Server configuration error; from=<adminUser@domain.io> to=<AnotherUser@gmail.com> proto=ESMTP helo=<mail.domain.io>
2022-05-26T08:30:58.517056+00:00 mailu-postfix-5cf9cc5977-w446k postfix/smtpd[234200]: disconnect from 10-111-2-100.mailu-roundcube.mailu.svc.cluster.local[10.111.2.100] ehlo=2 xclient=0/1 mail=1 rcpt=0/1 rset=1 quit=1 commands=5/7
```
