### ISSUE TITLE
Outgoing traffic from a virtual ip over docker-compose

### ISSUE THREAD

**Issue by ritasear** [Mailu/Mailu#2389]
Hello, I started using this mail service for a personal project and I confess that I really like it. 
I would like to provide this service on a secondary ip (alias ip), however I am not able to perform the redirection. My setup is the following.

I use a VPS with two ips, primary ip (eth0) and a secondary ip (alias eth0:1):

```
Primary: Private: 10.0.1.8 - Public 50.60.70.1
Secondary: 10.0.1.9 (alias) - Public 50.60.70.2
```

Through docker-compose I redirected traffic from mailu to the second ip:

```
...
front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "10.0.1.9:8081:80"
      - "10.0.1.9:8082:443"
      - "10.0.1.9:25:25"
      - "10.0.1.9:465:465"
      - "10.0.1.9:587:587"
      - "10.0.1.9:110:110"
      - "10.0.1.9:995:995"
      - "10.0.1.9:143:143"
      - "10.0.1.9:993:993"
...
```

However when making calls from within the mailu_front container, I verify that the outgoing traffic is on the primary ip (10.0.1.8 / 50.60.70.1), I would like it to be on the secondary (10.0.1.9 / 50.60.70.2):

```
docker exec -ti docker_mailu_front_1 /bin/bash
container# curl https://api64.ipify.org?format=json
{"ip":"50.60.70.1"}
```

so i tried redirecting traffic with iptables:

```
#!/bin/bash
SourceIP=10.0.1.10 # Outgoing IP to use
IPADDR=$(docker inspect --format "{{ .NetworkSettings.Networks.docker_mailu_default.IPAddress  }}" docker_mailu_front_1)
sudo iptables -t nat -I POSTROUTING -s $IPADDR -j SNAT --to $SourceIP
```

However it didn't work, after this change webmail can no longer connect to the IMAP service.

Can anyone help me?
