### ISSUE TITLE
How just send mail from K8S to the external and disabling all other features ?

### ISSUE THREAD

**Issue by gigi206** [Mailu/Mailu#2428]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [X] Check if no issue or pull-request for this already exists.
- [X] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [ ] docker-compose
 - [X] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
Mailu seems to be a great tool and I would like to use in kubernetes to allow other pods to send mail. 

I don't need a lot of features, just relay mails to another smtp host, or in this particular case just send mail to the internet (without relay).

## Replication Steps
I use argocd:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailu
  namespace: argo-cd
spec:
  destination:
    namespace: mailu
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://mailu.github.io/helm-charts/'
    targetRevision: 0.3.3
    chart: mailu
    helm:
      parameters:
        - name: secretKey
          value: changeme
        - name: persistence.size
          value: 1Gi
        - name: subnet
          value: 10.42.0.0/16
        - name: timezone
          value: Europe/Paris
        - name: ingress.externalIngress
          value: 'false'
        # - name: mail.messageSizeLimitInMegabytes
        #   value: '50'
        - name: domain
          value: mail.gigix
        - name: hostnames[0]
          value: mail.gigix
        - name: certmanager.issuerName
          value: selfsigned-cluster-issuer
        - name: clamav.enabled
          value: 'false'
        - name: dovecot.enabled
          value: 'false'
        - name: externalService.enabled
          value: 'false'
        # - name: externalService.enabled
        #   value: 'true'
        # - name: externalService.type
        #   value: LoadBalancer
        # - name: externalService.externalTrafficPolicy
        #   value: Local
        # - name: external_relay
        #   value: host
        # - name: external_relay.host
        #   value: external_relay.gigix
        - name: fetchmail.enabled
          value: 'false'
        - name: front.hostPort.enabled
          value: 'false'
        - name: roundcube.enabled
          value: 'false'
        - name: webdav.enabled
          value: 'false'
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
```

## Expected behavior
I try to disable all features, but there are still some active parts that I can't disable like `rspamd` (I don't need it I send email only from my network).
My only need is to send emails out of the cluster, that's all :)

## Logs
Also, note that with these parameters I have some errors.

### rspamd
Events:
```
Startup probe failed: Get "http://10.42.0.88:11334/": dial tcp 10.42.0.88:11334: connect: connection refused
````

And the log is stuck at:
```
rspamd_url_init: start compiling of 9628 TLD suffixes; it might take a long time
```

### admin
How to disable dnssec? I don't need this feature locally and I have this error (I see that there is also an issue normally fixed with coredns):
```
CRITICAL:root:Your DNS resolver at 10.43.0.10 isn't doing DNSSEC validation; Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation.
```

### postfix
And of course, postfix can't connect to rspamd:
```mailu-postfix-c6c4c7c75-vmt6z postfix/smtpd[3052]: warning: connect to Milter service inet:mailu-rspamd:11332: Connection refused
mailu-postfix-c6c4c7c75-vmt6z postfix/smtpd[3052]: NOQUEUE: milter-reject: CONNECT from localhost[::1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
mailu-postfix-c6c4c7c75-vmt6z postfix/smtpd[3052]: disconnect from localhost[::1] quit=1 commands=1
```
