### ISSUE TITLE
Domain names always redirecting me to Mailu login

### ISSUE THREAD

**Issue by ayob2k** [Mailu/Mailu#2471]
With mailu, there isn't any issue with it, everything work great. But why everysingle domaine i link to my server,  when i try to use this domaine  it keep redirecting me to mailu sso login.
I want mailu to use only mail.domaine.com and not other domains.

Here is my the conf on nginx -> default.conf:

```
server {
    server_name domaine.com www.domaine.com;
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://server:3000;
    }
}
```

    
   and here is my nginx -> Dockerfile 
```
FROM nginx
COPY default.conf /etc/nginx/conf.d/default.conf
```
  Here is my docker-compose.yml

```
version: "3"
services:
  nginx:
    depends_on:
      - server
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx

  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    ports:
      - "3000:3000"

    volumes:
      - /app/node_modules
      - ./server:/app
    # environment:
```

NOTE: whenever i try to goto domaine.com, it redirect me to sso login
files structure
![Screen Shot 2022-10-14 at 12 43 30](https://user-images.githubusercontent.com/77556307/195839455-84a4cb9a-a685-4112-a77c-e485d282133e.png)
