### ISSUE TITLE
Settings -> User Interface in Webmail fails with 502 bad gateway

### ISSUE THREAD

**Issue by Simon1511** [Mailu/Mailu#2648]
### Environment

- [x] docker-compose v2.15.1
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master-arm`

## Description
The Settings page for "User Interface" (sorry, not sure if it's called like that, I have my GUI set to German) in Webmail fails with a 502 bad gateway. Surprisingly, all other settings/sites/etc work just fine.

![image](https://user-images.githubusercontent.com/46072379/216782899-2d29dd36-dcb3-452f-a00b-25737a9356ca.png)

## Replication Steps
Try to open Settings -> User Interface in Webmail.

## Observed behaviour
This specific settings page fails to load with a 502 bad gateway.

## Expected behaviour
This settings page should load and be viewable.

## Logs
Attached:
[compose.log](https://github.com/Mailu/Mailu/files/10609347/compose.log)

**Comment by nextgens** [comment]
You need to re-run setup and update your docker-compose.yml

Your logs show that your webmail container uses ``/var/www/webmail/`` when ``/var/www/roundcube/`` is current. Odds are you are using the old ``roundcube`` image instead of the new ``webmail``.

**Comment by Simon1511** [comment]
> You need to re-run setup and update your docker-compose.yml
> 
> Your logs show that your webmail container uses `/var/www/webmail/` when `/var/www/roundcube/` is current. Odds are you are using the old `roundcube` image instead of the new `webmail`.

Sorry, I should have mentioned that I set it to `roundcube` manually because `webmail` had the same issue.

**Comment by nextgens** [comment]
Please provide a copy of your new docker-compose.yml ; It shouldn't reference mailu/rainloop but mailu/webmail ... and other significant changes have been made

**Comment by Simon1511** [comment]
> Please provide a copy of your new docker-compose.yml ; It shouldn't reference mailu/rainloop but mailu/webmail ... and other significant changes have been made

Okay, I just noticed that the link that leads to "mailu setup utility" always links to the stable version (1.9), even when browsing mailu.io/master. So it gave me config files for mailu v1.9 and not for master. I did change 1.9 to master-arm everywhere though.

However, I now generated new config files (this time for master) and tried to run that one, however getting following error now:
```
# docker-compose -p mailu up -d
[+] Running 0/2
 ⠦ oletools Pulling                                                                                                                                                                                           1.6s
 ⠿ webmail Error                                                                                                                                                                                              1.6s
no matching manifest for linux/arm64/v8 in the manifest list entries
```
My docker-compose.yml now looks as follows:

```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/opt/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master-arm}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "192.168.178.130:8080:80"
      - "192.168.178.130:4443:443"
      - "192.168.178.130:25:25"
      - "192.168.178.130:465:465"
      - "192.168.178.130:587:587"
      - "192.168.178.130:110:110"
      - "192.168.178.130:995:995"
      - "192.168.178.130:143:143"
      - "192.168.178.130:993:993"
    networks:
      - default
      - webmail
    volumes:
      - "/opt/mailu/certs:/certs"
      - "/opt/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-master-arm}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-master-arm}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/data:/data"
      - "/opt/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-master-arm}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/mail:/mail"
      - "/opt/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-master-arm}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/mailqueue:/queue"
      - "/opt/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  oletools:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-master}
    hostname: oletools
    restart: always
    networks:
      - noinet
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-master-arm}
    hostname: antispam
    restart: always
    env_file: mailu.env
    networks:
      - default
      - noinet
    volumes:
      - "/opt/mailu/filter:/var/lib/rspamd"
      - "/opt/mailu/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-master-arm}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  webdav:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-master-arm}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/dav:/data"
    networks:
      - radicale

  fetchmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-master-arm}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/data/fetchmail:/data"
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - 192.168.203.254

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-master-arm}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/webmail:/data"
      - "/opt/mailu/overrides/snappymail:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  radicale:
    driver: bridge
  webmail:
    driver: bridge
  noinet:
    driver: bridge
    internal: true
```
