### ISSUE TITLE
How to config reverse proxy with caddy2?

### ISSUE THREAD

**Issue by baddate** [Mailu/Mailu#2661]
### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `1.9`

## Description

i cant config external proxy with caddy

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I am using Caddy with Mailu and it works perfectly. Could you explain better what works and what doesn't ?

What I recommend is to set all your mailu containers in a separate docker network, and only Mailu Frontend has access to the outside. You just have to reverse proxy the frontend with Caddy and it will work.
(I am using Caddy Docker Proxy with docker compose labels)

**Comment by baddate** [comment]
> Hi, I am using Caddy with Mailu and it works perfectly. Could you explain better what works and what doesn't ?
> 
> What I recommend is to set all your mailu containers in a separate docker network, and only Mailu Frontend has access to the outside. You just have to reverse proxy the frontend with Caddy and it will work. (I am using Caddy Docker Proxy with docker compose labels)

i run mailu server with built-in tls service, it works fine, and all configs generating by official mailu utility.

then i made changes with official docs, but i cant access my mailu service from browser.


here is my part of docker-compose configs after changing
```yaml
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
      - "server_ip:25:25"
      - "server_ip:465"
      - "server_ip:587:587"
      - "server_ip:110:110"
      - "server_ip:995:995"
      - "server_ip:143:143"
      - "server_ip:993:993"
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
```
full configs is here https://pastebin.com/q1z481dK

my caddy config
```
mail.mydomain.com {
        reverse_proxy http://localhost:8080
}
```

Where is the problem with these configs?

**Comment by rajaseg** [comment]
@LeVraiRoiDHyrule, Can you please share your configuration? I am trying to setup Mailu behind Caddy reverse proxy. But getting ```500 Internal Server Error``` when I try to access https://mail.example.com/admin (/webmail, /api)

Please find the files below for reference.   

#### Docker Compose ####
```
version: "3.7"

services:
  app:
    image: ghcr.io/mailu/nginx:2.0.16
    restart: unless-stopped
    depends_on:
      - resolver
    env_file: mailu.env
    networks:
      - caddy
      - mail
    dns:
      - 192.163.203.254
    volumes:
      - ./certs:/certs
      - ./nginx:/overrides:ro
  redis:
    image: redis:alpine
    restart: unless-stopped
    depends_on:
      - resolver
    volumes:
      - ./redis-data:/data
    networks:
      - mail
    dns:
      - 192.163.203.254
  resolver:
    image: ghcr.io/mailu/unbound:2.0.16
    restart: unless-stopped
    env_file: mailu.env
    networks:
      mail:
        ipv4_address: 192.163.203.254
  admin:
    image: ghcr.io/mailu/admin:2.0.16
    restart: unless-stopped
    depends_on:
      - resolver
      - redis
    env_file: mailu.env
    volumes:
      - ./dkim:/dkim
      - ./mailu:/data
    networks:
      - mail
    dns:
      - 192.163.203.254
  imap:
    image: ghcr.io/mailu/dovecot:2.0.16
    restart: unless-stopped
    depends_on:
      - resolver
      - app
    env_file: mailu.env
    volumes:
      - ./mail:/mail
      - ./dovecot:/overrides:ro
    networks:
      - mail
    dns:
      - 192.163.203.254
  smtp:
    image: ghcr.io/mailu/postfix:2.0.16
    restart: unless-stopped
    depends_on:
      - resolver
      - app
    env_file: mailu.env
    volumes:
      - ./mailqueue:/queue
      - ./postfix:/overrides:ro
    networks:
      - mail
    dns:
      - 192.163.203.254
  oletools:
    image: ghcr.io/mailu/oletools:2.0.16
    restart: unless-stopped
    networks:
      - mail
    depends_on:
      - resolver
    dns:
      - 192.163.203.254
  antispam:
    image: ghcr.io/mailu/rspamd:2.0.16
    restart: unless-stopped
    depends_on:
      - app
      - redis
      - oletools
      - antivirus
      - resolver
    env_file: mailu.env
    volumes:
      - ./spamfilter:/var/lib/rspamd
      - ./rspamd:/var/lib/rspamd
      - ./dkim:/dkim:ro
    networks:
      - mail
    dns:
      - 192.163.203.254
  antivirus:
    image: ghcr.io/mailu/clamav:2.0.16
    restart: unless-stopped
    env_file: mailu.env
    volumes:
      - "./virusfilter:/data"
    depends_on:
      - resolver
    networks:
      - mail
    dns:
      - 192.163.203.254
  webdav:
    image: ghcr.io/mailu/radicale:2.0.16
    restart: unless-stopped
    env_file: mailu.env
    volumes:
      - ./webdav:/data
    networks:
      - mail
  fetchmail:
    image: ghcr.io/mailu/fetchmail:2.0.16
    restart: unless-stopped
    env_file: mailu.env
    volumes:
      - "./fetchmail:/data"
    networks:
      - mail
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - 192.163.203.254
  webmail:
    image: ghcr.io/mailu/webmail:2.0.16
    restart: unless-stopped
    env_file: mailu.env
    depends_on:
      - app
    networks:
      - mail
    volumes:
      - ./webmail:/data
      - ./snappymail:/overrides:ro
  caddy:
    image: rajaseg/caddy
    restart: unless-stopped
    container_name: caddy
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 443
        published: 443
        mode: host
        protocol: udp
      - target: 25
        published: 25
        mode: host
      - target: 110
        published: 110
        mode: host
      - target: 143
        published: 143
        mode: host
      - target: 465
        published: 465
        mode: host
      - target: 587
        published: 587
        mode: host
      - target: 993
        published: 993
        mode: host
      - target: 995
        published: 995
        mode: host
      - target: 4190
        published: 4190
        mode: host
    networks:
      - caddy
      - inet
      - mail
      - noinet
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddydata:/data
      - ./caddyconfig:/config
      - ./caddylogs:/var/log/caddy
volumes:
  caddydata:
  caddyconfig:
  caddylogs:
  redis-data:
  certs:
  nginx:
  admindata:
  dkim:
  mail:
  dovecot:
  mailqueue:
  postfix:
  spamfilter:
  rspamd:
  webdav:
  fetchmail:
  webmail:
  sanppymail:
networks:
  caddy:
    external: true
  inet:
  mail:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.163.203.0/24
  noinet:
    driver: bridge
    internal: true
```
#### mailu.env ####
```
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=6IM5UH7PV7QYKSS0

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.163.203.0/24

# Main mail domain
DOMAIN=example.com

# Hostnames for this server, separated with comas
HOSTNAMES=mail.example.com

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=mail-letsencrypt

# Authentication rate limit per IP (per /24 on ipv4 and /48 on ipv6)
AUTH_RATELIMIT_IP=5/hour

# Authentication rate limit per user (regardless of the source-IP)
AUTH_RATELIMIT_USER=50/day

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=True

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, snappymail, none)
WEBMAIL=snappymail

# Expose the API interface (value: true, false)
API=true

# Dav server implementation (value: radicale, none)
WEBDAV=radicale

# Antivirus solution (value: clamav, none)
ANTIVIRUS=clamav

# Scan Macros solution (value: true, false)
SCAN_MACROS=true

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Message rate limit (per user)
MESSAGE_RATELIMIT=200/day

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Enable fetchmail
FETCHMAIL_ENABLED=true

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: gz, bz2, zstd)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

# IMAP full-text search is enabled by default. Set the following variable to off in order to disable the feature.
# FULL_TEXT_SEARCH=off

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/webmail

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/webmail

# Path to the API interface if enabled
WEB_API=/api

# Website name
SITENAME=Mailu

# Linked Website URL
WEBSITE=https://mailu.io


###################################
# Advanced settings
###################################

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Number of rounds used by the password hashing scheme
CREDENTIAL_ROUNDS=12

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

# Timezone for the Mailu containers. See this link for all possible values https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TZ=Etc/UTC

# Default spam threshold used for new users
DEFAULT_SPAM_THRESHOLD=80

# API token required for authenticating to the RESTful API.
# This is a mandatory setting for using the RESTful API.
API_TOKEN=
```
#### Caddyfile ####
```
mail.example.com {
    encode gzip zstd
    reverse_proxy app:80 {
        transport http {
            keepalive 300s
        }
        header_up X-Real-IP {remote_host}
    }
}
```
#### webmail.conf ####
```
location ~* ^/(admin|api|sso|static|webdav|webmail|(apple\.)?mobileconfig|(\.well\-known/autoconfig/)?mail/|Autodiscover/Autodiscover) {
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_pass https://localhost:8443;
}
```
