### ISSUE TITLE
fail to read the letter for ARM

### ISSUE THREAD

**Issue by why2lyj** [Mailu/Mailu#2662]
## Environment & Version

### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `1.9`

<!--
526d3d7aa7b5   mailu/roundcube:master-arm   "/bin/sh -c /start.py"   12 minutes ago   Up 12 minutes (healthy)   80/tcp                                                                                                                                                                                                                                                                                                                                                  mailu_webmail_1
96866ff111c9   mailu/dovecot:master-arm     "/bin/sh -c /start.py"   12 minutes ago   Up 12 minutes (healthy)   110/tcp, 143/tcp, 993/tcp, 2525/tcp, 4190/tcp                                                                                                                                                                                                                                                                                                           mailu_imap_1
182997ea127f   mailu/postfix:master-arm     "/bin/sh -c /start.py"   12 minutes ago   Up 12 minutes (healthy)                                                                                                                                                                                                                                                                                                                                                           mailu_smtp_1
9c2e3189ddd3   mailu/rspamd:master-arm      "/bin/sh -c /start.py"   12 minutes ago   Up 12 minutes (healthy)                                                                                                                                                                                                                                                                                                                                                           mailu_antispam_1
71da4f08aad1   mailu/admin:master-arm       "/bin/sh -c /start.py"   12 minutes ago   Up 12 minutes (healthy)                                                                                                                                                                                                                                                                                                                                                           mailu_admin_1
60180b8e6f4d   mailu/radicale:master-arm    "/bin/sh -c 'radical…"   12 minutes ago   Up 12 minutes (healthy)                                                                                                                                                                                                                                                                                                                                                           mailu_webdav_1
d91dc9820c9c   mailu/clamav:master-arm      "/bin/sh -c /start.py"   12 minutes ago   Up 12 minutes (healthy)                                                                                                                                                                                                                                                                                                                                                           mailu_antivirus_1
f0177a87ce98   mailu/fetchmail:master-arm   "/fetchmail.py"          12 minutes ago   Up 12 minutes (healthy)                                                                                                                                                                                                                                                                                                                                                           mailu_fetchmail_1
aee8f220bc6f   redis:alpine                 "docker-entrypoint.s…"   12 minutes ago   Up 12 minutes             6379/tcp                                                                                                                                                                                                                                                                                                                                                mailu_redis_1
43dcc1bd3917   mailu/nginx:master-arm       "/bin/sh -c /start.py"   12 minutes ago   Up 12 minutes (healthy)   0.0.0.0:25->25/tcp, :::25->25/tcp, 0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:110->110/tcp, :::110->110/tcp, 0.0.0.0:143->143/tcp, :::143->143/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:465->465/tcp, :::465->465/tcp, 0.0.0.0:587->587/tcp, :::587->587/tcp, 0.0.0.0:993->993/tcp, :::993->993/tcp, 0.0.0.0:995->995/tcp, :::995->995/tcp   mailu_front_1
e091b445b33b   mailu/unbound:master-arm     "/bin/sh -c /start.py"   12 minutes ago   Up 12 minutes (healthy)                                                                                                                                                                                                                                                                                                                                                           mailu_resolver_1
-->

## Description
![企业微信截图_1676303205926](https://user-images.githubusercontent.com/31466760/218504778-9d056880-2f11-4b50-827b-5e47e262e818.png)


## Replication Steps

docker-compose.yml
```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: mailu/nginx:master-arm
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: mailu/unbound:master-arm
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: mailu/admin:master-arm
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: mailu/dovecot:master-arm
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mail:/mail"
      - "/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: mailu/postfix:master-arm
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mailqueue:/queue"
      - "/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: mailu/rspamd:master-arm
    hostname: antispam
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/var/lib/rspamd"
      - "/mailu/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: mailu/clamav:master-arm
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  webdav:
    image: mailu/radicale:master-arm
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/dav:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  fetchmail:
    image: mailu/fetchmail:master-arm
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/data/fetchmail:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Webmail
  webmail:
    image: mailu/roundcube:master-arm
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/webmail:/data"
      - "/mailu/overrides/roundcube:/overrides:ro"
    depends_on:
      - imap
      - resolver
    dns:
      - 192.168.203.254

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```

## Observed behaviour

I changed all docker images to master-arm

## Expected behaviour
I want to read the email letter

## Logs
for contain `mailu_webmail_1` logs as below:

```
2023/02/13 23:42:53 [error] 15#15: *119 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Return type of zipdownload_mbox_filter::filter($in, $out, &$consumed, $closing) should either be compatible with php_user_filter::filter($in, $out, &$consumed, bool $closing): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/webmail/plugins/zipdownload/zipdownload.php on line 405PHP message: PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/webmail/program/lib/Roundcube/rcube_imap.php on line 1916PHP message: PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/webmail/program/include/rcmail_action.php on line 1221PHP message: PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/webmail/program/include/rcmail_action.php on line 1221PHP message: PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/webmail/program/include/rcmail_action.php on line 1221PHP message: PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/webmail/program/include/rcmail_action.php on line 1221PHP message: PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/webmail/program/include/rcmail_action.php on line 1221PHP message: PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/webmail/program/lib/Roundcube/rcube_mime.php on line 323PHP message: PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/webmail/program/lib/Roundcube/rcube_mime.php on line 323PHP message: PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/webmail/program/lib/Roundcube/rcube_mime.php
2023/02/13 23:43:31 [error] 15#15: *127 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Return type of zipdownload_mbox_filter::filter($in, $out, &$consumed, $closing) should either be compatible with php_user_filter::filter($in, $out, &$consumed, bool $closing): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/webmail/plugins/zipdownload/zipdownload.php on line 405" while reading response header from upstream, client: 192.168.203.2, server: , request: "POST /?_task=mail&_action=refresh HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8-fpm.sock:", host: "mail.myhost.com", referrer: "https://mail.myhost.com/webmail/?_task=mail&_mbox=INBOX"

```
