### ISSUE TITLE
Certdump: Make acme.json as a variable - enhancement

### ISSUE THREAD

**Issue by kirbylink** [Mailu/Mailu#2683]
### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `1.9`

## Description
I am using Traefik as reverse proxy and Traefik can handle multiple domain names for one host. For this reason i setup Traefik to store for each domain the certificates in different files, e. g. `acme-<domain>.json`
Certdumps script has a hardcoded point to acme.json in a specific folder. I mounted the volume of Traefik which contains the acme files.
Without editing the script in the running Certdump container i can't get the updated certificate that is done by Traefik

## Replication Steps
Store cert in a separate file.
traefik.yml:
```
certificatesResolvers:
  letsencrypt-<domain>:
    acme:
      email: certificate@example.com
      storage: /data/acme-<domain>.json
      tlsChallenge: {}
```
Using the cert resolver for Mailu.
Mailu docker-compose:
```
traefik.http.routers.mailu.tls.certresolver=letsencrypt-<domain>
```
Mount the acme.json folder to certdump
Mailu docker-compose:
```
certdumper:
    image: ${DOCKER_REGISTRY}/${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}traefik-certdumper:${MAILU_VERSION:-1.9}
    container_name: mailu_certdump-1.9
    restart: always
    environment:
      - DOMAIN=mail.<fqdn>
      - TRAEFIK_VERSION=${TRAEFIK_VERSION}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Folder, which contains the acme.json
      - "traefik_data:/traefik:ro"
      # Folder, where cert.pem and key.pem will be written
      - "certdumper-data-1.9:/output"
```
## Observed behaviour
In the Traefik folder is still an old acme.json file with expired certificates. Certdump always takes acme.json until I change it manually in `run.sh` script. Of course this works only until the container will be deployed again.
## Expected behaviour
Certdump should not take hardcoded acme.json
## Logs
Not necessary.
