### ISSUE TITLE
boucing emails spamming my server

### ISSUE THREAD

**Issue by migs35323** [Mailu/Mailu#2688]
### Environment

- [ ] docker-compose
- [X] kubernetes
- [ ] docker swarm

### Version

- Version: `1.9.50`

## Description

did setup a machine with mailu (linux, k3s), and as documented i used the mx tools to check for open relays and and it's seems ok

however my postmaster today suddenly started to being spammed with bounced mails from mailer daemon,
my issue is very similair to #583,
i am getting thousands of mails from mailer daemon saying that my message couldn't be delivered... 
but please note that the REJECT env is "yes" by default in the k8s chart and "not configurable", so the bouncing shouldn't happen...

i would like some help to understand what is going on..
i believe my machine was somehow tricked to send spam or something?

My vps provider just shutted down my machine since the traffic was unusually high

## Logs

DAEMON emails:
```
-------- Original Message --------
Subject: Postmaster Warning: Delayed Mail
Date: 2023-03-07 16:45
 From: MAILER-DAEMON@MYSERVER.com (Mail Delivery System)
To: postmaster@MYSERVER.com

<andrebreneville@myway.com>: delivery temporarily suspended: connect to
     myway.com[34.117.28.143]:25: Operation timed out

<andrecephas1@aol.com>: host mx-aol.mail.gm0.yahoodns.net[67.195.204.80]
said:
     421 4.7.0 [TSS04] Messages from <MAILU_EXTERNAL_IP> temporarily deferred
due to
     unexpected volume or user complaints - 4.16.55.1; see
     https://postmaster.yahooinc.com/error-codes (in reply to MAIL FROM
command)

<andregodfather@aol.com>: host
mx-aol.mail.gm0.yahoodns.net[67.195.204.80]
     said: 421 4.7.0 [TSS04] Messages from <MAILU_EXTERNAL_IP> temporarily
deferred
     due to unexpected volume or user complaints - 4.16.55.1; see
     https://postmaster.yahooinc.com/error-codes (in reply to MAIL FROM
command)

<andrecampoverde@yahoo.com>: host mta6.am0.yahoodns.net[67.195.204.77]
said:
     421 4.7.0 [TSS04] Messages from <MAILU_EXTERNAL_IP> temporarily deferred
due to
     unexpected volume or user complaints - 4.16.55.1; see
     https://postmaster.yahooinc.com/error-codes (in reply to MAIL FROM
command)

<andredavis03@yahoo.com>: host mta6.am0.yahoodns.net[67.195.204.77]
said: 421
     4.7.0 [TSS04] Messages from <MAILU_EXTERNAL_IP> temporarily deferred due
to
     unexpected volume or user complaints - 4.16.55.1; see
     https://postmaster.yahooinc.com/error-codes (in reply to MAIL FROM
command)

<andredegarza7@yahoo.com>: host mta6.am0.yahoodns.net[67.195.204.77]
said: 421
     4.7.0 [TSS04] Messages from <MAILU_EXTERNAL_IP> temporarily deferred due
to
     unexpected volume or user complaints - 4.16.55.1; see
     https://postmaster.yahooinc.com/error-codes (in reply to MAIL FROM
command)

<andreengrubb@yahoo.com>: host mta6.am0.yahoodns.net[67.195.204.77]
said: 421
     4.7.0 [TSS04] Messages from <MAILU_EXTERNAL_IP> temporarily deferred due
to
     unexpected volume or user complaints - 4.16.55.1; see
     https://postmaster.yahooinc.com/error-codes (in reply to MAIL FROM
command)

<andregaither545@yahoo.com>: host mta6.am0.yahoodns.net[67.195.204.77]
said:
     421 4.7.0 [TSS04] Messages from <MAILU_EXTERNAL_IP> temporarily deferred
due to
     unexpected volume or user complaints - 4.16.55.1; see
     https://postmaster.yahooinc.com/error-codes (in reply to MAIL FROM
command)

<andreguardado155@yahoo.com>: host mta6.am0.yahoodns.net[67.195.204.77]
said:
     421 4.7.0 [TSS04] Messages from <MAILU_EXTERNAL_IP> temporarily deferred
due to
     unexpected volume or user complaints - 4.16.55.1; see
     https://postmaster.yahooinc.com/error-codes (in reply to MAIL FROM
command)

<andregutierrezjr@yahoo.com>: host mta6.am0.yahoodns.net[67.195.204.77]
said:
     421 4.7.0 [TSS04] Messages from <MAILU_EXTERNAL_IP> temporarily deferred
due to
     unexpected volume or user complaints - 4.16.55.1; see
     https://postmaster.yahooinc.com/error-codes (in reply to MAIL FROM
command)

<andrefischer271@yahoo.de>: host
mx-eu.mail.am0.yahoodns.net[188.125.72.73]
     said: 421 4.7.0 [TSS04] Messages from <MAILU_EXTERNAL_IP> temporarily
deferred
     due to unexpected volume or user complaints - 4.16.55.1; see
     https://postmaster.yahooinc.com/error-codes (in reply to MAIL FROM
command)

<andregoy@yahoo.de>: host mx-eu.mail.am0.yahoodns.net[188.125.72.73]
said: 421
     4.7.0 [TSS04] Messages from <MAILU_EXTERNAL_IP> temporarily deferred due
to
     unexpected volume or user complaints - 4.16.55.1; see
     https://postmaster.yahooinc.com/error-codes (in reply to MAIL FROM
command)

Return-Path: <SRS0=rx/K=67=protege.cll=correo@MYSERVER.com>
Received: from User (unknown [10.42.3.12])
        by mailu.MYSERVER.com (Postfix) with SMTP id <REDACTED>;
        Tue,  7 Mar 2023 11:11:30 +0000 (UTC)
Reply-To: <bankofafrica20202022@gmail.com>
 From: "Mr. John Benson"<correo@protege.cll>
Subject: Your compensation funds of $10.800,000,00 United States Dollars
Date: Tue, 7 Mar 2023 03:12:07 -0800
MIME-Version: 1.0
Content-Type: text/plain;
        charset="Windows-1251"
Content-Transfer-Encoding: 7bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2600.0000
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2600.0000
Authentication-Results: mailu.MYSERVER.com;
        none
X-Spam-Level: **********
X-Spamd-Bar: ++++++++++
X-Spam: Yes
```

**Comment by nextgens** [comment]
Odds are you are running an open-relay.

Please report your issue on https://github.com/Mailu/helm-charts/ since that is what you are running and ensure that you have ``externalTrafficPolicy: Local`` somewhere.

**Comment by migs35323** [comment]
@nextgens well, MX toolbox said i was not running an open relay... it did green checked... 

the relevant values that i used:
```
clusterDomain: cluster.local
external_relay: {}
nodeSelector: 
  "machine-label": "mail-machine"
certmanager:
  enabled: true
  issuerType: ClusterIssuer

# Set ingress and loadbalancer config
ingress:
  externalIngress: true
  tlsFlavor: cert
  className: "traefik"
  #annotations:
    #nginx.ingress.kubernetes.io/proxy-body-size: "0"
  realIpHeader: X-Forwarded-For
  realIpFrom: 0.0.0.0/0

# Frontend load balancer for non-HTTP(s) services
front:
  externalService:
    enabled: true
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations: {}
    pop3:
      pop3: false
      pop3s: true
    imap:
      imap: false
      imaps: true
    smtp:
      smtp: true
      smtps: true
      submission: true
```
