### ISSUE TITLE
"flask mailu config-import" allows creating aliases with the same address as a user

### ISSUE THREAD

**Issue by NicolasGoeddel** [Mailu/Mailu#2716]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `1.9`

## Description

I created a Python script which is able to convert the data of a [postfixadmin](https://github.com/postfixadmin/postfixadmin) database into a configuration that can be imported with `flask mailu config-import [-u]`. During the development I overlooked that postfixadmin creates an alias which points to itself for each mailbox user. And so I accidentally did the same in the resulting YAML output for the Mailu config importer. This resulted in duplicates in the UI for each alias which has a mailbox as its destination.

## Replication Steps

To replicate the behaviour my idea was to to import this configuration:
```yaml
#duplicate.yaml
domain:
  - name: example.com

user:
  - email: user.name@example.com
    password: verysecurepassword

alias:
  - email: user.name@example.com
    destination:
      - user.name@example.com

  - email: alias@example.com
    destination:
      - user.name@example.com

relay: []
```
Now run:
```
docker compose exec -T admin flask mailu config-import -u < duplicate.yaml
```

## Observed behaviour

![image](https://user-images.githubusercontent.com/1520064/227715076-24d38f88-0175-4d86-9a6f-6154ff5a29f2.png)

## Expected behaviour

Since it is not possible to create an alias with the same name as an already existing user/mailbox using the UI, I expect the same error when importing the configuration using the CLI.

## Logs
There are no logs.
