### ISSUE TITLE
setup.mailu.io generated docker-compose.ym has invalid ipv6 syntax

### ISSUE THREAD

**Issue by togir2** [Mailu/Mailu#2749]
### Environment

- [x] docker compose version 1.22.0, build f46880fe centos 7
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

The docker-compose.yml file genrated from setup.mailu.io has the ipv6 adresses as:
```
 front:
   --snip--
    ports:
      - "185.244.195.200:80:80"
      - "[::1]:80:80"
      - "185.244.195.200:443:443"
      - "[::1]:443:443"
      - "185.244.195.200:25:25"
      - "[::1]:25:25"
      - "185.244.195.200:465:465"
      - "[::1]:465:465"
      - "185.244.195.200:587:587"
      - "[::1]:587:587"
      - "185.244.195.200:110:110"
      - "[::1]:110:110"
      - "185.244.195.200:995:995"
      - "[::1]:995:995"
      - "185.244.195.200:143:143"
      - "[::1]:143:143"
      - "185.244.195.200:993:993"
      - "[::1]:993:993"
    networks:
```
Docker compose is complaining about this syntax:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.front.ports is invalid: Invalid port "[::1]:110:110", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "[::1]:143:143", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "[::1]:25:25", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "[::1]:465:465", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "[::1]:587:587", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "[::1]:8443:443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "[::1]:993:993", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "[::1]:995:995", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```

## Fix 
To fix it the "[]" have to be removed from the ipv6 adress eg. "[::1]:110:110" -> "::1:110:110"

Link to a full genrated config with the "wrong" ipv6 adresses:
https://setup.mailu.io/2.0/setup/c0018769-2dbb-463d-be44-6b3dfc167ead
