### ISSUE TITLE
Webmail container with roundcube crashes on start after migrating to Mailu 2.0

### ISSUE THREAD

**Issue by sephentos** [Mailu/Mailu#2761]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-2.0}
docker-compose.yml:    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}

## Description

Webmail container with roundcube crashes on start after migrating to Mailu 2.0
I've found the issue #2693 but it could not help me. @nextgens 

```

  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "/d/mailu/data/webmail:/data"
      - "/d/mailu/data/overrides/roundcube:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front
```

## Replication Steps

```docker compose up -d```

## Logs

```
Initializing database
PHP Fatal error:  [snuffleupagus][0.0.0.0][disabled_function][drop] Aborted execution on call of the function 'ini_set', because its argument '$option' content (error_log) matched a rule in /var/www/roundcube/program/lib/Roundcube/rcube_config.php on line 254
Fatal error: Please check the Roundcube error log and/or server error logs for more information.
```

**Comment by nextgens** [comment]
Have you changed the error_log somewhere in the overrides? The test server at https://test.mailu.io seems fine

**Comment by sephentos** [comment]
No, my overrides for roundcube just contain

```
<?php
$config = array();
$config['product_name'] = 'Webmail';
```

but I think the issue is that roundcube tries to `ini_set` 

![grafik](https://user-images.githubusercontent.com/35430448/231081069-fc4d92ab-ee99-482e-8cc8-0d8a821cbe86.png)


which seems to be blacklisted in [snuffleupagus.rules](https://github.com/Mailu/Mailu/blob/master/webmails/snuffleupagus.rules)

Could that be the issue?

**Comment by nextgens** [comment]
That's definitely the issue... what I don't understand is why it works for others (including on the test server).

A rule like this would fix it:
```
sp.disable_function.function("ini_get").filename("/var/www/roundcube/program/lib/Roundcube/rcube_config.php").param("option").value("error_log").allow();
```

**Comment by nextgens** [comment]
We set 'log_driver' to 'stdout' ... have you changed that?

**Comment by sephentos** [comment]
> We set 'log_driver' to 'stdout' ... have you changed that?

I've copy-pasted the docker-compose from setup.mailu.io 

```

  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "/d/mailu/data/webmail:/data"
      - "/d/mailu/data/overrides/roundcube:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front
```

After changing it manually to:

```
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "/d/mailu/data/webmail:/data"
      - "/d/mailu/data/overrides/roundcube:/overrides:ro"
    logging:
      driver: stdout
    networks:
      - webmail
    depends_on:
      - front
```

it still does not work
