### ISSUE TITLE
Broken after reboot

### ISSUE THREAD

**Issue by furll** [Mailu/Mailu#2867]
### Environment
- [x] docker compose

### Version
- Version: `1.9 and 2.0`

## Description
I've been running mailu for like two years now, from a mystery version to 1.7, to 1.9.
During routine maintenance I had to restart server. This was apparently a mistake as I've been trying to fix mailu for two days now.

My (host) nginx is now full of "connect() failed (111: Connection refused) while connecting to upstream"
This nginx handles tls termination, everything "inside" is unencrypted ( with the exception of TLS_FLAVOR=mail in mailu, where i use my wildcard chain generated by host acme.sh)
I don't seem to find any errors in any of the mailu containers.

I did notice I suddenly have an /sso page that wasn't there before.
Figuring I ran half a borkup update (docker hub down), I regenerated docker-compose and env files using the builder. (1.9 to 2.0 update).
I imported those after changing ports, and observe the same behavior with one difference.
On 1.9 I am able to reach /sso by navigating to localhost:myport directly.
On 2.0 this times out.

## Logs (some excerpts)
```
admin_1     | [2023-06-24 05:45:30 +0000] [2655] [INFO] Starting gunicorn 20.1.0
admin_1     | [2023-06-24 05:45:30 +0000] [2655] [INFO] Listening at: http://0.0.0.0:80 (2655)
admin_1     | [2023-06-24 05:45:30 +0000] [2655] [INFO] Using worker: gthread
admin_1     | [2023-06-24 05:45:30 +0000] [2656] [INFO] Booting worker with pid: 2656
=====
antispam_1  | 2023-06-24 05:45:33 #162(controller) <5t8s4f>; map; http_map_finish: data is not modified for server sa-update.surbl.org, next check at Sat, 24 Jun 2023 05:50:33 GMT (timer based)
antispam_1  | 2023-06-24 05:45:37 #163(hs_helper) rspamd_rs_compile_cb: compiled 0 regular expressions to the hyperscan tree, postpone loaded notification for 1 seconds to avoid races
antispam_1  | 2023-06-24 05:45:38 #162(controller) <sa6cyy>; map; http_map_finish: need to reread map from http://admin/internal/rspamd/local_domains
antispam_1  | 2023-06-24 05:45:39 #162(controller) <sa6cyy>; map; http_map_finish: need to reread map from http://admin/internal/rspamd/local_domains
antispam_1  | 2023-06-24 05:45:43 #162(controller) <sa6cyy>; map; http_map_finish: cannot read empty map
antispam_1  | 2023-06-24 05:45:44 #162(controller) <sa6cyy>; map; http_map_finish: cannot read empty map
```
=====
```
front_1     | nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/certs/cert.pem"
front_1     | 2023/06/24 05:45:00 [notice] 1#1: using the "epoll" event method
front_1     | 2023/06/24 05:45:00 [notice] 1#1: nginx/1.22.1
front_1     | 2023/06/24 05:45:00 [notice] 1#1: OS: Linux 5.10.0-11-amd64
front_1     | 2023/06/24 05:45:00 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
front_1     | 2023/06/24 05:45:00 [notice] 1#1: start worker processes
front_1     | 2023/06/24 05:45:00 [notice] 1#1: start worker process 11
=====
imap_1      | Jun 24 05:40:23 master: Info: Dovecot v2.3.20 (80a5ac675d) starting up for imap, pop3, lmtp, sieve
imap_1      | Jun 24 05:45:01 master: Info: Dovecot v2.3.20 (80a5ac675d) starting up for imap, pop3, lmtp, sieve
=====
redis_1     | 1:M 24 Jun 2023 05:44:59.970 * Loading RDB produced by version 7.0.11
redis_1     | 1:M 24 Jun 2023 05:44:59.970 * RDB age 35 seconds
redis_1     | 1:M 24 Jun 2023 05:44:59.970 * RDB memory usage when created 1.98 Mb
redis_1     | 1:M 24 Jun 2023 05:44:59.973 * Done loading RDB, keys loaded: 25, keys expired: 0.
redis_1     | 1:M 24 Jun 2023 05:44:59.973 * DB loaded from disk: 0.002 seconds
redis_1     | 1:M 24 Jun 2023 05:44:59.973 * Ready to accept connections
```
=====
```
resolver_1  | [1687585465] unbound[1:0] info: average recursion processing time 0.490796 sec
resolver_1  | [1687585465] unbound[1:0] info: histogram of recursion processing times
resolver_1  | [1687585465] unbound[1:0] info: [25%]=0.065536 median[50%]=0.238313 [75%]=0.500457
resolver_1  | [1687585465] unbound[1:0] info: lower(secs) upper(secs) recursions
resolver_1  | [1687585465] unbound[1:0] info:    0.000000    0.000001 1
resolver_1  | [1687585465] unbound[1:0] info:    0.008192    0.016384 2
resolver_1  | [1687585465] unbound[1:0] info:    0.016384    0.032768 4
resolver_1  | [1687585465] unbound[1:0] info:    0.032768    0.065536 5
resolver_1  | [1687585465] unbound[1:0] info:    0.065536    0.131072 3
resolver_1  | [1687585465] unbound[1:0] info:    0.131072    0.262144 11
resolver_1  | [1687585465] unbound[1:0] info:    0.262144    0.524288 11
resolver_1  | [1687585465] unbound[1:0] info:    0.524288    1.000000 3
resolver_1  | [1687585465] unbound[1:0] info:    1.000000    2.000000 4
resolver_1  | [1687585465] unbound[1:0] info:    2.000000    4.000000 4
resolver_1  | [1687585499] unbound[1:0] notice: init module 0: validator
resolver_1  | [1687585499] unbound[1:0] notice: init module 1: iterator
resolver_1  | [1687585499] unbound[1:0] info: start of service (unbound 1.17.1).
resolver_1  | [1687585501] unbound[1:0] info: generate keytag query _ta-4f66. NULL IN
```
=====
```
smtp_1      | 2023-06-24 05:45:01 INFO     MAIN: uvloop is not available. Falling back to built-in event loop.
smtp_1      | INFO:MAIN:Eventloop started.
smtp_1      | 2023-06-24 05:45:01 INFO     MAIN: Eventloop started.
smtp_1      | INFO:MAIN:Server started.
smtp_1      | 2023-06-24 05:45:01 INFO     MAIN: Server started.
smtp_1      | INFO:MAIN:Proactive policy fetching is disabled.
smtp_1      | 2023-06-24 05:45:01 INFO     MAIN: Proactive policy fetching is disabled.
smtp_1      | Jun 24 05:45:05 furl postfix/postfix-script[336]: starting the Postfix mail system
smtp_1      | Jun 24 05:45:05 furl postfix/master[337]: daemon started -- version 3.7.4, configuration /etc/postfix
```
=====
```
webmail_1   | Executing database schema update.
webmail_1   | done.
webmail_1   | This instance of Roundcube is up-to-date.
webmail_1   | Have fun!
webmail_1   | 0 records deleted from 'contacts'
webmail_1   | 0 records deleted from 'contactgroups'
webmail_1   | 0 records deleted from 'identities'
webmail_1   | 0 records deleted from 'responses'
```
=====

When I refresh the webmail or admin, I get the nginx entry on host reg. upstream refused, but none of the logs in compose change.
I do get a log entry when I try to login on /sso (which, again, is unknown to me). (on 1.9 only)

Mid-writing update: Seems I can't reach IP:port directly anymore on 1.9.

When I use the newly generated config files as-is in an empty directory (fresh start), the behaviour seems to be the same.
I tried purging iptables but this did not help.
I disabled cloudflare proxying, this did not help.

I have no idea how to begin troubleshooting this and would appreciate help.

As this is (was) a production environment for a now very unhappy wife, I'm also fine with exporting email and importing it to gmail if that is possible at all.

**Comment by furll** [comment]
After a reboot I can access /sso again, from the mailu 2.0 compose directory.
Trying to log in with my accounts results in a password failure.

**Comment by nextgens** [comment]
Well you seem to be describing a lot of different problems here.

A reboot being required -> this most likely means that the old instance was still running or something else was binding the ports Mailu was configured to use.

"password failure", can you provide us with extracts from the logs please?

Have you configured ``REAL_IP_FROM`` as defined in https://mailu.io/2.0/configuration.html ? If not, you may be hitting the rate limiter ... as all login attempts would appear to come from your proxy.

The rate limiter can be disabled by setting a very high limit on both AUTH_RATELIMIT_IP and AUTH_RATELIMIT_USER; say "9999/minute"

**Comment by furll** [comment]
Password failure;
```
front_1     | 10.0.0.77 - - [24/Jun/2023:13:59:34 +0000] "POST /sso/login HTTP/1.1" 200 2177 "http://10.0.0.177:8980/sso/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
front_1     | 10.0.0.77 - - [24/Jun/2023:13:59:34 +0000] "GET /static/vendor.css HTTP/1.1" 304 0 "http://10.0.0.177:8980/sso/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
admin_1     | [2023-06-24 13:59:34,417] WARNING in base: Login failed for admin@my.tld from 10.0.0.77.
```
10.0.0.77 is my windows machine, 10.0.0.177 is the server. my.tld is of course filled in properly usually.

rate limiting seems to work fine considering the admin container is slowly blacklisting the entire planet;
```
admin_1     | [2023-06-24 13:57:44,217] WARNING in limiter: Authentication attempt from 141.98.10.150 has been rate-limited.
admin_1     | [2023-06-24 13:57:55,938] WARNING in limiter: Authentication attempt from 46.148.40.185 has been rate-limited.
admin_1     | [2023-06-24 13:58:03,718] WARNING in limiter: Authentication attempt from 141.98.10.151 has been rate-limited.
admin_1     | [2023-06-24 13:58:32,767] WARNING in limiter: Authentication attempt from 141.98.10.150 has been rate-limited.
admin_1     | [2023-06-24 13:58:36,298] WARNING in limiter: Authentication attempt from 46.148.40.147 has been rate-limited.
admin_1     | [2023-06-24 13:58:41,203] WARNING in limiter: Authentication attempt from 141.98.10.151 has been rate-limited.
admin_1     | [2023-06-24 13:59:17,028] WARNING in limiter: Authentication attempt from 141.98.10.151 has been rate-limited.
admin_1     | [2023-06-24 13:59:21,782] WARNING in limiter: Authentication attempt from 141.98.10.150 has been rate-limited.
```
So much noise...

My REAL_IP_FROM is set to 
```
REAL_IP_HEADER=X-Real-IP
REAL_IP_FROM=10.0.0.1,10.0.0.177,127.0.0.1,192.168.133.1
```

I don't recall containers or ports being in use already, I'm fairly confident I'd recognize the error - but I also know things are easy to miss sometimes.

For completeness here is the related part in my host's nginx config;
```
        location /webmail {
#       location ~* ^/(webmail|admin|sso|static|webdav|webmail|(apple\.)?mobileconfig|(\.well\-known/autoconfig/)?mail/|Autodiscover/Autodiscover) {
                proxy_pass http://127.0.0.1:8980/webmail;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto "http";
                proxy_ssl_name "my.tld";
                proxy_ssl_server_name on;
        }
```

**Comment by nextgens** [comment]
OK, let's focus on the "Login failed" error.

``docker compose exec admin flask mailu config-export user`` ... does the password field start with ``$bcrypt-sha256$`` ?

**Comment by furll** [comment]
```
└──╼docker-compose exec admin flask mailu config-export user
user: []

```
Well this seems like a different output than expected!

**Comment by nextgens** [comment]
Hmm. Do you have a data/main.db file? If so, do you see anything with the below?

```
sqlite3 data/main.db 'select * from user;'
```

**Comment by furll** [comment]
```
└──╼ docker-compose exec admin flask mailu config-export
domain: []
user: []
alias: []
relay: []
```
I don't like the way this is going...

There is no main.db file, in data I have;
```
external_psql
instance
psql_backup
psql_db
```

**Comment by furll** [comment]
Hold on I was running a test environment, my apologies!

**Comment by furll** [comment]
Passwords start with
` password: $bcrypt-sha256$v=2,t=2b,`
Let me retry on the correct environment... I've been working too much on this and need a break!

**Comment by nextgens** [comment]
Does your password contain non ascii characters? If so, please confirm that you are running at least https://github.com/Mailu/Mailu/releases/tag/2.0.14 using ``docker-compose exec admin cat /version``.

If not, please try resetting the password from the command line (or creating a separate user) and see if that works. You can use ``docker compose exec admin flask mailu ...`` to do so

**Comment by furll** [comment]
So, here I can navigate to the /sso/login page, enter my details, and the page seems to refresh.
There's no meaningful log entries I think.
This is the entire admin log
```
admin_1      | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
admin_1      | INFO  [alembic.runtime.migration] Will assume transactional DDL.
admin_1      | [2023-06-24 14:53:33 +0000] [9] [INFO] Starting gunicorn 20.1.0
admin_1      | [2023-06-24 14:53:33 +0000] [9] [INFO] Listening at: http://0.0.0.0:80 (9)
admin_1      | [2023-06-24 14:53:33 +0000] [9] [INFO] Using worker: gthread
admin_1      | [2023-06-24 14:53:33 +0000] [10] [INFO] Booting worker with pid: 10
```
And the (related) front logs, i snipped a few GETs
```
front_1      | 10.0.0.77 - - [24/Jun/2023:14:55:51 +0000] "GET /static/app.js HTTP/1.1" 304 0 "http://10.0.0.177:8980/sso/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
front_1      | 10.0.0.77 - - [24/Jun/2023:14:55:51 +0000] "GET /static/fa-solid-900.woff2 HTTP/1.1" 304 0 "http://10.0.0.177:8980/static/vendor.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
front_1      | 10.0.0.77 - - [24/Jun/2023:14:55:56 +0000] "POST /sso/login HTTP/1.1" 302 218 "http://10.0.0.177:8980/sso/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
front_1      | 10.0.0.77 - - [24/Jun/2023:14:55:56 +0000] "GET /webmail HTTP/1.1" 301 162 "http://10.0.0.177:8980/sso/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
front_1      | 10.0.0.77 - - [24/Jun/2023:14:55:56 +0000] "GET /webmail/ HTTP/1.1" 302 138 "http://10.0.0.177:8980/sso/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
```

**Comment by nextgens** [comment]
That seems to indicate that the login has succeeded... the webmail may be broken but that's a different problem that may be related to how mailu is being proxyied.

Can you reach the /admin/ page?

**Comment by furll** [comment]
I can not, whatever I type in, I get redirected to `http://10.0.0.177:8980/sso/login`
FWIW my URL-based(?) still throws bad gateway errors.

**Comment by nextgens** [comment]
I don't understand how this could happen.

please provide your docker-compose.yml as well as what is set for the following variables in mailu.env:
```
DOMAIN
HOSTNAMES
SUBNET
TLS_FLAVOR
WEB_ADMIN
WEB_WEBMAIL
WEBROOT_REDIRECT
*_ADDRESS
```

**Comment by furll** [comment]
Sure thing. My compose; (i've now not hidden tld or changes, hope my firewall holds up!)
```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/mailu/redis:/data"
    networks:
      default:
        ipv4_address: 192.168.207.246

  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - 25:25
      - 465:465
      - 587:587
      - 110:110
      - 995:995
      - 143:143
      - 993:993
      - "10.0.0.177:8980:80"
      - "10.0.0.177:8443:443"
    volumes:
      - "/root/.acme.sh/furl.frl/:/certs"
      - "/mailu/overrides/nginx:/overrides"

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.207.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    depends_on:
      - redis

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mail:/mail"
      - "/mailu/overrides:/overrides"
    depends_on:
      - front

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/overrides:/overrides"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.207.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/var/lib/rspamd"
      - "/mailu/dkim:/dkim"
      - "/mailu/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.207.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.207.254



  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rainloop:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/webmail:/data"
    depends_on:
      - imap

  database:
    image: postgres:13
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "/mailu/data/external_psql/pgdata:/var/lib/postgresql/data/pgdata"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.207.0/24
```
The stuff:
```
DOMAIN=furl.frl
HOSTNAMES=furl.frl,boektuin.nl
SUBNET=192.168.207.0/24
TLS_FLAVOR=mail
WEB_ADMIN=/maiuai
WEB_WEBMAIL=/epost
WEBROOT_REDIRECT=/epost
```
I'm afraid I don't have a *_ADDRESS. In fact, nothing ends in ADDRESS at all.
