### ISSUE TITLE
constant connection logs (Help)

### ISSUE THREAD

**Issue by rohankm** [Mailu/Mailu#2879]
Hi im running mailu behind Nginx Proxy Manager.

im getting these logs constantly 

```
2023/07/06 02:04:45 [info] 17#17: *591 client 172.18.0.1:45668 connected to 0.0.0.0:465
2023/07/06 02:04:47 [error] 17#17: *591 172.18.0.1 could not be resolved (3: Host not found) while in resolving client address, client: 172.18.0.1, server: 0.0.0.0:465
2023/07/06 02:04:54 [info] 17#17: *591 client login failed: "Temporary authentication failure (rate-limit)" while in http auth state, client: 172.18.0.1, server: 0.0.0.0:465, login: "screenscreen0"
2023/07/06 02:05:01 [info] 17#17: *596 client 172.18.0.1:52248 connected to 0.0.0.0:465
2023/07/06 02:05:04 [error] 17#17: *596 172.18.0.1 could not be resolved (3: Host not found) while in resolving client address, client: 172.18.0.1, server: 0.0.0.0:465
2023/07/06 02:05:11 [info] 17#17: *596 client login failed: "Temporary authentication failure (rate-limit)" while in http auth state, client: 172.18.0.1, server: 0.0.0.0:465, login: "websmtptzp@123"
```

im not sure if I'm under attack

**Comment by nextgens** [comment]
Have you set REAL_IP_FROM as documented on https://mailu.io/master/configuration.html ?

**Comment by rohankm** [comment]
> Have you set REAL_IP_FROM as documented on https://mailu.io/master/configuration.html ?

Hi i have set them both

```
# Header to take the real ip from
REAL_IP_HEADER=X-Real-IP

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=172.18.0.2
```

**Comment by nextgens** [comment]
The proxy seems to be at 172.18.0.1; You should set REAL_IP_FROM=172.18.0.0/24

**Comment by rohankm** [comment]
@nextgens 
Im using NGINX PROXY MANAGER and the headers are already default configured [https://github.com/NginxProxyManager/nginx-proxy-manager/blob/2a06384a4aa597777931d38cef49cf89540392e6/docker/rootfs/etc/nginx/conf.d/include/proxy.conf#L5](as you can see here)

also I'm using the generated lets encrypt SSL as cert with mailu configuration file. also i can confirm that the certificates are working fine.

**Comment by nextgens** [comment]
So what exactly is not working? In the logs you have pasted above, "front" seems to think that all the clients are on 172.18.0.1 (presumably because REAL_IP_FROM was set incorrectly). This is why you were running into rate-limits.

Please paste a new fresh log extract and we will see if it now sees the "real" ip addresses from the clients.

**Comment by rohankm** [comment]
> So what exactly is not working? In the logs you have pasted above, "front" seems to think that all the clients are on 172.18.0.1 (presumably because REAL_IP_FROM was set incorrectly). This is why you were running into rate-limits.
> 
> Please paste a new fresh log extract and we will see if it now sees the "real" ip addresses from the clients.

Hi I think there is some configuration problem with docker... the ports are always being accessed via `172.18.0.1 ` idk why

**Comment by rohankm** [comment]
```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '3.8'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "./mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      #- "0.0.0.0:80:80"
      #- "0.0.0.0:443:443"
      - "0.0.0.0:110:110"
      - "0.0.0.0:143:143"
      - "0.0.0.0:993:993"
      - "0.0.0.0:995:995"
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 465
        published: 465
        protocol: tcp
        mode: host
      - "0.0.0.0:587:587"
    networks:
      - default
      - webmail
      - radicale
      - customproxy
    volumes:
      #- "./mailu/certs:/certs"
      - ../nginx-proxy-manager/letsencrypt/archive/npm-7/cert1.pem:/certs/cert.pem
      - ../nginx-proxy-manager/letsencrypt/archive/npm-7/privkey1.pem:/certs/key.pem
      - "./mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "./mailu/data:/data"
      - "./mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "./mailu/mail:/mail"
      - "./mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "./mailu/mailqueue:/queue"
      - "./mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2.0}
    hostname: oletools
    restart: always
    networks:
      - noinet
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - noinet
    volumes:
      - "./mailu/filter:/var/lib/rspamd"
      - "./mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "./mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  webdav:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-2.0}
    restart: always
    volumes:
      - "./mailu/dav:/data"
    networks:
      - radicale


  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "./mailu/webmail:/data"
      - "./mailu/overrides/roundcube:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  radicale:
    driver: bridge
  webmail:
    driver: bridge
  noinet:
    driver: bridge
    internal: true
  customproxy:
    external: true

```

Here is the docker compose ffile where I even tried to map the ports direct to the host.. but still ending up with the same client IP address 
and customproxy is the my reverse nginx proxy
