### ISSUE TITLE
Unable to start Mailu - "Invalid address"

### ISSUE THREAD

**Issue by TheFes** [Mailu/Mailu#2884]
### Environment

- [X] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

## Description
After downloading the config files I'm unable to start the resolver

## Replication Steps
* setup mailu from wizard
* download config files for docker-compose
* run `docker-compose up -d`

## Observed behaviour
```
ERROR: for fc7197901839_mailu-resolver-1  Cannot start service resolver: Invalid address 10.10.10.254: It does not belong to any of this network's subnets

ERROR: for resolver  Cannot start service resolver: Invalid address 10.10.10.254: It does not belong to any of this network's subnets
ERROR: Encountered errors while bringing up the project.
```

## Expected behaviour
I would expect the docker container to start

## docker compose config
Not my own internal network uses `192.168.2.0/24`
I've used `10.10.10.0/24` for the subnet for the docker-compose network.

```yaml
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/docker-compose/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 10.10.10.254

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "192.168.2.17:80:80"
      - "192.168.2.17:443:443"
      - "192.168.2.17:25:25"
      - "192.168.2.17:465:465"
      - "192.168.2.17:587:587"
      - "192.168.2.17:110:110"
      - "192.168.2.17:995:995"
      - "192.168.2.17:143:143"
      - "192.168.2.17:993:993"
    networks:
      - default
    volumes:
      - "/docker-compose/mailu/certs:/certs"
      - "/docker-compose/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 10.10.10.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 10.10.10.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "/docker-compose/mailu/data:/data"
      - "/docker-compose/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 10.10.10.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "/docker-compose/mailu/mail:/mail"
      - "/docker-compose/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 10.10.10.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "/docker-compose/mailu/mailqueue:/queue"
      - "/docker-compose/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 10.10.10.254

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2.0}
    hostname: oletools
    restart: always
    networks:
      - noinet
    depends_on:
      - resolver
    dns:
      - 10.10.10.254

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - noinet
    volumes:
      - "/docker-compose/mailu/filter:/var/lib/rspamd"
      - "/docker-compose/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 10.10.10.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "/docker-compose/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 10.10.10.254



  # Webmail

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
  noinet:
    driver: bridge
    internal: true
```
