### ISSUE TITLE
Setup should double check that it doesn't produce a broken config even if browsers don't send it the data it requires

### ISSUE THREAD

**Issue by phen0** [Mailu/Mailu#2890]
### Environment

- [x ] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

## Description

My setup mailu with TLS_FLAVOUR mail. Mailu is setup to listen on 8080 & 8443. My reverse nginx proxy listening on 80/443 is forwarding all requests to mail on port :8080. Something's weird with the mailu front nginx server. All requests to the mail domain with / for webmail end up in a loop of 302 but /admin is working fine but no way to login to webmail. Even if I connect directly to the mailu IP and port it doesn't work at all.
## Replication Steps

Setup a mailu server with the docker-compose and mailu.env file enclosed.
docker-compose.yml
```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/opt/docker/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    environment:
      - LETSENCRYPT_RESTART_CONTAINER=true
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "10.0.55.85:8080:80"
      - "10.0.55.85:8443:443"
      - "10.0.55.85:25:25"
      - "10.0.55.85:465:465"
      - "10.0.55.85:587:587"
      - "10.0.55.85:110:110"
      - "10.0.55.85:995:995"
      - "10.0.55.85:143:143"
      - "10.0.55.85:993:993"
    networks:
      - default
      - webmail
    volumes:
      - "/opt/docker/mailu/certs:/certs"
      - "/opt/docker/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-master}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "/opt/docker/mailu/data:/data"
      - "/opt/docker/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "/opt/docker/mailu/mail:/mail"
      - "/opt/docker/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "/opt/docker/mailu/mailqueue:/queue"
      - "/opt/docker/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-master}
    hostname: oletools
    restart: always
    networks:
      - noinet
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-master}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - noinet
    volumes:
      - "/opt/docker/mailu/filter:/var/lib/rspamd"
      - "/opt/docker/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/docker/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/docker/mailu/webmail:/data"
      - "/opt/docker/mailu/overrides/roundcube:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  webmail:
    driver: bridge
  noinet:
    driver: bridge
    internal: true
```

mailu.env
```
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=XXXXXXXXXXXXXXXX

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.168.203.0/24

# Main mail domain
DOMAIN=example.com

# Hostnames for this server, separated with commas
HOSTNAMES= mail.example.com

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=mail

# Authentication rate limit per IP (per /24 on ipv4 and /48 on ipv6)
AUTH_RATELIMIT_IP=5/hour

# Authentication rate limit per user (regardless of the source-IP)
AUTH_RATELIMIT_USER=50/day

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=False

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, snappymail, none)
WEBMAIL=roundcube

# Expose the API interface (value: true, false)
API=false

# Dav server implementation (value: radicale, none)
WEBDAV=none

# Antivirus solution (value: clamav, none)
ANTIVIRUS=none

# Scan Macros solution (value: true, false)
SCAN_MACROS=false

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Message rate limit (per user)
MESSAGE_RATELIMIT=200/day

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Enable fetchmail
FETCHMAIL_ENABLED=False

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: gz, bz2, zstd)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

# IMAP full-text search is enabled by default. Set the following variable to off in order to disable the feature.
# FULL_TEXT_SEARCH=off

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/

# Path to the API interface if enabled
WEB_API=

# Website name
SITENAME=Capere Mail

# Linked Website URL
WEBSITE=https://mail.example.com


###################################
# Advanced settings
###################################

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Number of rounds used by the password hashing scheme
CREDENTIAL_ROUNDS=12

# Header to take the real ip from
REAL_IP_HEADER=X-Real-IP

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=0.0.0.0/0, ::0

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=yes

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

# Timezone for the Mailu containers. See this link for all possible values https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TZ=Europe/Berlin

# Default spam threshold used for new users
DEFAULT_SPAM_THRESHOLD=80

# API token required for authenticating to the RESTful API.
# This is a mandatory setting for using the RESTful API.
API_TOKEN=

# SESSION COOKIE DISABLED TO AVOID ENDLESS 302/REDIRECTS
SESSION_COOKIE_SECURE=False
``` 
## Observed behaviour

Login to https://mail.example.com/ ending up in a HTTP 302 loop
## Expected behaviour

Webmail should be accessible and open once requested via /
## Logs

```
- - mail.example.com - 10.0.55.1 forwarded for - - - [28/Jul/2023:14:17:20 +0000]  "POST /sso/login?url=/ HTTP/2.0" 302 231 "https://mail.example.com/sso/login?url=/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
- - mail.example.com - 10.0.55.1 forwarded for - - - [28/Jul/2023:14:17:20 +0000]  "GET / HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
- - mail.example.com - 10.0.55.1 forwarded for - - - [28/Jul/2023:14:17:22 +0000]  "GET /sso.php HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
- - mail.example.com - 10.0.55.1 forwarded for - - - [28/Jul/2023:14:17:23 +0000]  "GET /sso.php HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
- - mail.example.com - 10.0.55.1 forwarded for - - - [28/Jul/2023:14:17:24 +0000]  "GET /sso.php HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
- - mail.example.com - 10.0.55.1 forwarded for - - - [28/Jul/2023:14:17:25 +0000]  "GET /sso.php HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
- - mail.example.com - 10.0.55.1 forwarded for - - - [28/Jul/2023:14:17:26 +0000]  "GET /sso.php HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
- - mail.example.com - 10.0.55.1 forwarded for - - - [28/Jul/2023:14:17:27 +0000]  "GET /sso.php HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
- - mail.example.com - 10.0.55.1 forwarded for - - - [28/Jul/2023:14:17:28 +0000]  "GET /sso.php HTTP/2.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"

```

**Comment by phen0** [comment]
I guess I found the issue. nginx.conf on front server is missing all mail ports except of 25.
There's only one port configured which is smtp.

**Comment by phen0** [comment]
I've tried a fresh clean install of version 2.0 with letsencrypt TLS_FLAVOR but no way at all to get this working.
Can't login to the webmail....what's wrong with it?

**Comment by nextgens** [comment]
``WEB_WEBMAIL=/`` and ``WEBROOT_REDIRECT=/`` won't work.


``WEB_WEBMAIL=/webmail`` and ``WEBROOT_REDIRECT=/webmail``

**OR**

``WEB_WEBMAIL=/`` and ``#WEBROOT_REDIRECT=``

**Comment by nextgens** [comment]
Oh and by the way, ``REAL_IP_FROM=0.0.0.0/0, ::0`` is a really bad idea. Find out which private ip range is being used by the proxy and just whitelist that.

**Comment by phen0** [comment]
Thanks for your feedback.
Of course setting REAL_IP_FROM=0.0.0.0/0, ::0 was only for testing purposes.

But what's misleading if this config won't work:
```
WEB_WEBMAIL=/ and WEBROOT_REDIRECT=/ won't work.
``` 

Why does the default config by mailu config generator suggest it?
```
###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=

# Path to the API interface if enabled
WEB_API=

# Website name
SITENAME=Mailu

# Linked Website URL
WEBSITE=https://mailu.io
``` 

Will test your suggestion later on.

**Comment by nextgens** [comment]
The default config will suggest ``WEB_WEBMAIL=/webmail`` if you have enabled a webmail

**Comment by phen0** [comment]
Well you're wrong! Try the config generator by yourself. With Roundcube selected you get this config:
```
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=HZS3AJM8ND71CN2U

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.168.203.0/24

# Main mail domain
DOMAIN=mailu.io

# Hostnames for this server, separated with comas
HOSTNAMES=mail.mailu.io

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=letsencrypt

# Authentication rate limit per IP (per /24 on ipv4 and /48 on ipv6)
AUTH_RATELIMIT_IP=5/hour

# Authentication rate limit per user (regardless of the source-IP)
AUTH_RATELIMIT_USER=50/day

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=False

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, snappymail, none)
WEBMAIL=roundcube

# Expose the API interface (value: true, false)
API=false

# Dav server implementation (value: radicale, none)
WEBDAV=none

# Antivirus solution (value: clamav, none)
ANTIVIRUS=none

# Scan Macros solution (value: true, false)
SCAN_MACROS=true

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Message rate limit (per user)
MESSAGE_RATELIMIT=200/day

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Enable fetchmail
FETCHMAIL_ENABLED=False

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: gz, bz2, zstd)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

# IMAP full-text search is enabled by default. Set the following variable to off in order to disable the feature.
# FULL_TEXT_SEARCH=off

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/

# Path to the API interface if enabled
WEB_API=

# Website name
SITENAME=Mailu

# Linked Website URL
WEBSITE=https://mailu.io



###################################
# Advanced settings
###################################

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Number of rounds used by the password hashing scheme
CREDENTIAL_ROUNDS=12

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

# Timezone for the Mailu containers. See this link for all possible values https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TZ=Etc/UTC

# Default spam threshold used for new users
DEFAULT_SPAM_THRESHOLD=80

# API token required for authenticating to the RESTful API.
# This is a mandatory setting for using the RESTful API.
API_TOKEN=
```

**Comment by nextgens** [comment]
I just did and this is not what I have, see:
https://setup.mailu.io/2.0/setup/6a42d007-b379-4098-9baa-502b62cc8d3a

**Comment by phen0** [comment]
Well your setup generator might be buggy!
If you open the generator you get this.
<img width="1232" alt="Screenshot 2023-08-14 at 12 33 42" src="https://github.com/Mailu/Mailu/assets/12190248/54e60042-cc6b-4891-a110-7d1fa26f3293">

And this is the config generated on the next page:
https://setup.mailu.io/2.0/file/6a42d007-b379-4098-9baa-502b62cc8d3a/mailu.env

**Comment by nextgens** [comment]
This is a browser issue. Which browser are you using? Any extension enabled?

Here is how it looks with a working browser:
![image](https://github.com/Mailu/Mailu/assets/77500/12f46373-2bdb-452e-84c3-5db68114259b)

**Comment by phen0** [comment]
Could be a browser issue. I've tested it on Safari v16.5.2 and Chrome v115.0.5790.170
Alright don't wanted to offend you. I'll test again and let you know the outcome :)

**Comment by phen0** [comment]
So finally I could test it again. This time I installed it on a synology but you were right. The redirect and webmail path caused the issue. Now that I'm using these settings in mailu.env it works like a charm.
So it seems to be an issue that the browser somehow doesn't recognize the right webmail settings hence generating a wrong config.

```
###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/webmail

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/webmail
``` 

This means I'll go with mailu...already thought about switching to another mailserver but now I'm happy.

**Comment by mamiu** [comment]
Thanks to @ben221199! [His workaround](https://github.com/Mailu/Mailu/issues/2886#issuecomment-1661209534) fixed the issue for me:

```bash
cd /mailu
docker compose down && docker compose up -d
```

**Comment by ben221199** [comment]
No problem. I still have the issue, but it is solved after that command and then Mailu works again for some days/weeks.

**Comment by mamiu** [comment]
@ben221199 Oh ok... so I'll have to do this regularly (until the bug's fixed)?

**Comment by ben221199** [comment]
I guess. I don't have another solution at the moment.

**Comment by mamiu** [comment]
@ben221199 Ok, thanks for letting me know!

**Comment by nextgens** [comment]
@phen0 Have you found why your browsers are failing with the page? Do you see anything if you open the console/error log?

Could it be that you block access to [https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js](view-source:https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js) ?

**Comment by ben221199** [comment]
In my case it seemed that Dovecot got a SIGKILL. After that the redirect loop started happening.

**Comment by nextgens** [comment]
I can't reproduce this with chrome here. Can you post a screenshot of the "network" tab in the dev tools please?

I suspect that "something" is preventing jquery from loading. DNS blocking of google's domain?

**Comment by phen0** [comment]
I'm using Chrome Version 116.0.5845.110 (Official Build) (arm64). This is the screenshot

<img width="2003" alt="Screenshot 2023-08-29 at 10 40 03" src="https://github.com/Mailu/Mailu/assets/12190248/25f25fb0-e644-4b5e-9f9d-fcb754b9436c">

**Comment by mamiu** [comment]
Sorry guys, I hope I didn't cause confusion... I think here are two issues discussed in this thread. One is the Mailu setup tool and the other one is the redirect loop when trying to login to the webmail UI. I was talking about the latter one. As long as I'm logged out all URLs work fine. But as soon as I logged into the webmail (https://mail.mydomain.com/sso/login?url=/webmail/sso.php) I was stuck in the redirect loop. And this was browser independent (I could even replicate this issue with cURL). There were no blocked resources or anything like that (yes, I checked the network tab in the Chrome DevTools).

**Comment by phen0** [comment]
Hi @mamiu,
no offence but could you please share your mailu.env? I got the same endless redirect loop and solved it.
So please share your setup. Btw are you using an additional nginx as reverse proxy?

**Comment by mamiu** [comment]
@phen0 Sure, I've shared it [here](https://github.com/Mailu/Mailu/issues/2886#issuecomment-1697982131).

**Comment by Diman0** [comment]
@nextgens I can replicate this issue. When JavaScript is disabled, then when selecting the webmail, the text box for WEB_WEBMAIL is not displayed. Obviously it is not supported when JavaScript is disabled. 

I will check If I can enhance setup with a check if JavaScript is enabled.

**Comment by phen0** [comment]
Well in my Browser (Safari or Chrome) Javascript is enabled...but I got this issue. I've upgraded now to the most recent version 2 release. Let's see if the issue still persists.

**Comment by Diman0** [comment]
You can the PR by creating an .env file with the contents:
```
# Current versions
#DEVELOPMENT=local
DEVELOPMENT=pr-3025
#DOCKER_ORG=mailu
DOCKER_ORG=ghcr.io/mailu
```

and docker-compose.yml file with contents:
```
version: '3.6'

services:
  redis:
    image: redis:alpine
    restart: always

  development:
    image: ${DOCKER_ORG}/setup:${DEVELOPMENT}
    ports:
      - "0.0.0.0:1234:80"
    env_file: .env
    environment:
      stable_version: ${DEVELOPMENT}
      this_version: ${DEVELOPMENT}
      VERSIONS: ${DEVELOPMENT}
    depends_on:
      - redis
    restart: always

```

Access the setup site via `http://hostname:1234/pr-3025`
Please note that in the  download statements with WGET, you must change `https` to `http`
