### ISSUE TITLE
Mailu doesn't work when IPv6 is force-disabled on the host

### ISSUE THREAD

**Issue by phen0** [Mailu/Mailu#2913]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

I wanted to start mailu on my raspberry with Debian 11 but the imap service refuses to start. There are various containers running already on my pi and I've also tested docker-mailserver which is working fine....so no clue why it's failing here? Is it an issue in version 2.0?

## Replication Steps

My mailu.env:
```
SECRET_KEY=XXXXXXXX
SUBNET=192.168.203.0/24
DOMAIN=exmple.com
HOSTNAMES=mail.exmple.com
POSTMASTER=admin
TLS_FLAVOR=mail
AUTH_RATELIMIT_IP=5/hour
AUTH_RATELIMIT_USER=50/day
DISABLE_STATISTICS=False
ADMIN=true
WEBMAIL=roundcube
API=false
WEBDAV=none
ANTIVIRUS=none
SCAN_MACROS=true
MESSAGE_SIZE_LIMIT=50000000
MESSAGE_RATELIMIT=200/day
FETCHMAIL_ENABLED=False
FETCHMAIL_DELAY=600
RECIPIENT_DELIMITER=+
DMARC_RUA=admin
DMARC_RUF=admin
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!
WEBROOT_REDIRECT=/webmail
WEB_ADMIN=/admin
WEB_WEBMAIL=/webmail
SITENAME=Company Mail
WEBSITE=https://www.exmple.com
COMPOSE_PROJECT_NAME=mailu
CREDENTIAL_ROUNDS=12
REAL_IP_HEADER=X-Real-IP
REAL_IP_FROM=10.0.55.85
LOG_LEVEL=WARNING
TZ=Europe/Berlin
DEFAULT_SPAM_THRESHOLD=80
LOGO_URL=https://www.example.com/logo.png
SESSION_COOKIE_SECURE=false
INITIAL_ADMIN_ACCOUNT=admin
INITIAL_ADMIN_DOMAIN=example.com
INITIAL_ADMIN_5txsKxQ9=XXXXXXXX
INITIAL_ADMIN_MODE=ifmissing
``` 

Here's my docker-compose:
```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/volume1/docker/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "10.0.55.85:5025:25"    ### SMTP UNSECURE ###
      - "10.0.55.85:5080:80"  ### HTTP          ###
      - "10.0.55.85:5443:443" ### HTTPS         ###
      - "10.0.55.85:5110:110"  # pop3
      - "10.0.55.85:5143:143"  # imap
      - "10.0.55.85:5465:465"  # imap ssl
      - "10.0.55.85:5587:587"  ### SMTP SSL      ###
      - "10.0.55.85:5993:993"  ### IMAP SSL      ###
      - "10.0.55.85:5995:995"  # pop3 ssl
    networks:
      - default
      - webmail
    volumes:
      - "/volume1/docker/mailu/certs:/certs"
      - "/volume1/docker/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "/volume1/docker/mailu/data:/data"
      - "/volume1/docker/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "/volume1/docker/mailu/mail:/mail"
      - "/volume1/docker/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "/volume1/docker/mailu/mailqueue:/queue"
      - "/volume1/docker/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2.0}
    hostname: oletools
    restart: always
    networks:
      - noinet
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - noinet
    volumes:
      - "/volume1/docker/mailu/filter:/var/lib/rspamd"
      - "/volume1/docker/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - resolver
    dns:
      - 192.168.203.254

  # Optional services



  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "/volume1/docker/mailu/webmail:/data"
      - "/volume1/docker/mailu/overrides/roundcube:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  webmail:
    driver: bridge
  noinet:
    driver: bridge
    internal: true
``` 
## Logs
<!--
Often it is very useful to include log fragments of the involved component.
You can get the logs via `docker logs <container name> --tail 1000`.
For example for the admin container: `docker logs mailu_admin_1 --tail 1000`
or using docker compose `docker compose -f /mailu/docker-compose.yml logs --tail 1000 admin`

If you can find the relevant section, please share only the parts that seem relevant. If you have any logs, please enclose them in code tags, like so:

```
WARNING:root:Disabling hardened-malloc on this CPU
Error: socket() failed: Address family not supported by protocol
Aug 19 02:09:11 master: Error: socket() failed: Invalid argument
Error: service(managesieve-login): listen(::, 4190) failed: Address family not supported by protocol
Aug 19 02:09:11 master: Error: service(managesieve-login): listen(::, 4190) failed: Address family not supported by protocol
Error: socket() failed: Address family not supported by protocol
Aug 19 02:09:11 master: Error: socket() failed: Invalid argument
Error: service(pop3-login): listen(::, 110) failed: Address family not supported by protocol
Aug 19 02:09:11 master: Error: service(pop3-login): listen(::, 110) failed: Address family not supported by protocol
Error: socket() failed: Address family not supported by protocol
Aug 19 02:09:11 master: Error: socket() failed: Invalid argument
Error: service(pop3-login): listen(::, 995) failed: Address family not supported by protocol
Aug 19 02:09:11 master: Error: service(pop3-login): listen(::, 995) failed: Address family not supported by protocol
Error: socket() failed: Address family not supported by protocol
Aug 19 02:09:11 master: Error: socket() failed: Invalid argument
Error: service(lmtp): listen(::, 2525) failed: Address family not supported by protocol
Aug 19 02:09:11 master: Error: service(lmtp): listen(::, 2525) failed: Address family not supported by protocol
Error: socket() failed: Address family not supported by protocol
Aug 19 02:09:11 master: Error: socket() failed: Invalid argument
Error: service(imap-login): listen(::, 143) failed: Address family not supported by protocol
Aug 19 02:09:11 master: Error: service(imap-login): listen(::, 143) failed: Address family not supported by protocol
Error: socket() failed: Address family not supported by protocol
Aug 19 02:09:11 master: Error: socket() failed: Invalid argument
Error: service(imap-login): listen(::, 993) failed: Address family not supported by protocol
Aug 19 02:09:11 master: Error: service(imap-login): listen(::, 993) failed: Address family not supported by protocol
Fatal: Failed to start listeners
Aug 19 02:09:11 master: Fatal: Failed to start listeners```
-->
