### ISSUE TITLE
IMAP can't load SSL certificate 

### ISSUE THREAD

**Issue by phen0** [Mailu/Mailu#2915]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

I'm using mailu more or less with default setup. TLS_FLAVOR is set to mail but the IMAP service is complaining about the certificate. Although I wonder where it comes from cause certs directory is not available as volume for imap.
## Replication Steps

docker-compose snippet:
```
  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "/opt/docker/mail/mail:/mail"
      - "/opt/docker/mail/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254
``` 

## Observed behaviour

I had a check in the container and I noticed the following settings in /etc/dovecot/conf.d/10-ssl.conf:
```
ssl_cert = </etc/ssl/dovecot/server.pem
ssl_key = </etc/ssl/dovecot/server.key
``` 
These files do exist and they aren't empty.

## Expected behaviour

I would expect that SSL for IMAP is been initialised properly.
