### ISSUE TITLE
Sender IP is different then binding IP

### ISSUE THREAD

**Issue by mfide** [Mailu/Mailu#2921]
Hello,

I just ordered a dedicated server, installed docker and started playing with `mailu `installation through `docker-composer`.
My server has one ethernet interface (enp2s0) but has 5 static public IPs.

Lets call these public IPs as
```
1.1.1.0  -> configured for bind9
1.1.1.1
1.1.1.2
1.1.1.3  -> configured for mailu
1.1.1.4
```

I have configured `1.1.1.0` as a name server and installed `bind9`.
I did all configuration in the `bind9` and assigned `1.1.1.3` as my mail server which will be served by `mailu`.

I used `https://setup.mailu.io/2.0/` to generate `yml` file and configured IPv4 listen address to be `1.1.1.3`
MX, SPF, DKIM all are configured. Server is up and I could receive email from gmail, perrfect.

But when I try to send an email to `gmail`, It returned with an undelivered message saying that basically "sender IP 1.1.1.0 does not belong to my email domain".

The problem is that I configured `mailu` to send and receive emails from `1.1.1.3` but obviously it receives from `1.1.1.3` but try to send from `1.1.1.0` which is wrong in my case. 

Any idea how to fix yml file generated by setup.mailu.io to send emails using IPv4 listen address configured?

Here is yml:
```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/home/tester/docker-mailu/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "1.1.1.3:80:80"
      - "1.1.1.3:443:443"
      - "1.1.1.3:25:25"
      - "1.1.1.3:465:465"
      - "1.1.1.3:587:587"
      - "1.1.1.3:110:110"
      - "1.1.1.3:995:995"
      - "1.1.1.3:143:143"
      - "1.1.1.3:993:993"
    networks:
      - default
      - webmail
      - radicale
    volumes:
      - "/home/tester/docker-mailu/mailu/certs:/certs"
      - "/home/tester/docker-mailu/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "/home/tester/docker-mailu/mailu/data:/data"
      - "/home/tester/docker-mailu/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "/home/tester/docker-mailu/mailu/mail:/mail"
      - "/home/tester/docker-mailu/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "/home/tester/docker-mailu/mailu/mailqueue:/queue"
      - "/home/tester/docker-mailu/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2.0}
    hostname: oletools
    restart: always
    networks:
      - noinet
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - noinet
    volumes:
      - "/home/tester/docker-mailu/mailu/filter:/var/lib/rspamd"
      - "/home/tester/docker-mailu/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/tester/docker-mailu/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  webdav:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-2.0}
    restart: always
    volumes:
      - "/home/tester/docker-mailu/mailu/dav:/data"
    networks:
      - radicale

  fetchmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/tester/docker-mailu/mailu/data/fetchmail:/data"
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - 192.168.203.254

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
    restart: always
    env_file: mailu.env
    volumes:
      - "/home/tester/docker-mailu/mailu/webmail:/data"
      - "/home/tester/docker-mailu/mailu/overrides/roundcube:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  radicale:
    driver: bridge
  webmail:
    driver: bridge
  noinet:
    driver: bridge
    internal: true
```

Thank you.

**Comment by mfide** [comment]
Ok I solved the problem by referencing that: [https://forums.docker.com/t/ping-from-specific-host-ip/137117](https://forums.docker.com/t/ping-from-specific-host-ip/137117)

Simply changed the network part of the yml file at the end as:

```
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
    driver_opts:
      com.docker.network.host_ipv4: 1.1.1.3
  radicale:
    driver: bridge
    driver_opts:
      com.docker.network.host_ipv4: 1.1.1.3
  webmail:
    driver: bridge
    driver_opts:
      com.docker.network.host_ipv4: 1.1.1.3
  noinet:
    driver: bridge
    internal: true
```

Then I need to execute docker-compose down and up.

Verification is easy, attach to shell of smtp container and  type:
`curl https://www.showmyip.com | grep '<h2 id="ipv4">'`

Reports outgoing IP as `1.1.1.3` as expected instead of `1.1.1.0`
