### ISSUE TITLE
Implement a new TLS flavor for people using an HTTP reverse proxy

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#306]
Because most reverse proxy will only profify Web, and because many people already have a proxy setup for ports 80 and 443, it would be interesting to have a TLS flavor, namely ``mail`` that does TLS.. for mail only.

It would not, in fact be incompatible with letsencrypt as long as the reverse proxy forwards requests to the acme endpoint, but it would mean that the front reverse proxy does not already handle letsencrypt, therefore probably has no TLS itself, which we absolutely want to avoid.

Therefore, the ``mail`` TLS flavor will disable TLS for email, reject requests that do not have proxy headers (as a foolguard, not an actual security measure) and not run letsencrypt.

**Comment by kaiyou** [comment]
This was just added in master.

**Comment by ltouro** [comment]
Also, the env file should be updated with the new option. Will send a PR against master.

```
# Choose how secure connections will behave (value: letsencrypt, cert, notls)
TLS_FLAVOR=cert
```

```
# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail)
TLS_FLAVOR=cert
```

**Comment by morriswinkler** [comment]
Where is this implemented? That setting is nowhere evaluated in code.

**Comment by ltouro** [comment]
Here, the certs are set according to the specified option: https://github.com/Mailu/Mailu/blob/master/core/nginx/config.py

Here, the certs are generated with openssl / letsencrypt in respect to the specified option:
https://github.com/Mailu/Mailu/blob/master/core/nginx/start.py

Here, the NGINX is configured according to the specified option:
https://github.com/Mailu/Mailu/blob/master/core/nginx/conf/nginx.conf

Can't see how the setting is not evaluated.

**Comment by Harti** [comment]
@kaiyou Could you please shed some light onto this, once and for all?

Documentation is _very_ sparse on this matter. I understand if it is not your specialty, but we do need to know how the different TLS flavors work. 

Say, I'm using https://github.com/SteveLTN/https-portal. There would be no way on earth for me to figure out how to apply the working solutions in https://github.com/Mailu/Mailu/issues/460 for my setup. 

I could map the certs generated by https-portal onto my HDD, and map these to the front container's cert folder. But how? And how do the certs need to be called?

In another issue (https://github.com/Mailu/Mailu/issues/535#issuecomment-409696463) you commented that one could use the `notls` flavor "and create your own endpoints". Excuse me, what does this mean? What do I have to create? What ports need to be mapped? What do you mean by endpoint, specifically?

Because I don't know better, as a workaround, I just now stopped my complete reverse proxy, re-added ports 80 and 443 to the front container, restarted the front container (so that it can obtain its certificate), and restarted my reverse proxy.

I would very much prefer to use https-portal's auto-renew. I do already auto-create a certificate for that domain which lets me access webmail. I'm so confused...

**Comment by ltouro** [comment]
@Harti Regarding how to use your own certificate:

```
I could map the certs generated by https-portal onto my HDD, and map these to the front container's cert folder. But how? And how do the certs need to be called?
```

I copy the externally auto-generated certs to the designated folder, used by mailu. I set this on a CRON job:
```
cp /data/letsencrypt/certs/mydomain.tld/fullchain.pem /data/mailu/certs/cert.pem'
```
```
cp /data/letsencrypt/certs/mydomain.tld/key.pem /data/mailu/certs/key.pem'
```

.env file
```
# Set this to the path where Mailu data and configuration is stored
ROOT=/data/mailu
...
DOMAIN=mydomain.tld
...
TLS_FLAVOR=mail
```
docker-compose.yml
```
front:
    image: mailu/nginx:$VERSION
    restart: always
    env_file: .env
    environment:
      VIRTUAL_HOST: mydomain.tld <-- used by the proxy to map a domain to the container
      LETSENCRYPT_HOST: mydomain.tld <-- used by the proxy to generate certs
    ports:
    - "$BIND_ADDRESS4:110:110"
    - "$BIND_ADDRESS4:143:143"
    - "$BIND_ADDRESS4:993:993"
    - "$BIND_ADDRESS4:995:995"
    - "$BIND_ADDRESS4:25:25"
    - "$BIND_ADDRESS4:465:465"
    - "$BIND_ADDRESS4:587:587"
    volumes:
      - "$ROOT/certs:/certs"
```

Note that I don't use ports 80 or 443 for the front container. A reverse proxy handles that.

Also, note that I map the certs folder volume to the container, maybe that is what u missing.
