### ISSUE TITLE
please add auto update with watchtower

### ISSUE THREAD

**Issue by vahidalvandi** [Mailu/Mailu#3265]
It is very important that new updates are received daily and automatically

```
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
```
