### ISSUE TITLE
Resolver stops working with Docker 26.1.3

### ISSUE THREAD

**Issue by jeehoonkang** [Mailu/Mailu#3274]
## Environment & Version

- Docker: 26.1.3, build b72abbb
- Docker Compose: v2.27.0
- Mailu: 2.0.43
- Platform: Ubuntu 22.04.4

## Description

The resolver container stops working after upgrading Docker. (It worked fine.) The symptom is similar to this issue: https://github.com/Mailu/Mailu/issues/2868 Though `docker compose exec front ping 1.1.1.1` worked for me (but not `docker compose exec front ping google.com`).

I temporarily fixed the issue by changing DNS from `172.31.203.254` to `1.1.1.1` for all containers in docker-compose.yml, but I wish to use mailu's resolver again.

## Replication Steps

Download a setup from setup.mailu.io and run `docker compose up -d`.

## Observed behaviour

The admin container keeps reporting DNS resolution error, eventually transitioning from "starting" to "unhealthy" status. As a result, the web UI doesn't work.

## Expected behaviour

The admin container should succeed in resolving DNS from the resolver container without errors.

## Logs

```
$ docker compose logs admin
[...]
admin-1  | CRITICAL:root:Your DNS resolver at 127.0.0.11 is not working (All nameservers failed to answer the query example.org. IN A: Server 1
27.0.0.11 UDP port 53 answered SERVFAIL). Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical
-your-dns-resolver-isn-t-doing-dnssec-validation
[...repeated...]
```

```
$ docker exec -it resolver bash
[...switching to resolver...]
# nslookup example.org localhost
;; communications error to ::1#53: connection refused
;; communications error to ::1#53: connection refused
;; communications error to ::1#53: connection refused
Server:         localhost
Address:        127.0.0.1#53

** server can't find example.org: SERVFAIL
```

**Comment by nextgens** [comment]
What's the output of ``docker compose logs resolver``?

**Comment by jeehoonkang** [comment]
@nextgens it's similar with #2868:

```
[1687623007] unbound[1:0] notice: init module 0: validator
[1687623007] unbound[1:0] notice: init module 1: iterator
[1687623007] unbound[1:0] info: start of service (unbound 1.17.1).
```

**Comment by nextgens** [comment]
Are you using netplan? Do you have working internet connectivity in resolver?

What's the output of ``host example.com 192.168.203.254`` ?

**Comment by glitterlip** [comment]
I am having the same issue here.
Use unbound without netplan.

It works fine until I decided to change the domain. I tried destroy containers and reconfig and rebuild still the same error in admin container 

admin container log

```
admin-1  | CRITICAL:root:Your DNS resolver at 127.0.0.11 is not working (The resolution lifetime expired after 11.601 seconds: Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.). Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation
```


host resover
```
resolvectl status | grep DNSSEC
      DNSSEC setting: allow-downgrade
    DNSSEC supported: yes
          DNSSEC NTA: 10.in-addr.arpa
      DNSSEC setting: allow-downgrade
```


logs in front container exec ping
```
docker compose exec front ping example.com
WARN[0000] /root/mailu/docker-compose.yml: `version` is obsolete
PING example.com (93.184.215.14): 56 data bytes
64 bytes from 93.184.215.14: seq=0 ttl=51 time=159.437 ms
64 bytes from 93.184.215.14: seq=1 ttl=51 time=159.393 ms
64 bytes from 93.184.215.14: seq=2 ttl=51 time=159.330 ms
64 bytes from 93.184.215.14: seq=3 ttl=51 time=159.168 ms
64 bytes from 93.184.215.14: seq=4 ttl=51 time=159.106 ms
```

exec host command in resolver container
```
host example.com 192.168.203.254
Using domain server:
Name: 192.168.203.254
Address: 192.168.203.254#53
Aliases:

example.com has address 93.184.215.14
example.com has IPv6 address 2606:2800:21f:cb07:6820:80da:af6b:8b2c
example.com mail is handled by 0 .
```
logs in resolver 
```
resolver-1  | [1717317750] unbound[1:0] notice: init module 0: validator
resolver-1  | [1717317750] unbound[1:0] notice: init module 1: iterator
resolver-1  | [1717317750] unbound[1:0] info: start of service (unbound 1.20.0).
resolver-1  | [1717317751] unbound[1:0] info: generate keytag query _ta-4f66. NULL IN
resolver-1  | [1717319047] unbound[1:0] info: service stopped (unbound 1.20.0).
resolver-1  | [1717319047] unbound[1:0] info: server stats for thread 0: 410 queries, 101 answers from cache, 309 recursions, 0 prefetch, 0 rejected by ip ratelimiting
resolver-1  | [1717319047] unbound[1:0] info: server stats for thread 0: requestlist max 7 avg 2.64725 exceeded 198 jostled 0
resolver-1  | [1717319047] unbound[1:0] info: average recursion processing time 0.661231 sec
resolver-1   | [1717319047] unbound[1:0] info: histogram of recursion processing times
```
currently `/admin`,`/webmail` returns 502 

in front container
```
curl http://localhost/webmail/ -i
HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Sun, 02 Jun 2024 09:46:11 GMT
Content-Type: text/html
Content-Length: 170
Connection: close

<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

log shows connection refused

```
front-1  | 2024/06/02 09:46:11 [error] 17#17: *48 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /webmail/ HTTP/1.1", subrequest: "/internal/auth/user", upstream: "http://192.168.203.5:8080/internal/auth/user", host: "localhost"
front-1  | 2024/06/02 09:46:11 [error] 17#17: *48 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /webmail/ HTTP/1.1", host: "localhost"
front-1  | 127.0.0.1 - - [02/Jun/2024:09:46:11 +0000] "GET /webmail/ HTTP/1.1" 500 170 "-" "curl/8.5.0"
```
here are containers 
```
docker ps
CONTAINER ID   IMAGE                         COMMAND                  CREATED             STATUS                      PORTS                                                                                                                                                                                                                                                                           NAMES
2d6ca5d92d91   ghcr.io/mailu/fetchmail:2.0   "/fetchmail.py"          About an hour ago   Up 17 minutes (healthy)                                                                                                                                                                                                                                                                                     mailu-fetchmail-1
7dfeac40b955   ghcr.io/mailu/webmail:2.0     "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (healthy)                                                                                                                                                                                                                                                                                     mailu-webmail-1
7e351fa47236   ghcr.io/mailu/dovecot:2.0     "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (healthy)     110/tcp, 143/tcp, 993/tcp, 2525/tcp, 4190/tcp                                                                                                                                                                                                                                   mailu-imap-1
e21a60b12f58   ghcr.io/mailu/postfix:2.0     "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (healthy)                                                                                                                                                                                                                                                                                     mailu-smtp-1
1fce0b8aa877   ghcr.io/mailu/rspamd:2.0      "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (unhealthy)                                                                                                                                                                                                                                                                                   mailu-antispam-1
be501512694e   ghcr.io/mailu/admin:2.0       "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (unhealthy)                                                                                                                                                                                                                                                                                   mailu-admin-1
25b440111eb2   ghcr.io/mailu/nginx:2.0       "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (healthy)     156.238.240.200:25->25/tcp, 156.238.240.200:110->110/tcp, 156.238.240.200:143->143/tcp, 156.238.240.200:465->465/tcp, 156.238.240.200:587->587/tcp, 156.238.240.200:993->993/tcp, 156.238.240.200:995->995/tcp, 156.238.240.200:10080->80/tcp, 156.238.240.200:10443->443/tcp   mailu-front-1
711184d8dc97   redis:alpine                  "docker-entrypoint.s…"   About an hour ago   Up 17 minutes               6379/tcp                                                                                                                                                                                                                                                                        mailu-redis-1
bdc97ffbbb23   ghcr.io/mailu/oletools:2.0    "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (healthy)                                                                                                                                                                                                                                                                                     mailu-oletools-1
f11df031a910   ghcr.io/mailu/unbound:2.0     "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (healthy)                                                                                                                                                                                                                                                                                     mailu-resolver-1
```

`f11` is resolver 
```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' f11
192.168.203.254
```
```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' be
192.168.203.5
```

**Comment by glitterlip** [comment]
> I am having the same issue here. Use unbound without netplan.
> 
> It works fine until I decided to change the domain. I tried destroy containers and reconfig and rebuild still the same error in admin container
> 
> admin container log
> 
> ```
> admin-1  | CRITICAL:root:Your DNS resolver at 127.0.0.11 is not working (The resolution lifetime expired after 11.601 seconds: Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.). Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation
> ```
> 
> host resover
> 
> ```
> resolvectl status | grep DNSSEC
>       DNSSEC setting: allow-downgrade
>     DNSSEC supported: yes
>           DNSSEC NTA: 10.in-addr.arpa
>       DNSSEC setting: allow-downgrade
> ```
> 
> logs in front container exec ping
> 
> ```
> docker compose exec front ping example.com
> WARN[0000] /root/mailu/docker-compose.yml: `version` is obsolete
> PING example.com (93.184.215.14): 56 data bytes
> 64 bytes from 93.184.215.14: seq=0 ttl=51 time=159.437 ms
> 64 bytes from 93.184.215.14: seq=1 ttl=51 time=159.393 ms
> 64 bytes from 93.184.215.14: seq=2 ttl=51 time=159.330 ms
> 64 bytes from 93.184.215.14: seq=3 ttl=51 time=159.168 ms
> 64 bytes from 93.184.215.14: seq=4 ttl=51 time=159.106 ms
> ```
> 
> exec host command in resolver container
> 
> ```
> host example.com 192.168.203.254
> Using domain server:
> Name: 192.168.203.254
> Address: 192.168.203.254#53
> Aliases:
> 
> example.com has address 93.184.215.14
> example.com has IPv6 address 2606:2800:21f:cb07:6820:80da:af6b:8b2c
> example.com mail is handled by 0 .
> ```
> 
> logs in resolver
> 
> ```
> resolver-1  | [1717317750] unbound[1:0] notice: init module 0: validator
> resolver-1  | [1717317750] unbound[1:0] notice: init module 1: iterator
> resolver-1  | [1717317750] unbound[1:0] info: start of service (unbound 1.20.0).
> resolver-1  | [1717317751] unbound[1:0] info: generate keytag query _ta-4f66. NULL IN
> resolver-1  | [1717319047] unbound[1:0] info: service stopped (unbound 1.20.0).
> resolver-1  | [1717319047] unbound[1:0] info: server stats for thread 0: 410 queries, 101 answers from cache, 309 recursions, 0 prefetch, 0 rejected by ip ratelimiting
> resolver-1  | [1717319047] unbound[1:0] info: server stats for thread 0: requestlist max 7 avg 2.64725 exceeded 198 jostled 0
> resolver-1  | [1717319047] unbound[1:0] info: average recursion processing time 0.661231 sec
> resolver-1   | [1717319047] unbound[1:0] info: histogram of recursion processing times
> ```
> 
> currently `/admin`,`/webmail` returns 502
> 
> in front container
> 
> ```
> curl http://localhost/webmail/ -i
> HTTP/1.1 500 Internal Server Error
> Server: nginx
> Date: Sun, 02 Jun 2024 09:46:11 GMT
> Content-Type: text/html
> Content-Length: 170
> Connection: close
> 
> <html>
> <head><title>500 Internal Server Error</title></head>
> <body>
> <center><h1>500 Internal Server Error</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>
> ```
> 
> log shows connection refused
> 
> ```
> front-1  | 2024/06/02 09:46:11 [error] 17#17: *48 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /webmail/ HTTP/1.1", subrequest: "/internal/auth/user", upstream: "http://192.168.203.5:8080/internal/auth/user", host: "localhost"
> front-1  | 2024/06/02 09:46:11 [error] 17#17: *48 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: , request: "GET /webmail/ HTTP/1.1", host: "localhost"
> front-1  | 127.0.0.1 - - [02/Jun/2024:09:46:11 +0000] "GET /webmail/ HTTP/1.1" 500 170 "-" "curl/8.5.0"
> ```
> 
> here are containers
> 
> ```
> docker ps
> CONTAINER ID   IMAGE                         COMMAND                  CREATED             STATUS                      PORTS                                                                                                                                                                                                                                                                           NAMES
> 2d6ca5d92d91   ghcr.io/mailu/fetchmail:2.0   "/fetchmail.py"          About an hour ago   Up 17 minutes (healthy)                                                                                                                                                                                                                                                                                     mailu-fetchmail-1
> 7dfeac40b955   ghcr.io/mailu/webmail:2.0     "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (healthy)                                                                                                                                                                                                                                                                                     mailu-webmail-1
> 7e351fa47236   ghcr.io/mailu/dovecot:2.0     "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (healthy)     110/tcp, 143/tcp, 993/tcp, 2525/tcp, 4190/tcp                                                                                                                                                                                                                                   mailu-imap-1
> e21a60b12f58   ghcr.io/mailu/postfix:2.0     "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (healthy)                                                                                                                                                                                                                                                                                     mailu-smtp-1
> 1fce0b8aa877   ghcr.io/mailu/rspamd:2.0      "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (unhealthy)                                                                                                                                                                                                                                                                                   mailu-antispam-1
> be501512694e   ghcr.io/mailu/admin:2.0       "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (unhealthy)                                                                                                                                                                                                                                                                                   mailu-admin-1
> 25b440111eb2   ghcr.io/mailu/nginx:2.0       "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (healthy)     156.238.240.200:25->25/tcp, 156.238.240.200:110->110/tcp, 156.238.240.200:143->143/tcp, 156.238.240.200:465->465/tcp, 156.238.240.200:587->587/tcp, 156.238.240.200:993->993/tcp, 156.238.240.200:995->995/tcp, 156.238.240.200:10080->80/tcp, 156.238.240.200:10443->443/tcp   mailu-front-1
> 711184d8dc97   redis:alpine                  "docker-entrypoint.s…"   About an hour ago   Up 17 minutes               6379/tcp                                                                                                                                                                                                                                                                        mailu-redis-1
> bdc97ffbbb23   ghcr.io/mailu/oletools:2.0    "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (healthy)                                                                                                                                                                                                                                                                                     mailu-oletools-1
> f11df031a910   ghcr.io/mailu/unbound:2.0     "/bin/sh -c /start.py"   About an hour ago   Up 17 minutes (healthy)                                                                                                                                                                                                                                                                                     mailu-resolver-1
> ```
> 
> `f11` is resolver
> 
> ```
> docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' f11
> 192.168.203.254
> ```
> 
> ```
> docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' be
> 192.168.203.5
> ```

changing `192.168.203.254` to `1.1.1.1` fixed the problem

**Comment by bonswouar** [comment]
Same issue here when trying to upgrade while migrating to another server.
For some reason `192.168.203.254:53` doesn't seem to accept connections

Docker 27.0.2 / Debian 12

**Comment by Occhioverde** [comment]
I, too, ran into this issue while trying to set up Mailu for the first time.

In my case, however, using `1.1.1.1` as the DNS for the containers (and deleting all the Mailu data before re-creating them) didn't solve the problem, producing a `CRITICAL:root:Your DNS resolver at 127.0.0.11 isn't doing DNSSEC validation; Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation.` error instead.

My `docker-compose.yml`:
```yml
services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/docker-infr/mail/redis:/data"
    depends_on:
      - resolver
    dns:
      - 1.1.1.1
      #- 192.168.203.254

  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "192.168.1.254:80:80"
      - "192.168.1.254:443:443"
      - "192.168.1.254:25:25"
      - "192.168.1.254:465:465"
      - "192.168.1.254:587:587"
      - "192.168.1.254:110:110"
      - "192.168.1.254:995:995"
      - "192.168.1.254:143:143"
      - "192.168.1.254:993:993"
      - "192.168.1.254:4190:4190"
    networks:
      - default
    volumes:
      - "/docker-infr/mail/certs:/certs"
      - "/docker-infr/mail/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 1.1.1.1
      #- 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2024.06}
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-resolver
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "/docker-infr/mail/data:/data"
      - "/docker-infr/mail/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 1.1.1.1
      #- 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "/docker-infr/mail/mail:/mail"
      - "/docker-infr/mail/overrides/dovecot:/overrides:ro"
    networks:
      - default
    depends_on:
      - front
      - resolver
    dns:
      - 1.1.1.1
      #- 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "/docker-infr/mail/mailqueue:/queue"
      - "/docker-infr/mail/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 1.1.1.1
      #- 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
    volumes:
      - "/docker-infr/mail/filter:/var/lib/rspamd"
      - "/docker-infr/mail/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - resolver
    dns:
      - 1.1.1.1
      #- 192.168.203.254

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```

**Comment by asaurer** [comment]
I'm experiencing a similar issue; changing DNS to `1.1.1.1` fixes it. It only affects certain domains, however. Recreating the containers does not fix it.

This also leads to emails received from this domain being rejected with "Sender address rejected: Domain not found".

Env:
- Docker version 27.1.2, build d01f264
- Docker Compose version v2.29.1
- Mailu: 2024.06.10
- Ubuntu 22.04.4

Commands:
```shell
$ docker compose exec smtp host uzh.ch
Host uzh.ch not found: 2(SERVFAIL)

$ docker compose exec smtp host google.com
google.com has address 142.250.186.174
google.com has IPv6 address 2a00:1450:4001:82b::200e
google.com mail is handled by 10 smtp.google.com.

$ docker compose exec resolver host uzh.ch
uzh.ch has address 130.60.184.132
uzh.ch mail is handled by 10 uzh-ch.mail.protection.outlook.com.

$ docker compose exec resolver host google.com
google.com has address 216.58.206.46
google.com has IPv6 address 2a00:1450:4001:810::200e
google.com mail is handled by 10 smtp.google.com.

$ docker compose exec resolver host uzh.ch 192.168.203.254
Using domain server:
Name: 192.168.203.254
Address: 192.168.203.254#53
Aliases:

Host uzh.ch not found: 2(SERVFAIL)

$ docker compose exec resolver host google.com 192.168.203.254
Using domain server:
Name: 192.168.203.254
Address: 192.168.203.254#53
Aliases:

google.com has address 142.250.186.174
google.com has IPv6 address 2a00:1450:4001:82b::200e
google.com mail is handled by 10 smtp.google.com.
```

**Comment by Aetherinox** [comment]
Actually weird. wonder if it's a certain setup, because I didn't have to change to `1.1.1.1`

I used the `resolve` container IP
```env
MAILU_SUBNET=10.11.0.0/16
RESOLVER_IP=10.11.255.254
```

And then for all of my containers, I just call the IP for the resolver

```yml
  admin:
    container_name: mail-admin
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-latest}
    restart: unless-stopped
    env_file:
      - ${MAILU_ENV}
    mem_limit: "512m"
    mem_reservation: "128m"
    cpus: 0.5
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "${VOLUMES_DIR}/data:/data"
      - "${VOLUMES_DIR}/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - ${RESOLVER_IP}
```
