### ISSUE TITLE
Avoid passing sensitive information via environment variables

### ISSUE THREAD

**Issue by kkarsten62** [Mailu/Mailu#3573]
## Environment & Version

- `docker compose version`: v2.29.7
- Version: `master`: 2024.06

## Description

Sensitive information like `SECRET_KEY` and `RELAYPASSWORD` are stored in plain text in `mailu.env` and are exposed in all mailu container.
As a more secure approach Docker `Secrets` (_FILE) mechanism should be implemented, like other Docker apps has already introduced, example see mariadb, https://hub.docker.com/_/mariadb

Possible looklike for smtp:
```
...
  smtp:
...
       dns:
      - 192.168.203.254
    secrets:
      - smtp_relay_pwd
    environment:
      RELAYPASSWORD_FILE: /run/secrets/smtp_relay_pwd
...
secrets:
  smtp_relay_pwd:
    file: ./smtp_relay_pwd.txt
```
