### ISSUE TITLE
Mailu dosent start

### ISSUE THREAD

**Issue by Mephisto090** [Mailu/Mailu#3635]
## Environment & Version

- `docker compose version` Docker Compose version v2.29.7
- Version: 
![image](https://github.com/user-attachments/assets/71ff095b-3a90-449b-9cea-8fa815a667e5)

## Description

After running for several months, I was no longer able to send emails to my mail server. When I tried to check it, it had crashed. Attempting to restart it, it no longer boots up (see logs).
Neither a server restart nor `docker compose up -d` provide a solution.

## Replication Steps

i dont know

## Observed behaviour

Does not start (see logs).

## Expected behaviour

Start Mailu

## Logs
![image](https://github.com/user-attachments/assets/f5f123a0-a119-4e9a-8e80-dc1ca29b8ae5)

```
 ✔ Network Mailserver-Clamav-Network    Created                                                                                                                                                                                         0.1s
 ✔ Network Mailserver-webmail-Network   Created                                                                                                                                                                                         0.1s
 ✔ Network Mailserver-Radicale-Network  Created                                                                                                                                                                                         0.1s
 ✔ Network Mailserver-Network           Created                                                                                                                                                                                         0.1s
 ✔ Network Mailserver-Oletools-Network  Created                                                                                                                                                                                         0.1s
 ✔ Container Mailserver-Antivirus       Created                                                                                                                                                                                         0.0s
 ✔ Container Mailserver-Webdav          Created                                                                                                                                                                                         0.0s
 ✔ Container Mailserver-Resolver        Created                                                                                                                                                                                         0.0s
 ✔ Container Mailserver-Redis           Created                                                                                                                                                                                         0.0s
 ✔ Container Mailserver-OleTools        Created                                                                                                                                                                                         0.0s
 ✔ Container Mailserver-Front           Created                                                                                                                                                                                         0.0s
 ✔ Container Mailserver-Admin           Created                                                                                                                                                                                         0.0s
 ✔ Container Mailserver-Webmail         Created                                                                                                                                                                                         0.0s
 ✔ Container Mailserver-Antispam        Created                                                                                                                                                                                         0.0s
 ✔ Container Mailserver-Imap            Created                                                                                                                                                                                         0.0s
 ✔ Container Mailserver-Smtp            Created                                                                                                                                                                                         0.0s
 ✔ Container Mailserver-Fetchmail       Created                                                                                                                                                                                         0.0s
Attaching to Mailserver-Admin, Mailserver-Antispam, Mailserver-Antivirus, Mailserver-Fetchmail, Mailserver-Front, Mailserver-Imap, Mailserver-OleTools, Mailserver-Redis, Mailserver-Resolver, Mailserver-Smtp, Mailserver-Webdav, Mailserver-Webmail
Mailserver-Antivirus  | Starting Freshclamd
Mailserver-Antivirus  | Starting ClamAV
Socket for clamd not found yet, retrying (0/1800) ...ClamAV update process started at Fri Nov  8 19:06:01 2024
Mailserver-Antivirus  | daily.cld database is up-to-date (version: 27452, sigs: 2067676, f-level: 90, builder: raynman)
Mailserver-Antivirus  | main.cvd database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
Mailserver-Antivirus  | bytecode.cvd database is up-to-date (version: 335, sigs: 86, f-level: 90, builder: raynman)
Mailserver-Webdav     | [2024-11-08 19:06:01 +0000] [1] [INFO] Loaded default config
Mailserver-Webdav     | [2024-11-08 19:06:01 +0000] [1] [INFO] Loaded config file '/radicale.conf'
Mailserver-Webdav     | [2024-11-08 19:06:01 +0000] [1] [INFO] Loaded command line arguments
Mailserver-Webdav     | [2024-11-08 19:06:01 +0000] [1] [INFO] Starting Radicale
Mailserver-Webdav     | [2024-11-08 19:06:01 +0000] [1] [INFO] auth type is 'radicale.auth.http_x_remote_user'
Mailserver-Webdav     | [2024-11-08 19:06:01 +0000] [1] [INFO] storage type is 'radicale.storage.multifilesystem'
Mailserver-Webdav     | [2024-11-08 19:06:01 +0000] [1] [INFO] rights type is 'radicale.rights.owner_only'
Mailserver-Webdav     | [2024-11-08 19:06:01 +0000] [1] [INFO] web type is 'radicale.web.internal'
Mailserver-Webdav     | [2024-11-08 19:06:01 +0000] [1] [INFO] permit delete of collection: True
Mailserver-Webdav     | [2024-11-08 19:06:01 +0000] [1] [INFO] Listening on '0.0.0.0:5232'
Mailserver-Webdav     | [2024-11-08 19:06:01 +0000] [1] [INFO] Listening on '[::]:5232'
Mailserver-Webdav     | [2024-11-08 19:06:01 +0000] [1] [INFO] Radicale server ready
Mailserver-Redis      | 1:C 08 Nov 2024 19:06:01.964 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
Mailserver-OleTools   | <string>:63: SyntaxWarning: invalid escape sequence '\['
Mailserver-Redis      | 1:C 08 Nov 2024 19:06:01.965 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
Mailserver-Redis      | 1:C 08 Nov 2024 19:06:01.965 * Redis version=7.4.1, bits=64, commit=00000000, modified=0, pid=1, just started
Mailserver-Redis      | 1:C 08 Nov 2024 19:06:01.965 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
Mailserver-Redis      | 1:M 08 Nov 2024 19:06:01.965 * monotonic clock: POSIX clock_gettime
Mailserver-Redis      | 1:M 08 Nov 2024 19:06:01.967 * Running mode=standalone, port=6379.
Mailserver-Redis      | 1:M 08 Nov 2024 19:06:01.968 * Server initialized
Mailserver-Redis      | 1:M 08 Nov 2024 19:06:01.968 * Loading RDB produced by version 7.4.1
Mailserver-Redis      | 1:M 08 Nov 2024 19:06:01.968 * RDB age 18 seconds
Mailserver-Redis      | 1:M 08 Nov 2024 19:06:01.968 * RDB memory usage when created 2.03 Mb
Mailserver-Redis      | 1:M 08 Nov 2024 19:06:01.978 * Done loading RDB, keys loaded: 10298, keys expired: 0.
Mailserver-Redis      | 1:M 08 Nov 2024 19:06:01.978 * DB loaded from disk: 0.011 seconds
Mailserver-Redis      | 1:M 08 Nov 2024 19:06:01.978 * Ready to accept connections tcp
Mailserver-OleTools   | <string>:204: DeprecationWarning: There is no current event loop
Mailserver-Resolver exited with code 0
Mailserver-Admin exited with code 0
Mailserver-Smtp exited with code 0
Mailserver-Imap exited with code 132
Mailserver-Webmail exited with code 0
Mailserver-Antispam exited with code 0
Mailserver-Fetchmail exited with code 132
Mailserver-Front exited with code 0
Socket for clamd not found yet, retrying (20/1800) ...Fri Nov  8 19:06:21 2024 -> Limits: Global time limit set to 120000 milliseconds.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: Global size limit set to 419430400 bytes.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: File size limit set to 104857600 bytes.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: Recursion level limit set to 17.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: Files limit set to 10000.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: MaxEmbeddedPE limit set to 41943040 bytes.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: MaxHTMLNormalize limit set to 41943040 bytes.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: MaxHTMLNoTags limit set to 8388608 bytes.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: MaxScriptNormalize limit set to 20971520 bytes.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: MaxZipTypeRcg limit set to 1048576 bytes.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: MaxPartitions limit set to 50.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: MaxIconsPE limit set to 100.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: MaxRecHWP3 limit set to 16.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: PCREMatchLimit limit set to 100000.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: PCRERecMatchLimit limit set to 2000.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Limits: PCREMaxFileSize limit set to 104857600.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Archive support enabled.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> AlertExceedsMax heuristic detection disabled.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Heuristic alerts enabled.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Portable Executable support enabled.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> ELF support enabled.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Mail files support enabled.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> OLE2 support enabled.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> PDF support enabled.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> SWF support enabled.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> HTML support enabled.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> XMLDOCS support enabled.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> HWP3 support enabled.
Mailserver-Antivirus  | Fri Nov  8 19:06:21 2024 -> Self checking every 600 seconds.
Mailserver-Antivirus  | socket found, clamd started.

```

**Comment by Mephisto090** [comment]
```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

services:

  # External dependencies
  redis:
    image: redis:alpine
    container_name: Mailserver-Redis
    restart: always
    volumes:
      - "/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 172.40.0.254

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    container_name: Mailserver-Front
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "37.157.254.110:80:80"
      - "37.157.254.110:443:443"
      - "37.157.254.110:25:25"
      - "37.157.254.110:465:465"
      - "37.157.254.110:587:587"
      - "37.157.254.110:110:110"
      - "37.157.254.110:995:995"
      - "37.157.254.110:143:143"
      - "37.157.254.110:993:993"
      - "37.157.254.110:4190:4190"
    networks:
      - default
      - webmail
      - radicale
    volumes:
      - "/mailu/certs:/certs"
      - "/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 172.40.0.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2024.06}
    container_name: Mailserver-Resolver
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-resolver
    restart: always
    networks:
      default:
        ipv4_address: 172.40.0.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    container_name: Mailserver-Admin
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 172.40.0.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    container_name: Mailserver-Imap
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "/mailu/mail:/mail"
      - "/mailu/overrides/dovecot:/overrides:ro"
    networks:
      - default
    depends_on:
      - front
      - resolver
    dns:
      - 172.40.0.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    container_name: Mailserver-Smtp
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "/mailu/mailqueue:/queue"
      - "/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 172.40.0.254

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2024.06}
    container_name: Mailserver-OleTools
    hostname: oletools
    logging:
      driver: journald
      options:
        tag: mailu-oletools
    restart: always
    networks:
      - oletools
    depends_on:
      - resolver
    dns:
      - 172.40.0.254


  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}
    container_name: Mailserver-Antispam
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - oletools
      - clamav
    volumes:
      - "/mailu/filter:/var/lib/rspamd"
      - "/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 172.40.0.254

  # Optional services
  antivirus:
    image: clamav/clamav-debian:1.2.0-6
    container_name: Mailserver-Antivirus
    restart: always
    logging:
      driver: journald
      options:
        tag: mailu-antivirus
    networks:
      - clamav
    volumes:
      - "/mailu/filter/clamav:/var/lib/clamav"
    healthcheck:
      test: ["CMD-SHELL", "kill -0 `cat /tmp/clamd.pid` && kill -0 `cat /tmp/freshclam.pid`"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  webdav:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-2024.06}
    container_name: Mailserver-Webdav
    restart: always
    logging:
      driver: journald
      options:
        tag: mailu-webdav
    volumes:
      - "/mailu/dav:/data"
    networks:
      - radicale

  fetchmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-2024.06}
    container_name: Mailserver-Fetchmail
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-fetchmail
    volumes:
      - "/mailu/data/fetchmail:/data"
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - 172.40.0.254

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2024.06}
    container_name: Mailserver-Webmail
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-webmail
    volumes:
      - "/mailu/webmail:/data"
      - "/mailu/overrides/roundcube:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    name: Mailserver-Network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/24
       #   gateway: 172.40.0.1
  radicale:
    name: Mailserver-Radicale-Network
    driver: bridge
  webmail:
    name: Mailserver-webmail-Network
    driver: bridge
  clamav:
    name: Mailserver-Clamav-Network
    driver: bridge
  oletools:
    name: Mailserver-Oletools-Network
    driver: bridge
    internal: true
```
