### ISSUE TITLE
Default docker setup with IPv6 disabled results in an open relay

### ISSUE THREAD

**Issue by Cenness** [Mailu/Mailu#3680]
## Environment & Version

- `Docker Compose version v2.29.7`
- Version: `2024.06`

## Description

Default docker setup with IPv6 disabled results in an open relay, because setup instructions don't mention that `userland-proxy` must be disabled.

## Replication Steps
1. follow instruction at https://mailu.io/2024.06/setup.html
2. setup docker, docker compose
3. create mailu.env and compose files using https://setup.mailu.io/2024.06/
4. start up services
5. wait a couple days
6. check up rspamd history and marvel at walls of sent emails from smtp container ip address
![image](https://github.com/user-attachments/assets/499b7553-7e58-49f0-8d2e-1aac6a7dd0ee)

## Observed behaviour
Spam messages seemingly originating from smtp container

## Expected behaviour
No smap messages originating from new installation

## Logs
```
Oct 25 03:33:07 mail postfix/smtpd[59863]: connect from mailu-front-1.mailu_default[192.168.203.3]
INFO:root:Connect 
INFO:root:Connect 
Oct 25 03:33:07 mail postfix/smtpd[59863]: A303311BB3A: client=unknown[192.168.203.1]
INFO:root:Connect 
Oct 25 03:33:08 mail postfix/cleanup[59866]: A303311BB3A: message-id=<62ab6a39deee84dab5e460d51d121c64@REDACTED>
Oct 25 03:33:09 mail postfix/qmgr[352]: A303311BB3A: from=<customer@REDACTED>, size=42254, nrcpt=1 (queue active)
INFO:root:Connect 
Oct 25 03:33:09 mail postfix/smtpd[59863]: disconnect from unknown[192.168.203.1] helo=1 ehlo=1 xclient=0/1 mail=1 rcpt=1 data=1 quit=1 commands=6/7
Oct 25 03:33:12 mail postfix/smtp[59867]: Trusted TLS connection established to mx3.qq.com[203.205.219.57]:25: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Oct 25 03:33:14 mail postfix/smtp[59867]: A303311BB3A: to=<506923955@qq.com>, relay=mx3.qq.com[203.205.219.57]:25, delay=7.2, delays=2.1/0.05/2.9/2.1, dsn=2.0.0, status=sent (250 OK: queued as.)
Oct 25 03:33:14 mail postfix/qmgr[352]: A303311BB3A: removed
```

## Additional notes

The only place current docs mention `userland-proxy` is FAQ note about how to enable IPv6 - https://mailu.io/2024.06/faq.html#how-to-make-ipv6-work.
Issues and discussions with explicit recommendation to disable  `userland-proxy` - https://github.com/Mailu/Mailu/discussions/3042#discussioncomment-7495362 https://github.com/Mailu/Mailu/discussions/3072  https://github.com/Mailu/Mailu/issues/2821 https://github.com/Mailu/Mailu/issues/2857#issuecomment-1603849178

**Comment by Cenness** [comment]
```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "./mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "127.0.0.1:8000:80"
      - "127.0.0.1:8400:443"
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
      - "4190:4190"
    networks:
      - default
      - webmail
    volumes:
      - "./mailu/certs:/certs"
      - "./mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2024.06}
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-resolver
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "./mailu/data:/data"
      - "./mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "./mailu/mail:/mail"
      - "./mailu/overrides/dovecot:/overrides:ro"
    networks:
      - default
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "./mailu/mailqueue:/queue"
      - "./mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254



  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - clamav
    volumes:
      - "./mailu/filter:/var/lib/rspamd"
      - "./mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - antivirus
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: clamav/clamav-debian:1.2.3-45
    restart: always
    logging:
      driver: journald
      options:
        tag: mailu-antivirus
    networks:
      - clamav
    volumes:
      - "./mailu/filter/clamav:/var/lib/clamav"
    healthcheck:
      test: ["CMD-SHELL", "kill -0 `cat /tmp/clamd.pid` && kill -0 `cat /tmp/freshclam.pid`"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s


  fetchmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-fetchmail
    volumes:
      - "./mailu/data/fetchmail:/data"
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - 192.168.203.254

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-webmail
    volumes:
      - "./mailu/webmail:/data"
      - "./mailu/overrides/snappymail:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  webmail:
    driver: bridge
  clamav:
    driver: bridge
```
