### ISSUE TITLE
Unable to use existing LetsEncrypt Certificate via `TLS_FLAVOR=cert`

### ISSUE THREAD

**Issue by LumiWasTaken** [Mailu/Mailu#3693]
## Environment & Version
- Docker Compose Version: 27.1.2
- Mailu Version: master

## Description
When configuring Mailu with an existing certificate using the "cert" option, the service fails with a generic SSL error:
```
SSL_accept() failed: error:0A000412:SSL routines::ssl/tls alert bad certificate: SSL alert number 42
```

While this could potentially be a user error, I have extensive experience with this setup and have eliminated all common issues. The same certificate configuration previously worked successfully with mailserver-docker.

### Environment Variables (mailu.env)
```
# TLS Configuration
TLS_FLAVOR=cert
TLS_CERT_FILENAME=live/npm-12/fullchain.pem
TLS_KEYPAIR_FILENAME=live/npm-12/privkey.pem
```

### Complete Docker Compose Configuration
```yaml
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "./redis_data:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
#      - "127.0.0.1:80:80"       # HTTP
#      - "127.0.0.1:443:443"     # HTTPS
     - "127.0.0.1:25:25"        # SMTP (unencrypted)
     - "465:465"                # SMTP over SSL/TLS
     - "587:587"                # SMTP with STARTTLS
     - "127.0.0.1:110:110"      # POP3 (unencrypted)
     - "995:995"                # POP3 over SSL/TLS
     - "127.0.0.1:143:143"      # IMAP (unencrypted)
     - "993:993"                # IMAP over SSL/TLS
     - "127.0.0.1:4190:4190"    # Sieve mail filtering
    networks:
      - default
      - webmail
      - radicale
      - proxy_network
    volumes:
      - "/etc/letsencrypt:/certs"
      - "./nginx_overrides:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-master}
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-resolver
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "./mailu_data:/data"
      - "./mailu_dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "./mailu_mail:/mail"
      - "./dovecot_overrides:/overrides:ro"
    networks:
      - default
      - fts_attachments
    depends_on:
      - front
      - fts_attachments
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "./postfix_mailqueue:/queue"
      - "./postfix_overrides:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-master}
    hostname: oletools
    logging:
      driver: journald
      options:
        tag: mailu-oletools
    restart: always
    networks:
      - oletools
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  fts_attachments:
    image: apache/tika:2.9.2.1-full
    hostname: tika
    logging:
      driver: journald
      options:
        tag: mailu-tika
    restart: always
    networks:
      - fts_attachments
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
    healthcheck:
      test: ["CMD-SHELL", "wget -nv -t1 -O /dev/null http://127.0.0.1:9998/tika || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-master}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - oletools
      - clamav
    volumes:
      - "./rspamd_filter:/var/lib/rspamd"
      - "./rspamd_overrides:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: clamav/clamav-debian:1.2.3-45
    restart: always
    logging:
      driver: journald
      options:
        tag: mailu-antivirus
    networks:
      - clamav
    volumes:
      - "./data_clamav:/var/lib/clamav"
    healthcheck:
      test: ["CMD-SHELL", "kill -0 `cat /tmp/clamd.pid` && kill -0 `cat /tmp/freshclam.pid`"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  webdav:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-master}
    restart: always
    logging:
      driver: journald
      options:
        tag: mailu-webdav
    volumes:
      - "./webdav_data:/data"
    networks:
      - radicale

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-master}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-webmail
    volumes:
      - "./snappymail_data:/data"
      - "./snappymail_overrides:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  radicale:
    driver: bridge
  webmail:
    driver: bridge
  clamav:
    driver: bridge
  oletools:
    driver: bridge
    internal: true
  fts_attachments:
    driver: bridge
    internal: true
  proxy_network:
    external: true
```

Note: Ports 80 and 443 are intentionally commented out as a reverse proxy handles these connections. The front container is accessible internally through the proxy network.

### Certificate Structure
The certificate files in `/etc/letsencrypt/live/npm-12/` are structured as follows:
```
lrwxrwxrwx 1 root root  30 Nov 25 16:53 cert.pem -> ../../archive/npm-12/cert8.pem
lrwxrwxrwx 1 root root  31 Nov 25 16:53 chain.pem -> ../../archive/npm-12/chain8.pem
lrwxrwxrwx 1 root root  35 Nov 25 16:53 fullchain.pem -> ../../archive/npm-12/fullchain8.pem
lrwxrwxrwx 1 root root  33 Nov 25 16:53 privkey.pem -> ../../archive/npm-12/privkey8.pem
```

The entire `/etc/letsencrypt` directory is mounted to preserve symlinks.

## Setup Process
1. Let's Encrypt certificates are pre-generated by an external certbot from nginx-proxy-manager
2. The host system's `/etc/letsencrypt/` folder is mounted inside the front container at `/certs`
3. SSL certificate paths are configured via environment variables
   - Note: Invalid certificate paths trigger a dovecot configuration error, confirming the paths are being read

The web UI is accessible through the reverse proxy, and domain/user management functions work correctly.

Important: When using `TLS_FLAVOR=cert`, the nginx-proxy must reference `https://front:443` instead of `http://front:80` to prevent redirect loops.

## Observed Behavior
External email clients (e.g., Thunderbird) receive a connection refused error:
```
Could not connect to mail server mail.lumify.cat; the connection was refused.
```

The front container logs show:
```
front-1 | Dec 23 03:11:46 submission-login: Info: Disconnected: Connection closed: SSL_accept() failed: error:0A000412:SSL routines::ssl/tls alert bad certificate: SSL alert number 42 (no auth attempts in 1 secs): user=<>, rip=87.xxx.xxx.xxx, rport=47366, lip=192.168.203.3, lport=465, TLS handshaking: SSL_accept() failed: error:0A000412:SSL routines::ssl/tls alert bad certificate: SSL alert number 42
```

## Expected Behavior
External email clients should be able to connect successfully using SSL/TLS, as the certificates are valid and properly configured.

## Complete Logs
```
docker compose logs front 
front-1  | Dec 23 03:10:20 master: Info: Dovecot v2.3.21.1 (d492236fa0) starting up for sieve, imap, pop3, lmtp, submission
front-1  | 2024/12/23 03:10:20 [notice] 17#17: using the "epoll" event method
front-1  | 2024/12/23 03:10:20 [notice] 17#17: nginx/1.26.2
front-1  | 2024/12/23 03:10:20 [notice] 17#17: OS: Linux 6.1.0-23-arm64
front-1  | 2024/12/23 03:10:20 [notice] 17#17: getrlimit(RLIMIT_NOFILE): 1048576:1048576
front-1  | 2024/12/23 03:10:20 [notice] 17#17: start worker processes
front-1  | 2024/12/23 03:10:20 [notice] 17#17: start worker process 58
front-1  | 2024/12/23 03:10:20 [notice] 17#17: start worker process 59
front-1  | 2024/12/23 03:10:20 [notice] 17#17: start worker process 60
front-1  | 2024/12/23 03:10:20 [notice] 17#17: start worker process 61
front-1  | 2024/12/23 03:10:20 [notice] 17#17: start worker process 62
front-1  | 2024/12/23 03:10:20 [notice] 17#17: start worker process 63
front-1  | 2024/12/23 03:10:20 [notice] 17#17: start worker process 64
front-1  | 2024/12/23 03:10:20 [notice] 17#17: start worker process 65
front-1  | Dec 23 03:10:55 submission-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 3 secs): user=<general@lumify.cat>, method=LOGIN, rip=87.120.93.10, rport=51024, lip=192.168.203.3, lport=465, TLS: Connection closed
front-1  | Dec 23 03:11:25 submission-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 20 secs): user=<sdk@lumify.cat>, method=LOGIN, rip=xxx.xxx.xxx.xxx, rport=64210, lip=192.168.203.3, lport=465, TLS: Connection closed
front-1  | Dec 23 03:11:32 submission-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 2 secs): user=<guest@lumify.cat>, method=LOGIN, rip=87.120.93.10, rport=53018, lip=192.168.203.3, lport=465, TLS: Connection closed
front-1  | Dec 23 03:11:46 submission-login: Info: Disconnected: Connection closed: SSL_accept() failed: error:0A000412:SSL routines::ssl/tls alert bad certificate: SSL alert number 42 (no auth attempts in 1 secs): user=<>, rip=87.123.80.116, rport=47366, lip=192.168.203.3, lport=465, TLS handshaking: SSL_accept() failed: error:0A000412:SSL routines::ssl/tls alert bad certificate: SSL alert number 42
front-1  | Dec 23 03:11:46 imap-login: Info: Disconnected: Connection closed: SSL_accept() failed: error:0A000412:SSL routines::ssl/tls alert bad certificate: SSL alert number 42 (no auth attempts in 1 secs): user=<>, rip=87.123.80.116, rport=46024, lip=192.168.203.3, lport=993, TLS handshaking: SSL_accept() failed: error:0A000412:SSL routines::ssl/tls alert bad certificate: SSL alert number 42
front-1  | Dec 23 03:11:46 pop3-login: Info: Disconnected: Connection closed: SSL_accept() failed: error:0A000412:SSL routines::ssl/tls alert bad certificate: SSL alert number 42 (no auth attempts in 0 secs): user=<>, rip=87.123.80.116, rport=52374, lip=192.168.203.3, lport=995, TLS handshaking: SSL_accept() failed: error:0A000412:SSL routines::ssl/tls alert bad certificate: SSL alert number 42
front-1  | Dec 23 03:11:56 submission-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 21 secs): user=<nsk@lumify.cat>, method=LOGIN, rip=xxx.xxx.xxx.xxx, rport=15156, lip=192.168.203.3, lport=465, TLS: Connection closed
front-1  | Dec 23 03:12:04 submission-login: Info: Disconnected: Connection closed (unfinished AUTH command) (client didn't finish SASL auth, waited 0 secs): user=<>, method=LOGIN, rip=xxx.xxx.xxx.xxx, rport=30790, lip=192.168.203.3, lport=465, TLS: Connection closed
front-1  | Dec 23 03:12:11 submission-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 2 secs): user=<sales01@lumify.cat>, method=LOGIN, rip=87.120.93.10, rport=54608, lip=192.168.203.3, lport=465, TLS: Connection closed
front-1  | Dec 23 03:12:50 submission-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 19 secs): user=<thai@lumify.cat>, method=LOGIN, rip=xxx.xxx.xxx.xxx, rport=46492, lip=192.168.203.3, lport=465, TLS: Connection closed
front-1  | Dec 23 03:12:51 submission-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 2 secs): user=<scan@lumify.cat>, method=LOGIN, rip=87.120.93.10, rport=56486, lip=192.168.203.3, lport=465, TLS: Connection closed
front-1  | Dec 23 03:13:01 imap-login: Info: Disconnected: Connection closed: SSL_accept() failed: error:0A000102:SSL routines::unsupported protocol (no auth attempts in 2 secs): user=<>, rip=147.185.132.141, rport=50104, lip=192.168.203.3, lport=993, TLS handshaking: SSL_accept() failed: error:0A000102:SSL routines::unsupported protocol
front-1  | Dec 23 03:13:18 submission-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 19 secs): user=<etu@lumify.cat>, method=LOGIN, rip=xxx.xxx.xxx.xxx, rport=62166, lip=192.168.203.3, lport=465, TLS: Connection
```

-->
