### ISSUE TITLE
Mailu with nginx-proxy and docker-letsencrypt-nginx-proxy-companion setup

### ISSUE THREAD

**Issue by perarg** [Mailu/Mailu#381]
Hello, i have some issues running correctly mailu. My setup is the following:

I use a [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) for reverse proxy. I use also the [JrCs/docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) for creating and auto renew Letsencrypt certificates.
Now i am trying Mailu but i am certainly miss something. Because of the reverse proxy, i edit the docker-compose.yml into the following
```
version: '2'

services:

  front:
    image: mailu/nginx:$VERSION
    restart: always
    env_file: .env
  #  ports:
  #  - "$BIND_ADDRESS4:8080:80"
  #  - "$BIND_ADDRESS4:8443:443"
  #  - "$BIND_ADDRESS4:110:110"
  #  - "$BIND_ADDRESS4:143:143"
  #  - "$BIND_ADDRESS4:993:993"
  #  - "$BIND_ADDRESS4:995:995"
  #  - "$BIND_ADDRESS4:25:25"
  #  - "$BIND_ADDRESS4:465:465"
  #  - "$BIND_ADDRESS4:587:587"
  #  - "$BIND_ADDRESS6:8080:80"
  #  - "$BIND_ADDRESS6:8443:443"
  #  - "$BIND_ADDRESS6:110:110"
  #  - "$BIND_ADDRESS6:143:143"
  #  - "$BIND_ADDRESS6:993:993"
  #  - "$BIND_ADDRESS6:995:995"
  #  - "$BIND_ADDRESS6:25:25"
  #  - "$BIND_ADDRESS6:465:465"
  #  - "$BIND_ADDRESS6:587:587"
    expose:
      - 80
      - 443
      - 110
      - 143
      - 993
      - 995
      - 25
      - 465
      - 587
    environment:
      VIRTUAL_HOST: mail.mydomain.com
    volumes:
      - "$ROOT/certs:/certs"

(everything else stays the same)

networks:
  default:
    external:
      name: ngproxy-net <--- same network as the nginx-proxy container
```
In .env file, the variable `ENABLE_CERTBOT=True` was missing so i added it manually.

Then i tried to `docker-compose up -d` and then `docker-compose run --rm admin python manage.py admin root example.net password` replacing the root, example.net and password with my own.

I got message

```
$ docker-compose run --rm admin python manage.py admin root example.net password
Starting mailu_redis_1 ... done
Generating TLS certificates using Certbot
Error while generating certificates:
IMPORTANT NOTES:
 - Your account credentials have been saved in your Certbot
   configuration directory at /certs. You should make a secure backup
   of this folder now. This configuration directory will also contain
   certificates and private keys obtained by Certbot so making regular
   backups of this folder is ideal.
IMPORTANT NOTES:
 - Your account credentials have been saved in your Certbot
   configuration directory at /certs. You should make a secure backup
   of this folder now. This configuration directory will also contain
   certificates and private keys obtained by Certbot so making regular
   backups of this folder is ideal.
```
in `$ docker logs mailu_imap_1` i get `doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 59: ssl_cert: Can't open file /certs/cert.pem: No such file or directory`

My default.conf in nginx-proxy is the following:

```
# mail.mydomain.com
upstream mail.mydomain.com {
				## Can be connect with "ngpxoy-net" network
			# mailu_front_1
			server 172.21.0.7:80;
}
server {
	server_name mail.mydomain.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name mail.mydomain.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/mydomain.com.crt;   <--------
	ssl_certificate_key /etc/nginx/certs/mydomain.com.key;  <----------
	ssl_dhparam /etc/nginx/certs/mydomain.com.dhparam.pem; <---------
	add_header Strict-Transport-Security "max-age=31536000";
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://mail.mydomain.com;
	}
}
```

Notice that i have already got certificates for mydomain.com. I don't know if this causes the problem.
