### ISSUE TITLE
Antispam Container not able to reach Admin in Docker Portainer Setup

### ISSUE THREAD

**Issue by okdlukas** [Mailu/Mailu#3847]
I want to use a Mailu Server with Portainer. So far i've created the needed Containers and they are all up and running. Only the Antispam Container is not going to get healthy. I use an  upstream Resolver for my setup, so no need for an unbound running via container. DNS etc is also up. 

I can use the admin console of mailu and login to roundcube but i can't send any mails. The Antispam is throwing: WARNING:root:Admin is not up just yet, retrying in 1 second

The Admin Container is up and i am not sure how to configure Antispam any further and what is troubling it to work. 

In compose antispam is looking like this: 

```
  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}
    container_name: antispam
    hostname: antispam
    restart: always
    env_file: stack.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - oletools
    volumes:
      - "/mailu/filter:/var/lib/rspamd"
      - "/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
```
