### ISSUE TITLE
Incorrect location URL on SSO login; ignores custom port

### ISSUE THREAD

**Issue by SKJoy** [Mailu/Mailu#3870]
## Intention
- Access `MailU` web interface through a custom port
- Eliminate requirement of a separate `domain`/`subdomain`
- **Wish**: If all `MailU` web UI could be accessed with an URL `path prefix` like;
  - `https://domain.gtld/mailu/admin/`
  - `https://domain.gtld/mailu/webmail/`
  - `https://domain.gtld/mailu/api/`

## Setup
- `MailU` front container `HTTP` port is exposed at `64980`
- `NginX` reverse proxy (`NginX Proxy Manager`) with valid `SSL`
- `NginX` listens on `54443` for `HTTPS`
- `NginX` proxies to backend `MailU` on port `64980` for `HTTP`

## What happens
- Internet request comes in to `https://domain.gtld:54443/admin/`
- NginX forwards request to `http://MailU:64980/`
- Log in form is shown with **incorrect redirect URL** in address bar
	- `SSO` redirection shows `https://domain.gtld/admin/`
	- It should have been `https://domain.gtld:54443/admin/`
- Upon form submission, `404` error occurs due to wrong URL `https://domain.gtld/admin/`
- Typing `https://domain.gtld:54443/admin/` shows the admin UI without issue
- All subsequent operations/URL seem to work/set correctly

## `docker-compose.yml`
```
  ...
  front:
    image: ghcr.io/mailu/nginx:2024.06
    restart: always
    env_file: mailu.env
    logging:
      ...
    ports:
      - 192.168.253.1:64980:80
      ...
    volumes:
      ...
    depends_on:
      - redis
    dns:
      - 192.168.253.254
  ...

  networks:
    default:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 192.168.253.0/24

```

## NginX configuration
```
server {
	server_name domain.gtld;

	listen 54443 ssl;
	listen [::]:54443 ssl;
	ssl_certificate /SSL/domain.gtld.crt;
	ssl_certificate_key /SSL/domain.gtld.key;
	
	access_log /var/log/nginx/MailU.log main;

	add_header Strict-Transport-Security "max-age=31536000";
	add_header X-XSS-Protection "1; mode=block" always;
	add_header X-Content-Type-Options "nosniff" always;

	proxy_redirect off;

	proxy_set_header Host $host;

	proxy_set_header X-Forwarded-Scheme $scheme;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Forwarded-For $remote_addr;
	proxy_set_header X-Forwarded-Server $host;
	proxy_set_header X-Forwarded-Host $host;
	proxy_set_header X-Forwarded-Port $server_port;
	proxy_set_header X-Real-IP $remote_addr;

	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection $http_connection;
	proxy_http_version 1.1;

	location / {
		proxy_pass http://192.168.253.1:64980/;
	}
}
```
