### ISSUE TITLE
Problems with certificates while running Mailu under nginx-proxy/letsencrypt-companion

### ISSUE THREAD

**Issue by flayks** [Mailu/Mailu#430]
I found Mailu a good solution to host my emails as I'm trying to rebuild my server with Docker, but I get several issues about getting it running properly, especially with the certificates.
Experimented with `TLS_FLAVOR` in my `.env` file, set to `cert` or `mail` but the admin only works with `notls`.

I run my own nginx container for accessing the admin at `mails.server.site.com`, but I always get a 502 error or a 403 with mail or cert option.

Also, when I run the containers, I get this error from the `mailu-front`:
> **mailu-front  | Missing cert or key file, disabling TLS**
> mailu-front  | 2018/03/30 10:20:37 [notice] 7#7: using the "epoll" event method
> mailu-front  | 2018/03/30 10:20:37 [notice] 7#7: nginx/1.12.2
> mailu-front  | 2018/03/30 10:20:37 [notice] 7#7: OS: Linux 4.9.20-std-1
> mailu-front  | 2018/03/30 10:20:37 [notice] 7#7: getrlimit(RLIMIT_NOFILE): 1048576:1048576
> mailu-front  | 2018/03/30 10:20:37 [notice] 7#7: start worker processes
> mailu-front  | 2018/03/30 10:20:37 [notice] 7#7: start worker process 9
> mailu-front  | 2018/03/30 10:20:37 [notice] 7#7: start worker process 10
> mailu-front  | 2018/03/30 10:20:37 [notice] 7#7: start worker process 11
> mailu-front  | 2018/03/30 10:20:37 [notice] 7#7: start worker process 12

The certificates generated by [docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) are actually present on `/etc/certs/mail.site.com` and working, but when I try to symlink anything it doesn't work and I get the same message for the front container.

Did I missed something? I looked at all the issues here about nginx-proxy, reverse proxies or certificates, read the docs carefully, but nothing sounds to work in my situation.

### My configs
**.env**
```
###################################
# Common configuration variables
###################################

# Set this to the path where Mailu data and configuration is stored
ROOT=/data/tools/mailu

# Mailu version to run (1.0, 1.1, etc. or master)
VERSION=1.5

# Set to a randomly generated 16 bytes string
SECRET_KEY=key

# Address where listening ports should bind
BIND_ADDRESS4=127.0.0.1
BIND_ADDRESS6=::1

# Main mail domain
DOMAIN=site.com

# Hostnames for this server, separated with comas
HOSTNAMES=mail.site.com

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail)
# TLS_FLAVOR=letsencrypt
# TLS_FLAVOR=notls
TLS_FLAVOR=cert

# Authentication rate limit (per source IP address)
AUTH_RATELIMIT=10/minute;1000/hour

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=True

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=none

# Dav server implementation (value: radicale, none)
WEBDAV=none

# Antivirus solution (value: clamav, none)
ANTIVIRUS=clamav
[...]
```

**docker-compose.yml**
```yaml
version: "3.6"

networks:
  reverse-proxy:
    external: true
  mail_network:
    driver: bridge

services:
  nginx:
    container_name: mailu-nginx
    image: nginx
    restart: always
    volumes:
      - ./mailu.conf:/etc/nginx/conf.d/default.conf
      - /data/logs/mailu:/logs
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: mails.server.site.com
      LETSENCRYPT_HOST: mails.server.site.com
      LETSENCRYPT_EMAIL: email
    networks:
      reverse-proxy:
      mail_network:

  front:
    container_name: mailu-front
    image: mailu/nginx:$VERSION
    restart: always
    env_file: .env
    ports:
      - "$BIND_ADDRESS4:8080:80"
      - "$BIND_ADDRESS4:8443:443"
      - "$BIND_ADDRESS4:110:110"
      - "$BIND_ADDRESS4:143:143"
      - "$BIND_ADDRESS4:993:993"
      - "$BIND_ADDRESS4:995:995"
      - "$BIND_ADDRESS4:25:25"
      - "$BIND_ADDRESS4:465:465"
      - "$BIND_ADDRESS4:587:587"
      - "$BIND_ADDRESS6:8080:80"
      - "$BIND_ADDRESS6:8443:443"
      - "$BIND_ADDRESS6:110:110"
      - "$BIND_ADDRESS6:143:143"
      - "$BIND_ADDRESS6:993:993"
      - "$BIND_ADDRESS6:995:995"
      - "$BIND_ADDRESS6:25:25"
      - "$BIND_ADDRESS6:465:465"
      - "$BIND_ADDRESS6:587:587"
    volumes:
      - "$ROOT/certs:/certs"
    networks:
      mail_network:

[...the rest is untouched]
```

**nginx custom mailu.conf**
```nginx
upstream www-mailu {
    server front;
}

server {
    server_name mails.server.site.com;
    access_log /logs/access.log;
    error_log /logs/error.log;

    location / {
        proxy_pass http://www-mailu/admin;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_cache_valid 200 302 1m;
    }
}
```

**Comment by flayks** [comment]
Some progress there.
I finally found a way to get the certs working with the `TLS_FLAVOR=cert` (using `cp /etc/certs/mail.site.com/fullchaim.pem /data/tools/mailu/certs/cert.pem` also for `key.pem` – not ideal but works hey, a cron script could be good for that, or a symlink?), so I don't get the "mailu-front | Missing cert or key file, disabling TLS" error.

Though, I'm still trying to access the admin with a custom nginx reverse proxy via my `nginx` container in the same file, but it still gives me 502 Bad Gateway, I can't really find a way to get this working.

```nginx
server {
    access_log /logs/access.log;
    error_log /logs/error.log;

    location / {
        proxy_pass https://localhost:8443/admin;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
```

**Comment by kaiyou** [comment]
The logic is pretty simple: unless the admin specifically wants TLS disabled (in which case notls should be set), we do not want Mailu to be used at all if TLS is not working properly. This is why we disable TLS completely and display 403 and deny SMTP/IMAP access when the cert and key are not in place.

To answer your latest question, could you provide us with the part of your ``docker-compose.yml`` that binds port 8443 for the ``front`` to be available to your reverse proxy? When using ``mail``, the ``front`` container does *not* listen over port 443 and does not have TLS enforced for HTTP requests.

**Comment by Greek64** [comment]
@flayks 
Your nginx-proxy/letsencrypt-companion configuration seems faulty.
The `VIRTUAL_PORT`,`VIRTUAL_HOST`,`LETSENCRYPT_HOST`, and `LETSENCRYPT_EMAIL` Enviromental Variables should be defined for the `front` service/container, and not for the `nginx` container itself.
see the documentation [here](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion).

Basically, the `VIRTUAL_HOST` Variable contains the host for which the certificates are generated. Every request to the nginx container containing that hostname is then redirected to the container that has defined that `VIRTUAL_HOST` Variable (To the port defined in `VIRTUAL_PORT`).

Also note that in your setup it makes no sense to bind the ports 80 and 443 of the `front`
service/container. As explained above, all http requests are redirected from the `nginx` service/container to your `front` service/container in port 80 (as defined by `VIRTUAL_PORT`). A binding of those ports would effectively "bypass" you reverse proxy, as the mailu pages would be accesible from "mails.server.site.com:80", "mails.server.site.com:443", as well as "yoursystemaddress:8080", "yoursystemaddress:8443". (`yoursystemaddress` is effectively your `$BIND_ADDRESS4` address)

Now, concerning the certificates:
In your "cert" directory of your letsencrypt companion you should have following structure:
```
mail.site.com [Directory]
mail.site.com.chain.pem [symlink]
mail.site.com.crt [symlink]
mail.site.com.dhparam.pem [symlink]
mail.site.com.key [symlink]
```

The `mail.site.com.crt` is the `cert.pem` and `mail.site.com.key` is the `key.pem` needed by the "front" container. I suggest "linking" them through docker-compose itself using:
```
volumes:
   -type: bind
     source: /etc/certs/mail.site.com.crt
     target: /certs/cert.pem
     read_only: true
```
This ensures that the container fails if the certificates do not exist (and prevents the ominous directories that docker creates when the files do not exist)
