### ISSUE TITLE
site can't be reached..

### ISSUE THREAD

**Issue by pepya2** [Mailu/Mailu#511]
i have done everything as in your docs in a new digital ocean droplet (ubuntu 16.04.4 x64), i haven't enabled firewall yet, added initial admin account as per your instructions but when i try to access the server i am getting Site can't be reached..

All installation went ok.
![mailu](https://user-images.githubusercontent.com/25289859/42120219-88f7ff08-7c20-11e8-8f16-b3e7dc5549fe.png)

even listed containers and showed me..
![mailu1](https://user-images.githubusercontent.com/25289859/42120225-9c822d50-7c20-11e8-9286-489ad8b31829.png)

any help please..

**Comment by kaiyou** [comment]
Do you have any detailed information about your issue, like how are the sites non available? Is it a timeout, a TLS error, an HTTP error?

Also, could you provide details about your configuration, mostly your TLS mode, enabled features and hostnames.

Finally, the most common issue would be the front container getting stuck while trying to generate diffie hellman parameters. Could you check the logs for the front container? If it is indeed stuck, you could try restarting it, or generating the dh parameters outside the do droplet, because these VMS have so little available kernel entropy

**Comment by GuillaumeDesforges** [comment]
I have the same issue, I can't reach any website.

When I try to curl, I get `Failed to connect to xxxxx port 80: Connection refused`

I use Google Engine VM so I can't use IPv6. So I edited docker-compose.yml :
```YAML
  front:
    image: mailu/nginx:$VERSION
    restart: always
    env_file: .env
    ports:
    - "80:80"
    - "443:443"
    - "110:110"
    - "143:143"
    - "993:993"
    - "995:995"
    - "25:25"
    - "465:465"
    - "587:587"
```
