### ISSUE TITLE
[rspamd] DNS query blocked on multi.uribl.com

### ISSUE THREAD

**Issue by sam2kb** [Mailu/Mailu#554]
```
(controller) <3nxzfe>; monitored; rspamd_monitored_dns_cb: DNS query blocked on multi.uribl.com (127.0.0.1 returned), possibly due to high volume
(rspamd_proxy) <f69f64>; surbl; surbl_test_url: disable surbl multi.uribl.com as it is reported to be offline
```
I understand that requests are blocked because of the use of public DNS resolvers like 8.8.8.8 or 1.1.1.1 If that's so, is there a way to use my own DNS nameserver across all MailU services or just in the antispam container?

**Comment by sam2kb** [comment]
If you wonder, the number of emails/day is under 100 so there's no way I'm hitting a rate-limit

**Comment by sam2kb** [comment]
The above mentioned unbound image didn't want to resolve any DNS requests, so I just hooked up a different image and it works well now

```
surbl; process_dns_results: <0.0.0.A3.1D42F4BFB3ABFB4.32F383@mail.ketodiet808.us> domain [ketodiet808.us.multi.uribl.com] is in surbl multi.uribl.com(2)
```

**Comment by sam2kb** [comment]
```
version: '3.6'
services:
  unbound:
    container_name: unbound
    #image: ofthesun9/unbound-mailu:1.1
    image: mvance/unbound:latest
    restart: unless-stopped
    ports:
    - 0.0.0.0:53:53/tcp
    - 0.0.0.0:53:53/udp
networks:
  default:
    external: true
    name: mail_default
```
