### ISSUE TITLE
Add Netdata in docker-compose stack possible?

### ISSUE THREAD

**Issue by v1ru535** [Mailu/Mailu#567]
Hi all,

Is it possible to integrate netdata in the docker-compose.yml file?
has anyone ever done this configuration successfully?

I've unsuccessful tested:
```
  netdata:
    image: firehol/netdata
    hostname: mail.mynet.fr
    ports:
      - 19999:19999
#      - 8443:8443
    cap_add:
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
#    environment:
#      - NETDATA_PORT=8443
```

Thanks in advance.
