### ISSUE TITLE
Authentication issues when using IPv6 via robbertkl/ipv6nat

### ISSUE THREAD

**Issue by cooperaj** [Mailu/Mailu#827]
I'm using robbertkl/ipv6nat to simplify my IPv6 management and it's causing issues with auth due to the new $SUBNET requirement for things. 

TLDR. I believe that IPv6 causes issues for containers that communicate over IPv6 since the authentication is based on the IPv4 $SUBNET property.

Using robbertkl/ipv6nat lets me treat IPv6 on my server in an identical fashion to my normal IPv4 services. It does standard NAT using the iptables firewall so that opening ports on a container works for both standards without changes.

The issue is that, on an apparent random basis (I think) the internal traffic uses the ULA local addresses to communicate amongst containers and as this does not match the $SUBNET things sometimes don't work. The most noticeable service with this issue is the Rspamd UI which spews near constant error messages, which when viewed in the inspector, are 403 errors. 

My (abbreviated) compose file is:

```
version: '2.1'

services:

  front:
    image: mailu/nginx:$VERSION
    restart: always
    env_file: .env
    logging:
      driver: $LOG_DRIVER
    ports:
    - "80:80"
    - "443:443"
    - "110:110"
    - "143:143"
    - "993:993"
    - "995:995"
    - "25:25"
    - "465:465"
    - "587:587"
    volumes:
      - "$ROOT/certs:/certs"
      - "$ROOT/overrides/nginx:/overrides"

... other services ...

networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: $SUBNET
        - subnet: $SUBNET6
```

As you can see I've added some IPv6 config to the network which is needed for the ipv6nat container to be able to route to the services.

The reason I setup the system this way (and not even because I tend to always do it) is because without doing this the standard docker-compose file you recommend would have my IPv6 services be inaccessible. I was not able to have any service connect to them. This is on a standard Ubuntu 18.04 VM with the latest vendor Docker installed and the UFW firewall running. Using the ipv6nat tool allows me to keep the firewall without changes as docker then manages the IPv6 the same way as IPv4.
