### ISSUE TITLE
mailu_front not coming up - remains in restart loop

### ISSUE THREAD

**Issue by qm78** [Mailu/Mailu#856]
Hello,

I just gave the new mailu 1.6 release a try. I used new setup tool to create docker-compose artifacts for a vanilla installation (no upgrade). Front container fails to start and remains in a restart loop

After starting docker docker-compose ps shows:

```
$ docker-compose ps
      Name                     Command                  State                           Ports                    
-----------------------------------------------------------------------------------------------------------------
mailu_admin_1       /bin/sh -c /start.py             Up (healthy)   80/tcp                                       
mailu_antispam_1    /bin/sh -c /start.py             Up (healthy)   11332/tcp, 11334/tcp, 11335/tcp              
mailu_antivirus_1   /bin/sh -c /start.py             Up (healthy)   3310/tcp                                     
mailu_front_1       /bin/sh -c /start.py             Restarting                                                  
mailu_imap_1        /bin/sh -c /start.py             Up (healthy)   110/tcp, 143/tcp, 2525/tcp, 4190/tcp, 993/tcp
mailu_redis_1       docker-entrypoint.sh redis ...   Up             6379/tcp                                     
mailu_resolver_1    /bin/sh -c /start.py             Up (healthy)   53/tcp, 53/udp                               
mailu_smtp_1        /bin/sh -c /start.py             Up (healthy)   10025/tcp, 25/tcp                            
mailu_webdav_1      /bin/sh -c radicale -f -S  ...   Up (healthy)   5232/tcp                                     
mailu_webmail_1     docker-php-entrypoint /bin ...   Up (healthy)   80/tcp                                       
```

$docker-compose logs -f | grep front_1
```
front_1      | nginx: [emerg] invalid number of arguments in "location" directive in /etc/nginx/nginx.conf:93
front_1      | nginx: [emerg] invalid number of arguments in "location" directive in /etc/nginx/nginx.conf:93
front_1      | nginx: [emerg] invalid number of arguments in "location" directive in /etc/nginx/nginx.conf:93
...
```

docker-compose version 1.23.2, build 1110ad01

my docker-compose.xml
```
# This file is auto-generated by the Mailu configuration wizard.
# Please read the documentation before attempting any change.
# Generated for compose flavor

version: '3.6'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/opt/mailu/redis:/data"
    
  # Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.6}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "anonymized:80:80"
      - "anonymized:80:80"
      - "anonymized:443:443"
      - "anonymized:443:443"
      - "anonymized:25:25"
      - "anonymized:25:25"
      - "anonymized:465:465"
      - "anonymized:465:465"
      - "anonymized:587:587"
      - "anonymized:587:587"
      - "anonymized:110:110"
      - "anonymized:110:110"
      - "anonymized:995:995"
      - "anonymized:995:995"
      - "anonymized:143:143"
      - "anonymized:143:143"
      - "anonymized:993:993"
      - "anonymized:993:993"
    volumes:
      - "/opt/mailu/certs:/certs"
      - "/opt/mailu/overrides/nginx:/overrides"

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.6}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.6}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/data:/data"
      - "/opt/mailu/dkim:/dkim"
    depends_on:
      - redis

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.6}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/mail:/mail"
      - "/opt/mailu/overrides:/overrides"
    depends_on:
      - front

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.6}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/overrides:/overrides"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.6}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/filter:/var/lib/rspamd"
      - "/opt/mailu/dkim:/dkim"
      - "/opt/mailu/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.6}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  webdav:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-1.6}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/dav:/data"


  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rainloop:${MAILU_VERSION:-1.6}
    restart: always
    env_file: mailu.env
    volumes:
      - "/opt/mailu/webmail:/data"
    depends_on:
      - imap


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```

my mailu.env
```
# Mailu main configuration file
#
# Generated for compose flavor
#
# This file is autogenerated by the configuration management wizard.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set this to the path where Mailu data and configuration is stored
# This variable is now set directly in `docker-compose.yml by the setup utility
# ROOT=/opt/mailu

# Mailu version to run (1.0, 1.1, etc. or master)
#VERSION=1.6

# Set to a randomly generated 16 bytes string
SECRET_KEY=anonymized

# Address where listening ports should bind
# This variables are now set directly in `docker-compose.yml by the setup utility
# PUBLIC_IPV4= anonymized (default: 127.0.0.1)
# PUBLIC_IPV6= anonymized (default: ::1)

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.168.203.0/24

# Main mail domain
DOMAIN=anonymized

# Hostnames for this server, separated with comas
HOSTNAMES=anonymized

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=letsencrypt

# Authentication rate limit (per source IP address)
AUTH_RATELIMIT=10/minute;1000/hour 

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=True

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=rainloop

# Dav server implementation (value: radicale, none)
WEBDAV=radicale

# Antivirus solution (value: clamav, none)
#ANTIVIRUS=clamav

#Antispam solution
ANTISPAM=none

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: bz2, gz)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/webmail

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=

# Website name
SITENAME=anonymized

# Linked Website URL
WEBSITE=https://anonymized



###################################
# Advanced settings
###################################

# Log driver for front service. Possible values:
# json-file (default)
# journald (On systemd platforms, useful for Fail2Ban integration)
# syslog (Non systemd platforms, Fail2Ban integration. Disables `docker-compose log` for front!)
# LOG_DRIVER=json-file

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Default password scheme used for newly created accounts and changed passwords
# (value: BLF-CRYPT, SHA512-CRYPT, SHA256-CRYPT, MD5-CRYPT, CRYPT)
PASSWORD_SCHEME=BLF-CRYPT

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

###################################
# Database settings
###################################
DB_FLAVOR=sqlite
```
