### ISSUE TITLE
kubernetes ingresses needs to be fixed for multiple hosts (suggestion added)

### ISSUE THREAD

**Issue by cr1st1p** [Mailu/Mailu#892]
I want to test with 2 email domains, inside kubernetes.
In order to do that, I had to modify the ingresses and do a 'for' loop inside each ingress, around the 'tls' definition and inside the 'rules' entry.
Something along the lines of:
```
...
  tls:
  - hosts:
{% for host in HOSTNAMES.split(",") %}
    - "{{ host }}"
{% endfor %}
    secretName: ...
  rules:
   {% for host in HOSTNAMES.split(",") %}
  - host: "{{ host }}"
    http:
      paths:
      - path: "/admin"
        backend:
          serviceName: admin
          servicePort: 80
{% endfor %}

```
Regards,
-- Cristi
