### ISSUE TITLE
Add logging to Syslog Server (Postfix logs for example) for later Review

### ISSUE THREAD

**Issue by ripkens** [Mailu/Mailu#920]
With fluentd installed on the Postfix Docker Image and configuration available with an override, we could parse the postfix logfile and save alle mail traffic logs in mongoDB for later review as RSPAMD history is totaly insufficient.

Here is a tutorial: https://www.fluentd.org/guides/recipes/maillog-mongodb

The regular expression could be better to get the status of the mail in a dedicated field.

I would be very happy if that could be achieved.

The MongoDB server can be a docker image but also any MongoDB Server reachable (maybe on the MailU docker Host).

**Comment by ripkens** [comment]
I have now established the following:

Postfix logs will be sent to a syslog Server for later review

### First, we add mongo, elasticsearch and graylog as docker containers

in docker-compose.yml add:

```
  mongodb:
    image: mongo:3
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  graylog:
    image: graylog/graylog:2.5
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    environment:
      - GRAYLOG_PASSWORD_SECRET=[SET A RANDOM_16_CHAR_STRING]
      - GRAYLOG_ROOT_PASSWORD_SHA2=[SEE NOTES BELOW]
      - GRAYLOG_WEB_ENDPOINT_URI=http://[YOUR_EXTERNAL_IP]:9001/api
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9001:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local

```

### Then add the following tou your smtp container:

```
    logging:
      driver: gelf
      options:
        mode: non-blocking
        max-buffer-size: 4m
        gelf-address: "udp://173.212.193.33:12201"
        tag: postfix
```

### Create SSH2 Password for graylog:

`echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1`

### Then restart your Environment:

`docker-compose up -d`

Open the url you have set in the config and login with user "admin" and your Passwort you have generated.

Now you have to add an input under "System -> Inputs", select "GELF UDP" and save.

And of you go, you are now collectin ALL Messages from postfix into graylogs
