### ISSUE TITLE
LOG_DRIVER=journald no longer works in 1.6

### ISSUE THREAD

**Issue by v1ru535** [Mailu/Mailu#950]
Hi all,

I've upgrade from 1.5 to 1.6 one week ago.

LOG_DRIVER with 1.5 was OK (journald), but now with 1.6 I've a problem with it.
I've set `LOG_DRIVER=journald` in my mailu.env but nothing appear in the logs on my host.
I've test with option syslog but same appear.

The previous issue in 1.5 for this option was #584.

Thanks for the investigation.
```
journalctl -b CONTAINER_NAME=mailu_front_1
-- No entries --
```

**Comment by UnrealKazu** [comment]
I just migrated from 1.5 to 1.6, and am able to use the `journald` log driver. Using the same commands I do get a log trace, so it is working for me.

Are you sure that the `LOG_DRIVER` setting from the `mailu.env` file is being used in your `docker run` or `docker-compose` command?

**Comment by Darkitty** [comment]
Hello,

I get the same error. I didn't migrate from any previous version.

**Comment by daniellibonati** [comment]
Hi, I've experienced the same behavior and I've found the `docker-compose.yml` file contains a hard reference to the logging driver:

```
# Core services
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.6}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
    ...
    volumes:
    ...
```
Seems the auto-generated `docker-compose.yml` no longer reads this value from the environment. Replacing `json-file` with `journald` or `syslog` worked fine for me.
